### ISSUE TITLE
Unicode Support PY2 and PY3 differences?

### ISSUE THREAD

**Issue by damon-atkins** [mhammond/pywin32#1117]
Hi Guys,
Where is Unicode support upto within pywin32. For example when reading data from the registry Non-US characters seem to come back as ? in PY2.7, however in PY3 they are correct.
e.g. 发送时间   in PY2 is return as `????` and in PY3 returned as `\u53d1\u9001\u65f6\u95f4`

Is their anything preventing pywin32 under python 2.7 returning correct Unicode strings.

Thanks

**Comment by damon-atkins** [comment]
cc: @twangboy

**Comment by xoviat** [comment]
BTW, I wouldn't expect to get a response on this for a few weeks.

**Comment by damon-atkins** [comment]
Hi @xoviat thanks for the info.   Would you happen to know which parts of the code determine what data type is return and if current code in py2 returns any PY2 Unicode  instead of PY2 String.

**Comment by xoviat** [comment]
Yes I do know this code fairly well. See https://github.com/pywin32/pywin32/blob/master/win32/src/PyUnicode.cpp for the Unicode stuff.

**Comment by damon-atkins** [comment]
Thanks @xoviat  unfortunately I do not known anything about writing C interfaces for Python.  Is their any  python or pywin32 doco that needs to be read to help understand.

**Comment by xoviat** [comment]
Unfortunately understanding pywin32 requires a good working knowledge of both C++, the windows API, and the Python C API. There's not really a way around that.

**Comment by xoviat** [comment]
Don't take this personally: I could probably help you. But I want to make it as painful as possible for people who continue to use Python 2.7 because I have had to spend countless additional time on fixing problems to make libraries work with it. Others (particularly @mhammond) may feel differently, but I have other things to do.

**Comment by mhammond** [comment]
Python 2.x defaults to strings - you need to manually decode it using the "mbcs" charset. If you are using win32api directly, you can probably use the "W" functions to get it directly as unicode.
