### ISSUE TITLE
Behavior inconsistent between versions on pypi and sourceforge 

### ISSUE THREAD

**Issue by cbucdc** [mhammond/pywin32#1126]
# Code
I am attempting to make an example service with this code:
```import win32serviceutil
import win32service
import win32event
import servicemanager
import socket
import time
import logging
# Logs to the temp directory under C
logging.basicConfig(
    filename='C:\\Temp\\allamericanregress.log',
    level=logging.DEBUG,
    format='[allamericanregress-service] %(levelname)-7.7s %(message)s'
)

class AllAmericanRegressService(win32serviceutil.ServiceFramework):
    _svc_name_ = "AllAmericanRegress"
    _svc_display_name_ = "AllAmericanRegress"

    def __init__(self, args):
        win32serviceutil.ServiceFramework.__init__(self, args)
        self.stop_event = win32event.CreateEvent(None, 0, 0, None)
        socket.setdefaulttimeout(60)
        self.stop_requested = False

    # How to respond to service stop command
    def SvcStop(self):
        self.ReportServiceStatus(win32service.SERVICE_STOP_PENDING)
        win32event.SetEvent(self.stop_event)
        logging.info('Stopping service ...')
        self.stop_requested = True

    # When launched by service control manager, log brief intro
    def SvcDoRun(self):
        servicemanager.LogMsg(
            servicemanager.EVENTLOG_INFORMATION_TYPE,
            servicemanager.PYS_SERVICE_STARTED,
            (self._svc_name_, '')
        )
        self.main()

    def main(self):
        logging.info(' ** Doing things ** ')
        return


if __name__ == '__main__':
    win32serviceutil.HandleCommandLine(AllAmericanRegressService, None, ["AllAmericanRegressService","--startup=auto", "install"])
    win32serviceutil.HandleCommandLine(AllAmericanRegressService, None, ["AllAmericanRegressService", "start"])
    # win32serviceutil.HandleCommandLine(AllAmericanRegressService)
```

# Pypi version behavior

When installing pypiwin32 via pip and executing this file from administrator command prompt I get an error and my service never starts.

Installation:
```
C:\Users\chris>pip install pypiwin32                                                                                    Collecting pypiwin32                                                                                                      Using cached pypiwin32-220-cp36-none-win_amd64.whl                                                                    Installing collected packages: pypiwin32                                                                                Successfully installed pypiwin32-220     
```

Executing:

```
Installing service AllAmericanRegress
Changing service configuration
Service updated
Starting service AllAmericanRegress
Error starting service: The service did not respond to the start or control request in a timely fashion.
```

# Sourceforge version behavior

However, when installing via the installer available at https://sourceforge.net/projects/pywin32/files/pywin32/Build%20221/pywin32-221.win-amd64-py3.6.exe/download I get no errors and the services is instantiated ad executes as expected and I get this output:
```
Installing service AllAmericanRegress
Changing service configuration
Service updated
Starting service AllAmericanRegress
```

# Question
Why do these version behave differently? Alternatively, how can the installer be executed headlessly?

**Comment by xoviat** [comment]
Do you want to fix this issue?

**Comment by TheCDC** [comment]
@xoviat I would love to look into it. Can you point me in the right direction?

**Comment by xoviat** [comment]
You need to download the latest installers from Sourceforge and then run `wheel convert` on them. You also need to edit the metadata so that the project name is "pypiwin32" rather than "pywin32." See pypa/wheel#157 for the possible issues you might encounter

**Comment by xoviat** [comment]
Please upload the wheels to a GitHub repository after you are finished, and I will check them to make sure that they are OK.

**Comment by mhammond** [comment]
I'm still learning about how wheel etc work, but the underlying problem is probably that pip doesn't execute the pywin32 postinstall script, so things like services and COM objects simply don't work correctly - and that postinstall script must be run with elevated permissions, which I suspect pip etc simply don't support (and shouldn't IMO)

So I expect the reality to be that if you want to use pywin32 "globally", you will continue to need to use the installer executable.
