### ISSUE TITLE
Further information about "/Automate" option

### ISSUE THREAD

**Issue by thopiekar** [mhammond/pywin32#1133]
As I already added in #1130 the option to change it, I wonder which role this option takes.
Personally I see it nowhere else mentioned, then in the win32com.server.register code.
There seems to be nothing special, that is catching or checking for this commandline argument.
Or am I wrong?

PS: Probably found the missing bit: https://github.com/goatpig/py2exe/blob/35ad88369fff3b171f131ae64f98aafb06626774/py2exe/boot_com_servers.py

**Comment by mhammond** [comment]
As you say, py2exe has some special support for this arg - which is more of a convention than anything. Thus, #1130 is going to also need a py2exe patch before it works. Either way, let's continue the discussion in #1130.
