### ISSUE TITLE
Missing example of python-based server and client with events

### ISSUE THREAD

**Issue by thopiekar** [mhammond/pywin32#1135]
Currently I managed to get a server running, which is dispatchable, etc, but I still miss the key feature I wanted to use: events.
Could you please add an example how to implement events? Or even better: A full working example?

In my case it does not matter what I do: WithEvents() and DispatchWithEvents() do not work.
I checked my IDL and all seems to be fine (from as far as I can say, I'm new to these files).

I also took the PyWin32 book, I bought for this and again found nothing about such an example.

My sources are at: https://github.com/thopiekar/CuraInterfacePlugin/tree/master-sending-and-receiving-signals

**Comment by mhammond** [comment]
Sadly the PyWin32 book pre-dates events, but you can find a number of event samples in the win32com/demos directory.

**Comment by thopiekar** [comment]
Alright. I took a look at some tests already, but these were not so helpful for a newbie as I am, because one was sharing info between a server and a client (which I can't do, because I want to use a Python server + VBA client) and the other was that complex, that I couldn't understand, but only see a structure.

Will take a closer look at the demos now.
