### ISSUE TITLE
Allow Jedi to make use of generated static type information for Automation objects

### ISSUE THREAD

**Issue by zspitz** [mhammond/pywin32#1137]
[Jedi](https://jedi.readthedocs.io/en/latest/) is:
> a static analysis tool for Python that can be used in IDEs/editors ... [whose] historic focus is autocompletion

Is it possible for Jedi to make use of the Python files generated from Automation object definitions using `makepy`?

(I've filed a similar issue [here](https://github.com/Microsoft/vscode-python/issues/487).)

**Comment by mhammond** [comment]
> Is it possible for Jedi to make use of the Python files generated from Automation object definitions using makepy?

I've never used jedi, so I don't know the answer to that question - but this is better asked on the Jedi forums, which I notice you have done - so I'm going to close this issue for now, but feel free to come back with a PR if anything comes from that.

**Comment by zspitz** [comment]
@mhammond I haven't asked on  the Jedi forums; I've raised an issue on the Visual Studio Code repo, which makes use of Jedi.

Also, is there any documentation on how to use makepy and what it outputs?
