### ISSUE TITLE
Does installer run in non-interactive environments?

### ISSUE THREAD

**Issue by smontanaro** [mhammond/pywin32#1138]
I'm trying to run the pywin32 installer in an Appveyor virtual machine. It just hangs with no error messages or other obvious output. My guess (I have no access to an actual Windows command line) is that it's prompting for a response of some sort, but the prompt isn't showing up in the Appveyor log. Is there a way to run the installer in a completely non-interactive environment?

**Comment by smontanaro** [comment]
Poking around a bit more, I stumbled on a PyPI package called pypiwin32. Is that a pip-installable version of pywin32?

**Comment by xoviat** [comment]
I'm the current maintainer of pypiwin32. After Mark uploads wheels to the pywin32 project on pypi, I will upload a shim package that redirects installations to pywin32.

**Comment by smontanaro** [comment]
Got it. Thanks...
