### ISSUE TITLE
DDE server working, but only delivering one character

### ISSUE THREAD

**Issue by rmoctezuma** [mhammond/pywin32#1139]
Hello, I am working with the 32 bits version of pywin32.
My python version is 3.6

My requeriment is get information from python on excel, from a DDE server.
For this, and once my server is up, I use this format on Excel: =BARCODE|CODE!DATA
This is working, but the cell is only showing the first char of the string delivered by the python DDE server. 
Any ideas of why this is not working?
This is my code
Regards,
```

import time
import win32ui
import dde
from pywin.mfc import object

class DDETopic(object.Object):
    def __init__(self, topicName):
        self.topic = dde.CreateTopic(topicName)
        object.Object.__init__(self, self.topic)
        self.items = {}

    def setData(self, itemName, value):
        try:
            self.items[itemName].SetData( str(value) )
        except KeyError:
            if itemName not in self.items:
                self.items[itemName] = dde.CreateStringItem(itemName)
                self.topic.AddItem( self.items[itemName] )
                self.items[itemName].SetData( str(value) )

ddeServer = dde.CreateServer()
ddeServer.Create('BARCODE')
ddeTopic = DDETopic('CODE')
ddeServer.AddTopic(ddeTopic)

while True:
    yourData = 'DataToDeliverOnExcel'
    ddeTopic.setData('DATA', yourData)
    win32ui.PumpWaitingMessages(0, -1)
    time.sleep(0.1)
```

**Comment by mhammond** [comment]
I suspect there is an issue with the DDE modules on python 3.x - does it work with Python 2.x?

**Comment by ManPython** [comment]
This same issue, but the first char is F or t type in any of difrent setData

**Comment by gakowalski** [comment]
I used external app, [DDE Query v1.5](https://github.com/chrisoldwood/DDEQuery), to debug this and it seems that the script sends data in multibyte format (UTF-16?) while DDE client expect regular string. For example, string "We" is send as six bytes: 0x57, 0x00, 0x65, 0x00, 0x00, 0x00. It ends with double zero. DDE client expects string terminated by single zero and that's why it stops after first letter - "W".

**Comment by kangchihlun** [comment]
I have the same issue , any solution ?

**Comment by sobeasy** [comment]
Same here... @gakowalski Thanks for your finding !
But is it no cure ?

**Comment by karlsgodt** [comment]
I'm having this issue as well. Is there any fix?

**Comment by c1ntango** [comment]
We have spent many hours on this with my team and it turns out this library works perfectly in python 2.7 - the bug only exists above.

**Comment by lcse66** [comment]
Same issue, pywin32 version 300, python 3.8.6, Windows 7, excel 2013


```
C:\>pip show pywin32
Name: pywin32
Version: 300
Summary: Python for Window Extensions
Home-page: https://github.com/mhammond/pywin32
Author: Mark Hammond (et al)
Author-email: mhammond@skippinet.com.au
License: PSF
Location: c:\users\#######\appdata\local\programs\python\python38\lib\site-packages
Requires:
Required-by:

C:\>python --version
Python 3.8.6
```

**Comment by markuskimius** [comment]
Hi, I'm having the same issue using pywin32 version 303 and [Python 3.10.4](https://www.python.org/downloads/release/python-3104/). [Python 2.7.18](https://www.python.org/downloads/release/python-2718/) works fine, though. I'm just testing with the demo script that comes with pywin32, [ddeserver.py](https://github.com/mhammond/pywin32/blob/main/win32/Demos/dde/ddeserver.py). Could the issue be stemming from the difference in string encoding between python2 and python3 [link](https://portingguide.readthedocs.io/en/latest/strings.html)?

**Comment by karlsgodt** [comment]
Hey Mark,
I stopped working on this a long time ago, so I can't help you. Good luck!

Stephen Karlsgodt

President
Savoy Engineering, LLC
https://www.savoyengineering.com/
‪(213) 538-2766

**Comment by markuskimius** [comment]
Submitted pull request to fix this issue: https://github.com/mhammond/pywin32/pull/1861

Thanks,
Mark

**Comment by mhammond** [comment]
hopefully fixed by #1861

**Comment by markuskimius** [comment]
It was fixed in pywin32 version 304

**Comment by BrianVu-PP** [comment]
yea I just realized my pip only give me 301. Had to specify version. TY
