### ISSUE TITLE
can't find a Windows SDK

### ISSUE THREAD

**Issue by zhangliutian** [mhammond/pywin32#1145]
python 3.61 Installation of this error
` D:\Software Package\pywin32-master\pywin3`

`Converting...`

`Executing...`

`Building pywin32 3.6.221.0`

`Traceback (most recent call last):`

 ` File "setup3.py", line 16, in <module>`

 `exec(str(got))`

` File "<string>", line 305, in <module>`

`RuntimeError: Can't find the Windows SDK `

**Comment by mhammond** [comment]
For better or worse, you need a fairly complicated build environment setup to install from sources - see the top of setup.py for details. You should install one of the binary packages instead.
