### ISSUE TITLE
Can't find the Windows SDK

### ISSUE THREAD

**Issue by Svickie7** [mhammond/pywin32#1150]
D:\scrapy\pywin32-master>python setup.py install
Building pywin32 2.7.222.1
Traceback (most recent call last):
  File "setup.py", line 319, in <module>
    raise RuntimeError("Can't find the Windows SDK")
RuntimeError: Can't find the Windows SDK

**Comment by mhammond** [comment]
You are attempting to build from source - please see https://github.com/mhammond/pywin32#building-from-source
