### ISSUE TITLE
pypiwin32 version 222 - Failed to be installed

### ISSUE THREAD

**Issue by kfirilani** [mhammond/pywin32#1151]
New version of pypiwin32 (version 222) updated on 25-1-2018 cannot be installed.

Sometimes, package is being installed, however when trying to import "win32api" module, an exception occurred.

Does anyone have this problem?

**Comment by xoviat** [comment]
I can confirm this issue. @mhammond Did you verify that the wheels work correctly?

**Comment by xoviat** [comment]
Note: the "pypiwin32" project has ended; it's now simply a shim package that requires "pywin32".

**Comment by tardyp** [comment]
@mhammond would have been nice to add a little message in the long_description stating that the pypiwin32 package is obsolete

**Comment by topnotcher** [comment]
> Sometimes, package is being installed, however when trying to import "win32api" module, an exception occurred.

This:
```
>>> import win32api
ImportError: DLL load failed: The specified module could not be found.
```

This is in a virtualenv. It is trying to import one of the DLLs in pywin32_system32.

I don't know if the pywi32_postinstall script is even running, but I have my doubts -- the DLLs are *not* present in `sys.prefix`. In any case, I don't expect it to work. As far as I can tell, it installs to system32 or `sys.prefix` if that fails. I don't think `sys.prefix` is sufficient in the virtual environment -- it points to the root of the venv, which is not in `PATH` and does not contain python.exe (i.e. it's not a DLL search path).

`pypiwin32` seemed to work around this in the .pth file:
*pypiwin32.pth*:
```
import os;os.environ["PATH"]+=(';'+os.path.join(sitedir,"pypiwin32_system32"))
```

**Comment by mhammond** [comment]
The post_install script needs to be run as mentioned in readme.md. I can't find support for automatically running it when building the wheel.

**Comment by mhammond** [comment]
> I can confirm this issue. @mhammond Did you verify that the wheels work correctly?

See README.md for the issues I had. Unassigning as I'm not working on this, but PRs obviously welcome.

**Comment by xoviat** [comment]
I've opened gh-1153 for a possible fix.

**Comment by jabdoa2** [comment]
Any chance you could remove the broken version from pypi until this is fixed? This generates a lot a user complaints for us because on of our dependencies depends on pypiwin32 on windows

**Comment by mhammond** [comment]
> depends on pypiwin32 on windows

I believe I've changes the pypiwin32 project so that build 222 is hidden while build 220 is visible. I made no changes to "pywin32" on pypi. Did that help?

**Comment by tardyp** [comment]
Hi @mhammond , I reverted my workaround at https://github.com/buildbot/buildbot/pull/3930

but the CI still finds version 222 of pypiwin32:
https://ci.appveyor.com/project/djmitche/buildbot/build/1.0.5848/job/aeki06t49p12r3in

If I go on the pypi page, I still see that 222 is the latest version https://pypi.python.org/pypi/pypiwin32

**Comment by meejah** [comment]
We are seeing this problem on Tahoe-LAFS windows builds on Travis -- pinning to `pypiwin32==219` is the solution that works so far.

**Comment by csm10495** [comment]
I'm seeing this too. Version 222 should be taken down from pypi until this is resolved. Forcing pypiwin32==219 works around this for me now.

**Comment by mhammond** [comment]
pypi seems strange - I set build 222 to hidden, but when I perform a search for simply "pypiwin32" it still shows that build.  I'm not even sure how build 222 ended up in that project - I only updated the "pywin32" project. 

I just went ahead and removed build 222 completely from the pypiwin32 project - both build 220 and 219 are unhidden - but it's not clear to me if there is also an issue with build 220 causing everyone to pin versions to build 219.

**Comment by meejah** [comment]
At least this one Travis build can't find version 220: https://ci.appveyor.com/project/tahoe-lafs/tahoe-lafs/build/1.0.1015/job/s6uw8ws5y2j9omvo

**Comment by tardyp** [comment]
works for me as well.
Note that appveyor picks version 219 for python 2.7 and 3.5, and 220 for 3.6.

220 only has wheels for 3.6:
https://pypi.python.org/pypi/pypiwin32/220

thanks

**Comment by weiwongfaye** [comment]
@mhammond , same for me.  One of our test machine sometimes fetch 219, sometimes 222. 
currently, we just pin the version to 219 directly.

**Comment by johan-bjareholt** [comment]
This issue is really wierd.
When doing "python -m pip install pywin32" I still sometimes get the 222 version, forcing it with "python -m pip install pywin32>=223" works fine.
