### ISSUE TITLE
No module named ‘win32api'

### ISSUE THREAD

**Issue by ucasiggcas** [mhammond/pywin32#1167]
hello，have a question after pip install pywin32
there isn't   win32api, I don't know what's wrong.
have try many times,need help,  Thx

**Comment by xoviat** [comment]
Duplicate gh-1151.

**Comment by xoviat** [comment]
Duplicate of gh-1151.

**Comment by xoviat** [comment]
Duplicate of gh-1151.

**Comment by xoviat** [comment]
Duplicate of #1151.

**Comment by xoviat** [comment]
Duplicate of #1151.
