### ISSUE TITLE
Memory leak in adodbapi (resources not released when cursor goes out of scope)

### ISSUE THREAD

**Issue by bkline** [mhammond/pywin32#1170]
I've been tearing my hair out trying to find out why some of our long-running jobs were exhausting all of the memory on the servers. I finally tracked it down to a failure of the `adodbapi` `Cursor` objects to release the memory of the resources under their control when they go out of scope. The following code snippet will eventually exhaust all memory on the machine when running under `adodbapi`:

```python
while True:
    cursor = conn.cursor()
```
With other DB API 2.0 packages (for example, `pyodbc`), memory usage remains flat running this same code, as all of their resources are released when the cursor objects go out of scope.

A workaround is to explicitly close all cursor objects before they go out of scope everywhere in your code.

**Comment by vernondcole** [comment]
Hmmm.  I'll bet that something is not being cleaned up during cursor.__del__() -- probably in the new stuff I added so that the connection has a list of its cursor, I suspect.
  I will try to track that one down.

**Comment by bkline** [comment]
Thanks, Vernon.

**Comment by vernondcole** [comment]
Pull request to come, pending testing.

Short version...
In Connection.__init__()
replace

self.connection_string = ''
self.cursors = {}
self.dbms_name = ''

with

self.connection_string = ''
self.cursors = weakref.WeakValueDictionary()
self.dbms_name = ''

**Comment by bkline** [comment]
Yes, that does the trick. Well done!

**Comment by vernondcole** [comment]
fixed in #1445, but still exists in remote and server code.
I am leaving this open until those modules are either fixed and supported, or removed.

**Comment by vernondcole** [comment]
Support for the remote has been removed until it can be better implemented. So this issue is no longer current.
