### ISSUE TITLE
Could not find a version that satisfies the requirement pywin32>=223

### ISSUE THREAD

**Issue by vincentcox** [mhammond/pywin32#1172]
Since a few days I have issues with installing pyInstaller (depending on pywin32). It's running on a continious deployment platform, so I am surprised it appeared out of the blue.

The error I am having is: `Could not find a version that satisfies the requirement pywin32>=223 (from pypiwin32->pyinstaller) (from versions: ) No matching distribution found for pywin32>=223 (from pypiwin32->pyinstaller)`

I tried to bypass this by installing the pythonwheel manually. I downloaded `https://pypi.python.org/packages/65/83/0b14690d70bcd193a67c8b0a640129717e37a11d8e6a3e28a01e47910737/pywin32-223-cp27-cp27m-win_amd64.whl#md5=c9d2d260ef87592bb04cbc59f1ffe2d2` but the installation is failing because `pywin32-223-cp27-cp27m-win_amd64.whl is not a supported wheel on this platform.`

The full error trail:

```
wine64 c:\\Python-64\\python.exe c:\\Python-64\\scripts\\pip.exe install pyinstaller --upgrade
e:heap:HeapSetInformation 0x3b4000 0 0x32fcd0 4
fixme:heap:HeapSetInformation 0x8e0000 0 0x329110 4
Collecting pyinstaller
fixme:toolhelp:CreateToolhelp32Snapshot Unimplemented: heap list snapshot
fixme:toolhelp:Heap32ListFirst : stub
  Downloading PyInstaller-3.3.1.tar.gz (3.5MB)
    100% |################################| 3.5MB 121kB/s 
fixme:heap:HeapSetInformation 0x3b4000 0 0x32fcd0 4
fixme:heap:HeapSetInformation 0x8e0000 0 0x3252a0 4
Collecting setuptools (from pyinstaller)
  Downloading setuptools-38.5.1-py2.py3-none-any.whl (489kB)
    100% |################################| 491kB 685kB/s 
Collecting pefile>=2017.8.1 (from pyinstaller)
  Downloading pefile-2017.11.5.tar.gz (61kB)
    100% |################################| 65kB 3.1MB/s 
fixme:heap:HeapSetInformation 0x3b4000 0 0x32fcd0 4
fixme:heap:HeapSetInformation 0x8e0000 0 0x3252a0 4
Collecting macholib>=1.8 (from pyinstaller)
  Downloading macholib-1.9-py2.py3-none-any.whl (40kB)
    100% |################################| 40kB 3.7MB/s 
Collecting future (from pyinstaller)
  Downloading future-0.16.0.tar.gz (824kB)
    100% |################################| 827kB 468kB/s 
fixme:heap:HeapSetInformation 0x3b4000 0 0x32fcd0 4
fixme:heap:HeapSetInformation 0x8e0000 0 0x3252a0 4
Collecting pypiwin32 (from pyinstaller)
  Downloading pypiwin32-223-py3-none-any.whl
Collecting altgraph>=0.15 (from macholib>=1.8->pyinstaller)
  Downloading altgraph-0.15-py2.py3-none-any.whl
Collecting pywin32>=223 (from pypiwin32->pyinstaller)
  Could not find a version that satisfies the requirement pywin32>=223 (from pypiwin32->pyinstaller) (from versions: )
No matching distribution found for pywin32>=223 (from pypiwin32->pyinstaller)
```

Any idea what is causing this?

The full build log can be found here, if you need more context information on the issue: https://travis-ci.org/vincentcox/StaCoAn/jobs/346428154 (but as far I can see I posted all the relevant information here). 

Related issue: https://github.com/pyinstaller/pyinstaller/issues/3340#issuecomment-369051788

**Comment by xoviat** [comment]
We don't support Python 3.4.

**Comment by thopiekar** [comment]
I was able to build v221 or v222 manually for Python 3.5 (which was build
before) using VS2017.
Now due to an additional check in the setup.py file, it is not possible
anymore to use VS2017, but I uploaded a PR to add support for it.

What is the error (message) you are getting when building it with VS2010?

2018-03-19 12:35 GMT+01:00 José Gabriel Rivera <notifications@github.com>:

**Comment by jrivera294** [comment]
If I try to build it with VS2015 through setup3.py this is the output:
```
Traceback (most recent call last):
  File "setup3.py", line 16, in <module>
    exec(str(got))
  File "<string>", line 326, in <module>
RuntimeError: Can't find the Windows SDK
```
I was trying to setup a vs 2010 environment but I'm having problems to install the Visual c++ Redistributable x86

Python doesn't have version restrictions to compile certain packages? It doesn't affect pywin32? I found this on the documentation: https://wiki.python.org/moin/WindowsCompilers

**Comment by thopiekar** [comment]
There are functions inside setup.py, which are trying to find the MS SDK for you. If they are not able to find it, you will get the error you see. In that case, you need to specify the location manually by using the MSSDK environment variable.
However, since I haven't had any issues before this check has been added, I can imagine that the SDK searching functions are not needed anymore. For me it just built fine without any of these checks.
So what you can try to do is removing the check or set the MSSDK variable to the location, where your SDK can be found.

**Comment by jrivera294** [comment]
Ok, I managed to do it setting the MSSDK environment variable, thanks!

If you set the MSSDK environment variable it will not try to search the SDK.

`set MSSdk=C:\Program Files (x86)\Microsoft SDKs\Windows\v7.1A`

I had to install the VS 2010 because it throw an error later on the build.

**Comment by thopiekar** [comment]
No problem 👍

**Comment by webknjaz** [comment]
Hello @mhammond @thopiekar @pfmoore @glyph
Could someone please publish old distributions from https://github.com/mhammond/pywin32/releases/tag/b221 to PYPI? I need to specify a proper dependency in cherrypy/cherrypy#1700

**Comment by mhammond** [comment]
> Could someone please publish old distributions from https://github.com/mhammond/pywin32/releases/tag/b221 to PYPI? I need to specify a proper dependency in cherrypy/cherrypy#1700

pywin32 build 221 never existed on pypi. https://pypi.python.org/pypi/pypiwin32/220 might be helpful.

**Comment by jrivera294** [comment]
@thopiekar I'm having problems with the postinstall script on my pywin32 (223) build. For some reason when I try to run the postinstall script it fails with this traceback:
`Traceback (most recent call last):
  File "c:\python34\scripts\pywin32_postinstall.py", line 605, in <module>
    install()
  File "c:\python34\scripts\pywin32_postinstall.py", line 328, in install
    LoadSystemModule(lib_dir, "pywintypes")
  File "c:\python34\scripts\pywin32_postinstall.py", line 166, in LoadSystemModule
    mod = imp.load_dynamic(modname, filename)
ImportError: DLL load failed: Formato EXE erróneo en %1.
`
It doesn't happend with old versions, so I suppose that I'm doing something bad on the build process.
I'm trying to install the DLL using the script because If I copy the DLL manually I got the same error if I try to import win32com or win32api.

Would you have any clue about why it may be happening?

**Comment by thopiekar** [comment]
Are you cross-compiling? It mentions that the format of the executable is wrong. Can imagine you built pywin32 for 64bit, but due to your %Path% environment variable, it is using a 32bit installation.
However, it is only a guess.

**Comment by jrivera294** [comment]
I'm compiling it with a Python 3.4.4 (32 bits) on Windows 10 64 bits, with VS and SDK 2010.
But you are right, I'm trying to install it on Wine 32 bits.

This is the traceback if I try to install it on the same environment that I used to compile it (W10)
`Traceback (most recent call last):
  File "env\Scripts\pywin32_postinstall.py", line 605, in <module>
    install()
  File "env\Scripts\pywin32_postinstall.py", line 328, in install
    LoadSystemModule(lib_dir, "pywintypes")
  File "env\Scripts\pywin32_postinstall.py", line 166, in LoadSystemModule
    mod = imp.load_dynamic(modname, filename)
ImportError: DLL load failed: %1 no es una aplicación Win32 válida.`

**Comment by thopiekar** [comment]
Sorry, but have no experiences running PyWin32 on Wine.

**Comment by webknjaz** [comment]
@mhammond thanks for pointing this out. Still it would be useful if someone published that version as well :)
I'll stick to your solution for now.

**Comment by webknjaz** [comment]
@mhammond there's only 2 wheels for 3.6 for v220 :(
No source dist: https://pypi.python.org/simple/pypiwin32/
Will have to stick to 219, which actually has sdist published.

**Comment by M4CC** [comment]
I'm on Python 2.7.10 and I still get this error. Shouldn't it install properly for this version? Thank you!

**Comment by ArgiesDario** [comment]
Mee too i'm using Python 2.7.3 and same error is displayed:

> Download error on https://pypi.org/simple/: [Errno 1] _ssl.c:504: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version -- Some packages may not be found!
> No local packages or working download links found for pywin32>=223
> error: Could not find suitable distribution for Requirement.parse('pywin32>=223')

**Comment by webknjaz** [comment]
@ArgiesDario you have outdated pip. Upgrade it first.

**Comment by ondrej23** [comment]
The module is not compatible with Python 3.7? That really sucks :(

**Comment by vernondcole** [comment]
Huh?  Of course it has a Python 3.7 version. Perhaps something is wrong
with your requirements file?

> C:\Users\Owner>py --version
> Python 3.7.1
>
> C:\Users\Owner>type requirements.txt
> pywin32>=223
>
> C:\Users\Owner>py -m pip install -r requirements.txt
> Requirement already satisfied: pywin32>=223 in
> c:\python37\lib\site-packages (from -r requirements.txt (line 1)) (224)
>
> C:\Users\Owner>
>

**Comment by ralfhauser** [comment]
same with python 3.8 as per https://github.com/jupyter/notebook/issues/4909

**Comment by softmarshmallow** [comment]
updates?

**Comment by starlightromero** [comment]
Why did this issue close?

**Comment by glyph** [comment]
I'm also on python 3.8 and I don't see the issue on my windows 10 development machine.  PyInstaller itself no longer even depends on pywin32, it's using pywin32-ctypes, but there's also a wheel available for pywin32 itself and it installs without issue.

Perhaps you should open a new issue describing your specific symptoms?

**Comment by Dharmesh007** [comment]
Could not find a version that satisfies the requirement pywin32==300

**Comment by selfcontrol7** [comment]
Working on CentOS 8 and I have the same issue. 
Please, any updates?

**Comment by webknjaz** [comment]
@selfcontrol7 this library is Windows-specific. Trying to run it on other platforms is pointless.

**Comment by DiaHidvegi** [comment]
Any updates? Still not working..

**Comment by mhammond** [comment]
Works for me and most others. This makes it very difficult for me to work out what's odd about your environment.

**Comment by vernondcole** [comment]
The original problem was a restriction in the format of a requirements file.
The >= operator only works with structured version numbers, like 2.3.4
Since pywin32 uses integer version numbers, you cannot use a greater-than operation, only an exact version.

**Comment by webknjaz** [comment]
I'm pretty sure that this operator works in all cases

**Comment by webknjaz** [comment]
I'm pretty sure that this operator works in all cases

**Comment by annemaryjose** [comment]
Anyone have a fix to this?

**Comment by vernondcole** [comment]
My error. webknjaz was correct that PIP does parse integer version numbers correctly.
The problem seen by me, and, I suppose, most others, is that Windows parses the ">" sign as a redirect operator.
Therefore, when you type `py -m pip install pywin32>=300` Windows will run the installer, and will create a file named "300" and will write the text there intended to inform the user about the progress of the installation.
To use relative version numbers on the command line, you must QUOTE the command. . .
`py -m pip install "pywin32>=301"`
will work as it should.

**Comment by fabiansald** [comment]
Hi! I've hit this issue on Windows 2019 with Python 3.10, fresh install:

```
ERROR: Could not find a version that satisfies the requirement pywin32>=223 (from pypiwin32) (from versions: none)
ERROR: No matching distribution found for pywin32>=223
```

Could it be a bug with Python 3.10?

Thanks!

**Comment by pfmoore** [comment]
> Could it be a bug with Python 3.10?

Nope, it's just that wheels for Python 3.10 haven't been published yet.

**Comment by Amanpreet708** [comment]
could not find a version that satisfies the requirement pywin32==303
no matching distribution found for pywin32==303

i am getting this error at time of deploying my app. Anyone plz help me to resolve .

**Comment by mhammond** [comment]
> i am getting this error at time of deploying my app. Anyone plz help me to resolve .

I suspect you are trying to use it somewhere other than Windows - pywin32 is only available on Windows.

**Comment by Amanpreet708** [comment]
> > i am getting this error at time of deploying my app. Anyone plz help me to resolve .
> 
> I suspect you are trying to use it somewhere other than Windows - pywin32 is only available on Windows.

Nope.... I am doing it on Windows 7

**Comment by mhammond** [comment]
huh - sorry, but in that case I have no idea - pywin32 build 303 is certainly available at https://pypi.org/project/pywin32/

**Comment by Ankit-Rao-lab** [comment]
any updates?
