### ISSUE TITLE
pywin32 does not publish a python3 wheel, breaking pypiwin32

### ISSUE THREAD

**Issue by jmholla** [mhammond/pywin32#1174]
I wasn't sure where to post this, since pypiwin32 doesn't seem to have its own home, but pypiwin32 introduced a dependency on pywin32 which either never has, or stopped providing python 3 wheels. This means you cannot install the latest into a python 3 environment.

``
Collecting pywin32>=223 (from pypiwin32->pyinstaller)

  Could not find a version that satisfies the requirement pywin32>=223 (from pypiwin32->pyinstaller) (from versions: )

No matching distribution found for pywin32>=223 (from pypiwin32->pyinstaller)
``

**Comment by mhammond** [comment]
pywin32 supports python 3.5, 3.6 and 3.7. I suspect you are trying to install it on an old python 3.x version, and if so, you should consider upgrading.

**Comment by jmholla** [comment]
I am running python 3.5.

``
C:\U\j\VEs> virtualenv -p python3.5.exe pywin32_issue
Running virtualenv with interpreter C:\Program Files (x86)\Python 3.5\python3.5.exe
Using base prefix 'C:\\Program Files (x86)\\Python 3.5'
New python executable in C:\Users\jholland\VEs\pywin32_issue\Scripts\python3.5.exe
Also creating executable in C:\Users\jholland\VEs\pywin32_issue\Scripts\python.exe
Installing setuptools, pip, wheel...done.

C:\U\j\VEs> pywin32_issue\Scripts\activate

C:\U\j\VEs> pip install -i https://pypi.org pywin32
Collecting pywin32
  Could not find a version that satisfies the requirement pywin32 (from versions: )
No matching distribution found for pywin32

C:\U\j\VEs> python --version
Python 3.5.2

C:\U\j\VEs>
``

**Comment by mhammond** [comment]
What I get:
> C:\Users\skip\AppData\Local\Programs\Python\Python35>python -m pip install pywin32
> Collecting pywin32
>   Downloading pywin32-223-cp35-cp35m-win_amd64.whl (9.0MB)
>     100% |################################| 9.0MB 172kB/s
> Installing collected packages: pywin32
> Successfully installed pywin32-223
> 
> C:\Users\skip\AppData\Local\Programs\Python\Python35>python --version
> Python 3.5.1

**Comment by jmholla** [comment]
Ah. You have to pass the pypi folder as well. So installation is
pip install -i https://pypi.org/pypi pywin32

Sorry for bothering you with this.
