### ISSUE TITLE
Failed installation

### ISSUE THREAD

**Issue by dhenryFabrice** [mhammond/pywin32#1180]
Hi,

I have installed pywin32 with pywin32-223.win-amd64-py3.6.exe on a windows10 computer and python 3.6: Python 3.6.4 (v3.6.4:d48eceb, Dec 19 2017, 06:54:40) [MSC v.1900 64 bit (AMD64)] on win32
I got an error : ModuleNotFoundError: No module named 'win32.error' when importing
import win32com.client
As the bitness and the version of python seems to be correct I have no clue on what is going one.

Any help will be very appreciated.

Best regards

**Comment by aronhelser** [comment]
version 223 doesn't 'import' for me on Win10 + python3.6. I had to revert to version 220, which works well.

**Comment by thopiekar** [comment]
@dhenryFabrice What makes me curious is your version: "v3.6.4:d48eceb"
Are Python installations now "tagged" like this? Because I never noticed it and can imagine you built Python yourself.

Thanks! :)

**Comment by b3bb** [comment]
For a workaround - works fine (for me) with Anaconda:
```
(base) C:\Users\micha>ipython
Python 3.6.5 |Anaconda custom (64-bit)| (default, Mar 29 2018, 13:32:41) [MSC v.1900 64 bit (AMD64)]
Type 'copyright', 'credits' or 'license' for more information
IPython 6.3.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import win32com.client

In [2]: win32com.client
Out[2]: <module 'win32com.client' from 'C:\\Users\\micha\\Anaconda3\\lib\\site-packages\\win32com\\client\\__init__.py'>
```
Current Version is 223:
```
(base) C:\Users\micha>pip show pywin32
Name: pywin32
Version: 223
Summary: Python for Window Extensions
Home-page: https://github.com/mhammond/pywin32
Author: Mark Hammond (et al)
Author-email: mhammond@skippinet.com.au
License: PSF
Location: c:\users\micha\anaconda3\lib\site-packages
Requires:
```
If this is an option for you: [Download Anaconda Distribution Webpage](https://www.anaconda.com/download/)

Minimal Version (Anaconda Installer includes ~ 200 Packages) is [Miniconda](https://conda.io/miniconda.html). Minconda includes Package Manager and Python - you have to install pywin32 with `conda install pywin32`

**Comment by b3bb** [comment]
@thopiekar 
```
Python 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 17:00:18) [MSC v.1900 64 bit (AMD64)] on win32
```
for CPython from https://www.python.org/ftp/python/3.6.5/python-3.6.5-amd64.exe

**Comment by mhammond** [comment]
Can you please paste the complete traceback you get?
