### ISSUE TITLE
Get errors 7000 and 7009

### ISSUE THREAD

**Issue by dacoolChang** [mhammond/pywin32#1182]
The service will fail to start when we reboot the OS in some computers, when this happens we will get error code 7000 and 7009 in the event viewer.
7000: The ServiceName service failed to start due to the following error:
The service did not respond to the start or control request in a timely fashion.
7009: A timeout was reached (30000 milliseconds) while waiting for The ServiceName service to connect.

We checked our program, the Service timeout was before launching our program. We have no idea what made the Service timeout, we found a workaround after searching as link below.
https://support.microsoft.com/en-us/help/922918/a-service-does-not-start-and-events-7000-and-7011-are-logged-in-window

We don’t think this is a good solution because it is not a good idea to change user’s registry. Please help to provide the solution if there is any. Thank you.

**Comment by mhammond** [comment]
Please see https://github.com/mhammond/pywin32/blob/master/README.md#support for how to get support for pywin32
