### ISSUE TITLE
msmq call in python 3.6

### ISSUE THREAD

**Issue by jeffjapan** [mhammond/pywin32#1194]
The following code works in python 3.4 / pywin32 version 219, but throws an exception in python 3.6.4 or 3.6.5 / pywin32 version 222 or 223. (Both 32 and 64 bit installations of either.)

**Code:**
from win32com.client import Dispatch
queue = Dispatch("MSMQ.MSMQQueueInfo")
message = Dispatch("MSMQ.MSMQMessage")
message.AdminQueueInfo = queue

**Stack Trace:**
Traceback (most recent call last):
  File ".\bug.py", line 5, in <module>
    message.AdminQueueInfo = queue
  File "C:\Python3\lib\site-packages\win32com\client\dynamic.py", line 565, in __setattr__
    self._oleobj_.Invoke(entry.dispid, 0, invoke_type, 0, value)
pywintypes.com_error: (-2147352573, 'Member not found.', None, None)

**Comment by mhammond** [comment]
You probably want "EnsureDispatch" so you have early bindings setup, but please see https://github.com/mhammond/pywin32/blob/master/README.md#support for how to get support.
