### ISSUE TITLE
_GetDescInvokeType regression on dynamic.py

### ISSUE THREAD

**Issue by GitBadSanta** [mhammond/pywin32#1198]
Regarding this [commit](https://github.com/mhammond/pywin32/commit/a22ddedfd0d1a117c95876bf7e25e2dd4a419604#diff-f7b7ba0d109e33715b45f2165b6ba329)

We found a regression when trying to set ```AdminQueueInfo``` on an ```MSMQ.MSMQMessage``` as shown in this sample :

<pre>
from win32com.client import Dispatch
import pythoncom

def _GetDescInvokeTypeNew(entry, invoke_type):
    # determine the wFlags argument passed as input to IDispatch::Invoke
    if not entry or not entry.desc: return invoke_type
    varkind = entry.desc[4] # from VARDESC struct returned by ITypeComp::Bind
    if varkind == pythoncom.VAR_DISPATCH and invoke_type == pythoncom.INVOKE_PROPERTYGET:
        return pythoncom.INVOKE_FUNC | invoke_type # DISPATCH_METHOD & DISPATCH_PROPERTYGET can be combined in IDispatch::Invoke
    else:
        return invoke_type

def _GetDescInvokeTypeOld(entry, default_invoke_type):
    if not entry or not entry.desc: return default_invoke_type
    return entry.desc[4]

queue = Dispatch("MSMQ.MSMQQueueInfo")
message = Dispatch("MSMQ.MSMQMessage")

attr = 'AdminQueueInfo'
message.__LazyMap__(attr)
entry = message._olerepr_.propMapPut[attr]

invoke_type = _GetDescInvokeTypeNew(entry, pythoncom.INVOKE_PROPERTYPUT)
message._oleobj_.Invoke(entry.dispid, 0, invoke_type, 0, "TOTO")
</pre>
 
Previous code was returning ```8```, corresponding to ```entry.desc[4]```.
New code is returning ```invoke_type = INVOKE_PROPERTYPUT```, so ```4```, that made invoke crash. 

I'm not expert so I'm not understanding the underlying reason of this update, but what do you think of this change : 

https://github.com/GitBadSanta/pywin32/commit/6b4dcb9b5609d3b6dd210b148f1d11f48f751200

PS : This is covering issue [1194](https://github.com/mhammond/pywin32/issues/1194)

**Comment by thopiekar** [comment]
Great! Could you create a pull request for that?

Additionally, it would be nice if you could edit your commits description with some technical details. I'm not a real expert in MS development, but other people, who do better, could confirm that your statement is correct and your pull request could get merged sooner.

Regards!

**Comment by mhammond** [comment]
Should be fixed by 1350d43
