### ISSUE TITLE
win32helpmodule: Compilation error when building for Python 3.4 or 3.3

### ISSUE THREAD

**Issue by thopiekar** [mhammond/pywin32#1200]
Caught this while updating my AppVeyor recipe with the latest changes.
I have never seen this errors before, so I guess they are due to https://github.com/mhammond/pywin32/commit/c2302d46ee2eb99c7e29e8325cc21ced07312b0c

https://ci.appveyor.com/project/thopiekar/pywin32/build/1.0.106

PS: Can see the same in Python 3.3

```
win32helpmodule.cpp
win32/src/win32helpmodule.cpp(2549) : warning C4018: '<' : signed/unsigned mismatch
c:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\BIN\link.exe /DLL /nologo /INCREMENTAL:NO /LIBPATH:C:\Python34\libs /LIBPATH:C:\Python34\PCbuild /LIBPATH:build\temp.win32-3.4\Release "/LIBPATH:C:\Program Files (x86)\Windows Kits\8.1\lib\winv6.3\um\x86" htmlhelp.lib user32.lib advapi32.lib /EXPORT:PyInit_win32help build\temp.win32-3.4\Release\win32/src/win32helpmodule.obj /OUT:build\lib.win32-3.4\win32\win32help.pyd /IMPLIB:build\temp.win32-3.4\Release\win32/src\win32help.lib /MANIFEST:NO /MACHINE:x86 /BASE:0x1ea70000 /DEBUG /PDB:build\temp.win32-3.4\Release\win32help.pdb
   Creating library build\temp.win32-3.4\Release\win32/src\win32help.lib and object build\temp.win32-3.4\Release\win32/src\win32help.exp
htmlhelp.lib(init.obj) : error LNK2001: unresolved external symbol ___report_rangecheckfailure
build\lib.win32-3.4\win32\win32help.pyd : fatal error LNK1120: 1 unresolved externals
error: command 'c:\\Program Files (x86)\\Microsoft Visual Studio 10.0\\VC\\BIN\\link.exe' failed with exit status 1120
```

**Comment by mhammond** [comment]
Note that I'm only building pywin32 for py 3.5 and up, but to fix this we will need to expand the check at https://github.com/mhammond/pywin32/blob/c2302d46ee2eb99c7e29e8325cc21ced07312b0c/win32/src/win32helpmodule.cpp#L23

**Comment by thopiekar** [comment]
Well, the question is what we want from this point.
On the one hand we can fix it there or we drop officially support for Python3 < 3.5 and remove the tests for these versions from AppVeyor.

**Comment by mhammond** [comment]
> we drop officially support for Python3 < 3.5

Without binary builds for those versions, I think we can consider official support is dropped.

**Comment by thopiekar** [comment]
Alright, will kick it out from the CI then. Personally, I would keep this issue open, but mark it as "won't fix". So if someone got that issue and really wants to fix it, then she/he can fix it on her/his own.

But, yeah, it is up to you how to handle this.

**Comment by mhammond** [comment]
Thanks! I'd probably take a patch for this as a courtesy (and because it would be trivial) but in general I'd discourage and push back on patches to support unsupported versions, so I think we should kill it.
