### ISSUE TITLE
How to cast to a `coclass_interface`

### ISSUE THREAD

**Issue by kaifresh** [mhammond/pywin32#1202]
Hi ya'll,

I can't find any good documentation on the net about this, so I'm opening an issue here.

I've used `makepy.py` to generate some wrappers around a COM object. Now I need to cast from one generated class to another interface that it implements (i.e. listed in the `coclass_interfaces` array). 

Does anyone know how to perform this cast?  I'm sure its straightforward.

Thanks! 😄

**Comment by mhammond** [comment]
Please see https://github.com/mhammond/pywin32/blob/master/README.md#support for how to get support.
