### ISSUE TITLE
how can i change win proxy via this lib

### ISSUE THREAD

**Issue by Dashu-Xu** [mhammond/pywin32#1204]
thanks for this lib, i can't find the doc for this lib, so i just put my question here.
i want change my win10  proxy let all my software get internet use this proxy.
please tell my what should i do to change proxy and reset it.
or you can just tell my where the doc is ,thank you

**Comment by mhammond** [comment]
Please see https://github.com/mhammond/pywin32/blob/master/README.md#support for how to get support
