### ISSUE TITLE
Means of enabling triggers via win32com.taskscheduler?

### ISSUE THREAD

**Issue by zarquon5** [mhammond/pywin32#1205]
We are using the win32com.taskscheduler to create tasks in Windows, but what we've discovered is that, in such created tasks, the "status" field of triggers  always says "Disabled," and we have to manually edit the properties of the trigger to check the "Enabled" box.  I've tried to follow some examples I found online about setting the Enable bit of the trigger to True, but this doesn't seem to work through the python interface.  Is this feature missing, or if not, how do I achieve my desired result?  (without the trigger being enabled, the task never actually fires.)

**Comment by mhammond** [comment]
Please see https://github.com/mhammond/pywin32/blob/master/README.md#support for how to get support for this package.
