### ISSUE TITLE
Can't open event log on remote server. 

### ISSUE THREAD

**Issue by lintamacar** [mhammond/pywin32#1220]
The line of code that's a problem is this: 

`hand = win32evtlog.OpenEventLog(MY_SERVER, MY_LOGTYPE)`

I get this error: 

> pywintypes.error: (5, 'OpenEventLogW', 'Access is denied.')

This code works fine when I actually run it on my remote server directly, and I can view its event log from my local server by connecting to it through the Windows Event Viewer. There are no parameters for user credentials or anything, so I don't know what to do.

**Comment by mhammond** [comment]
Please see https://github.com/mhammond/pywin32/blob/master/README.md#support for how to obtain support.
