### ISSUE TITLE
pywintypes.TimeStamp() constructor crashes interpreter

### ISSUE THREAD

**Issue by kunom** [mhammond/pywin32#1224]
This is Python 3.7.0 64-bit from python.org with debug symbols and pywin32 2.2.3 from PyPI (`py -m pip install pywin32`).

The following code crashes the intpreter:
```python
import pywintypes
pywintypes.TimeStamp(0)
```

The crash location is
```
python37.dll!new_date_ex(int year, int month, int day, _typeobject * type) Line 841	C
pywintypes37.dll!000000006e39931a()	Unknown
pywintypes37.dll!000000006e399708()	Unknown
[...]
```
where the `type` argument is unexpectedly `NULL`, leading to an AccessViolation.

I encountered the crash as part of `win32security.InitializeSecurityContext()` (see the third return value) which is used by the requests-negotiate-sspi package, but #1221 might also be related.

**Comment by matt-hoskins** [comment]
Looks like a similar issue to what I've reported here with a general problem of how pywin32's datetime stuff is calling _datemodule in the pip build of pywin32 for 3.7.0: https://github.com/mhammond/pywin32/issues/1233

**Comment by mhammond** [comment]
I believe this will be fixed by https://github.com/mhammond/pywin32/releases/tag/b224 - please reopen if that's not the case.

**Comment by kunom** [comment]
@mhammond Yes. Release 2.2.4 on PyPI does not show anymore the described crash.
