### ISSUE TITLE
problem reporting f string syntax error

### ISSUE THREAD

**Issue by ghost** [mhammond/pywin32#1227]
build 223
 windows 10 
python version = '3.6.4 (v3.6.4:d48eceb, Dec 19 2017, 06:04:45) [MSC v.1900 32 bit (Intel)]'
Open a new Python Script and enter:
```
f'{g_f}'
# other code
# other code
f'{g f}'
```
save script; Hit ctrl+shift+c; in the status bar you will see:

`Failed to check - syntax error - invalid syntax (<fstring>, line 1)`

Stare at line 1 trying to find the error. Eventually discover it in line 4.

**Comment by mhammond** [comment]
This looks more like a python issue

```
>>> exec("f'{g_f}'\n# comment\nf'{g f}'\n")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<fstring>", line 1
    (g f)
       ^
SyntaxError: invalid syntax
>>>
```

So Python itself isn't giving any clues about what source like caused the issue. Compare with, say:
```
>>> exec("import sys\n# comment\nfoo bar\n")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<string>", line 3
    foo bar
          ^
SyntaxError: invalid syntax
```

**Comment by Avasam** [comment]
This is either a Python thing, or has been resolved.
Using Python3.9, the right line is shown.
![image](https://github.com/mhammond/pywin32/assets/1350584/4a9d89ad-34f4-40ba-b900-eec412374208)
