### ISSUE TITLE
python 3.7.0 crashes while installing a script as a windows service

### ISSUE THREAD

**Issue by toozik** [mhammond/pywin32#1234]
pywin32 build 223 + python 3.7.0 amd64.
I run _python test_service.py install_
and python crashes.

```
import os, sys
import win32serviceutil,win32api,win32service

class MyService(win32serviceutil.ServiceFramework):
    _svc_name_ = 'TestService'
    _svc_display_name_ = 'TestService'

```

    def SvcDoRun(self):
        pass

    def SvcStop(self):
        self.ReportServiceStatus(win32service.SERVICE_STOP_PENDING)
        self.ReportServiceStatus(win32service.SERVICE_STOPPED)

```
if __name__ == '__main__':
    win32serviceutil.HandleCommandLine(MyService)
```

`

**Comment by baerdt** [comment]
I encountered this issue too on Windows Server 2016 (10.0.14393)

**Comment by stlehmann** [comment]
Same issue on Windows 10 with Python 3.7.0 and pywin32 223

**Comment by mats-erik** [comment]
Ran into the same problem. It's a call to win32api.FindFiles in win32serviceutil.py GetServiceClassString() that causes python.exe to crash without traceback.
Using Python 3.7.0, pywin32 223, Windows Server Server 2016.
In the meantime it can be worked around by making HandleCommandLine() skip the GetServiceClassString() call like this:

service_class_string = os.path.splitext(os.path.abspath(__file__))[0] + '.Service'
win32serviceutil.HandleCommandLine(Service, serviceClassString=service_class_string)

**Comment by mhammond** [comment]
I believe this will be fixed by https://github.com/mhammond/pywin32/releases/tag/b224 - please reopen if that's not the case.

**Comment by DavidVentura** [comment]
it does indeed fix it for me

**Comment by mats-erik** [comment]
Works now. Thanks!
