### ISSUE TITLE
Wrong reference to Excel COM object (Range.Characters)

### ISSUE THREAD

**Issue by llorencs** [mhammond/pywin32#1235]
When we want to access to a specific character of the Range.Characters it returns an error that the object Characters is not callable. 

However, according to the Microsoft Office Reference of this object it has 2 arguments: start and length.

Snippet of the code:

```
from win32com.client.gencache import EnsureDispatch
xl = EnsureDispatch('Excel.Application')
wb = Workbooks.Add()
sh = wb.ActiveSheet
sh.Cells(1,1).Value = 'Test'
print(sh.Cells(1,1).Characters.Text)
```
If we want to access individually to a character like:
sh.Cells(1,1).Characters(1,1)

We get a TypeError of Object not Callable.

However, this COM object interface should be callable, or at least it is expected to be.

**Comment by ep081106** [comment]
hi！ i find the same issue also？ 
i want to change the color of some characters in a string，such as change CDE to the red font in “abCDEf”，i try to use the “Range("AK4").Characters（3，3）” and get the error ：“pywintypes.com_error: (-2147352573, '找不到成员。', None, None)”
or could you give me a better way to change the characters‘s color in a string？

**Comment by Avasam** [comment]
Looks like this may have been fixed.

Python 3.9, pywin32 306, Windows 10, Excel 16
```py
from win32com.client.gencache import EnsureDispatch

xl = EnsureDispatch('Excel.Application')
if int(xl.Version.split(".")[0]) >= 8:
    wb = xl.Workbooks.Add()
else:
    wb = xl.Workbooks().Add()
sh = wb.ActiveSheet
sh.Cells(1,1).Value = 'Test'
print(sh.Cells(1,1).Characters.Text)
```
Successfully prints `Test`

Closing, but let us know if you replicate with the same snippet.
