### ISSUE TITLE
Add a web link to the docs for the project in the README.md file.

### ISSUE THREAD

**Issue by rswgnu** [mhammond/pywin32#1243]
I suggest you add a link to http://timgolden.me.uk/pywin32-docs/ in your README.md file so people who are just browsing the project on Github have a quick way to look at what APIs it covers and how.  Right now the README.md is woefully lacking in detail about the project, so this would help a lot.

**Comment by Avasam** [comment]
I agree @tjguk 's doc is nice, but closing in favor of https://github.com/mhammond/pywin32/issues/394#issuecomment-421921395 to keep the discussion centralized.
