### ISSUE TITLE
Python 3.7.0 hangs up getting Outlook Calendar Start or End Properties of an Appointment Item

### ISSUE THREAD

**Issue by javiergmarcos** [mhammond/pywin32#1246]
This code worked ok in Python 3.5.2. in the same machines.
In Python 3.7.0 it hangs up when you try to get the Appointment Properties Start or End. It hangs up just with the first request for Start or End. No error message appears.

Tested under Windows 10 and Windows 7, both 64 bits. Tested form Command Console and with Jupyter Notebook.
pywin32 is 223

:::Python

```
import win32com.client
import datetime
outlook = win32com.client.Dispatch("Outlook.Application").GetNamespace("MAPI")
calendar = outlook.GetDefaultFolder(9)
appointments = calendar.Items
appointments.Sort("[Start]")
appointments.IncludeRecurrences = "True"

#This block restrict the time range. Doesn't change the hang up
begin = datetime.date(2018, 9, 1)  #year, month, day
end = datetime.date(2018, 10, 1)
print(f"Activities from: {begin}, to: {end}")
restriction = "[Start] >= '" + begin.strftime("%d/%m/%Y") + "' AND [End] <= '" +end.strftime("%d/%m/%Y") + "'"
print("restriction:", restriction)
restrictedItems = appointments.Restrict(restriction)

# The problem arise accessing as a unique item 
appointment = restrictedItems[1]
print(appointment.Subject)
print(appointment.Organizer)
print(appointment.Start) # Generate Hang up
print(appointment.End) # Generate Hang up

# Also hangs up inside a loop of appointments
for appointment in restrictedItems:
    print(appointment.Subject)
    print(appointment.Organizer)
    print(appointment.Start) # Generate Hang up
    print(appointment.End) # Generate Hang up
```

**Comment by mhammond** [comment]
I believe this will be fixed by https://github.com/mhammond/pywin32/releases/tag/b224 - please reopen if that's not the case.

**Comment by javiergmarcos** [comment]
Hi Mark,

 

Now It works perfect whit Python 3.7.0 both Windows 7 and Window 10!!

 

I appreciate your involvement in solving this issue. Thanks for your support and fast response.

 

Have a nice day and Regards.

 

Javier González Marcos | +34 638 210 480

Dhomo Solutions | Calle Aurora, 28 | 28035 | Madrid

 

De: Mark Hammond [mailto:notifications@github.com] 
Enviado el: viernes, 28 de septiembre de 2018 8:54
Para: mhammond/pywin32
CC: javiergmarcos; Author
Asunto: Re: [mhammond/pywin32] Python 3.7.0 hangs up getting Outlook Calendar Start or End Properties of an Appointment Item (#1246)

 

I believe this will be fixed by https://github.com/mhammond/pywin32/releases/tag/b224 - please reopen if that's not the case.
