### ISSUE TITLE
pywintypes37.dll not find

### ISSUE THREAD

**Issue by ybpub** [mhammond/pywin32#1247]
i use “win32serviceutil.ServiceFramework” to create window server

the service inatall success, but cannot start
so i find and execute the exefile with service , it report "can not find pywintypes37.dll"

**Comment by mhammond** [comment]
Is this with a pip installed pywin32? If so, you probably need to run "python pywin32_postinstall.py -install" from an elevated command prompt - see https://github.com/mhammond/pywin32#installing-via-pip

Please feel free to reopen if that's not the case.

**Comment by ybpub** [comment]
it work, thank you very much
