### ISSUE TITLE
PyObject_FromWIN32_FIND_DATA crashes on Windows 10

### ISSUE THREAD

**Issue by GChristensen** [mhammond/pywin32#1252]
PyObject_FromWIN32_FIND_DATA crashes Python 3.7 on Windows 10 (1803) here: https://github.com/mhammond/pywin32/blob/d64fac8d7bda2cb1d81e2c9366daf99e802e327f/com/win32comext/shell/src/PyIShellLink.cpp#L65

Was a great showstopper for me. Since I have no possibility to test on which Python/Windows versions crash takes place, just locally patched by omitting find data, since I don't need it.

**Comment by mhammond** [comment]
I believe this will be fixed by https://github.com/mhammond/pywin32/releases/tag/b224 - please reopen if that's not the case.
