### ISSUE TITLE
Win32 exception occurred releasing IUnknown at ...

### ISSUE THREAD

**Issue by axc450** [mhammond/pywin32#1259]
Im using pywin32 to interact with the SAPB1 DI API COM object to perform some operations. The module works correctly and my operations succeed, but on a ".Disconnect()" or the program ending, I get:
```
Win32 exception occurred releasing IUnknown at ...
```
Googling around, this didnt turn up much, however, adding 
```PYTHON
import sys
sys.coinit_flags = 0
```
does seem to fix this issue. Is this exception an issue? Can it be ignored? Is the sys fix safe?

My full code can be found below (sensitive info omitted). Apologies if this is more of a problem with the COM object then pywin32!

```PYTHON
# To fix exception #
import sys
sys.coinit_flags = 0

import win32com.client

vCompany = win32com.client.Dispatch("SAPBobsCOM.Company")
vCompany.Server = ...
vCompany.CompanyDB = ...
vCompany.UserName = ...
vCompany.Password = ...
vCompany.DbServerType = ...
vCompany.LicenseServer = ...

status = vCompany.Connect()

if status != 0:
    print(vCompany.GetLastError())
    exit(1)

print(vCompany.CompanyName)

order = vCompany.GetBusinessObject(17)
# Order is set up here
order.Add()

vCompany.Disconnect() # Exception is thrown on this line
```

**Comment by mhammond** [comment]
This is an issue with the COM object. The coinit_flags change is probably fine, especially in a single-threaded app.
