### ISSUE TITLE
import winreg fail on python3

### ISSUE THREAD

**Issue by schultzm** [mhammond/pywin32#1261]
Hi, 

Could you please help me to fix this issue?

When running the `pywin32` install, I get:

```
import winreg # py3k
    ModuleNotFoundError: No module named 'winreg'
```

I am unable to find a suitable `winreg` module for python3.  I have seen all the posts about it being renamed in python3 to `winreg` instead of `_winreg`; however a `pip3 search winreg` returns nothing.   Without `winreg`, I am unable to install `pywin32`.  

Tha

**Comment by mhammond** [comment]
Something must be wrong with your Python install - winreg is builtin to python 3.

**Comment by Lucas-C** [comment]
I had the same error using Python3.6.2. Tested under `cmd.exe` & Cygwin

**Comment by mhammond** [comment]
If you mean the cygwin version of python, then that's probably expected.

However, if you have windows python and `py -3 -c "import winreg"` doesn't work, your python is broken.

**Comment by phatjak** [comment]
> If you mean the cygwin version of python, then that's probably expected.
> 
> However, if you have windows python and `py -3 -c "import winreg"` doesn't work, your python is broken.

I did insert the command above and it worked, but when I try to import it to a python script it won't work.

**Comment by riodw** [comment]
Is it possible to get `winreg` working in cygwin?

**Comment by Dentrax** [comment]
Hit same issue, I think we can not compile `pywin32` on Linux, right?

**Comment by mhammond** [comment]
> Hit same issue, I think we can not compile `pywin32` on Linux, right?

1) pywin32 does not work on linux, correct.
2) winreg has nothing to do with pywin32 in the first place.

**Comment by ChengruiMeng** [comment]
Hello, May I ask for how you solved the problem in the end ?
