### ISSUE TITLE
The keybd_event of shift + arrows does not work as I have expected.

### ISSUE THREAD

**Issue by HE-Xinyu** [mhammond/pywin32#1267]
I am using Win10, Python 3.6 (both in 64-bit), and the latest release version of pywin32.

My code looks something like this:

```
def work():
    # Alt + Tab works, but Shift + Down arrow doesn't.
    win32api.keybd_event(18, 0, 0, 0)  # Alt
    win32api.keybd_event(9, 0, 0, 0)  # Tab
    win32api.keybd_event(18, 0, win32con.KEYEVENTF_KEYUP, 0)
    win32api.keybd_event(9, 0, win32con.KEYEVENTF_KEYUP, 0)

    time.sleep(0.5)

    win32api.keybd_event(16, 0, 0, 0)  # Shift
    win32api.keybd_event(40, 0, 0, 0)  # Down arrow
    win32api.keybd_event(16, 0, win32con.KEYEVENTF_KEYUP, 0)
    win32api.keybd_event(40, 0, win32con.KEYEVENTF_KEYUP, 0)
```

My intension was to first switch to a notepad, then select the current line. But after I ran the code, it seems that only the Down Arrow button was pushed (i.e. the line was not selected). I also tried Shift + Right Arrow and Shift + End, but they also failed. (I tried to add time.sleep(0.05) in multiple positions, but I couldn't make it work neither.)

One thing I did notice is that Ctrl + A worked, although it was not what I want. Shift + Z worked too.

**Comment by mhammond** [comment]
Please see https://github.com/mhammond/pywin32/blob/master/README.md#support for how to get support for using this package.
