### ISSUE TITLE
how can i register to an eventlog source?

### ISSUE THREAD

**Issue by MannusEtten** [mhammond/pywin32#1268]
i have a custom event log called "BGT Monitoring"

i want a handler to that so i can write to this eventlog from python
hAppLog = win32evtlog.RegisterEventSource(None, "BGT Monitoring Log".encode("ascii"))

result is:  Objects of type 'bytes' can not be converted to Unicode.

what can i do?

**Comment by mhammond** [comment]
Please see https://github.com/mhammond/pywin32/blob/master/README.md#support for how to obtain support for this package.
