### ISSUE TITLE
How can see log in context menu handler?

### ISSUE THREAD

**Issue by winneryong** [mhammond/pywin32#1270]
Hi,
I run context_menu.py in win10, and the context menu is running is ok.
context_menu.py contains many print statement.
 how to see print statement output in windows?

**Comment by mhammond** [comment]
I tend to use win32traceutil - see the comments at the top of that library. In general, please see https://github.com/mhammond/pywin32/blob/master/README.md#support - this tracker is for bugs, not support questions.
