### ISSUE TITLE
No matching distribution found for pywin32

### ISSUE THREAD

**Issue by E3V3A** [mhammond/pywin32#1272]
I'm trying to install this with `pip install pywin32` on Cygwin (Windows x64), but I'm welcomed by the very popular error: 

```bash
# pip3 install pywin32
Collecting pywin32
  Could not find a version that satisfies the requirement pywin32 (from versions: )
No matching distribution found for pywin32
```
**What does this mean?**

I'm using Python 3.6.4.

This issue may be related to #1177

**Comment by mhammond** [comment]
It means there's no cygwin specific version - you should just use the windows version of python.

**Comment by cup** [comment]
https://github.com/mhammond/pywin32/issues/1378
