### ISSUE TITLE
win32timezone.TimeZoneInfo(u'<timezone name>') produces incorrect  results

### ISSUE THREAD

**Issue by zarquon5** [mhammond/pywin32#1276]
There is still a problem with win32timezone, at least as of pywin32-221:  

If your timezone is Eastern Standard Time, and you  ask for win32timezone.TimeZoneInfo().local(), you get a TimeZoneInfo(u'Eastern Standard Time') object.  However, if you ask for the same thing explicitly, i.e. by win32timezone.TimeZoneInfo(u'Eastern Standard Time'), it _says_ it's the same thing, but it is not, in fact, an equivalent object and it returns the wrong information, viz:
```
>>> import win32timezone
>>> win32timezone.TimeZoneInfo().local()                       # => good object
TimeZoneInfo(u'Eastern Standard Time')

>>> win32timezone.TimeZoneInfo(u'Eastern Standard Time')       # => bad object
TimeZoneInfo(u'Eastern Standard Time')

>>> win32timezone.TimeZoneInfo().local().GetDSTEndTime(2018)                   # => right info
datetime.datetime(2018, 11, 4, 2, 0)

>>> win32timezone.TimeZoneInfo(u'Eastern Standard Time').GetDSTEndTime(2018)   # => wrong info
 datetime.datetime(2018, 10, 28, 2, 0)

```

**Comment by Avasam** [comment]
Looks like this has been fixed at some point between 221 and 300 then.
On both 300 and 306 with the following code:
```py
import win32timezone
win32timezone.TimeZoneInfo.local().timeZoneName
win32timezone.TimeZoneInfo.local().GetDSTEndTime(2018)
win32timezone.TimeZoneInfo(u'Eastern Standard Time').GetDSTEndTime(2018)
```

I get:
```
'Eastern Standard Time'
datetime.datetime(2018, 11, 4, 2, 0)
datetime.datetime(2018, 11, 4, 2, 0)
```
