### ISSUE TITLE
Background mouse events possible?

### ISSUE THREAD

**Issue by Ohmano1** [mhammond/pywin32#1282]
Hello,

I am searching for a possibility to do mouse events(clicks, movements and maybe screenshots and screen recognition) in the background(for example in minimized windows). Is this possible with the pywin32 module?

Is there any alternative for Mac users? I really wanted to stay on Mac OS, but would change if there is no alternative to pywin32 for background mouse movements.

Thanks

**Comment by mhammond** [comment]
Please see https://github.com/mhammond/pywin32/blob/master/README.md#support for how to obtain support for this package.
