### ISSUE TITLE
How to get frame when i handle ie ??

### ISSUE THREAD

**Issue by flyme2012** [mhammond/pywin32#1287]
I want to achieve automation by pywin32 , and  i have two questions : 1. When I use Pywin32 to operate ie, how do I get the existing ie objects?   2. How to Switch Frames in Web Pages ？ frame have not name and id .

**Comment by mhammond** [comment]
Please see https://github.com/mhammond/pywin32/blob/master/README.md#support for how to obtain support for this package.
