### ISSUE TITLE
pywin32 SendMessage return 0 and don't work

### ISSUE THREAD

**Issue by wx409790282** [mhammond/pywin32#1291]
I am new to python and want to write an script to click an program. So pywin32 is good choice and i successfully use it's method like mouse_event

`def mouseClickReally(width,high):
win32api.SetCursorPos([int(width),int(high)])
time.sleep(0.5)
win32api.mouse_event(win32con.MOUSEEVENTF_LEFTDOWN, 0, 0, 0, 0)
time.sleep(0.05)
win32api.mouse_event(win32con.MOUSEEVENTF_LEFTUP, 0, 0, 0, 0)`

but mouse_event need my program stay in front of desktop,and i want to hidden it in background,so i want to change to SendMessage method

`def left_click(hwd, x_position, y_position):
long_position = win32api.MAKELONG(x_position, y_position)
win32gui.PostMessage(hwd, win32con.WM_LBUTTONDOWN, win32con.MK_LBUTTON, long_position)
win32api.PostMessage(hwd, win32con.WM_LBUTTONUP, win32con.MK_LBUTTON, long_position)`

but it doesn't work. i changed it to SendMessage or use RBUTTON. SendMessage just return 0, and nothing happend i wrote in windows10 ,python 3.6,pywin32 224

**Comment by mhammond** [comment]
See README.md for how to obtain support.
