### ISSUE TITLE
Faulty Detection of Win8.1 SDK

### ISSUE THREAD

**Issue by PGAnonamous** [mhammond/pywin32#1293]
I noticed that setup.py is looking in `SOFTWARE\Microsoft\Windows Kits\Installed Roots`. However, on my machine the value it is looking for is in `SOFTWARE\WOW6432Node\Microsoft\Windows Kits\Installed Roots`

Shouldn't it be checking to see if the machine is 64 bit or 32 bit and look in the corresponding registry location?

I ran setup.py build and it built just fine (I had to go and find EdkMdb.h which I got from https://github.com/stephenegriffin/mfcmapi and placed in both win10sdk include/um and win8.1 sdk include/um since I wasn't sure where to put it.) The only thing that wasn't build was exchdapi: No 64-bit library for utility functions available.

**Comment by mhammond** [comment]
That's odd - it implies a 32bit win8.1 sdk on a 64bit host. But I've no objection to a PR that falls back to that key if the "native" key fails.

**Comment by mhammond** [comment]
Fixed in 48db04de
