### ISSUE TITLE
getting error pywintypes.com_error: (-2147221021, 'Operation unavailable', None, None) when connecting to alm

### ISSUE THREAD

**Issue by neeraj2019** [mhammond/pywin32#1305]
Note that issues in this repository are only for bugs or feature requests in the pywin32.

**If you need support or help using this package, please follow [these instructions](https://github.com/mhammond/pywin32/blob/master/README.md#support)** - support or help requests will be closed without comment.

For all bugs, please provide the following information.

* Steps to reproduce the problem.

td = win32com.client.Dispatch("TDApiOle80.TDConnection.1")
    #Starting to connect
td.InitConnectionEx(qcServer)
td.Login(qcUser, qcPassword)
td.Connect(qcDomain, qcProject)
if td.Connected is True:
    print("Connected to " + qcProject)
else:
    print("Connection failed")

* Version of Python and pywin32

python 3.5
pywin32 - 224

**Comment by mhammond** [comment]
Please follow the instructions you quoted for support.
