### ISSUE TITLE
Cite pywin32 using a DOI

### ISSUE THREAD

**Issue by amabdallah** [mhammond/pywin32#1314]
Mark,

Thanks for the very useful tool. Would you please create a DOI for this repository so I can cite it appropriately? Peer-reviewed papers/journals love DOIs :)

Here is how you could easily do it with Zonedo in case you're not aware of it    
https://guides.github.com/activities/citable-code/

Thank you so much for the handy tool
Adel

**Comment by amabdallah** [comment]
I'd like to give you credit in my paper. Please create a DOI :)

**Comment by mhammond** [comment]
You are the first person to request this, and there's more overhead in doing it than I like. I'm happy to go uncredited ;)

**Comment by amabdallah** [comment]
lol come on! giving credit to you is the right thing to do. 
I'm not sure what you mean by overhead. Once you create the link with Zonedo, it becomes automatic. Each time you create a new release, it automatically generates a DOI under the main one

**Comment by vernondcole** [comment]
May I humbly suggest that any web address can be cited using standard
formatting without having to have any software watching it?
How To Cite a Website <https://www.mendeley.com/guides/web-citation-guide>
