### ISSUE TITLE
Unable to import pywin32

### ISSUE THREAD

**Issue by ExpertsGaming** [mhammond/pywin32#1315]
I am making a program that can change time (personal project) and I found some premade code that helps to change it, but when I installed pywin32 (tried both pip and installer), I get `ModuleNotFoundError: No module named 'pywin32'`
This is the code:
`def _win_set_time(time_tuple):
    import pywin32
    # http://timgolden.me.uk/pywin32-docs/win32api__SetSystemTime_meth.html
    # pywin32.SetSystemTime(year, month , dayOfWeek , day , hour , minute , second , millseconds )
    dayOfWeek = datetime.datetime(time_tuple).isocalendar()[2]
    pywin32.SetSystemTime( time_tuple[:2] + (dayOfWeek,) + time_tuple[2:])`

pywin32 version is 224

**Comment by mhammond** [comment]
There's no pwin32 module. http://timgolden.me.uk/pywin32-docs/win32api__SetSystemTime_meth.html says to use `win32api` which is a module included with pywin32.

Please see https://github.com/mhammond/pywin32#support for how to obtain support.
