### ISSUE TITLE
pip install works, setuptools doesn't (Windows Python 3.6.8)

### ISSUE THREAD

**Issue by fdav10** [mhammond/pywin32#1320]
I'm finding that installing pywin32 using pip succeeds whereas listing it as a dependency using the  `install_requires` argument to `setup` in a setup.py file fails.  This is on Windows 10 using Python 3.6.8 64 bit and pywin32==224.

My steps:

**Pip install**
1. Set up an empty virtual env
2.  `pip install pywin32`
3. `python -c "import win32api"`

Results in no output - i.e. successful imoprt

**Setuptools**

1. Set up another fresh virtualenv
2.  create a minimal setup.py consisting of:
```
from setuptools import setup

setup(name='testpackage',
      version=1,
      install_requires=[
          "pywin32",
      ])
```
3. at shell run `python setup.py install`
4. `python -c "import win32api"`
5.  On my machine this results in 
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'win32api'
```

**Comment by macginitie** [comment]
when I try "pip install pywin32" I get:
Could not find a version that satisfies the requirement pywin32 (from versions: )
No matching distribution found for pywin32

**Comment by Aareon** [comment]
Looks suspiciously like a circular depedency issue

**Comment by shriharshmishra** [comment]
> when I try "pip install pywin32" I get:
> Could not find a version that satisfies the requirement pywin32 (from versions: )
> No matching distribution found for pywin32

I am also facing similar issue when running - 
`pip install -r requirements.txt` and my requirement.txt contains `pywin32==224`

**Comment by Avasam** [comment]
> 3\. at shell run `python setup.py install`

Note that [`python setup.py` and the use of setup.py as a command line tool are deprecated](https://packaging.python.org/en/latest/discussions/setup-py-deprecated/#is-setup-py-deprecated). pywin32 itself needs to move away from it. #2208

**Comment by Avasam** [comment]
@fdav10 Due to many changes in the Python packaging ecosystem and improvements to pywin32's own isntallation, could you try again using:
- the latest pip
- latest setuptools
- Python>=3.8
- pywin32 >= 226

---

@shriharshmishra & @macginitie Could you also make sure you are trying to install from a Windows machine ?
