### ISSUE TITLE
Windows Service CWD is System32

### ISSUE THREAD

**Issue by axc450** [mhammond/pywin32#1321]
Hey,

When I install my application as a Windows Service, the CWD of this app is the System32 folder despite the service showing the correct path under "Path to executable:".

I noticed that `sys.argv[0]` contains the correct path too, so I can extract it and then use a `os.chdir` before I run my app. I was wondering if this is intended behaviour and if this is the correct way to be dealing with this (if so, is this the correct place to be changing the CWD?). In my opinion, the default CWD of a service should be where the exe is, but I am in no means an expert with Windows Services 😄  Code for service below:

```
import servicemanager
import socket
import sys
import win32event
import win32service
import win32serviceutil

import os


class TestService(win32serviceutil.ServiceFramework):
    _svc_name_ = "TestService"
    _svc_display_name_ = "Test Service"

    def __init__(self, args):
        win32serviceutil.ServiceFramework.__init__(self, args)
        self.hWaitStop = win32event.CreateEvent(None, 0, 0, None)
        socket.setdefaulttimeout(60)

    def SvcStop(self):
        self.ReportServiceStatus(win32service.SERVICE_STOP_PENDING)
        win32event.SetEvent(self.hWaitStop)

    def SvcDoRun(self):
        # Here I am changing the CWD. We can use sys.argv[0] to get the path.
        os.chdir("C:\\Test")

        import app
        app.run()


if __name__ == '__main__':
    if len(sys.argv) == 1:
        servicemanager.Initialize()
        servicemanager.PrepareToHostSingle(TestService)
        servicemanager.StartServiceCtrlDispatcher()
    else:
        win32serviceutil.HandleCommandLine(TestService)
```

Related: #720

**Comment by mhammond** [comment]
windows itself sets the cwd - this is the same behaviour you'd get from a C implemented service. You can change the cwd at any point you like.
