### ISSUE TITLE
LogonUser via LOGON32_LOGON_NEW_CREDENTIALS

### ISSUE THREAD

**Issue by kureeoffsec** [mhammond/pywin32#1323]
* Expected behavior:

After creating a new logon session, and then applying the token with impersonation, I want to use the token to authenticate to a remote system (for example to net use). 

Actual behavior.
The remote system does not receive the impersonated token. Instead it receives the default token, and authentication fails. 

* Steps to reproduce the problem.

from subprocess import Popen, PIPE
import subprocess
import win32api
import win32con
import win32security

domain = 'domain.com'
username = 'user'
password = 'password'

handle = win32security.LogonUser(username, domain, password, win32con.LOGON32_LOGON_NEW_CREDENTIALS, win32con.LOGON32_PROVIDER_WINNT50)
win32security.ImpersonateLoggedOnUser(handle)
#call command on remote system with subprocess
si = win32process.STARTUPINFO()
command = 'cmd.exe'
procArgs = (None,  # appName
                command,  # commandLine
                None,  # processAttributes
                None,  # threadAttributes
                1,  # bInheritHandles
                win32process.CREATE_NEW_CONSOLE,  # dwCreationFlags
                None,  # newEnvironment
                None,  # currentDirectory
                si) # startupinfo
procHandles = win32process.CreateProcess(*procArgs)

* Version of Python and pywin32
Python 3.7.2
pywin32==224

**Comment by mhammond** [comment]
Please see https://github.com/mhammond/pywin32#support
