### ISSUE TITLE
how can I use win32gui?

### ISSUE THREAD

**Issue by JackyNiu** [mhammond/pywin32#1324]
How can I use win32gui, there have nothing in win32gui,

`def AbortPath(*args, **kwargs): # real signature unknown
    pass

def AlphaBlend(*args, **kwargs): # real signature unknown
    pass

def AngleArc(*args, **kwargs): # real signature unknown
    pass

def AnimateWindow(*args, **kwargs): # real signature unknown
    pass

def AppendMenu(*args, **kwargs): # real signature unknown
    pass

def Arc(*args, **kwargs): # real signature unknown
    pass`

python 3.5.4  ; pywin32 virsion 224

**Comment by mhammond** [comment]
Please see https://github.com/mhammond/pywin32#support
