### ISSUE TITLE
win32gui.getWindwoRect() wrong on retina screen

### ISSUE THREAD

**Issue by huhuang03** [mhammond/pywin32#1330]
* Expected behavior and actual behavior.
win32gui.GetWindowRect() return different size vs spy++。

for example:
the sply++ return (3, 3, 300, 300)
but win32gui return (2, 2, 200, 200) 
which is x1.5 scale.

* Steps to reproduce the problem.
Install windows on mac's external drive. And run windows on mac.

* Version of Python and pywin32
Python 3.7
pip install's version

**Comment by mhammond** [comment]
GetWindowRect() just wraps the win32 API of the same name
