### ISSUE TITLE
win32process.CreateRemoteThread with no response

### ISSUE THREAD

**Issue by Wall-ee** [mhammond/pywin32#1332]
For all bugs, please provide the following information.

* Expected behavior and actual behavior.
I want to inject a dll into a program.  After inject by c++ using CreateRemoteThread.  there is a message box comes out. 

but after using win32process.CreateRemoteThread.  I got a tuple value respones. but nothing happened and no message box comming out.

so is this injection successful? 

* Steps to reproduce the problem.
1, using win32api.OpenProcess to get the target process handler
```
targetHandler = win32api.OpenProcess(win32con.PROCESS_ALL_ACCESS,True,wechatPid)
```

2,allocate a memory using  kernel32.VirtualAllocEx
```
targetNewDllAddress = kernel32.VirtualAllocEx(wechatHandler.handle,0,len(injectPath),win32con.MEM_COMMIT,win32con.PAGE_READWRITE)
```

3,using kernel32.WriteProcessMemory to write the dll path which i want to inject into the target process
```
writeState = kernel32.WriteProcessMemory(targetHandler.handle, targetNewDllAddress, injectPath, len(injectPath), byref(written))
```

4, using  this two step to get the LoadLibraryA  Address
```
kernel32Handler = win32api.GetModuleHandle("Kernel32.dll")
loadLibraryAddr = win32api.GetProcAddress(kernel32Handler,"LoadLibraryA")
```

5, using win32process.CreateRemoteThread command to perfome.
```
injectResult =  win32process.CreateRemoteThread(targetHandler.handle, None, 0,loadLibraryAddr, targetNewDllAddress,0)
```
and the result is:
(<PyHANDLE:1412>, 13824)
and nothing happened.   but a message box would comming out by C++ solution

* Version of Python and pywin32
python:
Python 3.6.4 |Anaconda, Inc.| (default, Jan 16 2018, 10:22:32) [MSC v.1900 64 bit (AMD64)] on 

pywin32:
pywin32-224.win-amd64-py3.6.exe

**Comment by mhammond** [comment]
I'm sorry, but nothing here points to a bug in out `CreateRemoteThread` wrapper - please follow the support instructions.

**Comment by violetsNight** [comment]
哈喽，你好，
请问你解决这个问题了吗？
我现在也是想要通过python实现同样的效果，情况和你一样

**Comment by violetsNight** [comment]
哈喽，你好，
请问你解决这个问题了吗？
我现在也想要通过python实现同样的效果，情况和你一样
![image](https://github.com/mhammond/pywin32/assets/40078075/9313d31d-0096-45e6-916e-89b8ef4f9155)
