### ISSUE TITLE
DLL for opc communication crashes for python3.5+ on windows

### ISSUE THREAD

**Issue by niklas-andersson** [mhammond/pywin32#1334]
* Description
There may be a pywin32 related problem that we've seen when we try to port the [OpenOPC project](http://openopc.sourceforge.net/) to Python 3.7 (x64) in Windows 10. OpenOPC was originally written for Python 2.7 (x86) but has since been ported to some extent by others to python 3. When trying to read a variable from an OPC server, the python session just crashes and terminates. The same problem is also described [here](https://stackoverflow.com/questions/52824127/python-3-6-x64-openopc) with the error message from the event viewer. 

* Expected behavior and actual behavior.
    Expected output (from read_matrikon_opc.py): 
        (6334, 'Good', '2019-04-23 21:12:40+00:00')
Actual behavior: 
    Python crashes and directly terminates. In the event viewer it can be seen that gbda_aut.dll caused the problem. 

* Steps to reproduce the problem.
 1. Unpack the attached files. [OpenOPC.zip](https://github.com/mhammond/pywin32/files/3109740/OpenOPC.zip)
 2. Package Pyro4 is required (pip install Pyro4)
 3. Register the dll in the OpenOPC folder. (The dll can also be downloaded from [OPC DA Auto Wrapper](http://gray-box.net/download_daawrapper.php?lang=en))
`regsvr32 gbda_aut.dll`
 4. Install an OPC-server, for example [matrikon](https://www.matrikonopc.com/downloads/178/drivers/index.aspx). For convenience it can also be downloaded from my [box](https://www.dropbox.com/s/m6h6bf9fju9zyrr/MatrikonOPCSimulation.exe?dl=0).
 5. Run the script read_matrikon_opc.py in the OpenOPC folder.

* Version of Python and pywin32
The bug only happens for Python 3.5+ (x64) in windows 10. 
Python 3.4 with pywin32 version 220 works fine. 
It also works fine in windows 7 for all tested python versions (2.7, 3.4 and 3.7) with pywin32 versions 220-224.

**Comment by mhammond** [comment]
The event viewer reports gbda_aut.dll as the issue, and the STR include taking a pre-built gbda_aut.dll and observing a crash - so I'm sorry, but this isn't actionable and there's no evidence of it being a pywin32 issue. If you can provide some evidence (eg, a stack trace or really *anything* which would explain why other such COM objects with fine with 3.5+ on Windows 10), I'm happy to reopen it.

**Comment by niklas-andersson** [comment]
Thank you for your quick reply. I can understand that it is hard to debug a pre-built dll with no stack trace. :) I'll try to provide some evidence. If you have any advice on how to debug such issues it would be a big help. Have a nice day.
