### ISSUE TITLE
 no module named win32types

### ISSUE THREAD

**Issue by tszw** [mhammond/pywin32#1335]
Note that issues in this repository are only for bugs or feature requests in the pywin32.

**If you need support or help using this package, please follow [these instructions](https://github.com/mhammond/pywin32/blob/master/README.md#support)** - support or help requests will be closed without comment.

For all bugs, please provide the following information.

* Expected behavior and actual behavior.

* Steps to reproduce the problem.

* Version of Python and pywin32: 220

**Comment by tszw** [comment]
there is a sentance 'import win32.com.client.CLSIDToClass, win32.com, win32types' in __init__.py , but there is a runtime error 'ModuleNotFoundError: No module named 'win32types'

**Comment by mhammond** [comment]
> there is a sentance 'import win32.com.client.CLSIDToClass, win32.com, win32types' in **init**.py

I'm not sure what init.py you refer to, but the string `win32types` does not appear in pywin32 and pywin32 has never shipped with a module of that name, so whatever code you are referring to is wrong.

**Comment by tszw** [comment]
This is the path of the init.py which I mentioned above 'C:\Users\..\AppData\Local\Temp\pywin32\gen_py\00020813-0000-0000-C000-000000000046x0x1x9\__init__.py'
Following is the beginning parts of the init.py file
# -*- coding: mbcs -*-
# Created by makepy.py version 0.5.01
# By python version 3.6.1 |Continuum Analytics, Inc.| (default, May 11 2017, 13:25:24) [MSC v.1900 64 bit (AMD64)]
# From type library '{00020813-0000-0000-C000-000000000046}'
# On Sun Apr 28 18:44:44 2019
'Microsoft Excel 16.0 Object Library'
makepy_version = '0.5.01'
python_version = 0x30601f0

import win32.com.client.CLSIDToClass, win32.com, win32types
.....

So, which package could include this win32types module?

**Comment by mhammond** [comment]
I have no idea, but I suspect it has been hand-edited, or generated by an edited genpy.py - there's no "win32.com" package either.
