### ISSUE TITLE
Controlling Pause and Continue command for print job

### ISSUE THREAD

**Issue by VictorZhang2014** [mhammond/pywin32#1337]
I'm new to pywin32 and windows api, but I want to control the printers' print job, so I found a doc by MSDN, link is here:
https://docs.microsoft.com/en-us/windows/desktop/cimwin32prov/win32-printjob
https://www.codeproject.com/Articles/6592/A-Simple-Approach-for-Controlling-Print-Jobs-using

 It says that `Win32_PrintJob` class has two methods, `Pause` and `Continue`, What I want is to use the two methods on Python `pywin32`.

**Comment by mhammond** [comment]
See https://github.com/mhammond/pywin32#support
