### ISSUE TITLE
Conversion from numpy.array to VARIANT fails with Python 3

### ISSUE THREAD

**Issue by panikc** [mhammond/pywin32#1346]
Passing a numpy.array to a COM method taking a VARIANT as parameter no longer works in Python 3 as compared to Python 2.

The underlying problem is that calling `PyCom_VariantFromPyObject` (oleargs.cpp) with an object of type `numpy.ndarray` containing elements of type `numpy.int32` fails with the error:

> Internal error - the buffer length is not the sequence length!

The expected output would be a `VARIANT` containing a Safearray of Variants of type `VT_I4`.

The problem can be reproduced with this minimal example without the need for an actual COM interface:

```python
from ctypes import POINTER, PyDLL, byref, py_object, wintypes
from comtypes.automation import VARIANT
import pythoncom
import numpy

_dll = PyDLL(pythoncom.__file__)
_pack = _dll.PyCom_VariantFromPyObject
_pack.argtypes = py_object, POINTER(VARIANT)
_pack.restype = wintypes.BOOL

def pack(obj):
    var = VARIANT()
    _pack(obj, byref(var))
    return var

input1 = [1,2,3]
input2 = numpy.array(input1)

arr1 = pack(input1) # works with python 2 & 3
arr2 = pack(input2) # work with python 2, fails with python 3
```
Reproduced using Python 3.7 and pywin32-224

There seem to be two problems:

1. The first problem seems to be that inside `PyCom_VariantFromPyObject` the `PYWIN_BUFFER_CHECK` branch is taken, which tries to produce a byte array and then causes the error message in `PyCom_SAFEARRAYFromPyObjectBuildDimension`, called from`PyCom_SAFEARRAYFromPyObjectEx`. This seems to be due to the different definition of `PYWIN_BUFFER_CHECK` in Python 3 compared to Python 2: In Python 2, the branch is taken if the object _is_ a buffer, whereas in Python 3 it is erroneously taken whenever the object _can be interpreted as_ a buffer.

2. When I tried to skip the `PYWIN_BUFFER_CHECK` branch in the debugger, the `PySequence_Check` branch is taken, which then correctly creates the Safearray. But then, converting each single array element from `numpy.int32` to `VARIANT` fails in an inner call to `PyCom_VariantFromPyObject` as the `PyLong_Check` branch is not taken. The reason for this seems to be that `numpy.int32` no longer has the `Py_TPFLAGS_LONG_SUBCLASS` flag in Python3, even though it can be converted using PyLong_AsLong.
As then, no branch is taken, it produces the error: "Objects of type 'numpy.int32' can not be converted to a COM VARIANT (but obtaining the buffer() of this object could)".

**Comment by mhammond** [comment]
Fixed by #1388
