### ISSUE TITLE
EnumChildWindows's return value should not be used

### ISSUE THREAD

**Issue by bbzy** [mhammond/pywin32#1350]
Note that issues in this repository are only for bugs or feature requests in the pywin32.

**If you need support or help using this package, please follow [these instructions](https://github.com/mhammond/pywin32/blob/master/README.md#support)** - support or help requests will be closed without comment.

For all bugs, please provide the following information.

* Expected behavior and actual behavior.
No exception raised
* Steps to reproduce the problem.
I found pywin32 uses the return value of EnumChildWindows() as according to set error state. Excactly, the code shows below:
rc = EnumChildWindows(hwnd, PyEnumWindowsProc, (LPARAM)&cb);
if (!rc)
	return PyWin_SetAPIError("EnumChildWindows");
But, msdn says the return value of EnumChildWindows() is not used.
* Version of Python and pywin32
3.7.3

**Comment by mhammond** [comment]
Thanks! Fixed in bc02e8dc
