### ISSUE TITLE
ntsecuritycon.FILE_ALL_ACCESS has the wrong value

### ISSUE THREAD

**Issue by bmw** [mhammond/pywin32#1354]
It's certainly possible that I'm misunderstanding something, but I suspect `ntsecuritycon.FILE_ALL_ACCESS` has the wrong value. It is set to:
```
STANDARD_RIGHTS_REQUIRED | SYNCHRONIZE | 1023
```
However, `winnt.h` in my Windows 10 setup defines it as:
```
STANDARD_RIGHTS_REQUIRED | SYNCHRONIZE | 511
```
This difference has caused some problems in my project because we're obtaining ACLs and comparing them to `ntsecuritycon.FILE_ALL_ACCESS`, but this comparison is never successful because `ntsecuritycon.FILE_ALL_ACCESS` has an extra bit set.

I created the following script to show this behavior:
```
import ntsecuritycon as con
import win32api
import win32security

# Get admin and user accounts
ADMINS = win32security.LookupAccountName("", "Administrators")[0]
USER = win32security.LookupAccountName("", win32api.GetUserName())[0]

# Create a file
FILENAME = "temp.txt"
open(FILENAME, "w").close()

# Get current security descriptor
sd = win32security.GetFileSecurity(FILENAME, win32security.DACL_SECURITY_INFORMATION)

# Create and set new ACL giving admins FILE_ALL_ACCESS
dacl = win32security.ACL()
dacl.AddAccessAllowedAce(win32security.ACL_REVISION, con.FILE_GENERIC_READ | con.FILE_GENERIC_WRITE, USER)
dacl.AddAccessAllowedAce(win32security.ACL_REVISION, con.FILE_ALL_ACCESS, ADMINS)
sd.SetSecurityDescriptorDacl(1, dacl, 0)
win32security.SetFileSecurity(FILENAME, win32security.DACL_SECURITY_INFORMATION, sd)

# Assert that admins ACE is set to FILE_ALL_ACCESS
sd = win32security.GetFileSecurity(FILENAME, win32security.DACL_SECURITY_INFORMATION)
dacl = sd.GetSecurityDescriptorDacl()
for i in range(dacl.GetAceCount()):
    ace = dacl.GetAce(i)
    if ace[2] == ADMINS:
        # This assertion fails
        assert ace[1] == con.FILE_ALL_ACCESS
```
I would expect the assertion on the last line to succeed because we set this ACE to `FILE_ALL_ACCESS` earlier in the script.

I encountered this behavior using Python 3.7.1 and pywin32 224.

**Comment by mhammond** [comment]
Huh - thanks for the report and that's very odd - I wonder the value changes in windows itself over the years? Either way, I confirmed you are correct and fixed it in 4be810d9.
