### ISSUE TITLE
win32service.SERVICE_DISABLED and win32service.SERVICE_RUNNING have the same int ( 4 )

### ISSUE THREAD

**Issue by dschiller** [mhammond/pywin32#1356]
* Expected behavior and actual behavior.

``win32service.SERVICE_DISABLED`` has a different int than ``win32service.SERVICE_RUNNING``

* Steps to reproduce the problem.

This function returns ``False`` for a disabled Service.

```
def isServiceDisabled(self, serviceName):
        isDisabled = win32serviceutil.QueryServiceStatus(serviceName)[1] == win32service.SERVICE_DISABLED
        return isDisabled
```

* Version of Python and pywin32
Python: 3.7.2 x64
pywin32: 224

**Comment by mhammond** [comment]
See https://docs.microsoft.com/en-us/windows/desktop/api/winsvc/ns-winsvc-_query_service_configa and https://docs.microsoft.com/en-us/windows/desktop/api/winsvc/ns-winsvc-_service_status - both are 4 which is OK as they are used in different contexts.

**Comment by dschiller** [comment]
I was thinking about that as well. Do you have any hints then how I can handle both states with Python Code ?
