### ISSUE TITLE
parameter error

### ISSUE THREAD

**Issue by arashtavakoli** [mhammond/pywin32#1360]
Note that issues in this repository are only for bugs or feature requests in the pywin32.

**If you need support or help using this package, please follow [these instructions](https://github.com/mhammond/pywin32/blob/master/README.md#support)** - support or help requests will be closed without comment.

For all bugs, please provide the following information.

* Expected behavior and actual behavior.

* Steps to reproduce the problem.

* Version of Python and pywin32

**Comment by arashtavakoli** [comment]
I am trying to get the media creation date for a file. I use the code below. and I get the error below. I tried to find the reason online but couldnt find anything has anyone had this issue before?
import pytz
import datetime
from win32com.propsys import propsys, pscon

filepath="D:/Google Drive/UVA_PhD/Summer Co-Projects/1.2.MP4"
properties = propsys.SHGetPropertyStoreFromParsingName(filepath)
dt = properties.GetValue(pscon.PKEY_Media_DateEncoded).GetValue()

if not isinstance(dt, datetime.datetime):
    # In Python 2, PyWin32 returns a custom time type instead of
    # using a datetime subclass. It has a Format method for strftime
    # style formatting, but let's just convert it to datetime:
    dt = datetime.datetime.fromtimestamp(int(dt))
    dt = dt.replace(tzinfo=pytz.timezone('UTC'))

dt_tokyo = dt.astimezone(pytz.timezone('Asia/Tokyo'))

ERROR:

Traceback (most recent call last):
  File "creation_date.py", line 6, in <module>
    properties = propsys.SHGetPropertyStoreFromParsingName(filepath)
pywintypes.com_error: (-2147024809, 'The parameter is incorrect.', None, None)

**Comment by markgoleby** [comment]
I had the same problem.  It was caused by the type of slashes in the file path (I was getting the path from askdirectory which returns forward slashes) . I had to translate the forward slashes to back slashes with the literal, e.g. "drive:\\folder\\folder\\filename".  Hope that helps.
