### ISSUE TITLE
 pywin32-224-cp36-cp36m-win32.whl is not a supported wheel on this platform.

### ISSUE THREAD

**Issue by psw13583112** [mhammond/pywin32#1367]
How to solve this problem,Other versions I've tried are still the problem.My system is Linux,thanks

**Comment by vernondcole** [comment]
The error message is correct. Python for Windows is not supported on operating systems other than Windows. The focus of this package consists of direct calls to Windows kernel APIs. Native Linux programs cannot use them and do not need them.
