### ISSUE TITLE
pywintypes.Time() raises OverflowError with value bigger than a C long

### ISSUE THREAD

**Issue by ghost** [mhammond/pywin32#137]
pythoncom.MakeTime\(\) takes only ints and so cannot 
make a time later than MakeTime\(sys.maxint\), which is 
2038-01-19 04:14:07. This is a problem when I am 
talking to a COM object that is expecting a date, and 
the date is the maturity of a 50-year interest swap.

&gt;&gt;&gt; pythoncom.MakeTime\(sys.maxint\)
&lt;PyTime:2038-01-19 04:14:07&gt;
&gt;&gt;&gt; pythoncom.MakeTime\(sys.maxint+1\)
Traceback \(most recent call last\):
File "&lt;interactive input&gt;", line 1, in ?
OverflowError: long int too large to convert to int

It appears that pythonwin.client's marshalling process 
suppresses this error and substitutes 
pythoncom.MakeTime\(0\).

Reported by: pkeating

Original Ticket: "pywin32/bugs/137":https://sourceforge.net/p/pywin32/bugs/137

**Comment by Avasam** [comment]
Since `sys.maxint` doesn't exist anymore and `pythoncom.MakeTime` is deprecated, here's the same issue replicated today:
```python
>>> import pywintypes
>>> pywintypes.Time(2**31-1)
pywintypes.datetime(2038, 1, 18, 22, 14, 7)
>>> pywintypes.Time(2**31)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OverflowError: Python int too large to convert to C long
```

**Comment by Avasam** [comment]
Closing as duplicate in favor of #1164
