### ISSUE TITLE
pywin32 for Linux

### ISSUE THREAD

**Issue by Srinirap** [mhammond/pywin32#1372]
Hi,

Could you please help me out to get pywin32 module for linux environment.
I am currently using centos 7 with python 3.6. 
I am getting the below error,

python3 -m pip install pywin32
Collecting pywin32
  ERROR: Could not find a version that satisfies the requirement pywin32 (from versions: none)
ERROR: No matching distribution found for pywin32

**Comment by v-python** [comment]
I'd be very surprised to learn that centos 7 supports Windows API calls. Since pywin32 is a wrapper for Windows API calls, could you please explain further what you expect to be able to do with pywin32 in centos 7?

**Comment by mhammond** [comment]
pywin32 for linux is never going to be a thing. You could try running it under [wine](https://www.winehq.org/) but even then I'd expect some issues.

**Comment by Srinirap** [comment]
@v-python @mhammond I am working on an automation task with my infrastructure using python, we have more than 100's of windows + Linux servers, I have to login to the machine and restart some services.
I am able to connect to Windows machines using wmi module. During importing WMI on windows I got an error that "ModuleNotFoundError: No module named 'win32com'" SO I have installed pywin32 and it's started working fine.
I got the same error while importing WMI on Linux So that I am searching pywin32 module for linux.

Could you help me with this issue, Or Could you please suggest any method to connect to a Windows machine from Linux and do some operation without enabling any service from the target side.?

Thank you.

**Comment by vernondcole** [comment]
For controlling both Windows and Linux machines, I use and recommend Salt
<http://docs.saltstack.com> which uses pywin32 internally on Windows, and
different operating systems calls on Linux platforms.
The commands used are consistent (as far as possible) between different
operating systems and versions. It is free and open source. Don't waste
time reinventing wheels.
I have written a fairly complete demo/training system which you can review
at http://github.com/salt-bevy/salt-bevy.

**Comment by vernondcole** [comment]
Your request also states that you do not want to run a service on the
client. You can do that using salt-ssh.
However, I recommend against that approach, since it is much slower, and
much less reliable. I have been able to rescue stalled or misconfigured
machines using their running Salt minion when it was impossible to get a
new remote login.

**Comment by shashank1623** [comment]
how can we install pywin32 on linux ubuntu

**Comment by sschukat** [comment]
As stated in the name pywin32 is mainly a wrapper for the win32 API, which is windows only. Hence there is no native installation on linux.

**Comment by Giuseppe-Ubertiello** [comment]
yeah but if i want to develop some windows software on linux?
