### ISSUE TITLE
SetSecurityDescriptorGroup does not accept None as group value 

### ISSUE THREAD

**Issue by Nocturem** [mhammond/pywin32#1382]
from https://docs.microsoft.com/en-us/windows/win32/api/securitybaseapi/nf-securitybaseapi-setsecuritydescriptorgroup

"pGroup

A pointer to a **SID** structure for the security descriptor's new primary group. The SID structure is referenced by, not copied into, the security descriptor. If this parameter is **NULL**, the function clears the security descriptor's primary group information. This marks the security descriptor as having no primary group."

However the equivalent 
`sd.SetSecurityDescriptorGroup(None, False)`
appears to trip on a testing for SID structure validity.
https://github.com/mhammond/pywin32/blob/63240273565f2c51c72d687ac3fd92021ea922d0/win32/src/PySECURITY_DESCRIPTOR.cpp#L508

tested on python 3.7 with pywin32-223 & pywin32-224

**Comment by mhammond** [comment]
thanks - fixed in e7cf4418
