### ISSUE TITLE
building 'perfmondata' extension fails

### ISSUE THREAD

**Issue by p4vv37** [mhammond/pywin32#1384]
Hi
I am trying to build the latest sources with VS 2015 on x64 Windows 10 by runningcommands from VS2015 x64 Native Tools Command Prompt:

```
D:\pywin32>"C:\Program Files\Autodesk\Maya2019\bin\mayapy"  setup.py install
Building pywin32 2.7.224.0
running install
running build
running build_py
running build_ext
building 'perfmondata' extension
mc.exe -h win32/src/PerfMon -r build\temp.win-amd64-2.7\Release\win32/src/PerfMon win32/src/PerfMon/PyPerfMsgs.mc
error: command 'mc.exe' failed: No such file or directory
```

I need to use pywin32 in:
```
Python 2.7.11 (default, Jul  1 2016, 02:08:48) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
```
Running 
```
mc.exe
```
in consoleworksa and opens Message Compiler btw

**Comment by p4vv37** [comment]
Running "mc.exe" in console works, tbtw

**Comment by mhammond** [comment]
That's a bit odd - distutils/msvccompiler.py (part of python itself) is what tries to find mc.exe, and it uses the same technique to try and find cl.exe etc too. It looks on PATH, so I'm surprised it can't find it - is it possible `mayapy` modified the environment?

**Comment by Avasam** [comment]
@p4vv37 Can you confirm whether you still get this error with the latest pywin32 version, as well as with the official CPython>=3.9  interpreter ?

**Comment by Avasam** [comment]
I'll close this with a few notes:
1. OP seems to be trying to do something on Python 2.7, which is no longer supported.
2. Calling setup.py directly is no longer supported (see https://github.com/mhammond/pywin32/issues/2208 )
3. `distutils/msvccompiler.py` doesn't even exist in https://github.com/pypa/distutils anymore

If you still have issues with a non-EOL version of Python using the latest version of pywin32 installed through a build frontend (like pip, poetry, uv, etc.) then feel free to open a new issue with all the required details!
