### ISSUE TITLE
pywintypes.datetime missing milliseconds field

### ISSUE THREAD

**Issue by JAGJ10** [mhammond/pywin32#1385]
Hi,

I'm using a built version of the current repo with python 3.6.7 and am experiencing some issues with the datetime object. I have a COM timestamp object that contains milliseconds, but when I fetch it using pywin32 it is always showing 0 for the milliseconds field.

I see that there was this issue: https://github.com/mhammond/pywin32/pull/1326 but I'm wondering if there might be another reason the milliseconds field isn't being populated?

Thanks

**Comment by mhammond** [comment]
That's the most likely reason - I'll try and get a new release out soon so you can see for sure.

**Comment by JAGJ10** [comment]
That would be really great! Thanks
