### ISSUE TITLE
Dispatch command hanging

### ISSUE THREAD

**Issue by JAGJ10** [mhammond/pywin32#1390]
Hi,

I have a multi-threaded application that receives a large number of messages (COM objects) in sudden bursts. During this time, I've noticed that if my other thread attempts to create a new COM object via the Dispatch call, that call seems to hang until the messages have been processed. I am wondering if this is because the win32 side of things is still trying to churn through all the messages? Is there a way to preempt this behavior to ensure that the object I'm trying to create gets created immediately?

Thanks!

**Comment by mhammond** [comment]
In the template text you deleted, you would have found the support link - https://github.com/mhammond/pywin32#support
