### ISSUE TITLE
RegSetValueEx does not work

### ISSUE THREAD

**Issue by deogo** [mhammond/pywin32#1398]
* Expected behavior and actual behavior.
Calling RegSetValueEx gives error
SystemError: ..\Objects\longobject.c:998: bad argument to internal function

* Steps to reproduce the problem.
`import win32api as wa`
`import win32con as wc`
`import ctypes`
`rbranch = wc.HKEY_LOCAL_MACHINE`
`rkey = 'SOFTWARE\\SomeBranch\\'`
`valueName = 'KeyName'`
`value = 128`
`try:`
`  hReg = wa.RegOpenKeyEx( rbranch, rkey, 0, wc.KEY_SET_VALUE )`
`except:`
`  hReg,ret = wa.RegCreateKeyEx( rbranch, rkey, wc.KEY_CREATE_SUB_KEY | wc.KEY_SET_VALUE )`
`wa.RegSetValueEx( hReg, valueName, 0, wc.REG_QWORD, value )`
`wa.RegCloseKey( hReg )`

in v.214 following variant worked
`wa.RegSetValueEx( hReg, valueName, 0, wc.REG_QWORD, ctypes.c_ulonglong( value ) )`
* Version of Python and pywin32
2.7.16/224

**Comment by mhammond** [comment]
You had to use a python long on 2.x with REG_QWORD, but I just pushed a fix so ints also work.
