### ISSUE TITLE
pywin32_postinstall.py fails with syntax error

### ISSUE THREAD

**Issue by zkghost** [mhammond/pywin32#1402]
# Repro:
```
# git clone repo
pip install pywin32
python .\pywin32_postinstall.py
```
# Expected
It works
# Actual
```
PS C:\Users\admin\Desktop\src\pywin32> python .\pywin32_postinstall.py
  File ".\pywin32_postinstall.py", line 75
    except OSError, details:
                  ^
SyntaxError: invalid syntax
```

# Versions
Python: 3.7.4
pywin32: 224

**Comment by zkghost** [comment]
FWIW the binary seems to have installed fine, but sad to run into a syntax error

**Comment by mhammond** [comment]
Installing into python 3 directly from a git checkout is going to be problematic - all the sources are still in python 2 syntax and it is the build process which converts them. While we can probably make the post-install script compatible with both 2 and 3, that's not going to be true for everything.

**Comment by mhammond** [comment]
I'm going to close this because it's not supported, but after the end of this year I'll end up dropping support for 2.x entirely and convert the entire repo to 3.x syntax.
