### ISSUE TITLE
SetConsoleWindowInfo : The parameter is incorrect

### ISSUE THREAD

**Issue by sctnightcore** [mhammond/pywin32#1407]
Note that issues in this repository are only for bugs or feature requests in the pywin32.

**If you need support or help using this package, please follow [these instructions](https://github.com/mhammond/pywin32/blob/master/README.md#support)** - support or help requests will be closed without comment.

For all bugs, please provide the following information.

* Expected behavior and actual behavior.

* Steps reproduce the problem. to
simple code : https://gist.github.com/sctnightcore/d74b01fd8b72d8d4bf62f229a714f55a

i try SetConsoleWindowInfo but get The parameter is incorrect
something wrong ? 
* Version of Python and pywin32
Python 3.7.4
pywin32 224

**Comment by mhammond** [comment]
Please follow the instructions for support that you quoted!

**Comment by sctnightcore** [comment]
Updated ! 

@mhammond  reopen issues pls .

**Comment by mhammond** [comment]
It looks like you are not reporting a bug, but instead having trouble using SetConsoleWindowInfo. If that's the case, you need to follow the instructions for getting support, which you quoted in your first comment.

**Comment by sctnightcore** [comment]
@mhammond  i read evenything of it . but it dont work.

**Comment by sctnightcore** [comment]
@mhammond 
I have tested win32console_demo.py as well.
`pywintypes.error: (87, 'SetConsoleWindowInfo', 'The parameter is incorrect.')`

I think it's a problem?

**Comment by mhammond** [comment]
I'll check it out.

**Comment by sctnightcore** [comment]
U can try see my code 
python : https://gist.github.com/sctnightcore/d74b01fd8b72d8d4bf62f229a714f55a
perl : https://github.com/sctnightcore/PlayServer-Perl/blob/master/src/Interface/Console.pm

**Comment by mhammond** [comment]
> I have tested win32console_demo.py as well.

This is working fine for me and https://gist.github.com/sctnightcore/347aa6846aba348a3c6cbf36bff85876 also ran until `i=31` before I killed it without an exception. I'm not sure why you are seeing this exception, but you might like to try sending an email to the python-win32 list.
