### ISSUE TITLE
Increment work memory in FormatMessage to avoid errors when formating Event log messages

### ISSUE THREAD

**Issue by cladic** [mhammond/pywin32#1414]
Sometime the 512 bytes is not enough and we get error during the process to format a message in event log api. I studied the source code and I think we need two modifications: Module **Win32apimodule.cpp**, two changes 1: ==> change "const int bufsize = **512**;" to "const int bufsize = **4096**;" , 2: ==> change "for (i = 0; i < numInserts + **2**; i++)  // Make sure clean for cleanup"  to "for (i = 0; i < numInserts + **8**; i++)  // Make sure clean for cleanup". I already tested these modifications and the error during the message formating was corrected

**Comment by mhammond** [comment]
That sounds fine - would you like to open a PR?

**Comment by cladic** [comment]
Yes...if helps....How can I do this ?

**Comment by cladic** [comment]
Maybe i did make the PULL REQUEST:  https://github.com/mhammond/pywin32/pull/1416  ... Is it correct ?

**Comment by cladic** [comment]
or this...https://github.com/mhammond/pywin32/issues/1414

**Comment by cladic** [comment]
I am sorry...I do not know the correct way to pull a request....
