### ISSUE TITLE
"Unknown encoding: unicode-internal" error is observed when trying to "freeze" project on Python 3.8

### ISSUE THREAD

**Issue by t-o-n-y-p** [mhammond/pywin32#1428]
This issue can be reproduced with both pywin32 v224 and v225 for Python 3.8.
Works fine with pywin32 v224 and v225 for Python 3.7.4.

Steps:
- download the project https://github.com/t-o-n-y-p/rssim/tree/a48fa0665844b2d9c17106ef5203a7fe6ce5ade2 , install pywin32 and all the other requirements
- run "python setup.py build"

Expected result: executable is built successfully

Actual result: "Unknown encoding: unicode-internal" error is observed inside pywin32 lib and build fails
![cxfreeze_python38_issue](https://user-images.githubusercontent.com/42129780/66822185-c43af400-ef54-11e9-9508-15d420aa57cd.png)

**Comment by mhammond** [comment]
Fixed by 74f9d8b

**Comment by Pinkyakterpinkyakt** [comment]
#1428
