### ISSUE TITLE
Visual Studio 2019 without legacy baggage

### ISSUE THREAD

**Issue by wimcolgate** [mhammond/pywin32#1436]
Sorry if this is not the right place or forum to ask this question. If not, feel free to direct me elsewhere.

Using b224, I've had trouble building with just Visual Studio 2019. 

I do have an environment with VS2012 w/ XP support files, VS2015 and VS2017 and I can build just fine, as the old legacy stuff is found by all that SDK sniffing.

But on a clean VM with just VS2019 (no bundled legacy tools, sdk, etc) and the most recent SDK (& WDK) I'm having issues.

Without overriding MSSDK_INCLUDE or MSSDK_LIB environment variables, I get the error that Windows 8.1 SDK cannot be found.

Overriding them, I get a compile, but link fails with one error: propsys.obj : error LNK2001: unresolved external symbol CLSID_PropertyChangeArray

What would it take to support the current Microsoft tool chain as is?

If I've missed something in the documentation, apologies ... and point me there.

Thanks.

**Comment by vernondcole** [comment]
The catch is that Python-callable modules must be compiled with the same
tool chain used to build the Python executable with which they work.
Unless you want to compile your own version of Python, your stuck with the
old libraries and compilers.

**Comment by mhammond** [comment]
Yeah - what Vernon said. `CLSID_PropertyChangeArray` is probably something that will bite me when Python moves to more modern compilers, so I'll certainly take a patch which addresses that - I guess it's been deprecated?

Also, I think you probably deleted a link to https://github.com/mhammond/pywin32#support when opening the issue - that link explains where the best place is for general discussion.

**Comment by wimcolgate** [comment]
I am in fact building pywin32 with the python3 that was just built by VS2019. Not only does the command line indicate, I also captured a procmon trace that shows the python3 built with VS2019 is building pywin32 -- as well as loading all its sundry imports from its Lib.

**Comment by wimcolgate** [comment]
Looking at the setup.py in b224 of pywin32, it looks like there is a fixed limitation to SDK's 7 & 8:

    # Windows SDKs up to version 7 use a reg key SOFTWARE\Microsoft\Microsoft SDKs\Windows
    # SDKs 8 and later use SOFTWARE\Microsoft\Windows Kits\Installed Roots
    # We currently target version 8.1
    try:
        key = winreg.OpenKey(winreg.HKEY_LOCAL_MACHINE,
                              r"SOFTWARE\Microsoft\Windows Kits\Installed Roots")
        installRoot = winreg.QueryValueEx(key, "KitsRoot81")[0]
    except EnvironmentError:
        print("Can't find a windows 8.1 sdk")
        return None

**Comment by wimcolgate** [comment]
Well, I've peeled the onion a bit, and it looks like the base python code hasn't kept up with the Microsoft tool churn either. So it looks like only a concerted effort to effect both pywin32 and the base python code base is going to be needed.
