### ISSUE TITLE
Is that pywin32==224 not supported in Python 3.8?

### ISSUE THREAD

**Issue by haroldrandom** [mhammond/pywin32#1437]
Today when I trying to install pywin32==24
```
ERROR: Could not find a version that satisfies the requirement pywin32==224 (from versions: none)
ERROR: No matching distribution found for pywin32==224
```
But it worked in Python 3.7.

My Environment:
- Windows 10
- Python 3.8

**Comment by fabiencelier** [comment]
If you check [version 224 on pypi](https://pypi.org/project/pywin32/224/#files) there is no wheel for python 3.8 for 224 and before.
Wheels for 3.8 start at [version 225](https://pypi.org/project/pywin32/225/#files)

I guess that's because 224 was released before Python 3.8

**Comment by haroldrandom** [comment]
Is there a plan for pywin32==224 to support Python 3.8

**Comment by mhammond** [comment]
> Is there a plan for pywin32==224 to support Python 3.8

No - you need to use 225 or later.
