### ISSUE TITLE
Make code python 2/3 compatible

### ISSUE THREAD

**Issue by dhairyanadapara** [mhammond/pywin32#1441]
Hey, I'm using this module with `wmi.py`. I'm trying to make my code python 2/3 compatible but currently repo doesn't support python 3. Is there any plan to make it python 2/3 compatible?
I can work on this you need help. :)

**Comment by mhammond** [comment]
I don't think it's possible to do this fully - we can probably get to *most* of it compatible with both, but the fact we can't get to 100% is why I use 2to3 (so you *can* use wmi.py on python 3 - just not directly from git).

Given the Python 2 EOL at the end of the year, I think it's best to just wait for then, and I'll declare the end of py 2 support for pywin32, and we can check the 2to3 output into git.
