### ISSUE TITLE
pyWin32 for linux OS

### ISSUE THREAD

**Issue by bhushan-2** [mhammond/pywin32#1449]
I was trying to install excel2Image python package on linux machine. As this package is highly dependent on Windows OS because it uses pyWin32 module,it is giving me following error.

**Could not find a version that satisfies the requirement pywin32>=223 (from pypiwin32->excel2img) (from versions: )
No matching distribution found for pywin32>=223 (from pypiwin32->excel2img)**

For windows machine it is working perfectly.
Is it possible to use pyWin32 library on Linux OS or equivalent library which does similar job as pyWin32 on Linux OS

Python Version : 3.x

**Comment by mhammond** [comment]
This package is windows only.
