### ISSUE TITLE
pywintypes module not found in virtualenv

### ISSUE THREAD

**Issue by eranzim** [mhammond/pywin32#1455]
Hi!
I pip-installed pywin32 on my machine, and everything works fine. I tried it in a virtualenv, and I get this error when importing pywintypes:
`ModuleNotFoundError: No module named 'pywintypes'`

I should also note that `pip show pywin32` shows it is installed (also inside the virtualenv), and the dll does exist inside `...\myvenv\Lib\site-packages\pywin32-227-py3.8-win-amd64.egg\pywin32_system32\pywintypes38.dll`

Python 3.8.0 64-bit on Windows 10 x64
pywin32 227
virtualenv 16.7.9

Possibly related: https://github.com/mhammond/pywin32/issues/1327 (though it seems a different issue to me)

Thanks!!

**Comment by mhammond** [comment]
That's odd. Note that there should be a `pywintypes.py` in the win32\Lib directory.

**Comment by eranzim** [comment]
Some more info:
1. `pywintypes.py` exists in `C:\Python38\Lib\site-packages\win32\lib\pywintypes.py` and in `C:\...\myvenv\Lib\site-packages\pywin32-227-py3.8-win-amd64.egg\win32\lib\pywintypes.py`.
1. A python shell finds pywintypes's dll:
```
>>> import pywintypes
>>> pywintypes
<module 'pywintypes' (C:\Python38\Lib\site-packages\pywin32_system32\pywintypes38.dll)>
```
3. `pywintypes38.dll` exists in `C:\Python38\Lib\site-packages\pywin32_system32\pywintypes38.dll` and in `C:\...\myvenv\Lib\site-packages\pywin32-227-py3.8-win-amd64.egg\pywin32_system32\pywintypes38.dll`
3. Python shell's `sys.path`:
```
['', 'C:\\Python38\\python38.zip', 'C:\\Python38\\DLLs', 'C:\\Python38\\lib', 'C:\\Python38', 'C:\\Python38\\lib\\site-packages', 'c:\\code\\xxx', 'C:\\Python38\\lib\\site-packages\\pypiwin32-223-py3.8.egg', 'C:\\Python38\\lib\\site-packages\\win32', 'C:\\Python38\\lib\\site-packages\\win32\\lib', 'C:\\Python38\\lib\\site-packages\\Pythonwin']
```
5. `sys.path` inside virtualenv:
```
['', 'c:\\...\\myvenv\\Scripts\\python38.zip', 'c:\\...\\myvenv\\DLLs', 'c:\\...\\myvenv\\lib', 'c:\\...\\myvenv\\Scripts', 'c:\\python38\\Lib', 'c:\\python38\\DLLs', 'c:\\...\\myvenv', 'c:\\...\\myvenv\\lib\\site-packages', 'c:\\code\\xxx', 'c:\\...\\myvenv\\lib\\site-packages\\netifaces-0.10.9-py3.8-win-amd64.egg', 'c:\\...\\myvenv\\lib\\site-packages\\urllib3-1.22-py3.8.egg', 'c:\\...\\myvenv\\lib\\site-packages\\jsonpickle-1.2-py3.8.egg', 'c:\\...\\myvenv\\lib\\site-packages\\yaxl-0.0.17-py3.8.egg', 'c:\\...\\myvenv\\lib\\site-packages\\pefile-2019.4.18-py3.8.egg', 'c:\\...\\myvenv\\lib\\site-packages\\plumbum-1.6.8-py3.8.egg', 'c:\\...\\myvenv\\lib\\site-packages\\pyyaml-5.3b1-py3.8-win-amd64.egg', 'c:\\...\\myvenv\\lib\\site-packages\\argh-0.26.2-py3.8.egg', 'c:\\...\\myvenv\\lib\\site-packages\\decorator-4.4.1-py3.8.egg', 'c:\\...\\myvenv\\lib\\site-packages\\construct-2.9.45-py3.8.egg', 'c:\\...\\myvenv\\lib\\site-packages\\pathlib2-2.3.5-py3.8.egg', 'c:\\...\\myvenv\\lib\\site-packages\\psutil-5.6.7-py3.8-win-amd64.egg', 'c:\\...\\myvenv\\lib\\site-packages\\parameterized-0.7.1-py3.8.egg', 'c:\\...\\myvenv\\lib\\site-packages\\pywin32-227-py3.8-win-amd64.egg', 'c:\\...\\myvenv\\lib\\site-packages\\future-0.18.2-py3.8.egg']
```

**Comment by colin-adams** [comment]
Is this still open? I have the same issue - within a virtualenv, it can't find the module. After deactivation, it can.

**Comment by colin-adams** [comment]
pip uninstall

followed by

pip install

(in the virtual environment) does the trick for me

**Comment by CristiFati** [comment]
Could you post the steps to reproduce?

**Comment by yuval9313** [comment]
Same issue on a bit more complex situation, I've tried to create a service using pywin32 and encounter this: 
![image](https://user-images.githubusercontent.com/30751157/79012065-16f51180-7b6e-11ea-8dc3-351c64f0438a.png)

Step to reproduce:
on global python 38.2
`pip install virtualenv`
on folder
`virtualenv venv`
and then
```
(venv) pip install pywin32
(venv) pip uninstall pywin32
(venv) python -m pip install pywin32
```

nothing works

**Comment by CristiFati** [comment]
All who are encountering the error, please post all the details:
- *Python* version (and architecture)
- Virtual environment creation command
- Any additional commands (`activate`, `pip install`, ...)
- The complete stacktrace

Actually, post all the commands used and their outputs.

For the service question: what does `python -c "import win32api"` output inside the *VEnv*?

**Comment by eranzim** [comment]
This is odd - I just created a new virtualenv from scratch, pip installed just pywin32, and it worked. Went back to the previous virtualenv, uninstalled and reinstalled pywin32, and now it works there as well...
So as far as I'm concerned, this issue can be closed (though it seems @yuval9313 still has an issue...)
@colin-adams - thanks :)

**Comment by yuval9313** [comment]
> For the service question: what does `python -c "import win32api"` output inside the _VEnv_?
So this actually outputs blank, Also `import pywintypes` outputs blank which means that I can import them, other than that it still doesn't work, I actually transferred to a second PC, reinstall python 3.8 and made updated virtualEnv and still gets the same error mentioned in my previous post

@eranzim can you post your code? If I could work with your's it means my issue might be a different one, which means this one could be closed and newly open more specific issue

**Comment by eranzim** [comment]
@yuval9313 The code that didn't work was simply `import pywintypes` from a python console, nothing more. To fix it, pip uninstall and pip install did the trick.

**Comment by CristiFati** [comment]
@yuval9313: What about `python -c "import win32api;print(win32api)"? From inside the *VEnv* (or using the same interpreter launched by the service)?

**Comment by yuval9313** [comment]
Once again, on freshly installed env
![image](https://user-images.githubusercontent.com/30751157/79455840-294fcf00-7ff6-11ea-8bc2-62b236659d91.png)
The picture shows that I can actually import this but the error stays the same as the one above.

**Comment by CristiFati** [comment]
I played very little with *PyWin32* services, but I imagine they are started by *SYSTEM*. Hmm you should write the contents of *sys.executable*, *sys.path*, *site.getsitepackages()*, *site.getusersitepackages()* in a file, before importing *win32api* and look at the file after the service fails. Also, do the same thing before by executing the script manually.

**Comment by mhammond** [comment]
Further, services aren't going to have the full user environment even when configured to run as a different user. The most common problem I've found is simply that the PATH isn't what you expect, so the DLLs aren't found (or in strange edge cases, the wrong ones are found). This is exactly why the .exe installer puts the DLLs into system32, and why pip installed pywin32s are always going to have issues in these kinds of contexts.

**Comment by yuval9313** [comment]
You were right!
So adding the `%Project_DIR%\venv\Lib\site-packages\pywin32_system32` to the **global** path actually solved the error above, so good job, that's a solution for anyone seek for it in regards to services

Although, now there is another issue which is more relevant to the title: 
![image](https://user-images.githubusercontent.com/30751157/79644401-70ce8a80-81b1-11ea-8bbf-e625b267e4c9.png)

So, what now? how come when `pywintypes38.dll` is recognized the library is not?
It's important to mention that this error occurs on any import and not just the one in the picture

**Comment by mhammond** [comment]
>  how come when `pywintypes38.dll` is recognized the library is not?

There's a `pywintypes.py` that must be on `sys.path`

**Comment by vernondcole** [comment]
Perhaps we should file a feature request with the virtualenv group?

**Comment by CristiFati** [comment]
This is strange. https://github.com/mhammond/pywin32/pull/1442, should take care of this particular case. 

Anyway, the original issue reported here doesn't seem to reproduce anymore. Probably it would be OK to create anew one (which only affects services?) I will take a look (give a shot), but only over the weekend.

**Comment by mhammond** [comment]
TBH, I don't think virtualenv is the correct tool to use for services - the stand alone server should be use. Same thing for implementing COM objects which should be made available to all users, such as shell extensions etc.

**Comment by CristiFati** [comment]
To summarize: a simple `import win32api` in a plain *PyWin32 **228*** install on a *Python **3.8*** virtual environment (*VirtualEnv* or *VEnv*) should be working now . If anyone experiences some problems, please post the steps to reproduce, and also repeat them on theirs *PC* before posting here (as the initial setup might be corrupt).

The service problem remains (unfortunately I didn't have the time to confirm / infirm it). Probably this issue should be renamed (and the description changed) to reflect reality, or simply closed and another one open.

In any case, if encountering any problems, please start from a clean initial environment!

**Comment by Avasam** [comment]
> To summarize: a simple `import win32api` in a plain _PyWin32 **228**_ install on a _Python **3.8**_ virtual environment (_VirtualEnv_ or _VEnv_) should be working now . If anyone experiences some problems, please post the steps to reproduce, and also repeat them on theirs _PC_ before posting here (as the initial setup might be corrupt).
> [...] or simply closed and another one open.

I agree, OP has been resolved.

> The service problem remains (unfortunately I didn't have the time to confirm / infirm it).

Paths and services issues are replicated in other stories as well. Like in https://github.com/mhammond/pywin32/issues/1399 and https://github.com/mhammond/pywin32/issues/1865#issuecomment-1111546777 (and old issues with less details many already closed)
