### ISSUE TITLE
Special Char Error. python pandas and win32com

### ISSUE THREAD

**Issue by elmaquito** [mhammond/pywin32#1472]
Hi, I hope you are having a good night/day. Im actually developing a module with django that extract a xlsx file with datas from my server and it worked for a few files. for the process, i request data from my server filtered by my need and put them into a pandas dataframe then i insert it in a xlsx template by using Win32com and export it on a local driver, when i tried yesterday, it worked!!!. But when i tried to do an extract from my webapp today. i had an unexpected surprise, an Exception Error:

com_error at /extract/extract_files (-2147352567, 'Exception occurred.', (0, None, None, None, 0, -2146827284), None)

so i did research on this error and on my database to see what is the problem between the files created last day and this one. actually it seems like the new one have a LOT of text with special character, but it's not like it's a few char that causing the problem.(the data for this file his more than 8000 rows). this is how put data into my template.

   
   
    df2 = pd.DataFrame(dict_datas_c2)
    df1 = pd.DataFrame(dict_datas_c1)
    df3 = pd.DataFrame(dict_datas_c3)

    # convertion de l'objet en date

    df1['Task End Date'] = pd.to_datetime(df1['Task End Date'])
    df1['Previous Inspection Date'] = pd.to_datetime(df1['Previous Inspection Date'])

    # conversion de date en str

    df1['Task End Date'] = df1['Task End Date'].dt.strftime('%Y-%m-%d')
    df1['Previous Inspection Date'] = df1['Previous Inspection Date'].dt.strftime('%Y-%m-%d')

    df1['Previous Inspection Date'] = df1['Previous Inspection Date'].replace('NaT', '')

    ########################## CREATION PERSONALIZED PATH AND PATH FOR OUTPUT FROM TEMPLATE##########################

    date_now = datetime.datetime.now()
    date_str = date_now.strftime("%d%m%Y" + "_" + "%H" + "%M")

    path = './SUPPORT DATA FILES/'
    filename = 'ED_' + ed + '_' + ed_name + '_' + date_str + '.xlsx'

    extract_filename = path +  filename 
    template_file = #another path

    copyfile(template_file, extract_filename)
    ########################## INSERTING DATAS INTO EXCELFILE ########################################################

    pythoncom.CoInitialize()

    # Open excel to access to template

    excel = win32.GetObject(None, 'Excel.Application')

    # def workbook

    wb = excel.Workbooks.Open(extract_filename)

    # each sheet

    first_sheet_info=wb.Worksheets("NOTES")
    second_sheet_C1=wb.Worksheets("C1. Scheduled Maintenance Tasks")
    third_sheet_C2= wb.Worksheets("C2. Findings&Corrective Actions")

    # inserting datas into each sheet

    first_sheet_info.Range(first_sheet_info.Cells(2,1),# Cell to start the "paste"
                first_sheet_info.Cells(1+len(df3.index)-1,
                1+len(df3.columns)-1)
            ).Value = df3.values

    second_sheet_C1.Range(second_sheet_C1.Cells(4,1),# Cell to start the "paste"
                second_sheet_C1.Cells(4+len(df1.index)-1,
                1+len(df1.columns)-1)
            ).Value = df1.values

    third_sheet_C2.Range(third_sheet_C2.Cells(4,1),# Cell to start the "paste"
            third_sheet_C2.Cells(4+len(df2.index)-1,
                    1+len(df2.columns)-1)
            ).Value = df2.values

    # excel close and save

    wb.Close(SaveChanges=1)
    excel.Quit()

    name_of_file = str(filename)
    list_files.append(name_of_file)
so, the sheet i'm struggling with is the "third_sheet_C2" where some columns have a special char:

This is the code that insert the dataframe into the template with win32com.client.
![Capture](https://user-images.githubusercontent.com/52471848/73245544-c300a080-41ac-11ea-93ef-86596a047771.PNG)

Please if you guys have any idea on how to help me or another solution to put the df into a templates without using win32com, tell me!! PS: i already tried to use openpyxl and it doesn't work.

**Comment by mhammond** [comment]
This isn't a pywin32 bug - try searching google for those error codes. If you need more help, please follow the support links, which was in the boilerplate issue test you deleted when creating this issue.
