### ISSUE TITLE
Pip install on python3.6 missing postinstall.py

### ISSUE THREAD

**Issue by vctibor** [mhammond/pywin32#1473]
Hi, if I install pywin using pip on python 3.6, install target directory doesn't contain postinstall.py. Doing the same on python 3.7 or 3.8 behaves as expected - postinstall.py is found in target dir.

* Steps to reproduce the problem:

`python.exe -m pip install pywin -t target_dir`

* Expected behavior:

`target_dir` contains (anywhere inside it) `postinstall.py`.

* Actual behavior:

`target_dir` doesn't contain `postinstall.py`.

* Version of Python and pywin32:

- python 3.6
- pywin32 227 
- Windows 10

Now I'm not sure if this is bug, expected or out of scope. It's possible to close this issue with "just upgrade python" but it would be great if there was other solution.

I'd be willing to help with PR, but I'm not sure if it's related to pip packaging or something else.

**Comment by mhammond** [comment]
Thanks for reporting. It's not expected and I really have no idea why it wouldn't be working only on 3.6.

**Comment by vernondcole** [comment]
Testing this report on a new Windows 10 virtual machine (from
https://github.com/salt-bevy/salt-bevy `vgr up win10` ), I get the
following results: . . .

(Note: pywin is a different product and does not install on either version.
Assuming RP intended to install pywin32.)

- installed Python 3.6.8 from python.org download via executable installer.
- mkdir target_dir
- py -m pip install --upgrade pip
- py -m pip install pywin32 -t target_dir
( found file C:\Users\vagrant\target_dir\bin\pywin32_postinstall.py )
- installed Python 3.8.1 as above
- mkdir target_2
- py -3.8 -m pip install pywin32 -t target_2
  ( found file C:\Users\vagrant\target_2\bin\pywin32_postinstall.py )

I found the same postinstall in the same place on both systems. Neither
installed "postinstall.py".  Lets call this a "cannot duplicate" report.
--
Vernon Cole

**Comment by vctibor** [comment]
So the issue was caused by old version of `pip`. This is my bad for not trying with up to date version.

Sorry for creating issue, but hopefully it will help someone.
