### ISSUE TITLE
DLL load failed

### ISSUE THREAD

**Issue by Mockbeth** [mhammond/pywin32#1481]
* Expected behavior and actual behavior.

I installed pywin32 via pip back around November, im not sure which version it was, but it worked and without any additional postinstall. 

Later I installed xlwings (ver 0.15.8)  and recently I had to reinstall xlwings (ver 0.18). Since the reinstall pywin32 is throwing an error when loading win32api:
"DLL load failed: The specified procedure could not be found."

I reinstalled pywin32 via pip and ran the postintall file, which didn't solve my issue. I reinstalled pywin32 via binary executable, which also didn't solve my issue. I tried running pywin32 version 224. It doesn't throw the DLL error, however it throws another error, which doesn't seem to be critical since the code itself is working.

Im not sure what else to try, any help is appreciated. 

* Steps to reproduce the problem.

To reproduce the problem I just try to import win32api in a jupyter notebook

* Version of Python and pywin32

Python 3.7.3 (via anaconda) 
pywin32 227
xlwings 0.18
windows 10
* update

Before the problem appeared i have installed a piece of software that conflicted with my application references. Since then i have deleted the software but the damage was done, It might be the case that dll references got mixed as well and pywin32 is looking for the dll's in the wrong place. i'll update once i know more

* update 2

as far as I can see py*.dlls are not in my missing shared dlls list in ccleaner

**Comment by vernondcole** [comment]
IIRC anaconda has a version of pywin32 pre installed. It is possible that
there is a version clash between the two installations. Perhaps using the
official installer from python.org would work correctly? (Have not tested
any of this, just guessing)

**Comment by Mockbeth** [comment]
i have uninstalled pywin32 via pip several times and deleted pywin32 folders from anaconda to make sure there is no trace of it before reinstalling
before reinstalling i checked for the library with 'pip show pywin32' to see if it is there still
i dont think i have two different versions installed

**Comment by mhammond** [comment]
Check for py*.dll in your system32 directories.

**Comment by Mockbeth** [comment]
My system32 directory contains 2 py dlls:
pythoncom37.dll
pywintypes37.dll

**Comment by juliuscrn** [comment]
having the same issue. tried reinstalling, running the post install script, nothing works. to make it worse I dont have admin rights.

**Comment by Mockbeth** [comment]
> having the same issue. tried reinstalling, running the post install script, nothing works. to make it worse I dont have admin rights.

before reinstalling i searched my C drive for every occurrence of py* or pywin32 to make sure i delete all of the dll's and weird things that are outside of anaconda directory 

make sure you follow the proper anaconda uninstall procedure (i used option A, option B didnt work for me) and wipe out everything that remains

admin rights are a tough thing. talk to your employer/try elevation, if your IT system supports it

**Comment by juliuscrn** [comment]
resolved by installing from wheel.

**Comment by Mockbeth** [comment]
Following the fresh anaconda reinstall I created a venv where I updated both pywin32 (to 227, I didnt run the post_install script) and xlwings (to 0.17.something) and my code ran without any error. this leads me to believe that indeed before I had some of my packages versions confused and dll references mixed up
