### ISSUE TITLE
pywin32window gets smaller (overall size and font) when use >>plt.show() 

### ISSUE THREAD

**Issue by CompuNeuroPsychiatryLabEinKerem** [mhammond/pywin32#1486]
[Open pywin32 window]
Write:

>>> from matplotlib import pyplot as plt
>>> plt.plot([1,2,3], [1,2,3])

On plt.plot() (before show() or draw()), the whole window (both window size and all fonts) becomes smaller be nearly half. Resizing the window doesn't change its font.

Why does this happen?
Thank you

**Comment by mhammond** [comment]
Different GUI environments often have trouble working together. You should probably use matplotlib from the command-line rather than via pythonwin.
