### ISSUE TITLE
setup.py build fails on Visual Studio 2019 with WDK 10

### ISSUE THREAD

**Issue by SofianJabal** [mhammond/pywin32#1487]
Hi,
I'm facing issues with building the package using VS 2019
Could you please add support to WDK 10 or or send instructions on how to do it?

**Comment by mhammond** [comment]
Sorry, I doubt I'm going to have time. How about *you* add this support and send me the instructions?

**Comment by SofianJabal** [comment]
I tried :), but I'll check again and update

**Comment by SofianJabal** [comment]
How did you build a wheel package (amd64) for Windows?

**Comment by mhammond** [comment]
See https://github.com/mhammond/pywin32/blob/master/make_all.bat

**Comment by icanhasmath** [comment]
I have had success building pywin32 on VS2019 by installing the `VS2015 MSVC v140 Toolset`, but I am wondering if it is possible to build with v142 Toolset components only?

This toolset is referenced here: https://github.com/mhammond/pywin32/issues/1489#issuecomment-602117958

**Comment by mhammond** [comment]
> but I am wondering if it is possible to build with v142 Toolset components only?

I have no idea, I've never tried.

**Comment by kxrob** [comment]
> `MSVC v140 Toolset`, but I am wondering if it is possible to build with v142 Toolset components only?

Whatever is behind these menu names in the various installation variants: The recent Python versions are still compiled against `vcruntime140.dll` - and conforming Python extensions always need to use the same msvc lib version (and corresponding headers) as the Python dll.  `setup.py` / distutils would bark if not found.

**Comment by Avasam** [comment]
Note to readers that [`python setup.py` and the use of setup.py as a command line tool are deprecated](https://packaging.python.org/en/latest/discussions/setup-py-deprecated/#is-setup-py-deprecated). pywin32 itself needs to move away from it. #2208

As for the build environment, please see the updated instructions in https://github.com/mhammond/pywin32/blob/main/build_env.md#build-environment
