### ISSUE TITLE
How to set up the build environment

### ISSUE THREAD

**Issue by markuskramerIgitt** [mhammond/pywin32#1489]
I try to set up and document the build environment (for Python 3)

Related: https://github.com/mhammond/pywin32/issues/1487

This is a rewrite of https://wiki.python.org/moin/WindowsCompilers

## Install Microsoft Visual C++ compiler for Python 3.5, 3.6, 3.7, 3.8

Microsoft Visual C++ 14.2 is in Visual Studio 2019

- Download the [Installer for Visual Studio 2019](https://visualstudio.microsoft.com/thank-you-downloading-visual-studio/?sku=BuildTools&rel=16#) (~ 1 MB)
- In the installer:
  - Check `C++ build tools`
    - In the menue to the right, check:
        - `MSVCv142 - VS 2019 C++ x64/x86 build tools`
        - `Windows 10 SDK`
        - `C++ MFC for latest v142 build tools` (automatically ticks `C++ ATL`)
          - Note: The installer does not contain MFC for v140
    - Press `Install` (~ 5 GB)
- Restart

- Include the "Microsoft (R) Message Compiler" into the path
  - Search

    dir /b /s mc.exe

  - and set (example)

    set "path=%path%;c:\Program Files (x86)\Windows Kits\10\bin\10.0.18362.0\x64"

- Run

    python setup.py -q build

## Error

    RuntimeError: No MFC files found!

What am I missing/doing wrong?

Thank you

**Comment by markuskramerIgitt** [comment]
If that helps: I searched for `mfc14*u.dll` and got a number of places
```
C:\>dir /b /s mfc14*u.dll
C:\Program Files\WindowsApps\Microsoft.VCLibs.140.00.UWPDesktop_14.0.27810.0_x64__8wekyb3d8bbwe\mfc140deu.dll
C:\Program Files\WindowsApps\Microsoft.VCLibs.140.00.UWPDesktop_14.0.27810.0_x64__8wekyb3d8bbwe\mfc140enu.dll
C:\Program Files\WindowsApps\Microsoft.VCLibs.140.00.UWPDesktop_14.0.27810.0_x64__8wekyb3d8bbwe\mfc140u.dll
C:\Program Files\WindowsApps\Microsoft.VCLibs.140.00.UWPDesktop_14.0.27810.0_x86__8wekyb3d8bbwe\mfc140deu.dll
C:\Program Files\WindowsApps\Microsoft.VCLibs.140.00.UWPDesktop_14.0.27810.0_x86__8wekyb3d8bbwe\mfc140enu.dll
C:\Program Files\WindowsApps\Microsoft.VCLibs.140.00.UWPDesktop_14.0.27810.0_x86__8wekyb3d8bbwe\mfc140u.dll
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Redist\MSVC\14.25.28508\x64\Microsoft.VC142.MFC\mfc140u.dll
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Redist\MSVC\14.25.28508\x64\Microsoft.VC142.MFCLOC\mfc140deu.dll
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Redist\MSVC\14.25.28508\x64\Microsoft.VC142.MFCLOC\mfc140enu.dll
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Redist\MSVC\14.25.28508\x86\Microsoft.VC142.MFC\mfc140u.dll
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Redist\MSVC\14.25.28508\x86\Microsoft.VC142.MFCLOC\mfc140deu.dll
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Redist\MSVC\14.25.28508\x86\Microsoft.VC142.MFCLOC\mfc140enu.dll
C:\Program Files (x86)\VR-NetWorld\mfc140deu.dll
C:\Program Files (x86)\VR-NetWorld\Recover\data\mfc140deu.dll
C:\Python35\Lib\site-packages\pythonwin\mfc140u.dll
C:\Windows\System32\mfc140deu.dll
C:\Windows\System32\mfc140enu.dll
C:\Windows\System32\mfc140u.dll
C:\Windows\SysWOW64\mfc140deu.dll
C:\Windows\SysWOW64\mfc140enu.dll
C:\Windows\SysWOW64\mfc140u.dll
```

**Comment by markuskramerIgitt** [comment]
After reading https://stackoverflow.com/questions/33154696/msbuild-error-the-builds-tools-for-v140-platform-toolset-v140-cannot-be-f and 
https://devblogs.microsoft.com/cppblog/visual-studio-build-tools-now-include-the-vs2017-and-vs2015-msvc-toolsets/ it seems:

MFC v140 may be in Visual Studio Build Tools 2017, which is available https://my.visualstudio.com after login. 

Installed MFC from Visual Studio Build Tools 2017 (15.9) without success.

Installed MFC from Visual Studio Build Tools 2017 (15.9) without success.

Error is always
```
C:\git\pywin32>python setup.py -q build
Building pywin32 3.5.227.1
Skipping exchdapi: No 64-bit library for utility functions available.
Skipping win32ui: The header 'afxres.h' can not be located.
Skipping win32uiole: The header 'afxres.h' can not be located.
Skipping dde: The header 'afxres.h' can not be located.
Skipping Pythonwin: The header 'afxres.h' can not be located.
Can't find MFC contents in VisualStudio. Looking into WinSxS now..
Could not find any redist libraries in WinSxS!
Traceback (most recent call last):
  File "setup.py", line 2583, in <module>
    ('', ('pywin32.pth',)),
  File "C:\Python35\lib\site-packages\setuptools\__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "C:\Python35\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Python35\lib\distutils\dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "C:\Python35\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 648, in run
    build.run(self)
  File "C:\Python35\lib\distutils\command\build.py", line 135, in run
    self.run_command(cmd_name)
  File "C:\Python35\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Python35\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Python35\lib\site-packages\setuptools\command\build_ext.py", line 75, in run
    _build_ext.run(self)
  File "C:\Python35\lib\distutils\command\build_ext.py", line 339, in run
    self.build_extensions()
  File "setup.py", line 1035, in build_extensions
    raise RuntimeError("No MFC files found!")
RuntimeError: No MFC files found!
```

**Comment by markuskramerIgitt** [comment]
This [devblogs](https://devblogs.microsoft.com/cppblog/visual-studio-build-tools-now-include-the-vs2017-and-vs2015-msvc-toolsets/) say (see Screenshot! )
> Many of you have told us that you still need the MSVC v140 toolset from Visual Studio 2015 to continue building older codebases


> The Visual C++ build tools workload in the Visual Studio Build Tools will install the latest v141 >toolset from VS2017 by default. The v140 toolset from VS2015 will install side-by-side with the v141 toolset. To install them just **select the “VC++ 2015.3 v140 toolset for desktop (x86,x64)” at the bottom of the “Optional” section.**

**Comment by markuskramerIgitt** [comment]
Question:
- Why do I need to include mc in the path?

**Comment by mhammond** [comment]
>     * Why do I need to include mc in the path?

mc is used in the build to embed message resources in a few of the built files. Is that what you are asking?

**Comment by markuskramerIgitt** [comment]
No, I don't question the reason for mc. Looks like an interesting technology. 

I wanted confirmation that amending the path environment variable on its own completes the pywin32 build environment, and that I don't miss steps which include amending the path.

Thank you, I will create a pull request for a markdown document.

**Comment by vernondcole** [comment]
Markus:
   Thank you! Good work on the document.

Dear Group:

I have been attempting on-and-off for several years to build a working
pywin32 build machine. I have never (yet) succeeded, but the project has
floated back to the top of my personal to-do list. This time, I am writing
a script to create an entire build-and-test assembly, so that I will never
again have to submit an untested pull request.  When complete, this script
is intended to be able to set up a build machine suitable for our CI/CD, or
for anyone who wants to be able to set up a build system with a few typed
(or cut-and paste) lines of command. None of the
pull-down-this-and-click-that kind of thing, so it will work on virtual
machines in a headless environment.

The deployment tool I have selected is Salt, <https://docs.saltstack.com>
which operates well on Windows, partly because it is written in Python
using pywin32. I am adding the necessary scripts to a Salt demonstration
system (salt-bevy <https://github.com/salt-bevy/salt-bevy>) which I
maintain, which already has most of the tools needed. The first baby steps
are in the pywin32_test_environment
<https://github.com/salt-bevy/salt-bevy/tree/pywin32_test_environment>
branch.

Consider this to be an announcement, and a request for frequent help. When
I hit each road block (the first of which I expect a few hours hence) I
will post a new thread on this forum. With help from all of you, each road
block will be solved in turn.
--
Vernon Cole

**Comment by markuskramerIgitt** [comment]
Hi @vernondcole, isn't that funny: I come to pywin32 because Salt uses it.

In particular, I would like to propose a headless distribution variant of pywin32, which fits even better into Salt. 

I was also wondering how to test pywin32, so I can use the bevy, very handy.

**Comment by markuskramerIgitt** [comment]
@vernondcole, I have repeated the install on a second PC, so I have confidence in the "pull-down-this-and-click-that" description of the setup.

As you are aware, Salt uses pywin32. 

I would like to build a pywin32 variant without MFC. This would exclude Pythonwin and Scintilla, and all other GUI elements, because Salt does not require, and therefore should not contain MFC.

I can ran `python setup.py -q build`.

Could you give me an advise how to proceed?
