### ISSUE TITLE
Read/WriteProcessMemory Support

### ISSUE THREAD

**Issue by achillis2016** [mhammond/pywin32#1502]
There is no ReadProcessMemory/WriteProcessMemory function in module win32process , why? This two functions is very important.

**Comment by mhammond** [comment]
Because no one has implemented it yet. A PR would be welcome.

**Comment by mhammond** [comment]
I added this in cd79d136

**Comment by AintIaStinker** [comment]
Thank you very much for adding this in! I am just learning python and this really saved me a lot of time. Appreciated 👍
