### ISSUE TITLE
Unresolved import in VS2019 but imports into command line no problem.

### ISSUE THREAD

**Issue by M103Tanker** [mhammond/pywin32#1505]
I installed the correct pywin32 for Python38 32 bit but none of the imports work in VS code 2019.  I see all of them in python site-packages, however.  When I go to cmd and open up python, I can import them in without error.  Any ideas? I have only been using python for a few days.

The VS error is "unresolved import 'win32api'"

**Comment by mhammond** [comment]
I suspect vscode is using a different python? https://github.com/mhammond/pywin32#support is a good place to get help with python on Windows.

**Comment by M103Tanker** [comment]
Unfortunately, both the installation and Visual Studio are using Python 3.8 32bit

**Comment by mhammond** [comment]
But vscode might ship with its own Python 3.8 and not be using your user-installed Python 3.8 where you installed pywin32? You should consider an email to the mailing list that's mentioned in the above #support link.
