### ISSUE TITLE
No error handling for CreateJobObject

### ISSUE THREAD

**Issue by christianbrugger** [mhammond/pywin32#1508]
### Expected behavior

`CreateJobObject` should raise a Python exception when the API call was not successful.

### Actual behaviour

Errors are silently ignored and the call even returns a valid handle.

### How to reproduce

```python
import win32api
import win32job

h1 = win32job.CreateJobObject(None, "test")
h2 = win32job.CreateJobObject(None, "test")

print("h1", h1)
print("h2", h2)
print("last error:", win32api.GetLastError(), win32api.FormatMessage())
```

This outputs

```
h1 <PyHANDLE:144>
h2 <PyHANDLE:436>
last error: 183 Cannot create a file when that file already exists.
```

### Possible workaround

Use `win32api.SetLastError(0)` before calling the function and check `win32api.GetLastError()` after calling the function.

### Possibly related issues

I looked at the source and suspect the same issue is present for other function in this module too, like `SetInformationJobObject`, `AssignProcessToJobObject`, `TerminateJobObject`, ... .

### Versions

Python 3.8.0, 64bit on Windows 10
pywin32 227 (installed via pip)

**Comment by mhammond** [comment]
That's how the [API is defined](https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-createjobobjecta) - you get a handle to the existing job, which you'd lose if an exception was thrown. 

pywin32 tries to keep the same semantics as the underlying API where possible, so this is working as intended.
