### ISSUE TITLE
Support for VirtualAllocEx/VirtualFreeEx

### ISSUE THREAD

**Issue by vbe0201** [mhammond/pywin32#1509]
Hello, I've been using pywin32 lately and wasn't able to find the functions mentioned in the title. Did I miss something or are they unimplemented?

In case of the latter, I'd be happy to open a Pull Request to add them, but I'll need some instructions on how to add support for new functions as I've never contributed to the project before.

**Comment by mhammond** [comment]
I added them in fa149c66 - probably isn't going to be a new release for a few weeks though.
