### ISSUE TITLE
Please add support for pywin32 on WSL (Windows Subsystem for Linux)

### ISSUE THREAD

**Issue by jspv** [mhammond/pywin32#1513]
Windows Subsystem for Linux is a compatibility layer for running Linux binary executables natively on Windows 10 and Windows Server 2019.  It's available on every Windows 10 system and is really nice, allows for running Ubuntu, Centos, etc. natively on Windows and the linux binaries have full visibility to the Windows filespace as well.  Seems like a potential fit for pywin32.

**Comment by vernondcole** [comment]
But,  sadly,  it is not a good fit.  Pywin32 interfaces with the COM
interface on Windows,  which does not exist in linux, nor on the linux
kernel which is the heart of WSL. In order to do COM things,  you have to
be running on the XT subsystem.

**Comment by jspv** [comment]
Thanks, was hoping that the windows components were more exposed to the subsystem.
