### ISSUE TITLE
ImportError with venv (Python 3.7)

### ISSUE THREAD

**Issue by axc450** [mhammond/pywin32#1514]
Hi,

I have been using pywin32 for around 2 years now with no issues. The apps that use pywin32 now need to be converted to use virtual environments. I am using the basic Python 3.7 `venv`.
I installed `pywin32` with `"env/Scripts/pip.exe" install pywin32`

I am getting the following error when running the app under a virtual environment:

```
import win32service, win32api, win32con, winerror
ImportError: DLL load failed: The specified module could not be found.
```
(in `win32serviceutil.py`)

I have run the post install script however it tried to modify things outside of the venv (I didnt pursue this any further as I didnt want to break the apps that are currently running).

Is there something simple I can do to fix this? Sharing the DLLs should be fine, but why cant it find them?

**Comment by mhammond** [comment]
Python is almost certainly finding older copies of the DLL which were installed via the installer.

**Comment by axc450** [comment]
Thanks. Ill trying updating the system wide version of pywin32 before attempting to migrate the apps to use a venv
