### ISSUE TITLE
No matching distribution found for pywin32

### ISSUE THREAD

**Issue by LavanyaKata** [mhammond/pywin32#1526]
Hi, 
I am using Pycharm IDE for python selenium automation. pywin32 installs successfully when installed in cmd prompt but when try to install the same in pycharm it says "Could not find a version that satisfies the requirement pywin32" and ' No matching distribution found for pywin32'.

Python version= 3.8.1
pycharm community edition.

Kindly help me put with the issue. Thanks in advance !!

**Comment by mhammond** [comment]
You should probably ask the pycharm project given it seems to work with vanilla python for you. You could also work out how to get diagnostic information from whatever command you are using - you don't actually say what command you tried to run.

**Comment by LavanyaKata** [comment]
I used below commands:
pip install --trusted-host pypi.python.org --trusted-host pypi.org --trusted-host files.pythonhosted.org pywin32

also pypiwin32 by replacing pywin32 in the above command. tried both but no luck.

**Comment by mhammond** [comment]
why such a complicated command? And what output?

**Comment by LavanyaKata** [comment]
the output is "Could not find a version that satisfies the requirement pywin32"

reason for such a long command is: installation has to be done offline using proxy.hence the command.

**Comment by mhammond** [comment]
I'm sure you can predict me saying the problem is likely with the proxy then? Either that, or something else about your environment - python 3.8 can install pywin32 from pypi fine.

**Comment by LavanyaKata** [comment]
ok Thanks..
