### ISSUE TITLE
[ci] Decrease build times

### ISSUE THREAD

**Issue by ofek** [mhammond/pywin32#1528]
(Opening this while it's in my mind)

While overall build times are faster than before, individual jobs take a bit longer than on AppVeyor

From https://github.com/mhammond/pywin32/blob/5f47dc1167270148880110f5b6541eb9e998c4d0/setup.py#L22-L24 Windows 8.1 SDK is a hard dependency

It didn't seem available on GitHub Actions runner https://help.github.com/en/actions/reference/software-installed-on-github-hosted-runners as `setup.py` failed

So we spend multiple minutes installing it from Chocolatey https://github.com/mhammond/pywin32/blob/5f47dc1167270148880110f5b6541eb9e998c4d0/.github/workflows/main.yml#L37-L38

Options:

- Drop 8.1?
- ~Maybe it's actually on runner & a .bat script somewhere needs to be executed?~
- Faster way to install it?

**Comment by ofek** [comment]
Hmm, found https://github.com/actions/virtual-environments/issues/842

> The Windows 8.1 SDK is no longer available in the Visual Studio installer. Please upgrade your C++ projects to the latest Windows 10 SDK. If you have a hard dependency on 8.1, you can download it from the Windows SDK archive.

> considering that it can be installed on runtime and it's a pretty old version, we won't install it by default in the images

**Comment by mhammond** [comment]
Dropping 8.1 sounds fine to me - the problems solved by insisting on that probably went away when earlier 2.x were dropped. It might make sense to tackle this after I drop 2.7 support though.

**Comment by ofek** [comment]
Did we drop 8.1 yet?

**Comment by mhammond** [comment]
yep
