### ISSUE TITLE
Feature: pythoncom, "Schedule.Service" and Principal2 (IPrincipal2)

### ISSUE THREAD

**Issue by quentinhardy** [mhammond/pywin32#1536]
Hello,

It seems the _IPrincipal2_ interface (https://docs.microsoft.com/is-is/windows/win32/api/taskschd/nn-taskschd-iprincipal2) is missing from **Scheduled Task** service.

For example, with the following code, you can get/set _Principal_ (https://docs.microsoft.com/is-is/windows/win32/api/taskschd/nn-taskschd-iprincipal) of a scheduled task:

```python
[...]
service = win32com.client.Dispatch("Schedule.Service")
service.Connect()
rootFolder = service.GetFolder(location)
taskDefinition = service.NewTask(0)
regInfo = taskDefinition.RegistrationInfo
[...]
principal = taskDefinition.Principal
principal.LogonType = logonType
[...]
```

However, I have not found a method for accessing to Principal2 for _AddRequiredPrivilege(_) for example.

I would like to do something like that (pseudo code):
```C++
IPrincipal2* pP2 = NULL;
 pPrincipal->QueryInterface(IID_IPrincipal2, (void**)&pP2)
```

Do you have an idea for accessing to principal2?

GUID of _IPrincipal2_ : {248919AE-E345-4A6D-8AEB-E0D3165C904E}

Thank you in advance for your help,

**Comment by sschukat** [comment]
You can access the interface as you suggested via QueryInterface and "interprete" the result as IDispatch. E.g.. 
```python
import pythoncom
IID_IPrincipal2 = pythoncom.MakeIID("{248919AE-E345-4A6D-8AEB-E0D3165C904E}")`
[...]
principal = taskDefinition.Principal
# get the raw interface
iprincipal2 = principal._oleobj_.QueryInterface(IID_IPrincipal2, pythoncom.IID_IDispatch)
# create a IDispatch Wrapper
principal = win32com.client.Dispatch(iprincipal2)
# call the function
principal.AddRequiredPrivilege(...)
```

**Comment by quentinhardy** [comment]
Thank you for your help.

It seems I have done a mistake somewhere...

When I would like to access to _AddRequiredPrivilege()_, I have the following error:

```python
[...]
    principal2.AddRequiredPrivilege("SeTimeZonePrivilege")
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\win32com\client\dyn
amic.py", line 527, in __getattr__
    raise AttributeError("%s.%s" % (self._username_, attr))
AttributeError: <unknown>.AddRequiredPrivilege
```

Are methods are automatically "mapped" with _Dispatch()_ ?
I don't need to declare manually _AddRequiredPrivilege()_ somewhere? with a IUnknown class for example?

Tested code:
```python
service = win32com.client.Dispatch("Schedule.Service")
service.Connect()
rootFolder = service.GetFolder(location)
taskDefinition = service.NewTask(0)
principal = taskDefinition.Principal
principal.LogonType = logonType
IID_IPrincipal2 = pythoncom.MakeIID("{248919AE-E345-4A6D-8AEB-E0D3165C904E}")
iprincipal2 = principal._oleobj_.QueryInterface(IID_IPrincipal2, pythoncom.IID_IDispatch)
principal2 = win32com.client.Dispatch(iprincipal2)
principal2.AddRequiredPrivilege("SeTimeZonePrivilege")
```

Thank you in advance for your help,

**Comment by sschukat** [comment]
If you are using dynamic dispatch you must not declare any extra function.  This is the output of my system
```python
>>> from win32com.client import Dispatch
>>> import pythoncom
>>> service = Dispatch("Schedule.Service")
>>> service.Connect()
>>> taskDefinition = service.NewTask(0)
>>> principal = taskDefinition.Principal
>>> IID_IPrincipal2 = pythoncom.MakeIID("{248919AE-E345-4A6D-8AEB-E0D3165C904E}")
>>> iprincipal2 = principal._oleobj_.QueryInterface(IID_IPrincipal2, pythoncom.IID_IDispatch)
>>> principal2 = Dispatch(iprincipal2)
>>> principal2.AddRequiredPrivilege("SeTimeZonePrivilege")
>>>
```
You could check if the method is available in the implementation of the COM server

```python
>>> principal2._oleobj_.GetIDsOfNames(0, "AddRequiredPrivilege")
13
```

**Comment by quentinhardy** [comment]
Thank you for your help.

It works now.
IPrincipal2 is not available on wind7 for example. On win10 it works.

Thank you again.
Best regards,
