### ISSUE TITLE
word.CentimetersToPoints(1.1)  fails

### ISSUE THREAD

**Issue by retsyo** [mhammond/pywin32#1538]
I met this problem on word 2019 on win 10 64 bits
1. there is `word.CentimetersToPoints`
2. but `word.CentimetersToPoints(1.1)`  crashes the program

so I searched and found [post from 2001](http://computer-programming-forum.com/56-python/83ed3e3767f78add.htm)

what is the suggested solution today? thanks

**Comment by mhammond** [comment]
Please see https://github.com/mhammond/pywin32#support
