### ISSUE TITLE
Different behavior when running from * .exe or * .py

### ISSUE THREAD

**Issue by AndreiRadac** [mhammond/pywin32#1544]
I have a Python project developed by a colleague, in which pywin32  is used to control the application: CANoe from Vector.

When he is running the *.py script from PyCharm (2019.2.5) everything is ok, if he used auto-py-to-exe to convert the python script to *.exe, and then he executes the *.exe everything is ok, in both cases the script is working perfectly fine.

Now the problem is the following: if I'm trying to run the *.py script from PyCharm (2020.1.2) the module pywin32 is throwing an exception:
raise AttributeError("'%s' object has no attribute '%s'" % (repr(self), attr))AttributeError: '<win32com.gen_py.CANoe 11.0 Type Library.ITestEnvironment instance at 0x2039251561776>' object has no attribute 'TestModules'

From what I checked the COM Library has 2 dispinterface: ITestEnvironment and ITestEnvironment2, and only ITestEnvironment2 has the attribute TestModules, and it seems that in my case somehow the script is not considering the correct interface.

If I use auto-py-to-exe to convert the python script to *.exe, and then execute the *.exe, everything works perfectly fine. If he converts the script to *.exe and then I run it on my PC, or I convert locally the script to *.exe and run it on my PC, in both cases the output of the script is the same.

I tried:
- Install the same PyCharm version as he uses- Run the code from Visual Studio 2017- Update pywin32 to latest version (228)
in all the cases the result is the same.

I'm using the same Python version as he uses: Py 3.6.7.
Dose anyone know why pywin32 has different behavior when running from * .exe or * .py, and also why it has different behavior on different PCs ?

P.S: I posted the same question also on the mailing list, but I didn't received any answer, maybe here someone can help.

**Comment by mhammond** [comment]
I suspect the problem will be something to do with the typelib. The exception raised mentioned "gen_py", so it's not doing much dynamically, but instead using a generated .py file. I suspect where it works is doing things dynamically? Try a third machine without pycharm involved - that will at least tell you which machine has the key difference (and as mentioned, it may well just be the fact the typelib is installed there but not on the others)

**Comment by AndreiRadac** [comment]
@mhammond I don't fully understand what you want to say with "doing things dynamically" ? The typelib is installed, otherwise I assume that the *.exe should not work.

**Comment by mhammond** [comment]
win32com works in 2 ways "dynamically" where it looks up the methods and attributes on the COM object as they are used, or more statically, where "gen_py" is run over a type-library (often via 'EnsureDispatch()` instead of a plain `Dispatch()`) and a .py file generated with all the attributes/methods and their args. In a normal .py environment, the generated files are in site-packages\win32com\gen_py. The latter is far more efficient. The fact the traceback references "gen_py" implies the latter.

**Comment by mhammond** [comment]
(and it's typically not necessary for a typelib to exist for the "dynamic" variant to work - many COM objects ship without typelibs, so dynamic dispatch is the only option. If a typelib does exist, then both dynamic and generated support are likely to work, but sometimes with subtly different semantics.)

**Comment by AndreiRadac** [comment]
@mhammond I checked the folder gen_py, and there were some files based on the type library that i'm using, one of them generated recent, so the attribute should be in there. What I did was to delete the entire content of gen_py, and now it seems that the script is not throwing the exception anymore.
The only files that are now generated is __init__.py and dicts.dat + __pycache__ folder.

**Comment by sschukat** [comment]
@AndreiRadac : In addition to Mark's comment. In the implementation win32com always tries to find a Python wrapper for a COM class. Hence even if you do not specify not to use a wrapper class (dynamic), the error might occur if a pre-generated wrapper was found. To circumvent this you could either cast to dynamic
```python
>>> from win32com.client import gencache
>>> service = gencache.EnsureDispatch("Schedule.Service") # generate python wrapper
>>> service # object using python wrapper class 
<win32com.gen_py.E34CB9F1-C7F7-424C-BE29-027DCC09363Ax0x1x0.ITaskService instance at 0x287535152>
>>> from win32com.client import dynamic
>>> servicedyn = dynamic.Dispatch(service) # Cast to dynamic
>>> servicedyn # object using dynamic class
<COMObject <unknown>>
``` 
or cast to the other interface contained in a full wrapper
```python
>>> from win32com.client import gencache
>>> service = gencache.EnsureDispatch("Schedule.Service", 0) # generate a full python wrapper
>>> service.Connect()
>>> taskDefinition = service.NewTask(0)
>>> principal = taskDefinition.Principal
>>> principal # object using python wrapper class 
<win32com.gen_py.E34CB9F1-C7F7-424C-BE29-027DCC09363Ax0x1x0.IPrincipal instance at 0x134745944>
>>> import sys
>>> principal2 = sys.modules[principal.__class__.__module__].IPrincipal2(principal)  # use other interface from wrapper
<win32com.gen_py.E34CB9F1-C7F7-424C-BE29-027DCC09363Ax0x1x0.IPrincipal2 instance at 0x115941168>
```

**Comment by AndreiRadac** [comment]
@sschukat Thanks for the info!

**Comment by mhammond** [comment]
Thanks @sschukat - given the above, it should be possible to reduce your problem to literally just a few lines that behave differently. It's difficult to speculate further without seeing any code.

**Comment by AndreiRadac** [comment]
@mhammond Yeah I know that analyzing directly the code is easier, but in this case is a private project and can't share the code. 
But considering that if I deleted the content off gen_py solved the issue, we can close the issue. If I encounter some similar problems in the future I'll try to solution from @sschukat. 

Thanks a lot!
