### ISSUE TITLE
Share:   pywin32 dll is not win32 issue.

### ISSUE THREAD

**Issue by xifarm** [mhammond/pywin32#1550]
python environ:

```
Python 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
```

windows 10 64.

i install from pip there are error: dll is not 32.
`pip install pywin32`

how to fixed?

the right method is:

- Step 1: https://pypi.org/project/pywin32/#files

download the right whl packge by hand.
**pywin32-228-cp37-cp37m-win_amd64.whl (9.1 MB)** 

- step 2: install 
pip install pywin32-228-cp37-cp37m-win_amd64.whl 

this work for me.

**Comment by mhammond** [comment]
Are you still able to reproduce this? `pip install pywin32` seems to work fine in general.

**Comment by mhammond** [comment]
Nothing I can do here without more details.
