### ISSUE TITLE
SystemError in win32com's PyIDispatch.Invoke

### ISSUE THREAD

**Issue by wkschwartz** [mhammond/pywin32#1551]
In the following example, pywin32com's `PyIDispatch.Invoke` mishandles a `TypeError` exception, causing Python to raise a `SystemError`. The example uses xlwings 0.15.8 on Python 3.7.7, Windows 10, and whatever the latest desktop version of Excel is.  The error does not occur if pywin32 version 224 is installed, but does occur if any of versions 225 through 228 is. I've also confirmed this behavior on `master` at f9428a90ba6e3b97480221daf574c0388f8275a3.

The Excel/xlwings aspect isn't the point here---all that matters is that the `TypeError` below is correctly raised and should be propagated. However, pywin32 causes another exception while the `TypeError` is pending.

```Python traceback
>>> import xlwings
>>> xlwings.__version__
'0.15.8'
>>> from uuid import uuid4
>>> book = xlwings.Book()
>>> book.sheets[0].range("A1").value = uuid4()
TypeError: must be real number, not UUID

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "venv\lib\site-packages\xlwings\main.py", line 1525, in value
    conversion.write(data, self, self._options)
  File "venv\lib\site-packages\xlwings\conversion\__init__.py", line 43, in write
    pipeline(ctx)
  File "venv\lib\site-packages\xlwings\conversion\framework.py", line 66, in __call__
    stage(*args, **kwargs)
  File "venv\lib\site-packages\xlwings\conversion\standard.py", line 63, in __call__
    self._write_value(ctx.range, ctx.value, scalar)
  File "venv\lib\site-packages\xlwings\conversion\standard.py", line 51, in _write_value
    rng.raw_value = value
  File "venv\lib\site-packages\xlwings\main.py", line 1146, in raw_value
    self.impl.raw_value = data
  File "venv\lib\site-packages\xlwings\_xlwindows.py", line 724, in raw_value
    self.xl.Value = data
  File "venv\lib\site-packages\xlwings\_xlwindows.py", line 98, in __setattr__
    return setattr(self._inner, key, value)
  File "venv\lib\site-packages\win32com\client\dynamic.py", line 565, in __setattr__
    self._oleobj_.Invoke(entry.dispid, 0, invoke_type, 0, value)
SystemError: <built-in method Invoke of PyIDispatch object at 0x000001D8780A9AF8> returned a result with an error set
```

The `SystemError` is raised [here](https://github.com/python/cpython/blob/5c02a39a0b31a330e06b4d6f44835afb205dc7cc/Objects/call.c#L61-L63) because `PyIDispatch::Invoke` returned a non-`NULL` result even though an error was set, presumably the `TypeError` shown just above the traceback. Python's [docs](https://docs.python.org/3/extending/extending.html#intermezzo-errors-and-exceptions) [recommend](https://docs.python.org/3/c-api/exceptions.html#exception-handling) against returning non-`NULL` with an error set, but apparently this convention is enforced at runtime.

The `TypeError` must be raised somewhere in [here](https://github.com/mhammond/pywin32/blob/f9428a90ba6e3b97480221daf574c0388f8275a3/com/win32com/src/PyIDispatch.cpp#L290-L334) because immediately before it, the function exits if there's an error set:

https://github.com/mhammond/pywin32/blob/f9428a90ba6e3b97480221daf574c0388f8275a3/com/win32com/src/PyIDispatch.cpp#L287-L288

I don't know enough about pywin32 to help diagnose further. I imagine the fix is to find where that `TypeError` is raised [in here](https://github.com/mhammond/pywin32/blob/f9428a90ba6e3b97480221daf574c0388f8275a3/com/win32com/src/PyIDispatch.cpp#L290-L334), check `PyErr_Occurred()`, and `return NULL` if needed.

In case you need it, here's more Python version info:

```
Python 3.7.7 (tags/v3.7.7:d7c567b08f, Mar 10 2020, 10:41:24) [MSC v.1900 64 bit (AMD64)] on win32
```

(For what it's worth, -1 appears in the A1 cell in Excel after the exception.)

**Comment by mhammond** [comment]
Thanks the the report. I suspect the problem is https://github.com/mhammond/pywin32/blob/30312fe7653991ac73f35e49a5de260de3632738/com/win32com/src/oleargs.cpp#L300 - the uuid object probably as a `tp_as_number` slot, because UUID objects have an __int__. You said you were able to test against master, which implies you got things building, so if you are keen, you could add a `PyErr_Occurred()` check after that call and return FALSE.

I suspect I could probably also get the test suite to fail, but I'm out of time for now - I'll get back to this next week or so.
