### ISSUE TITLE
SyntaxError: invalid syntax   /  IndentationError: unexpected indent

### ISSUE THREAD

**Issue by DomingosCostateste** [mhammond/pywin32#1553]
I am having this bug which im not understand why is that.   

Python version:  Python 3.8 (32-Bit) 
Extension: pywin32-228.win32-py3.8.exe

>>> import win32com.client as win32
>>> import os
>>>
>>> myDir = r'C:\Users\Utilizador\Desktop\Empresa\ABB\Power grid\Rodrigo\teste'
>>> XL = win32.Dispatch('Excel.Application')
>>> XL.Visible = 0
>>>
>>> XLbook = XL.Workbooks.Open(os.path.join(myDir,'Rodrigo_Spreadsheet.xlsx'))
>>> XLsheet = XLbook.Worksheets(1)
>>> XLrow = 2
>>> for myFile in os.listdir(myDir):
...  filepath = os.path.join(myDir,myFile)
...  filename = os.path.splitext(myFile)[0]
...  ext = os.path.splitext(myFile)[1]
...
>>> if ext == '.docx'
  File "<stdin>", line 1
    if ext == '.docx'
                    ^
SyntaxError: invalid syntax
>>>  word = win32.Dispatch('Word.Application')
  File "<stdin>", line 1
    word = win32.Dispatch('Word.Application')
    ^
IndentationError: unexpected indent
>>>  word.Visible = 0
  File "<stdin>", line 1
    word.Visible = 0
    ^
IndentationError: unexpected indent
>>> pywin32-228.win32-py3.8.exe
  File "<stdin>", line 1
    pywin32-228.win32-py3.8.exe
                ^
SyntaxError: invalid syntax

**Comment by mhammond** [comment]
I can't tell exactly what from what you pasted, but you have an indentation error in your code. The error is coming from Python, not from pywin32. You can find some good beginners resources for Python at https://www.python.org/about/help/
