### ISSUE TITLE
[Feature Request] Option to terminate Service and trigger recovery actions

### ISSUE THREAD

**Issue by LincolnPuzey** [mhammond/pywin32#1563]
I am using the `win32serviceutil.ServiceFramework` class to write a Windows Service.

I have a use-case where I would like my service to terminate in such a way that the recovery actions (e.g. restart service) are triggered.

By default these recovery actions are triggered when the service terminates without reporting a status of `SERVICE_STOPPED`.

I have tried overriding `svcRun` and raising an exception or calling `sys.exit()`, eg

    def SvcRun(self):
        self.ReportServiceStatus(win32service.SERVICE_RUNNING)

        # ideally this would cause the service process to end without any further calls to SetServiceStatus(),
        # so the recovery actions are triggered.
        raise Exception()

but pywin32 sets the service status to `SERVICE_STOPPED` in its cleanup actions after calling `SvcRun`.
https://github.com/mhammond/pywin32/blob/master/win32/src/PythonService.cpp#L907

Ideally there would be some way for `SvcRun` to flag that this cleanup should not be done.

My current workaround is to call `os.kill(os.getpid(), signal.SIGABRT)`, which avoids the cleanup. But I would like to avoid such a nuclear option.

**Comment by mhammond** [comment]
It's probably reasonable that we only report SERVICE_STOPPED if there's no exception raised from running the entry-point.

**Comment by LincolnPuzey** [comment]
For a better workaround, is there anything I can do to effect the `sshStatusHandle` value so that the first `if` [here
](https://github.com/mhammond/pywin32/blob/master/win32/src/PythonService.cpp#L906)

    if (pe && pe->sshStatusHandle) {  // Wont be true if debugging.
        if (!SetServiceStatus(pe->sshStatusHandle, &stoppedStatus))
            ReportAPIError(PYS_E_API_CANT_SET_STOPPED);
    }

is False and the status isn't set?

**Comment by mhammond** [comment]
Nope - but your workaround sounds fine and reasonable.

**Comment by LincolnPuzey** [comment]
Ok yeah I'm getting my head around the c++. I though maybe `sshStatusHandle` might be something on my service class.

**Comment by LincolnPuzey** [comment]
Your suggested fix sounds good to me.

**Comment by LincolnPuzey** [comment]
For the record my workaround now is to call `os._exit(0)` when I want the service to terminate.

**Comment by LincolnPuzey** [comment]
feature added in #1566

**Comment by LincolnPuzey** [comment]
To trigger recovery actions: 
1. Enable the "Enable actions for stops with errors" checkbox for your service.
2. Have `SvcRun()` raise an Exception

**Comment by ddurham2** [comment]
@LincolnPuzey, this seems like a dumb question, but did this really end up working for you?  I'm running v304 (recent release) and I'm raising an Exception from the end of SvcDoRun() but the service manager is not restarting my service.  If I change that to raise to os._exit(1) it does restart it (i.e. the service is configured properly to restart).

**Comment by LincolnPuzey** [comment]
@ddurham2 its been a while but yes I think it did work me for. Do you definitely have the "Enable actions for stops with errors" checkbox enabled for your service and a restart recovery action?

Note I was using pyinstaller to bundle my program into an `.exe` not sure if that makes a difference compared to what you're doing

**Comment by osomdev** [comment]
I can confirm that there is some problem with the exception handling (I'm working with v304) - probably it should be reported as new bug but for now I can leave my observation:

- if you throw exception (`raise Exception('please restart me')`) the service will NOT be restarted
- if you use `os._exit(1)` the service is restarted
- if you first do the `ReportServiceStatus` with the values like the PythonService send and then call `os._exit(1)` then the service will NOT be restarted - which is very interesting

I'm not yet sure if there is proper status that would work but at first glance it looks like the one stored in `stoppedErrorStatus` does not have expected effect https://github.com/mhammond/pywin32/blame/5c0b62bd4590440e0b59df5ac90beb5b56e4d306/win32/src/PythonService.cpp#L147

I'm running this using python3.9 and windows10.
