### ISSUE TITLE
availability to register x64 COM servers

### ISSUE THREAD

**Issue by slovj5** [mhammond/pywin32#1565]
Could you please add functionality to register x64 COM classes? Now it's working good in my 32-bit application, but in 64-bit com object creation method returns -2147221164(0x80040154): Class not registered

**Comment by mhammond** [comment]
You certainly can register x64 COM objects on x64 Windows. It's impossible to do so on 32bit windows

**Comment by slovj5** [comment]
i have created test COM-server, and it works only 32-bit.
 
`import win32com
import pythoncom

class XLReader:
    _public_methods_ = [ 'Test' ]
    _reg_progid_ = "PythonComTest2"
    _reg_desc_ = "PythonComTest - test 2"
    _reg_verprogid_ = "PythonComTest2.1"
    _reg_clsid_ = "{8EF23F1A-9088-4746-AA03-7029953D75FE}"

    def Test(self, filename: str = '') -> str:
        return str(filename) + '1 test string concat'

if __name__ == '__main__':
    import win32com.server.register
    win32com.server.register.UseCommandLine(XLReader)
`

I'm working with business logic platform, which has poor capabilities. So it's looking good to use python with various libraries to piece it out. The most efficient way to intergrate it is COM. My business logic platform has a 64-bit server side and a thick client, which is 32-bit. I have many COM dll already working written in C and C#, on both server and client side. But in fact C and C# is too sophisticated, so i'm looking for simplicity.
My question is, why this example does not working on server-side(x64)? it returns -2147221164(0x80040154): Class not registered?
why it could not create objects under x64? and works fine in x86-application?

**Comment by slovj5** [comment]
my python environment is
Python 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 23:03:10) [MSC v.1916 64 bit (AMD64)] on win32

**Comment by mhammond** [comment]
If you want to consume inproc objects from a 32bit process, you should use a 32bit Python.

**Comment by slovj5** [comment]
the point is in that i'm using x64 python and has no ability to use inproc objects in x64 process
and what's wondering, it works with 32-bit application

**Comment by mhammond** [comment]
I'm not sure what you are seeing, but x64 python definitely registers 64bit COM objects. If you look in the registry you will find them where you expect and not under Wow6432Node, which is where they'll appear if you use a 32bit Python to register objects on a 64bit Windows.

**Comment by slovj5** [comment]
i'm seeing that it register under wow6432Node
could it be a bug in pywin32?
i can execute commands you tell me to look out the environment, and post the output here

**Comment by slovj5** [comment]
my head is breaking because i expected that since i have 64bit python it will be registering 64-bit com objects

**Comment by mhammond** [comment]
It works for me. In regedit there's no `HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Python.Interpreter`.

Then:
```
C:\Users\skip\AppData\Local\Programs\Python\Python37>python -c "import sys;print(sys.version)
3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)]

C:\Users\skip\AppData\Local\Programs\Python\Python37>python lib\site-packages\win32com\servers\interp.py
Registering COM server...
Registered: Python.Interpreter
```

`HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Python.Interpreter` appears. Then
```
C:\Users\skip\AppData\Local\Programs\Python\Python37>python lib\site-packages\win32com\servers\interp.py --unregister
Registering COM server...
Unregistered: Python.Interpreter
```

It revanishes. 

I'm fairly sure many people would have noticed this if it was an actual bug. Are you sure you are using the python executable you think you are?

**Comment by slovj5** [comment]
Yes, i do

```
(.venv) PS Y:\1C\ABC-Test\Python\Dev\test_com> python
Python 3.8.5 (tags/v3.8.5:580fbb0, Jul 20 2020, 15:57:54) [MSC v.1924 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> exit
Use exit() or Ctrl-Z plus Return to exit
>>> exit()
(.venv) PS Y:\1C\ABC-Test\Python\Dev\test_com> python .\test_com.py
Registering COM server...
Registered: PythonComTest2
```

**Comment by slovj5** [comment]
The same thing with Python.Interpreter
How do I know if 32- or 64- version of pywin32 is installed?

**Comment by mhammond** [comment]
They can be both installed. 64bit python can only import 64bit pywin32 and vice-versa - you can't load 32bit code into a 64bit process and vice-versa. This is also why 64bit in-proc COM objects can only be used by 64bit host apps - in-proc means the DLL is loaded into the process and this literally can not be done between 32bit and 64bit processes - the bittedness must match.

Have you tried just from Python? ie, after registering the 64bit version, only Python's 64bit version will work with it

```
C:\Users\skip\AppData\Local\Programs\Python\Python37>python -c "import sys;print(sys.version)"
3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)]

C:\Users\skip\AppData\Local\Programs\Python\Python37>python -c "import win32com.client;win32com.client.Dispatch('Python.Interpreter')"
Traceback (most recent call last):
  File "C:\Users\skip\AppData\Local\Programs\Python\Python37\lib\site-packages\win32com\client\dynamic.py", line 89, in _GetGoodDispatch
    IDispatch = pythoncom.connect(IDispatch)
pywintypes.com_error: (-2147221005, 'Invalid class string', None, None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\skip\AppData\Local\Programs\Python\Python37\lib\site-packages\win32com\client\__init__.py", line 95, in Dispatch
    dispatch, userName = dynamic._GetGoodDispatchAndUserName(dispatch,userName,clsctx)
  File "C:\Users\skip\AppData\Local\Programs\Python\Python37\lib\site-packages\win32com\client\dynamic.py", line 114, in _GetGoodDispatchAndUserName
    return (_GetGoodDispatch(IDispatch, clsctx), userName)
  File "C:\Users\skip\AppData\Local\Programs\Python\Python37\lib\site-packages\win32com\client\dynamic.py", line 91, in _GetGoodDispatch
    IDispatch = pythoncom.CoCreateInstance(IDispatch, None, clsctx, pythoncom.IID_IDispatch)
pywintypes.com_error: (-2147221005, 'Invalid class string', None, None)

C:\Users\skip\AppData\Local\Programs\Python\Python37>python lib\site-packages\win32com\servers\interp.py
Registering COM server...
Requesting elevation and retrying...
Registering COM server...
Registered: Python.Interpreter

C:\Users\skip\AppData\Local\Programs\Python\Python37>python -c "import win32com.client;win32com.client.Dispatch('Python.Interpreter')"
```

Note you obviously can have both the 32 and 64 bit versions registered which is why they have different registry hives. If a 64bit process could load a 32bit inproc object (or vice-versa) they would share the same registry hive.

**Comment by slovj5** [comment]
It successed in 64-bit python

```
import win32com.client
o = win32com.client.Dispatch("PythonComTest2")

```

Since it work in 64-bit python, and 32-bit business application, it example above register both 32-bit and 64-bit
i suppose that COM creation in my business application sucks, and do not create 64 bit, if 32-bit is registered.

How can i register PythonComTest2 from my example 64-bit only?

**Comment by mhammond** [comment]
> Since it work in 64-bit python, and 32-bit business application, it example above register both 32-bit and 64-bit

I'm sorry, but you are confused about something - that most certainly does not register for both 32-bit and 64-bit. As I mentioned, it's literally impossible for the same inproc object to be used in both contexts. I suspect your business application is 64 bit.

> How can i register PythonComTest2 from my example 64-bit only?

I am absolutely certain that the commands above registered only for 64-bits. To register the 32bit version you'd need to execute the same commands from a 32bit Python.

**Comment by slovj5** [comment]
I'm sorry, my bad
The only thing is needed is to restart my server-side 64-bit application

Sorry for wasting your time and thank you!

**Comment by slovj5** [comment]
> I'm sorry, but you are confused about something - that most certainly does not register for both 32-bit and 64-bit. As I mentioned, it's literally impossible for the same inproc object to be used in both contexts. I suspect your business application is 64 bit.

No, it is absolutely so that after
```
(.venv) PS Y:\1C\ABC-Test\Python\Dev\test_com> python .\test_com.py
Registering COM server...
Registered: PythonComTest2
```
PythonComTest2 is available in 32-bit side(thick client) and server(64-bit)
I'm sure, because i've installed python environment only once, and have 64-bit python installed
