### ISSUE TITLE
ReadProcessMemory error (0xC0000005)

### ISSUE THREAD

**Issue by NULL-777** [mhammond/pywin32#1570]
I try to use ReadProcessMemory function to get a value.
But I got error code with 0xC0000005.
Could mhammond write an example to show how to use him?

My code:
threadID, pID = win32process.GetWindowThreadProcessId(hwndWindow)
hwndProcess = win32api.OpenProcess(win32con.PROCESS_ALL_ACCESS, 0, pID)
print(win32process.ReadProcessMemory(hwndProcess, 0x26B30850AEC, 4))

**Comment by mhammond** [comment]
Your process doesn't have rights to read that address - it's just an "access violation". Please see https://github.com/mhammond/pywin32#support for how to get support.
