### ISSUE TITLE
Unable to Collect Version 228 from pip

### ISSUE THREAD

**Issue by StephenNorCalControls** [mhammond/pywin32#1573]
Hello, I'm trying to install pywin32 for a repo that I cloned. 

The requirements file defines the following:
`pywin32~=228`

Pip reports an error when trying to collect the requirement:
`ERROR: Invalid requirement: 'pywin32~=228'`

Running the same from the command line also fails with the same error. 

Running `pip install pywin32` works and downloads version 228.

My Python version is 3.7.6.
My architecture is AMD64.
My pip version is 20.2.2.

I tested this on multiple systems, it seems like it might be a deployment issue, but it may just be me doing something wrong.

**Comment by JBonesMalone** [comment]
I am having the same issue. It looks like PyPi is not listing any versions of the package and pip is throwing a fit about it.

**Comment by joostjansenn** [comment]
Anybody already found a workaround?

**Comment by vernondcole** [comment]
From the comments in the PIP documentation for the "~=" operator, they are "assuming the package author is using semantic versioning." 
The pywin32 project got started before semantic versioning was really a thing, so it uses a simple increment of the version number.
So the work-around is very simple: do not use "~=", simply use ">=" to get the intended result.

**Comment by vernondcole** [comment]
Note the use of ">=" below...
`>py -m pip install -r requirements.txt
Collecting pywin32>=228
  Downloading pywin32-228-cp39-cp39-win_amd64.whl (9.1 MB)
     |████████████████████████████████| 9.1 MB 1.6 MB/s
Installing collected packages: pywin32
Successfully installed pywin32-228
`

**Comment by StephenNorCalControls** [comment]
This works!
