### ISSUE TITLE
SetProps failed with -2147221005 while reading a PST file properties

### ISSUE THREAD

**Issue by sameerkumargarg** [mhammond/pywin32#1587]
Note that issues in this repository are only for bugs or feature requests in the pywin32.

**If you need support or help using this package, please follow [these instructions](https://github.com/mhammond/pywin32/blob/master/README.md#support)** - support or help requests will be closed without comment.

For all bugs, please provide the following information.

* Expected behavior and actual behavior.

**Expected:** MAPI setprop() should execute without any error.
**Actual:** MAPI setprop() throw's an exception SetProps failed with (-2147221005, 'Invalid class string', None, None)

* Steps to reproduce the problem.
- We are trying to restore a outlook PST file. Now, while trying to set properties using SetProps, we are thrown an exception "(-2147221005, 'Invalid class string', None, None)"

* Version of Python and pywin32
- python: 2.7.18
- pywin32: b223

PFA the effected PST and property file of the effected PST:
[PST and property file.zip](https://github.com/mhammond/pywin32/files/5332327/PST.and.property.file.zip)

**Comment by mhammond** [comment]
This isn't going to be a bug in pywin32 - it's MAPI/COM throwing an exception. I see you left the instructions for how to get support in the issue description - please follow them!
