### ISSUE TITLE
Python 3.9 sorts extension sources causing PythonServiceMessages.h not to be generated

### ISSUE THREAD

**Issue by chrisburr** [mhammond/pywin32#1590]
Apologies that this bug report might be a little hazy, I'm very unfamiliar with Windows and have no way of trying things locally. This issue comes as a result of trying to update conda-forge for Python 3.9: https://github.com/conda-forge/pywin32-feedstock/pull/29

It appears that in Python 3.9 it's impossible to build from source with the error ([full log](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=221703&view=logs&j=00f5923e-fdef-5026-5091-0d5a0b3d5a2c&t=3cc4a9ed-60e1-5810-6eb3-5f9cd4a26dba&l=798)):

```
C:\Program Files (x86)\Windows Kits\8.1\include\shared\sdkddkver.h(200): note: see previous definition of '_WIN32_WINNT'
   Creating library build\temp.win-amd64-3.9\Release\win32/src\_winxptheme.lib and object build\temp.win-amd64-3.9\Release\win32/src\_winxptheme.exp
LINK : warning LNK4281: undesirable base address 0x1E3E0000 for x64 image; set base address above 4GB for best ASLR optimization
PythonService.cpp
win32/src/PythonService.cpp(49): fatal error C1083: Cannot open include file: 'PythonServiceMessages.h': No such file or directory
```

This appears to be from https://github.com/python/cpython/commit/0d30ae1a03102de07758650af9243fd31211325a where the sources are now sorted alphabetically, causing `PythonServiceMessages.mc` to be rearranged to after `PythonService.cpp`. I've tested this by [hackily reverting that commit](https://github.com/conda-forge/pywin32-feedstock/pull/29/commits/85de9d1b9ca638200973856529d4ccb9b912e8ea#diff-e178b687b10a71a3348107ae3154e44c) which appears to work ([full log](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=221844&view=logs&j=00f5923e-fdef-5026-5091-0d5a0b3d5a2c&t=3cc4a9ed-60e1-5810-6eb3-5f9cd4a26dba)). Alternatively renaming the `.mc` files also avoids the issue.

I suspect this needs to be reported as a cpython bug. If you agree, I can take care of moving this over to there.

**Comment by mhammond** [comment]
Thanks for the report - and yeah, this is a cpython bug. Their msvccompiler support has builtin support for the message compiler and you are seeing that the .h file generated by that compiler isn't available when building the c++ code. As a result, pywin32 needs to carefully specify the order (which you could argue is already a bug in msvcompiler) - but that commit you references means that the work-around no longer exists.  I think that's a fairly heavy handed approach they've taken - I suspect pywin32 is not going to be the only project for which the order of the files is important for esoteric reasons. Regardless, I think answer is probably just to [duplicate this loop](https://github.com/python/cpython/blob/13ff396c019d548ba181cf22c6f39309a300723c/Lib/distutils/msvccompiler.py#L360) with the first pass handling only .rc and .mc, and the second pass handling the rest. (Also, I'm not 100% sure that is the correct file - it might be `_msvccompiler.py`, or maybe both?)

**Comment by chrisburr** [comment]
Thanks for the quick response, I've reported it as [bpo-42009](https://bugs.python.org/issue42009).

In case it's useful to anyone else: [This diff](https://github.com/conda-forge/pywin32-feedstock/blob/f34c6f62084032d03f2dd83448e43c51aad878c8/recipe/ensure-PythonService-mc-before-cpp.diff) seems to be enough for conda-forge so the Python 3.9 migration can continue without needing to hack `distutils` itself.
