### ISSUE TITLE
can't create C:\program files\windowsapps\pythonsoftwarefoundation......

### ISSUE THREAD

**Issue by bbrendon** [mhammond/pywin32#1594]
For all bugs, please provide the following information.

* Expected behavior and actual behavior.
Can't install.

* Steps to reproduce the problem.
Install Win10
Install python3.7
run installer for amd64

![image](https://user-images.githubusercontent.com/6364477/96071013-2d9a5f00-0e56-11eb-85b9-40fac1048f5d.png)

I tried navigating to that folder but that results in the following even when elevating...
![image](https://user-images.githubusercontent.com/6364477/96071107-4f93e180-0e56-11eb-956b-41828460a0b6.png)

**Comment by mhammond** [comment]
I don't think this is a pywin32 bug - you probably need to work out how to get access as admin so you can give your user account access.
