### ISSUE TITLE
Why ReadProcessMemory error (0xC0000005)

### ISSUE THREAD

**Issue by aleaforny** [mhammond/pywin32#1599]
Please note I'm referring to this issue: https://github.com/mhammond/pywin32/issues/1570

I'm getting 0xC0000005 while attempting to use `ReadProcessMemory`, nevertheless it's not happening while using the library with `ctypes `(proving that it's not an access violation issue).

**FYI, I'm attempting to read an integer value** (from process with PID 18896)

The following codes produces 0xC0000005:
```
process = win32api.OpenProcess(win32con.PROCESS_ALL_ACCESS, False, 18896)
print(win32process.ReadProcessMemory(process, 0x20c6a34aa30, sys.getsizeof(wintypes.INT())))
```

When the following codes works as expected:
```
process = win32api.OpenProcess(win32con.PROCESS_ALL_ACCESS, False, 18896)

ReadProcessMemory = ctypes.WinDLL('kernel32', use_last_error=True).ReadProcessMemory
ReadProcessMemory.argtypes = [wintypes.HANDLE, wintypes.LPCVOID, wintypes.LPVOID, ctypes.c_size_t, ctypes.POINTER(ctypes.c_size_t)]
ReadProcessMemory.restype = wintypes.BOOL

int_buffer = 0

if ReadProcessMemory(process.handle, 0x20c6a34aa30, id(int_buffer), sys.getsizeof(wintypes.INT()), None):
    print("int_buffer= {}".format(int_buffer))
```

Any idea?

Thanks

**Comment by mhammond** [comment]
That's odd - if you can come up with a way for me to repro it I'm happy to see what I can find.

**Comment by aleaforny** [comment]
Thanks @mhammond 

Here the program I run where I attempt to get `int_content`:
https://pastebin.com/Q6wic9pi

Here the code which is working (`pywin32` + `ctypes`):
(https://pastebin.com/Xgtf0yk2)
  ![image text](https://i.imgur.com/hV35V0e.png)

Here the code resulting in 0xC0000005 (`pywin32` only):
https://pastebin.com/HukyEYXt
  ![image text](https://i.imgur.com/OeqUS28.png)

FYI, I'm running all the programs with the same privileges, under Windows 10 64bits (winver 1909), UAC enabled. 

Hope this can help!

**Comment by mhammond** [comment]
Thanks - silly mistake in win32process.i - will be fixed in the next release.

**Comment by aleaforny** [comment]
Awesome, thanks @mhammond !
