### ISSUE TITLE
feature request: win32clipboard support for copying image to clipboard

### ISSUE THREAD

**Issue by Vrucoder** [mhammond/pywin32#1627]
Hi, I'm new to GitHub. I want python to get the existing clipboard content and I found that pywin32 has a way for it. Specifically, I want python to be able to get the image out of the clipboard and I tried all the formats at [win32clipboard](http://timgolden.me.uk/pywin32-docs/win32clipboard__GetClipboardData_meth.html), but couldn't get the desired result. Here is what was tried: (_took a snip which is automatically copied to clipboard before trying this_)

    >>> import win32api
	>>> import win32clipboard
	>>> a = win32clipboard.GetClipboardData()
	Traceback (most recent call last):
	  File "<stdin>", line 1, in <module>
	TypeError: Specified clipboard format is not available
It's a humble request to consider adding the functionality in terms of some of these image (png, jpg/jpeg) formats available at [Microsoft](https://docs.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/platform-apis/aa359736%28v=vs.85%29).

> Written with [StackEdit](https://stackedit.io/).

**Comment by mhammond** [comment]
A plain `win32clipboard.GetClipboardData()` tries to get it as text, which isn't going to work if there's an image. Formats without builtin support use the binary data, so you should be able to get/set any format. The example above isn't demonstrating any problem - please follow the instructions at https://github.com/mhammond/pywin32#support to get support.
