### ISSUE TITLE
register Nuitka compiled COM server

### ISSUE THREAD

**Issue by FuPeiJiang** [mhammond/pywin32#1639]
I compiled a COM server using : `python -m nuitka --mingw64 com_server.py`

I register using `win32com.server.register.UseCommandLine()`
but I get many this error message
```
    "pythoncom is frozen, but sys.frozen is not set - don't know the context!"
AttributeError: module 'sys' has no attribute 'frozen'
```
this is line 198 in register.py
### Detecting Nuitka at run time
It doesn't set sys.frozen unlike other tools. For Nuitka, we have the module attribute __compiled__ to test if a specific module was compiled.

for me, `print(__compiled__)` gives
`__nuitka_version__(major=0, minor=6, micro=10, releaselevel='release')`
___
can Nuitka be supported ? 
by detecting `__compiled__`  instead of `sys.frozen` ?

is there currently a workaround ?

**Comment by mhammond** [comment]
> can Nuitka be supported ?
> by detecting `__compiled__` instead of `sys.frozen` ?

I don't have any objection to that, but it's not clear to me that would actually work (ie, it might get you past that problem and on to the next fundamental problem). Is there a Nuitka issue for this?

**Comment by Avasam** [comment]
Possibly relevant Nuitka issue: https://github.com/Nuitka/Nuitka/issues/1942

**Comment by kayhayen** [comment]
@mhammond this is the Nuitka author, pywin32 is considered largely supported. I didn't check the specific feature mentioned in the linked issue for a long time. With `__compiled__`  presence you can see if the code is compiled by Nuitka. An alternative would be for Nuitka to patch your code such that the check passes. Get in touch with me here or in that issue, or even via email or my Discord, if you want to work together to solve this. Nuitka is very compatible, and we did stuff to load your DLLs, and we have means to workaround strange things.

We have long moved beyond special code (using yaml), but for reference this is our code for pywin32 right now

```
        # TODO: This should be its own plugin.
        elif (
            full_name
            in (
                "pythoncom",
                "win32api",
                "win32clipboard",
                "win32console",
                "win32cred",
                "win32crypt",
                "win32event",
                "win32evtlog",
                "win32file",
                "win32gui",
                "win32help",
                "win32inet",
                "win32job",
                "win32lz",
                "win32net",
                "win32pdh",
                "win32pipe",
                "win32print",
                "win32process",
                "win32profile",
                "win32ras",
                "win32security",
                "win32service",
                "win32trace",
                "win32transaction",
                "win32ts",
                "win32wnet",
                "win32ui",
            )
            and isWin32Windows()
        ):
            pywin_dir = getPyWin32Dir()

            if pywin_dir is not None:
                for dll_name in "pythoncom", "pywintypes":
                    pythoncom_filename = "%s%d%d.dll" % (
                        dll_name,
                        sys.version_info[0],
                        sys.version_info[1],
                    )
                    pythoncom_dll_path = os.path.join(pywin_dir, pythoncom_filename)

                    if os.path.exists(pythoncom_dll_path):
                        yield self.makeDllEntryPoint(
                            source_path=pythoncom_dll_path,
                            dest_path=pythoncom_filename,
                            module_name=full_name,
                            package_name=None,
                            reason="needed by '%s'" % full_name.asString(),
                        )
```

If it would help, I could move it to Nuitka package configuration, such that it becomes easier to change for you as well.

**Comment by mhammond** [comment]
I've never used Nuitka and I'm not sure whether the fact this was reported just once over 3 years ago means the issue no longer exists, or there's really not much demand for this specific configuration, but either way, I've no real incentive to dig much further into this but would be happy to look at any PRs.

**Comment by kayhayen** [comment]
I am OK with your closing the issue then, and if there is anything needed from you, we can get back to it. I didn't care about the specific issue at the time, I will check it there myself.

**Comment by kayhayen** [comment]
Actually it's going to work with the next pre-release of Nuitka, relatively trivial to workaround things there.
