### ISSUE TITLE
Switch away from deprecated buffer protocol.

### ISSUE THREAD

**Issue by domdfcoding** [mhammond/pywin32#1644]
PyIID.cpp makes use of `PyObject_CheckReadBuffer` and `PyObject_AsReadBuffer`, which are part of the deprecated buffer protocol and were removed from Python 3.10 in https://github.com/python/cpython/pull/21117. 

https://github.com/mhammond/pywin32/blob/09c57bfa017687907a98d6f462e52bfe55848308/win32/src/PyIID.cpp#L25-L28

As such it is not possible to build and test pywin32 on Python 3.10. The suggested replacement for `PyObject_CheckReadBuffer` is [PyObject_GetBuffer](https://docs.python.org/3/c-api/buffer.html#c.PyObject_GetBuffer).

**Comment by mhammond** [comment]
Thanks for the report - I'm tracking this in #1588
