### ISSUE TITLE
Segmentation fault with  win32api.MapVirtualKey

### ISSUE THREAD

**Issue by Nereg** [mhammond/pywin32#1645]
Segmentation fault with  `win32api.MapVirtualKey`
* Expected behavior and actual behavior.
* Expected : call to windows [function](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-mapvirtualkeyexw)
* Actual : Segmentation fault
* Steps to reproduce the problem.
```py
win32api.MapVirtualKey(71,2,-257424350)
```
* Result : 
```
$ py
Python 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 19:29:22) [MSC v.1916 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import win32api
>>> win32api.MapVirtualKey(71,2,-257424350)
Segmentation fault
```
* Version of Python and pywin32
* Python 3.7.4 win32 and pytwin32 version 300

**Comment by mhammond** [comment]
Sorry for the delay here, but thanks for the report and it will be fixed in the next build.
