### ISSUE TITLE
What license does the source code using PyWin32 apply?

### ISSUE THREAD

**Issue by MKdays** [mhammond/pywin32#1646]
First of all, I'm sorry that I didn't use the issue template because it's out of the case.
I found 6 license documents in the repo.

> https://github.com/mhammond/pywin32/blob/master/com/License.txt
> https://github.com/mhammond/pywin32/blob/master/win32/License.txt
> https://github.com/mhammond/pywin32/blob/master/adodbapi/license.txt
> https://github.com/mhammond/pywin32/blob/master/Pythonwin/License.txt
> https://github.com/mhammond/pywin32/blob/master/Pythonwin/Scintilla/License.txt
> https://github.com/mhammond/pywin32/blob/master/com/win32comext/mapi/src/mapi_stub_library/LICENSE

But when I looked at each of them, except for one license document, I thought it was BSD or MIT.
1) If the app I deploy uses the pywin32 library, should all six copies of the license be included?
2) If so, should LGPL2.1 apply to all source codes that use the pywin32 library in accordance with the LGPL2.1 license rules?
3) Or do I simply apply PSF-2.0?

The library I used is below.
```
from win32api import GetCursorPos
import win32com.client
import win32gui
import win32con
import pythoncom
```

**Comment by mhammond** [comment]
I really need to update most of this license files, but that means I probably need to track down old contributors, which sounds like a PITA and might fail. My intent is that PSF 2.0 be used, so I'm fine with you assuming that intent.

**Comment by MKdays** [comment]
@mhammond

This is the limit of the information I can find out. The copyright holder is missing in adodbapi's case. 

pywin32
https://github.com/mhammond/pywin32
Copyright (c) 1994-2008, Mark Hammond 
PSF-2.0 License

pywin32/com
https://github.com/mhammond
Copyright (c) 1996-2008, Greg Stein and Mark Hammond

pywin32/win32
https://github.com/mhammond
Copyright (c) 1994-2008, Mark Hammond 

pywin32/adodbapi
http://sourceforge.net/projects/adodbapi
LGPLv2.1 License

pywin32/Pythonwin/
https://github.com/mhammond
Copyright (c) 1994-2008, Mark Hammond

pywin32/Pythonwin/Scintilla
Copyright 1998-2003 by Neil Hodgson
neilh@scintilla.org

pywin32/com/win32comext/mapi/src/mapi_stub_library
Copyright (c) 2018 Microsoft
MIT License

**Comment by vernondcole** [comment]
The copyright holder for adodbapi mysteriously quit making contact sometime
before I was permitted to take over maintenance of that project, which, if
memory serves, was around 2003 or 4. So the chance that he would object to
a change in the license is extremely remote. Nevertheless, I was not the
original author. As far as I am concerned, any open source license would be
acceptable. Most of the existing source code is now mine, but some few
lines of the original will probably still exist, as I have made no effort
to completely remove them, and at this point have no way of telling which
they are.
Can the license be changed? I would say "go ahead." But a lawyer might say
differently.

**Comment by mhammond** [comment]
> This is the limit of the information I can find out. The copyright holder is missing in adodbapi's case.

Anyone who contributed is a copyright holder.

**Comment by MKdays** [comment]
My concern is that the license for the adodbapi module is LGPL V2.1,
and the works using this module should be subject to LGPL V2.1 or GPL 2.0 or 3.0 in accordance with Section 3 of LGPL 2.1.
This is because the main use of GUI framework PySide2 is LGPL V3.0, which requires consideration of license compatibility.

I have summarized the table below, and **even if I use pywin32 it looks free from LGPL V2.1 if I don't use adodbapi.**

* The following table summarizes the path and license file presence according to import module.
In some cases, license files are missing from Local.


module/package | Path | License File | License Preview | License URL
-- | -- | -- | -- | --
isapi | site-packages\isapi | O | Copyright 2002-2003   by Blackdog Software Pty Ltd. | https://github.com/mhammond/pywin32/blob/master/isapi/README.txt
adodbapi | site-packages\adodbapi | O | LGPL V2.1 | https://github.com/mhammond/pywin32/blob/master/adodbapi/license.txt
pythonwin | site-packages\pythonwin | O | Copyright (c)   1994-2008, Mark Hammond | https://github.com/mhammond/pywin32/blob/master/Pythonwin/License.txt
pythonwin | site-packages\pythonwin | X | Copyright 1998-2003   by Neil Hodgson <neilh@scintilla.org> | https://github.com/mhammond/pywin32/blob/master/Pythonwin/Scintilla/License.txt
win32comext | site-packages\win32comext | X | MIT License Copyright   (c) 2018 Microsoft | https://github.com/mhammond/pywin32/blob/master/com/win32comext/mapi/src/mapi_stub_library/LICENSE
win32com | site-packages\win32com | O | Copyright (c)   1996-2008, Greg Stein and Mark Hammond. | https://github.com/mhammond/pywin32/blob/master/com/License.txt
win32 | site-packages\win32 | O | Copyright (c)   1994-2008, Mark Hammond | https://github.com/mhammond/pywin32/blob/master/win32/License.txt
win32api | site-packages\win32\win32api.pyd | O | ↑ | ↑
win32gui | site-packages\win32\win32gui.pyd | O | ↑ | ↑
win32con | site-packages\win32\lib\win32con.py | O | ↑ | ↑
pythoncom | site-packages\pywin32_system32\pythoncom39.dll |   |   |  
pywintypes | site-packages\pywin32_system32\pywintypes39.dll |   |   |
