### ISSUE TITLE
pywin32 provide some features to run exsting window task scheduler?

### ISSUE THREAD

**Issue by technqvi** [mhammond/pywin32#1649]
I am interested in  pywin32 . I am going to use it to run window task scheduler through Django  web application ?

**_Does pywin32 provide some features or method to run window task scheduler?_**  

I would like you to guide sample code to do as the following requirement.
1. My job has been created on Window task scheduler already as the figure below
My job is responsible for executing python file.

![image](https://user-images.githubusercontent.com/38780060/104473127-3c2c1a00-55ef-11eb-8d12-a2dfdf68be62.png)

2.  I would like you to guide code  to run job of  window task scheduler  in   view.py on  Django  web application 
I will code in def create_report(request)
![image](https://user-images.githubusercontent.com/38780060/104473955-1b17f900-55f0-11eb-94c3-ea1a2600a6cb.png)

please kindly guide me.
Pongthorn

**Comment by mhammond** [comment]
https://github.com/mhammond/pywin32#support
