### ISSUE TITLE
Don't set linker base addresses in setup.py

### ISSUE THREAD

**Issue by wkschwartz** [mhammond/pywin32#1652]
Currently (`master` at fa8554d), `setup.py` uses `link.exe`'s [`/BASE`](https://docs.microsoft.com/en-us/cpp/build/reference/base-base-address) option to set the base addresses of symbols in the various `.pyd` dynamic libraries. This is apparently to coordinate with Python's `PC/dllbase_nt.txt`: https://github.com/mhammond/pywin32/blob/fa8554d5f41dbff2e9281b5f24aab79f9c8729b5/setup.py#L2257-L2260
While `PC/dllbase_nt.txt` was originally created as a performance optimization (python/cpython@cbc66767c5fe08125d883a1e2432d80f8083649d), it and the setting of Python's own extension modules' base addresses were removed in Python 3.7.0b1 (python/cpython@d135f20ae8887acc7716561bc8f4c7eb6d58d24c).

The main reason in my mind to get rid of it is to reduce the complexity of the build process. However, I wonder if getting rid of it will actually solve #1462 as well. (Put differently, I'm making this a new ticket rather than commenting at #1462 because my use case would benefit from a simpler build process, whereas I do not use ARM64 presently and have nothing further to offer that discussion.)

**Comment by mhammond** [comment]
I don't have any objection to this if there's no cost. I can't find any discussion in the linked bpo issue about why this was removed - can you find any? I assume it's because (IIUC) aslr makes it redundant?

**Comment by wkschwartz** [comment]
> I assume it's because (IIUC) aslr makes it redundant?

I think manually specifying [`/BASE`] overrides the on-by-default [`/DYNAMICBASE`]. However, ASLR appears to have been added to Python in 3.4.0b1 (python/cpython@f3bf35eee4d48e214d9684d788934262687dbea3). I don't know how `PCbuild/pyproject.props`  or any of the `PCBuild/*.vcxproj` files interact with each other or with the building of the standard python.org distributions.

For what it's worth, the docs for [`/BASE`] say
> For security reasons, Microsoft recommends you use the **[`/DYNAMICBASE`]** option instead of specifying base addresses for your executables. This generates an executable image that can be randomly rebased at load time by using the address space layout randomization (ASLR) feature of Windows. The /DYNAMICBASE option is on by default.

I don't have time to work on this right now, but writing the patch should be as easy as Ctrl-Fing around `setup.py` for "base" and hitting the delete key.

 [`/DYNAMICBASE`]: https://docs.microsoft.com/en-us/cpp/build/reference/dynamicbase-use-address-space-layout-randomization?view=msvc-160
[`/BASE`]: https://docs.microsoft.com/en-us/cpp/build/reference/base-base-address?view=msvc-160

**Comment by mhammond** [comment]
Thanks for the response - I didn't realize /DYNAMICBASE existed and I'd be fine with pywin32 using it.
