### ISSUE TITLE
[Feature Request]Transforming the screenshot data into a OpenCV image

### ISSUE THREAD

**Issue by songyuc** [mhammond/pywin32#1653]
Hi, guys,
I have been using saveBitMap.SaveBitmapFile(saveDC, "output\\"+str+".bmp"), to get the .bmp file, but I am concerned that the transition to a .bmp file would be slower if I could just transform the data into a OpenCV image all in the RAM , without any IO operations.

**Comment by mhammond** [comment]
Unless there are specific windows APIs with opencv support that we could wrap, pywin32 isn't going to grow opencv support. Don't you just need some library that does support opencv and use that in conjunction with pywin32?

**Comment by songyuc** [comment]
I need to obtain the screenshot of a certain application, and process that image using OpenCV.

**Comment by songyuc** [comment]
Hi, @mhammond , could you please add this feature?

**Comment by mhammond** [comment]
If you can tell me which windows API function you would like to see here I can consider it. Currently all I know is that you need help grabbing a screenshot and using it with a 3rd party tool, in which case you should follow https://github.com/mhammond/pywin32#support

**Comment by songyuc** [comment]
@mhammond , in fact, opencv-python is a python library, so we don't need to wrap it. And, opencv-python use numpy.array as the data type for image data, so that we can just transform the screenshot data into numpy.array.

**Comment by mhammond** [comment]
I have no idea what you asking for exactly.

**Comment by songyuc** [comment]
I tried send e-mails to "python-win32"<python-win32@python.org>, which all failed.

**Comment by mhammond** [comment]
failed how? Please be specific

**Comment by songyuc** [comment]
Oh, I am sorry that I might have a wrong understanding for the nature of pywin32, I used to think it just **realize** the function of some Windows APIs, but it **wrap** some existed Windows API, so we cannot realize some custom function like transforming some middle data into numpy.array, am I right?

**Comment by songyuc** [comment]
My mailbox reported:
> For unknown reason: host mail.python.org[188.166.95.178] said: 553 Contact your postmaster/admin for assistance. Please provide the following information in your problem report: time (Jan 21 06:22:30) and client (59.36.132.13). (in reply to end of DATA command)

**Comment by mhammond** [comment]
yes, that's correct. You can probably expect pywin32 to be able to give you the binary data from a screenshot (assuming there is a windows function that offers that), and you should mail the python-win32 list if you are having trouble getting that to work. It's then up to you (or some other library) to work out how to integrate that with numpy or opencv.

**Comment by songyuc** [comment]
I just a little confused. I have mailed to python-win32 <python-win32@python.org> and mailman <mailman@python.org>, which all failed. So which e-mail address should I mailed to?

**Comment by mhammond** [comment]
That is the correct address.

> For unknown reason: host mail.python.org[188.166.95.178] said: 553 Contact your postmaster/admin for assistance. Please provide the following information in your problem report: time (Jan 21 06:22:30) and client (59.36.132.13). (in reply to end of DATA command)

You didn't provide the information!

**Comment by songyuc** [comment]
OK, that might be the problem with my mailbox provider, and I will contact them to see how to solve it.

**Comment by songyuc** [comment]
Would you accept a PR like:
```python
saveDC.SelectObject(saveBitMap)
saveDC.BitBlt((0, 0), (width, height), mfcDC, (0, 0), win32con.SRCCOPY)
array = saveBitMap.SaveNumpyArray(saveDC)
```

**Comment by mhammond** [comment]
That implies a new dependency on numpy? I'd accept a sane PR that does, say, `saveBitMap.as_buffer()`, which you could then pull in to numpy. You mentioned `win32bitmap.SaveBitmapFile()` before - there's also `win32bitmap.GetBitmapBits()`

**Comment by songyuc** [comment]
Oh, I get it. In fact, I just need to use `win32bitmap.GetBitmapBits()`, and transform the bits data into a `numpy.array`.
