### ISSUE TITLE
fix bug: microsecond must be in 0..999999

### ISSUE THREAD

**Issue by hujiaxing** [mhammond/pywin32#1655]
Note that issues in this repository are only for bugs or feature requests in the pywin32.

**If you need support or help using this package, please follow [these instructions](https://github.com/mhammond/pywin32/blob/master/README.md#support)** - support or help requests will be closed without comment.

For all bugs, please provide the following information.

* Expected behavior and actual behavior.

* Steps to reproduce the problem.

* Version of Python and pywin32

**Comment by hujiaxing** [comment]
in PyTime.cpp

    PyObject *PyWinObject_FromDATE(DATE t)
    {
#ifdef PYWIN_HAVE_DATETIME_CAPI
        // via https://www.codeproject.com/Articles/17576/SystemTime-to-VariantTime-with-Milliseconds
        // (in particular, see the comments)
        double fraction = t - (int)t;  // extracts the fraction part
        double hours = (fraction - (int)fraction) * 24.0;
        double minutes = (hours - (int)hours) * 60.0;
        double seconds = round((minutes - (int)minutes) * 60.0, 4);
        double milliseconds = round((seconds - (int)seconds) * 1000.0, 0);
        // the following is my fix
        // if seconds has decimal part greater than 0.9995, it will be converted to 1000 milliseconds,
        // and an exception will be caused: "microsecond must be in 0..999999",
        // so set milliseconds to 999
        if ((seconds - (int)seconds) >= 0.9995) {
            milliseconds = 999.0;
        }
        // assert(milliseconds>=0.0 && milliseconds<=999.0);

        // Strip off the msec part of time
        double TimeWithoutMsecs = t - (ONETHOUSANDMILLISECONDS / 1000.0 * milliseconds);

        // Let the OS translate the variant date/time
        SYSTEMTIME st;
        if (!VariantTimeToSystemTime(TimeWithoutMsecs, &st)) {
            return PyWin_SetAPIError("VariantTimeToSystemTime");
        }
        if (milliseconds > 0.0) {
            // add the msec part to the systemtime object
            st.wMilliseconds = (WORD)milliseconds;
        }
        return PyWinObject_FromSYSTEMTIME(st);
#endif  // PYWIN_HAVE_DATETIME_CAPI

#ifndef NO_PYWINTYPES_TIME
        return new PyTime(t);
#endif
    }

Is that a properly fix?

**Comment by mhammond** [comment]
Do you have a test case for the issue being fixed?

**Comment by hujiaxing** [comment]
> Do you have a test case for the issue being fixed?

I used pywin32 to access outlook and sometimes exception thrown by pywin32.
It is critical value problem, so I just set milliseconds to 999 amd program work fine.

**Comment by hujiaxing** [comment]
@mhammond

In PyTime.cpp

 static double round(double Value, int Digits)
    {
        assert(Digits >= -4 && Digits <= 4);
        int Idx = Digits + 4;
        double v[] = {1e-4, 1e-3, 1e-2, 1e-1, 1, 10, 1e2, 1e3, 1e4};
        return floor(Value * v[Idx] + 0.5) / (v[Idx]);
    }


 double milliseconds = round((seconds - (int)seconds) * 1000.0, 0); =>

    double value = seconds - (int)seconds; // >= 0.9995
    value = value * 1000; // >= 999.5
    round(value, 0); =>

      return floor(value + 0.5) // will return 1000.0

so milliseconds will cause an exception

**Comment by mhammond** [comment]
FWIW, I spent some time trying to reproduce this with the test COM objects and failed. I'll have another go soon, but I'm reluctant to check in a speculative fix without any certainty around whether it actually fixes the problem.

**Comment by hujiaxing** [comment]
I have the same problem with the following link:
       https://stackoverflow.com/questions/62169709/python-valueerror-microsecond-must-be-in-0-999999-while-using-win32com#

**Comment by hujiaxing** [comment]
Also this issue: #1466 Some date values in Excel cause ValueError: microsecond must be in 0..999999

**Comment by hujiaxing** [comment]
@mhammond  any suggestion?

**Comment by mhammond** [comment]
> @mhammond any suggestion?

The links above are other reports of the same bug, which I don't doubt exists. However, they don't seem to get me any closer to a repro.

**Comment by hujiaxing** [comment]
My fix is not good, I know that
I think there should be another patch for this bug
This bug has been exist for a long time
@mhammond

**Comment by mhammond** [comment]
> My fix is not good,

It might be good!

> This bug has been exist for a long time

Yeah - which is why I'd rather spend a little more time trying to get a repro rather than making a speculative fix. A tweak to the c++ test server that manages to find a float that causes this problem should be possible, but I failed to find it in my first attempt.

**Comment by hujiaxing** [comment]
@mhammond  I construct a double date with milliseconds: 18712.308206013888

**Comment by bardal** [comment]
Is there a workaround? I am getting DateTimes from Outlook - ReceivedTime on a message. I don't need microseconds so would happily zero them out ahead of referencing the ReceivedTime which generates the ValueError Exception. Is that possible?

**Comment by bardal** [comment]
Alternatively, do you think this bugfix will be released in the near future?

**Comment by mhammond** [comment]
I just merged that PR, so it will be in the next release, but I can't predict when that might be.
