### ISSUE TITLE
pythonservice.exe - pywintypes38.dll missing

### ISSUE THREAD

**Issue by bwncp** [mhammond/pywin32#1656]
I'm using Python 3.8.7 on Windows 10 with pywin32 300 installed using pip.

I have following script to install [RPyC](https://rpyc.readthedocs.io/en/latest/) as service.

```python
import win32serviceutil, argparse
import rpyc.utils.server, rpyc.core, rpyc.utils.classic

class RPyCService(win32serviceutil.ServiceFramework):
    _svc_name_="RPyCService"
    _svc_display_name_="RPyCService"
    _svc_description_="""RPyC's rpyc_classis service wrapper"""
    _svc_deps_=("tcpip",)
    def SvcDoRun(self):
        l.info("Starting service")
        #launch method taken from rpyc_classic.serve_threaded()
        #the constructor binds a named logger automatically
        self.t = rpyc.utils.server.ThreadedServer(
				rpyc.core.SlaveService,
				port=rpyc.utils.classic.DEFAULT_SERVER_PORT)
        self.t.start()
    def SvcStop(self):
        l.info("Stopping service")
        self.t.close()

if __name__=='__main__':
    win32serviceutil.HandleCommandLine(RPyCService)
```

Starting it with `python test.py debug`  results in the DLL not being found.

![grafik](https://user-images.githubusercontent.com/59439342/105985289-902d0900-609b-11eb-961a-0b52f59f3a6e.png)

Copying the DLL to `C:\Programme\python38\Lib\site-packages\win32` fixes the problem.

**Comment by mhammond** [comment]
This sucks, but is documented - see https://github.com/mhammond/pywin32/blob/master/README.md#installing-via-pip

**Comment by bwncp** [comment]
> This sucks, but is documented - see https://github.com/mhammond/pywin32/blob/master/README.md#installing-via-pip

Sorry, didn't read this. Thanks for the note!
