### ISSUE TITLE
ImportError: DLL load failed while importing win32api: The specified module could not be found

### ISSUE THREAD

**Issue by stier08** [mhammond/pywin32#1658]
* Expected behavior and actual behavior.

import win32api statement in embedded python (boost::python wrapper lined against Winpython32-3.8.7.0dot, boost version 1_68, vs2019 toolset v140 , os win10)
raises an exception ImportError: DLL load failed while importing win32api: The specified module could not be found.

See os.path and sys.path ( captured in the code) below for reference

Traceback (most recent call last):
  File "%USERPROFILE%\ws\portable\pcore\plugin\pynpp\pynppinit.py", line 47, in <module>
    import win32api
ImportError: DLL load failed while importing win32api: The specified module could not be found.

SYSPATH :

%USERPROFILE%\AppData\Roaming\Python\Python38\site-packages
%USERPROFILE%\ws\portable\app\Winpython32-3.8.7.0dot\python-3.8.7
%USERPROFILE%\ws\portable\app\Winpython32-3.8.7.0dot\python-3.8.7\DLLs
%USERPROFILE%\ws\portable\app\Winpython32-3.8.7.0dot\python-3.8.7\lib
%USERPROFILE%\ws\portable\app\Winpython32-3.8.7.0dot\python-3.8.7\lib\site-packages
%USERPROFILE%\ws\portable\app\Winpython32-3.8.7.0dot\python-3.8.7\lib\site-packages\Pythonwin
%USERPROFILE%\ws\portable\app\Winpython32-3.8.7.0dot\python-3.8.7\lib\site-packages\win32
%USERPROFILE%\ws\portable\app\Winpython32-3.8.7.0dot\python-3.8.7\lib\site-packages\win32\lib
%USERPROFILE%\ws\portable\app\Winpython32-3.8.7.0dot\python-3.8.7\python38.zip
%USERPROFILE%\ws\portable\pcore\pylibs
---------------------
OSPATH :
%USERPROFILE%\AppData\Roaming\Python\Python38\site-packages
%USERPROFILE%\ws\portable\app\Winpython32-3.8.7.0dot\python-3.8.7
%USERPROFILE%\ws\portable\app\Winpython32-3.8.7.0dot\python-3.8.7\DLLs
%USERPROFILE%\ws\portable\app\Winpython32-3.8.7.0dot\python-3.8.7\Lib\site-packages
%USERPROFILE%\ws\portable\app\Winpython32-3.8.7.0dot\python-3.8.7\Scripts
%USERPROFILE%\ws\portable\app\Winpython32-3.8.7.0dot\python-3.8.7\lib
%USERPROFILE%\ws\portable\app\Winpython32-3.8.7.0dot\python-3.8.7\lib\site-packages
%USERPROFILE%\ws\portable\app\Winpython32-3.8.7.0dot\python-3.8.7\lib\site-packages\Pythonwin
%USERPROFILE%\ws\portable\app\Winpython32-3.8.7.0dot\python-3.8.7\lib\site-packages\pywin32_system32
%USERPROFILE%\ws\portable\app\Winpython32-3.8.7.0dot\python-3.8.7\lib\site-packages\win32
%USERPROFILE%\ws\portable\app\Winpython32-3.8.7.0dot\python-3.8.7\lib\site-packages\win32\lib
C:\Windows
C:\Windows\System32\OpenSSH
C:\Windows\System32\Wbem
C:\Windows\System32\WindowsPowerShell\v1.0
C:\Windows\system32
---------------------

When python is executed from commad  line import win32api works fine. See below for convenience

%USERPROFILE%\ws\portable\app\Winpython32-3.8.7.0dot\python-3.8.7;%USERPROFILE%\ws\portable\app\Winpython32-3.8.7.0dot\python-3.8.7\DLLs;%USERPROFILE%\ws\portable\app\Winpython32-3.8.7.0dot\python-3.8.7\Lib\site-packages;%USERPROFILE%\ws\portable\app\Winpython32-3.8.7.0dot\python-3.8.7\Scripts;%USERPROFILE%\ws\portable\app\Winpython32-3.8.7.0dot\python-3.8.7\lib;%USERPROFILE%\ws\portable\app\Winpython32-3.8.7.0dot\python-3.8.7\lib\site-packages;%USERPROFILE%\ws\portable\app\Winpython32-3.8.7.0dot\python-3.8.7\lib\site-packages\Pythonwin;%USERPROFILE%\ws\portable\app\Winpython32-3.8.7.0dot\python-3.8.7\lib\site-packages\pywin32_system32;%USERPROFILE%\ws\portable\app\Winpython32-3.8.7.0dot\python-3.8.7\lib\site-packages\win32;%USERPROFILE%\ws\portable\app\Winpython32-3.8.7.0dot\python-3.8.7\lib\site-packages\win32\lib;C:\Windows;C:\Windows\System32\OpenSSH;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Windows\system32
>>> print(sys.path)
['', 'C:\\Users\\serge\\ws\\portable\\pcore\\pylibs', 'C:\\Users\\serge\\ws\\portable\\app\\Winpython32-3.8.7.0dot\\python-3.8.7\\python38.zip', 'C:\\Users\\serge\\ws\\portable\\app\\Winpython32-3.8.7.0dot\\python-3.8.7\\DLLs', 'C:\\Users\\serge\\ws\\portable\\app\\Winpython32-3.8.7.0dot\\python-3.8.7\\lib', 'C:\\Users\\serge\\ws\\portable\\app\\Winpython32-3.8.7.0dot\\python-3.8.7', 'C:\\Users\\serge\\AppData\\Roaming\\Python\\Python38\\site-packages', 'C:\\Users\\serge\\ws\\portable\\app\\Winpython32-3.8.7.0dot\\python-3.8.7\\lib\\site-packages', 'C:\\Users\\serge\\ws\\portable\\app\\Winpython32-3.8.7.0dot\\python-3.8.7\\lib\\site-packages\\win32', 'C:\\Users\\serge\\ws\\portable\\app\\Winpython32-3.8.7.0dot\\python-3.8.7\\lib\\site-packages\\win32\\lib', 'C:\\Users\\serge\\ws\\portable\\app\\Winpython32-3.8.7.0dot\\python-3.8.7\\lib\\site-packages\\Pythonwin']
>>>

* Steps to reproduce the problem.
Invoke import win32api from embedded python ( boost::python boost 

* Version of Python and pywin32
Winpython32-3.8.7.0dot
pywin32 300
boost 1_68
vs2019 toolset v140

**Comment by GadgetSteve** [comment]
When I have seen this in the past it has been because I (or the user) has failed to run **as admin** _python_dir_\pywin32_postinstall.py - personally I think that the need to do this should be more clearly addressed in the documentation or in the exception.

**Comment by mhammond** [comment]
I've added some relevant notes to https://github.com/mhammond/pywin32/blob/main/README.md#the-specified-procedure-could-not-be-found--entry-point-not-found-errors

**Comment by moipum16** [comment]
I managed to copy files from "yourPython"/Lib/site-packages/pywin32_system32, pywintypes310.dll and pythoncom310.dll to the app folder with the exe /win32 and in the app folder with the exe, I also copied the pywintypes311.dll file generated by pyinstaller in the app folder with the exe /win32 to System32
