### ISSUE TITLE
Wrong constants in winnt.py and missing functions

### ISSUE THREAD

**Issue by kolokoltsov** [mhammond/pywin32#1659]
Release 300.
1) not found FindFirstFile/FindNextFile
2) wrong constants in winnt.py
winnt.py:
IO_REPARSE_TAG_MOUNT_POINT = -1610612733
IO_REPARSE_TAG_SYMBOLIC_LINK = (2)

winnt.h:
#define IO_REPARSE_TAG_MOUNT_POINT              (0xA0000003L)
#define IO_REPARSE_TAG_SYMLINK                  (0xA000000CL)

**Comment by RoccoMatano** [comment]
1.
I think pywin32 doesn't not expose FindFirstFile/FindNextFile intentionally.
Instead there are win32api.FindFiles and win32file.FindFilesW.
E.g.

```
import os
import sysconfig
import win32file

pattern = os.path.join(sysconfig.get_path('stdlib'), '*.py')
print(pattern)
for ffd in win32file.FindFilesW(pattern):
    print(ffd[8], ffd[1])
```

2.
The hexadecimal number 0xA0000003 interpreted as a 32 bit signed integer equals the decimal value of -1610612733.

IO_REPARSE_TAG_**SYMBOLIC_LINK** != IO_REPARSE_TAG_**SYMLINK**

**Comment by mhammond** [comment]
Thanks @RoccoMatano, that's exactly correct. It's a little unfortunate that alot of the generated constants use negative numbers, but they do end up working when used with pywin32, so there's nothing to do here.
