### ISSUE TITLE
Question: How to "pywin32 v228" using "Microsoft Visual C++ Compiler for Python 2.7"

### ISSUE THREAD

**Issue by makiolo** [mhammond/pywin32#1662]
Is possible compile pywin32 using "Microsoft Visual C++ Compiler for Python 2.7", instead of compile with "Microsoft SDK 8.1". I have problems mixing Miniconda2 with Python 2.7 (MSVC9 runtime VS 2008 NO SP1) + Pywin32 (MSVC9 runtime VS 2008 SP1).
Is this mix compatible, or am I doing something wrong?
If there was a solution, it would be great to know.
Greats.
Ricardo.

**Comment by jborean93** [comment]
Based on the [changelog for v228](https://github.com/mhammond/pywin32/blob/master/CHANGES.txt)

> Python 2 is no longer supported - so long, Python 2, you served us well!

If you still wish to use this EOL and unsupported Python you will have to pin your dependencies of pywin32 to a version that does work on Python 2.7.

**Comment by kxrob** [comment]
As for compiling version b228 (last one supporting Py2.7) for regular Python2.7:  It is possible to compile most of pywin32, but not the MFC/ATL-dependent libraries (win32ui.pyd, PythonWin.exe in PythonWin/* ...) with "Microsoft Visual C++ Compiler for Python 2.7", because that doesn't contain the ATLMFC libraries. Same with "Visual Studio 2008 SP1 Express". You may find a VS2008 Pro Trial Editon which carries the ATLMFC folder. 

(I am not into the conda beast and don't know what, why and how are trying to mix, but it seems it has its own pywin32 (b228) build:  "conda install -c anaconda pywin32" and after "conda install pip" you could use pip to install PyPI packages which are not available on the anaconda channel - or get the PyPI build of pywin32 ... ? )

**Comment by makiolo** [comment]
Thanks for answers, I know python 2 is dead ... but I need to solve this, and maybe is a "miniconda2 or pywin32 or python2" bug?

With Python 2.7 (old, compiled with VS2008 + windows SDK) + pywin32 COM + Excel 32 bits + Win64 = All works ok. I can since Excel use a COM registered with python. And this the "correct" trace load is:
```
'EXCEL.EXE' (Win32): 'C:\Python27\Library\bin\pythoncomloader27.dll' cargado. El módulo se compiló sin símbolos.
'EXCEL.EXE' (Win32): 'C:\Python27\Library\bin\pythoncomloader27.dll' descargado
'EXCEL.EXE' (Win32): 'C:\Python27\Library\bin\pythoncomloader27.dll' cargado. El módulo se compiló sin símbolos.
'EXCEL.EXE' (Win32): 'C:\Windows\WinSxS\x86_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.9415_none_508df7e2bcbccb90\msvcr90.dll' cargado. No se puede encontrar o abrir el archivo PDB.
'EXCEL.EXE' (Win32): 'C:\Python27\Library\bin\pythoncom27.dll' cargado. No se puede encontrar o abrir el archivo PDB.
'EXCEL.EXE' (Win32): 'C:\Python27\Library\bin\pythoncom27.dll' descargado
'EXCEL.EXE' (Win32): 'C:\Python27\Library\bin\pythoncom27.dll' cargado. No se puede encontrar o abrir el archivo PDB.
'EXCEL.EXE' (Win32): 'C:\Windows\SysWOW64\python27.dll' cargado. No se puede encontrar o abrir el archivo PDB.
'EXCEL.EXE' (Win32): 'C:\Windows\SysWOW64\python27.dll' descargado
'EXCEL.EXE' (Win32): 'C:\Python27\Library\bin\pywintypes27.dll' cargado. No se puede encontrar o abrir el archivo PDB.
'EXCEL.EXE' (Win32): 'C:\Python27\Library\bin\pywintypes27.dll' descargado
'EXCEL.EXE' (Win32): 'C:\Windows\SysWOW64\python27.dll' cargado. No se puede encontrar o abrir el archivo PDB.
'EXCEL.EXE' (Win32): 'C:\Python27\Library\bin\pywintypes27.dll' cargado. No se puede encontrar o abrir el archivo PDB.
'EXCEL.EXE' (Win32): 'C:\Python27\Lib\site-packages\win32\win32api.pyd' cargado. No se puede encontrar o abrir el archivo PDB.
'EXCEL.EXE' (Win32): 'C:\Python27\Lib\site-packages\win32\win32api.pyd' descargado
'EXCEL.EXE' (Win32): 'C:\Python27\Lib\site-packages\win32\win32api.pyd' cargado. No se puede encontrar o abrir el archivo PDB.
'EXCEL.EXE' (Win32): 'C:\Python27\Lib\site-packages\win32\_win32sysloader.pyd' cargado. No se puede encontrar o abrir el archivo PDB.
'EXCEL.EXE' (Win32): 'C:\Python27\Lib\site-packages\win32\_win32sysloader.pyd' descargado
'EXCEL.EXE' (Win32): 'C:\Python27\Lib\site-packages\win32\_win32sysloader.pyd' cargado. No se puede encontrar o abrir el archivo PDB.
'EXCEL.EXE' (Win32): 'C:\Python27\Lib\site-packages\win32\win32trace.pyd' cargado. No se puede encontrar o abrir el archivo PDB.
'EXCEL.EXE' (Win32): 'C:\Python27\Lib\site-packages\win32\win32trace.pyd' descargado
'EXCEL.EXE' (Win32): 'C:\Python27\Lib\site-packages\win32\win32trace.pyd' cargado. No se puede encontrar o abrir el archivo PDB.
```

But, with Python 2.7 (Miniconda 2 compiled with VC++ Compiler for Python 2.7) + pywin32 COM + Excel 32 bits + Win64 = The problem is here. My Excel is "**closed sudently**". Generating this trace:
```
'EXCEL.EXE' (Win32): 'C:\Python27\Library\bin\pythoncomloader27.dll' cargado. El módulo se compiló sin símbolos.
'EXCEL.EXE' (Win32): 'C:\Python27\Library\bin\pythoncomloader27.dll' descargado
'EXCEL.EXE' (Win32): 'C:\Python27\Library\bin\pythoncomloader27.dll' cargado. El módulo se compiló sin símbolos.
'EXCEL.EXE' (Win32): 'C:\Windows\WinSxS\x86_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.9415_none_508df7e2bcbccb90\msvcr90.dll' cargado. No se puede encontrar o abrir el archivo PDB.
'EXCEL.EXE' (Win32): 'C:\Python27\Library\bin\pythoncom27.dll' cargado. No se puede encontrar o abrir el archivo PDB.
'EXCEL.EXE' (Win32): 'C:\Python27\Library\bin\pythoncom27.dll' descargado
'EXCEL.EXE' (Win32): 'C:\Python27\Library\bin\pythoncom27.dll' cargado. No se puede encontrar o abrir el archivo PDB.
'EXCEL.EXE' (Win32): 'C:\Windows\SysWOW64\python27.dll' cargado. No se puede encontrar o abrir el archivo PDB.
'EXCEL.EXE' (Win32): 'C:\Windows\SysWOW64\python27.dll' descargado
'EXCEL.EXE' (Win32): 'C:\Python27\Library\bin\pywintypes27.dll' cargado. No se puede encontrar o abrir el archivo PDB.
'EXCEL.EXE' (Win32): 'C:\Python27\Library\bin\pywintypes27.dll' descargado
'EXCEL.EXE' (Win32): 'C:\Windows\SysWOW64\python27.dll' cargado. No se puede encontrar o abrir el archivo PDB.
'EXCEL.EXE' (Win32): 'C:\Python27\Library\bin\pywintypes27.dll' cargado. No se puede encontrar o abrir el archivo PDB.
<---------- DEAD HERE (maybe, trying load win32api.pyd)
El subproceso 0x59b0 terminó con código 1 (0x1).
El subproceso 0x4a90 terminó con código 1 (0x1).
El subproceso 0x4dcc terminó con código 1 (0x1).
El subproceso 0x5788 terminó con código 1 (0x1).
```
Maybe, the problem is jumping to pyd "C:\Python27\Lib\site-packages\win32\win32api.pyd". But, I am not sure.
When COM Object is Remote (CLSCTX_SERVER), all works well, it only happen when COM is In process (CLSCTX_INPROC). In old python, "in process" works well.
If I register COM using "dll" also works well, only happen when register COM Object using .py.
I try to add "C:\Python27\Lib\site-packages\win32" in PATH, PYTHONPATH, or even in windows register "HKLM\SOFTWARE\WOW6432Node\Python\PythonCore\2.7\PythonPath", and nothing, Excel always closed when try instance the com object (registered since python) in same process that Excel 2013.

In bug https://bugs.python.org/issue7833 looks very similar to my problem, and Mark Hammond publish a patch for use "[Activation Context API](https://docs.microsoft.com/en-us/windows/win32/sbscs/using-the-activation-context-api)" and wrote:
```
I meant to mention: FWIW, *some* py2exe apps work fine with the old
scheme - specifically, IIUC, any app will work fine so long as the .pyd
files were next to the executable, which is next to the assembly.  I
understand this is a significant restriction, but its worth mentioning
for completeness.
```
I dont know why Excel can't load "win32api.pyd" ... My idea was compile pywin32 using "VC++ Compiler for Python 2.7" (Title os this issue), but maybe the problem is more silly, and works with prebuilt in-box.

Thank you very much, if anyone knows anything.

**Comment by mhammond** [comment]
I've no idea what the problem could be - I've never used "Microsoft Visual C++ Compiler for Python 2.7". It might well be the manifest problem you link to - setup.py has some hacks for manifests you might like to investigate. You might also like to follow the "support" instructions in README.md to get a wider audience.

**Comment by makiolo** [comment]
Thanks Mark for answer.
The problem was solved! The problem is Miniconda2 use different the environment variables PYTHONHOME and PYTHONPATH.
During my tests I have a PYTHONPATH custom, but no PYTHONHOME, in old python this works but with Miniconda2 no.
This is solved in 2 alternatives:
- set %PYTHONHOME%=C:\Python27
- append "C:\Python27\lib" to %PYTHONPATH%

And voila, now Miniconda2 find "win32api.pyd".

**Comment by mhammond** [comment]
Thanks for getting back - I don't think there's anything actionable here, so I'm going to close this.

**Comment by PeterChiang0316** [comment]
> As for compiling version b228 (last one supporting Py2.7) for regular Python2.7: It is possible to compile most of pywin32, but not the MFC/ATL-dependent libraries (win32ui.pyd, PythonWin.exe in PythonWin/* ...) with "Microsoft Visual C++ Compiler for Python 2.7", because that doesn't contain the ATLMFC libraries. Same with "Visual Studio 2008 SP1 Express". You may find a VS2008 Pro Trial Editon which carries the ATLMFC folder.

For some reason, I need to build b228 from source too, 
but faced with problem that the console always output  "system cannot find the file specified." after I run
'python setup.py install --skip-verstamp'

I checked the output log, it seems the setup process encounter this error when copying library file from temp.win32-2.7 to lib.win32.2-7.

is this due to 'pythonwin' cannot be build with VC9.0 due to lacking ATLMFC libraries?
or what additional steps I have to do when building b228 on windows server 2012 R2 system?

thanks in advance !
