### ISSUE TITLE
Install failure on Windows 2012

### ISSUE THREAD

**Issue by brifordwylie** [mhammond/pywin32#1665]
Using this installer: <https://github.com/mhammond/pywin32/releases/download/b300/pywin32-300.win-amd64-py3.9.exe>

## Expected behavior and actual behavior.
Expected: Installer completes without error
Actual: Installer gets to the end and gives this error message:
```
Parsed arguments are: Namespace(install=True, remove=False, wait=None, silent=False, quiet=False, destination='C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python39\\Lib\\site-packages')
Traceback (most recent call last):
  File "<string>", line 630, in <module>
  File "<string>", line 332, in install
  File "<string>", line 171, in LoadSystemModule
  File "<frozen importlib._bootstrap>", line 565, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1108, in create_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
ImportError: DLL load failed while importing pythoncom: The specified module could not be found.
```

## Steps to reproduce the problem.
1. Spin up a Window Server 2012 R2 VM, here's the ISO.. it's has a free 180 day eval license: <https://www.microsoft.com/en-us/evalcenter/evaluate-windows-server-2012-r2>
2. Install Python 3.9:  <https://www.python.org/downloads/>
3. Run the pywin32 installer: <https://github.com/mhammond/pywin32/releases/download/b300/pywin32-300.win-amd64-py3.9.exe>

## Version of Python and pywin32
- Python 3.9.2
- 300

## Notes
- Yes, this is a super old server, not my choice/option, client needs my service to run on this platform. :)

**Comment by mhammond** [comment]
Windows 2012 is windows 8.1 compatibility and I don't recall adding support for anything that would exclude that version (although it does build with the windows 10 SDK, so maybe something's misconfigured there).

However, this is so old that I'm not going to find the time to diagnose this - if you can work out what specifically is failing to load I might be able to help.

**Comment by brifordwylie** [comment]
I totally understand,  I have a few public  projects myself and putting effort in to support ancient platforms probably isn't the best use of time.  I'm going to go ahead and close this, if someone feels 'brave' they can use the replication instructions above and try to do some debugging.
