### ISSUE TITLE
Feature request: Allow use of streams than path in `wc.Dispatch("Word.Application").Documents.Open(docx_path)`

### ISSUE THREAD

**Issue by XtremeGood** [mhammond/pywin32#1673]
Note that issues in this repository are only for bugs or feature requests in the pywin32.

**If you need support or help using this package, please follow [these instructions](https://github.com/mhammond/pywin32/blob/master/README.md#support)** - support or help requests will be closed without comment.

For all bugs, please provide the following information.

* Expected behavior and actual behavior.
To convert docx to html , one would do 
```
word = wc.Dispatch("Word.Application")
doc = word.Documents.Open(docx_path)
doc.SaveAs(html_path, 8)
```
But here we require paths. I am using `python-docx-template` . I read a docx file, template it, then save to a StringIO(). But now I have to first save the doc as .docx, then open it and then create .html files, then deal with PermissionErrors. How can I use the StringIO() in place of paths.  Something like this:
```

word = wc.Dispatch("Word.Application")
doc = word.Documents.Open(docx_string_io)
doc.SaveAs(html_stream, 8)
```

* Steps to reproduce the problem.

* Version of Python and pywin32
Python: 3.8.0
Pywin32: latest(pip install'ed yesterday)

**Comment by mhammond** [comment]
This is a support question for how to use Word with pywin32. Please read the first 2 lines of the issue you opened for how to get such support.

**Comment by XtremeGood** [comment]
I don't know, like searching everywhere on StackOverflow or googling for hours , I couldn't find the answer and the source code also is to hard to understand.

**Comment by XtremeGood** [comment]
https://ibb.co/SNVyS4y
https://github.com/XtremeGood/MailerKivy/blob/master/src/mailer/prepare_message.py#L110    My code

What my code does is read a csv  , read and template  a Word document with the help of  https://pypi.org/project/docxtpl/ . Further it convert file from .docx  to .html. Then use smtplib to attach that html as message body. 
So the process goes as follow ,   
1) Read a csv row.
2) Create a dictionary
3) Use that dictionary as jinja context to fill the template
4)Save as docx, read  docx , convert to html, save to html, 
6) Read the html file which is saved, and attach it as email message body. 

I have the "bytes stream" available  of the templated docx. Now you can see that step 4) requires unnecessary saving of docx and html file on the disk which increases the time taken to send a mail.

**Comment by mhammond** [comment]
`Documents.Open` is defined by and supplied by Microsoft Word. There's literally nothing pywin32 can do to change how Word works. If Word doesn't supply an API to do what you ask, then you can't do it. I've no idea whether Word does supply such an API, but if it does, it would work from any language, so you should search for how it's done in any language, not only in Python.

**Comment by v-python** [comment]
So the process would probably be better done as:
1. Read a csv row
2. Create a dictionary
3. Use the dictionary to generate HTML
4. Attach the HTML as the email message body.

I'm not sure what benefit you are getting from  using Word, but Word generates horrendously bloated HTML code. Besides your performance issue of writing to the disk, the generated HTML could probably be a quarter the size or less than what would be generated by Word.

**Comment by XtremeGood** [comment]
> 
> 
> `Documents.Open` is defined by and supplied by Microsoft Word. There's literally nothing pywin32 can do to change how Word works. If Word doesn't supply an API to do what you ask, then you can't do it. I've no idea whether Word does supply such an API, but if it does, it would work from any language, so you should search for how it's done in any language, not only in Python.

yeah I just spent a few hours on the   IRC Freenode 's c# channel and got no useful help from there. So I need to think of something else.

**Comment by XtremeGood** [comment]
> 
> 
> So the process would probably be better done as:
> 
>     1. Read a csv row
> 
>     2. Create a dictionary
> 
>     3. Use the dictionary to generate HTML
> 
>     4. Attach the HTML as the email message body.
> 
> 
> I'm not sure what benefit you are getting from using Word, but Word generates horrendously bloated HTML code. Besides your performance issue of writing to the disk, the generated HTML could probably be a quarter the size or less than what would be generated by Word.

The point is that Microsoft Word is made for users while html is not.
