### ISSUE TITLE
format the repository with black

### ISSUE THREAD

**Issue by mhammond** [mhammond/pywin32#1674]
We should use black to convert all files in the repo. We should also follow the advice given at https://github.com/psf/black#migrating-your-code-style-without-ruining-git-blame (ie, one massive commit and capture the hash of that commit in a file)

Ideally we could then integrate it with CI so we "test" commits for formatting.

**Comment by kxrob** [comment]
Is this to be expected soon?

The default max line length of black seems to be 88 (--line-length). A tiny bit more than the classic "terminal" 80 chars. In pywin32 there a are many long lines, long constant names. And generally the need for indentations. I wonder if readability and nuisance (number of changes) remains better with somewhat more (potential free) space - e.g. 120 ?

Are current tabs / spaces preserved - at 4 indent chars?

( I have a longer patch series, successor of the (py2) ide-ex branch, mostly in pywin/*.  And some (private) py27 / "PY6" compatibility stuff. But maybe there is a way to rebase / rewrite history of such feature branches by applying the "black" after each commit, to get things across ... )

**Comment by mhammond** [comment]
> The default max line length of black seems to be 88 (--line-length). A tiny bit more than the classic "terminal" 80 chars. In pywin32 there a are many long lines, long constant names. And generally the need for indentations. I wonder if readability and nuisance (and number of changes) remains better with somewhat more (potential free) space - e.g. 120 ?

Yep, I'd be up for that.

> Are current tabs / spaces preserved - at 4 indentation chars?

It's actually tabs and trailing whitespace in existing files that prompted me to open this - I don't want to do it piecemeal (ie, convert every file as it is touched) as that has the "blame" problem described above, so thought I'd just open it to keep myself honest.

>  I have a longer patch series, successor of the (py2) ide-ex branch,

There's no hurry - I'm happy to wait for in-flight PRs to get done.

**Comment by LincolnPuzey** [comment]
In my experience, integrating with CI to check PRs for black formatting is a must-have.

Otherwise either new PRs slowly introduce incorrectly formatted code, or someone has to do the mental work of checking formatting on PRs, which defeats the purpose of black.

**Comment by LincolnPuzey** [comment]
@kxrob 

> Are current tabs / spaces preserved - at 4 indentation chars?

No, black will enforce 4-space indents on all files. ( black will only format `.py` files)

**Comment by LincolnPuzey** [comment]
@mhammond 

> There's no hurry - I'm happy to wait for in-flight PRs to get done.

I can see the following open PRs with recent activity that make non-trivial changes to `.py` files:
* https://github.com/mhammond/pywin32/pull/1676
* https://github.com/mhammond/pywin32/pull/1675
* https://github.com/mhammond/pywin32/pull/1664 (draft)

I am happy to contribute a PR applying black and CI integration once these are merged.

Any other PRs you would like to wait for?

**Comment by mhammond** [comment]
#1664 is the only one I'm bothered by.

**Comment by LincolnPuzey** [comment]
Formatting done in #1755 

@mhammond we can close this

**Comment by mhammond** [comment]
Thanks!
