### ISSUE TITLE
Outlook Not Reading Emails Past a Certain Date

### ISSUE THREAD

**Issue by msperansky** [mhammond/pywin32#1678]
```
import win32com.client as client
import os
from datetime import datetime, timedelta

outlook = client.Dispatch('Outlook.Application').GetNamespace('MAPI')
inbox = outlook.Folders('#emailAddress').Folders('inbox')
message = inbox.Items[0]
```

For some reason, message is giving me an email from February 26 and when I try other folders it is the same date. 

Any help would be appreciated.
Matt

**Comment by mhammond** [comment]
Please see https://github.com/mhammond/pywin32/blob/master/README.md#support
