### ISSUE TITLE
lpWindowName parameter missing in CreateWindow

### ISSUE THREAD

**Issue by JoaoPere** [mhammond/pywin32#1680]
First of all, thank you for the project.

Using the [Windows 10 Toast Notifications](https://github.com/jithurjacob/Windows-10-Toast-Notifications) library, ever since one of the most recent Windows 10 updates, the toast notification generated now displays a window title, that seems to default to the name of the executable (circled in green).

![image](https://user-images.githubusercontent.com/14939733/112011672-62ef5b00-8b20-11eb-8075-2b43e5b22385.png)

After trying and failiing to personalize this within the client code, I went through the win10toast and the pywin32 libraries in order to find the origin of the problem. I noticed that win10toast relies on the `CreateWindow` method as per

```
self.hwnd = CreateWindow(self.classAtom, "Taskbar", style,
    0, 0, CW_USEDEFAULT,
    CW_USEDEFAULT,
    0, 0, self.hinst, None)
```

https://github.com/jithurjacob/Windows-10-Toast-Notifications/blob/9d52b73f1af6c60162cf09b99269c4f7b13cdb00/win10toast/__init__.py#L83

When looking for the [original function declaration](https://github.com/mhammond/pywin32/blob/e7f02709345b4fc9e8bec1d3d9ad3e8b9a067c45/win32/src/win32gui.i#L2977) and compare it with the [official documentation ](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-createwindowa), I noticed that the `lpWindowName` parameter is missing. Furthermore, a broader search within the whole repo, reaps no results when querying for the aforementioned parameter name. Therefore, I believe that this shortcoming of not being able to personalize the window name of the toast notification lies with pywin32.

**Comment by kxrob** [comment]
> I noticed that the `lpWindowName` parameter is missing

Isn't it just another doc name for this (positional only) parameter:  `windowTitle : string` ?
(lpXX...   = "long pointer to"  less reasonable for Python ) 
The doc could be renamed "windowName" to resemble the winuser.h name.
Yet it already fitted your intro :  _the toast notification generated now displays a **window title**_  :)

**Comment by JoaoPere** [comment]
@kxrob not sure if I follow. I understand that the name conventions for Python differ from the C counterparts but is there any way to set that window title already? I take you're referencing `TCHAR *INPUT_NULLOK, // @pyparm string|windowTitle||` as the responsible for this, but if that was the case, the window in question, taken into consideration the call to `CreateWindow` in win10toast, should be titled "Taskbar" or am I in the wrong?

**Comment by kxrob** [comment]
>  the call to `CreateWindow` in win10toast, should be titled "Taskbar"

stepping into the hello world, it seems this lib CreateWindow()'s a dummy window (which together with its windowTitle is not visible at all at) just to receive notifications , but the actual "toast" is run via win32gui.Shell_NotifyIcon().  That is feed with the InfoTitle from the first arg of show_toast() - the actual toast title, the bold line of the toast. The extra thing with icon (-> hIcon) + "Python" in your pic seems to have to do with the operation / feeding of Shell_NotifyIcon() and Windows notifications and perhaps wants to tell the source application (for good reason). So you'd have to look from there.

**Comment by mhammond** [comment]
I updated the docs in 529dc4f8 so they are closer to what MS documents, but as @kxrob mentioned, this is a docs only change and that 2nd param is indeed `lpWindowName`.

**Comment by JoaoPere** [comment]
@mhammond @kxrob thank you both. seems that what I was looking for isn't personalizable through the Windows API, so unless there's a workaround to change the Python process description in Windows, this cannot be accomplished.
