### ISSUE TITLE
Microsoft word cannot be used while code is using it

### ISSUE THREAD

**Issue by XtremeGood** [mhammond/pywin32#1689]
Note that issues in this repository are only for bugs or feature requests in the pywin32.

**If you need support or help using this package, please follow [these instructions](https://github.com/mhammond/pywin32/blob/master/README.md#support)** - support or help requests will be closed without comment.

For all bugs, please provide the following information.

* Expected behavior and actual behavior.

* Steps to reproduce the problem.
---

* Version of Python and pywin32
* 3.8.0
* 300

My code requires to convert word docx to html via microsoft word. But what's happening is that while the code is running , if I open microsoft word if flashes and closes. My code is affected in no way though. This is when I run `python -m mailer`.

I made the executable, and as I opened it , clicked few buttons which trigger the action, microsoft word opened and asked to save the last unsaved doc(autosave feature). I clicked no and my executable stopped for infinite time . Word should not open here. Only task is to convert in background as a separate process. 
![image](https://user-images.githubusercontent.com/40588378/114086312-194c9180-98d0-11eb-89ee-e6979c1f11db.png)
```
[INFO   ] [GL          ] NPOT texture support is available
 Exception in thread Thread-2:
 Traceback (most recent call last):
   File "threading.py", line 932, in _bootstrap_inner
   File "threading.py", line 870, in run
   File "mailer\send_mail.py", line 36, in <lambda>
   File "mailer\send_mail.py", line 60, in make_mail_objects
   File "mailer\send_mail.py", line 139, in get_mail_object_from_row
   File "mailer\prepare_message.py", line 189, in add_message
   File "mailer\prepare_message.py", line 154, in _add_html_message
   File "mailer\prepare_message.py", line 129, in _convert_docx_to_other_and_save_to_disk
   File "win32com\client\dynamic.py", line 511, in __getattr__
 AttributeError: Open.SaveAs
```
 

```
from docxtpl import DocxTemplate, InlineImage
from win32com import client as wc

class PrepMessage:
    def __init__(self):
        self.msg = EmailMessage()
        self.templates = {}
        self.html_file_path = None

    def _convert_docx_to_other_and_save_to_disk(
        self, docx_bytes_io, extension, enumeration
    ):

        now = datetime.now()
        dt_string = now.strftime("%d-%m-%Y_%H-%M-%S")

        temporary_directory_path = tempfile.mkdtemp(
            prefix="tempdir-", suffix=dt_string)

        with open(
            os.path.join(temporary_directory_path, "word_template.docx"), "wb"
        ) as docx:
            docx.write(docx_bytes_io.getvalue())

        word = wc.Dispatch("Word.Application")
        doc = word.Documents.Open(
            os.path.join(temporary_directory_path, "word_template.docx")
        )
        doc.SaveAs(
            os.path.join(temporary_directory_path,
                         f"word_template_filled.{extension}"),
            enumeration,
        )

        doc.Close()
        word.Quit()
        self.html_file_path = os.path.join(
            temporary_directory_path, f"word_template_filled.{extension}"
        )
        return self.html_file_path

    def _add_plain_text_message(self, stream):

        with open(self._convert_docx_to_other_and_save_to_disk(stream, "txt", 2)) as fp:
            text = fp.read()
        msgAlternative = MIMEMultipart("alternative")

        msgAlternative.attach(MIMEText(text, _charset="utf-8"))
        self.msg.attach(msgAlternative)

    def _add_html_message(self, stream):

        with codecs.open(
            self._convert_docx_to_other_and_save_to_disk(stream, "html", 10)
        ) as fp:
            html = fp.read()
        html = self._put_images_in_email_message(html)
        msgAlternative = MIMEMultipart("alternative")

        msgAlternative.attach(
            MIMEText(html, _subtype="html", _charset="utf-8"))
        self.msg.attach(msgAlternative)

  ```

**Comment by mhammond** [comment]
This isn't a bug in pywin32, but a request for help using it with word. Please see the very first line of this issue which describes how support requests should be handled.

**Comment by XtremeGood** [comment]
can you please then respond to my mailing link request @mhammond ? I made that 1 month ago and just now too.

**Comment by mhammond** [comment]
Sorry, but I don't use Word so have no idea how to answer your questions. To be honest, I didn't understand your "use of streams" question, and I suspect the answer to your "can't use word while automating word" is "you can't" - but again, I haven't used Word via COM for many many years.

**Comment by XtremeGood** [comment]
Where did I say "can't use word while automating word"? What does it even means to automate word? The requirement is to use Word for converting word docx-> html like pandoc does but I want to use Word because users have word  installed on their pc's rather than pandoc or something similar. 
The problem is while the code is using word, if my user tries to open word to write some document or whatever things word closes immediately(flashes). 
I was expecting that pywin32 is opening word in a separate shell/thread. Why is Microsoft Word being being opened as a shared  process between my code and what the user is using?  It should be like two separate instances of word. My code sends mails for the marketing people in bulk(it's not spamming if it gives you that kind of smell) to their users. But this is not desirable that users are not able to use word during the running period of the code.

**Comment by mhammond** [comment]
> Where did I say "can't use word while automating word"? What does it even means to automate word?

Sorry, for some reason I thought you also opened #1689.

> I was expecting that pywin32 is opening word in a separate shell/thread. Why is Microsoft Word being being opened as a shared process between my code and what the user is using?

I think you misunderstand pywin32's role here - it just creates COM objects - how those objects work are up to those objects. There's literally zero code in pywin32 that deals with Word - it's all just generic COM objects.

> And please can I get approval of the mailing list request if it's still not clear?

I've approved all requests that I've seen from you and there are zero pending approval requests to the mailing list. https://mail.python.org/pipermail/python-win32/2021-March/thread.html was delivered but no one replied, probably because no one knew how to do what you were asking (which may literally be because it's impossible)

**Comment by mhammond** [comment]
> Sorry, for some reason I thought you also opened #1689.

Right - you *did* open that issue :) What you are doing - using Word via its COM interface - is often described as "automating". Your complaint is with Word, not with pywin32.

**Comment by XtremeGood** [comment]
Oh, didn't know this thing. But thanks for the info. Also microsoft is not open-source and so should I assume that I 'm stuck?

**Comment by XtremeGood** [comment]
> 
> 
> > Where did I say "can't use word while automating word"? What does it even means to automate word?
> 
> Sorry, for some reason I thought you also opened #1689.
> 
> > I was expecting that pywin32 is opening word in a separate shell/thread. Why is Microsoft Word being being opened as a shared process between my code and what the user is using?
> 
> I think you misunderstand pywin32's role here - it just creates COM objects - how those objects work are up to those objects. There's literally zero code in pywin32 that deals with Word - it's all just generic COM objects.
> 
> > And please can I get approval of the mailing list request if it's still not clear?
> 
> I've approved all requests that I've seen from you and there are zero pending approval requests to the mailing list. https://mail.python.org/pipermail/python-win32/2021-March/thread.html was delivered but no one replied, probably because no one knew how to do what you were asking (which may literally be because it's impossible)

That's very strange . I got no e-mail on "manglavishesh64@gmail.com"  or neither on "f20170548@pilani.bits-pilani.ac.in". These are only my 2 email addresses.
