### ISSUE TITLE
Feature Request: Registration-free COM server

### ISSUE THREAD

**Issue by Greedquest** [mhammond/pywin32#1696]
I don't believe there's currently a way to do this. At the moment we have to go through win32com.server.register, but I know it's possible to simply reference a dll from a project without registering it beforehand.

I've had a dig around the codebase, and asked a question on SO [here](https://stackoverflow.com/q/67382306/6609896), but it has not yet received any answers. I envisage a system where I can copy and paste my server.py around and reference either a server.dll/exe or the `pythoncomxx.dll` server from a project using early binding.

Is there currently a method to do this sort of thing?

**Comment by mhammond** [comment]
> but I know it's possible to simply reference a dll from a project without registering it beforehand.

I don't think it is in the general case. Obviously something could know how to loadlibrary a path and look for the well known symbols in it - ie, duplicating what COM itself does. You could do this via ctypes (but then you could load and use any symbol, not just COM ones).

If there's something in COMs documentation that we don't implement I'd be happy for an issue to remain alive, but I don't think supporting what you describe makes sense for pywin32.
