### ISSUE TITLE
Null pointer crash in PyCom_RegisterExtensionSupport

### ISSUE THREAD

**Issue by zooba** [mhammond/pywin32#1697]
I haven't been able to track down the exact location where the bug occurs, but this trace is the most common crash in Python 3.8 and 3.9 according to the telemetry I get from crash reports.

It appears to happen randomly when certain modules are imported (mostly `propsys.pyd` and `ifilter.pyd`, didn't spot any others in my sampling). My guess is that this is some kind of transparent dict cache, but I couldn't find it in the source code.

Hopefully this is enough info for someone familiar to find it by review, I don't really have any more info than this. (The `PyCom_IsGatewayRegistered` reference may be incorrect, judging by the size of the code offset, so it could be going through a private function rather than that one.)

n | Module | Function | Offset
-- | -- | -- | --
0 | python38.dll | PyDict_SetItem | 0x000000000000001C
1 | pythoncom38.dll | PyCom_IsGatewayRegistered | 0x000000000000017C
2 | pythoncom38.dll | PyCom_RegisterExtensionSupport | 0x0000000000000023
3 | propsys.pyd |   | 0x0000000000009EF8
4 |   |   | 0x0000000000000000
5 | unknown.dll | noop | 0x0000000000000000
6 | unknown.dll | noop | 0x0000000000000000
7 |   |   | 0x0000000000000000
8 |   |   | 0x0000000000000000
9 | python38.dll | _PyImport_LoadDynamicModuleWithSpec | 0x0000000000000108

**Comment by mhammond** [comment]
Thanks Steve,
  I can't come up with a "normal" scenario that explains this, but I did fine one that's only slightly abnormal - if one of these COM .pyd files was loaded outside of the win32com package. That would crash with a very similar stack.

While experimenting, I did find other scenarios where a MemoryError would cause crashes too, but they'd crash before these extension modules got a chance to crash in this way - I fixed the most obvious ones too.

All of which is to say that I believe f4798e0a will resolve this specific crash. I'll close this for now, but obviously welcome these reports (and hopefully reports that the crash rates are dropping once the next build get out - which should hopefully be very soon)
