### ISSUE TITLE
Deploying via Heroku

### ISSUE THREAD

**Issue by SomDutta2000** [mhammond/pywin32#1698]
I am trying to deploy my app in heroku which has pywin32==300 in requirements.txt file. So when i deploy it shows

 ERROR: Could not find a version that satisfies the requirement pywin32==300 (from -r /tmp/build_a2f8ecc6/requirements.txt (line 82)) (from versions: none)

 ERROR: No matching distribution found for pywin32==300 (from -r /tmp/build_a2f8ecc6/requirements.txt (line 82))

**Comment by mhammond** [comment]
#1197 has the same problem (although with a much earlier version), so let's track this there. Sadly I've no idea though as that version certainly exists.

**Comment by Avasam** [comment]
`/tmp/build_a2f8ecc6/requirements.txt` looks like a UNIX platform
