### ISSUE TITLE
Error message - "Can't load Python for pre-install script"

### ISSUE THREAD

**Issue by ghost** [mhammond/pywin32#170]
Hi all - 
I've downloaded and installed the Python 2.4 .msi
file for Windows \(I'm running Win XP\).  That install
went fine, and I can run Python code at the usual
prompt \(&gt;&gt;&gt;\). 
The .msi file that I downloaded was - 
python-2.4b2.msi .
I then downloaded the Python for Windows extensions
\(the file was pywin32-203.win32-py2.4.exe \). 
Double-clicked on that, and I got as far as "ready to
install". I then clicked the "next" button, and I got
the message "can't load Python for pre-install script".  
This was weird, because at the start of things \(when
I first double-clicked the .exe file\), the .exe file
\*did\* find my Python install \(in C:\Python24 \), so
goodness knows why it can't find Python later on .... :-\) 
I haven't changed anything from the defaults ....
the install of the .msi file was a full install, and I
changed nothing whatsoever.  

Reported by: mr_moose

Original Ticket: "pywin32/bugs/170":https://sourceforge.net/p/pywin32/bugs/170

**Comment by Avasam** [comment]
@mhammond The user's issue was resolved here. (also exe installers are deprecated)
