### ISSUE TITLE
 GetNamespace hangs 

### ISSUE THREAD

**Issue by satharasidinesh** [mhammond/pywin32#1703]
when i try to call GetNamespace  i get hang infinitely. 
mapi = outlook.GetNamespace("MAPI")
    outBox = mapi.Folders[sender].Folders['Outbox']
    OutboxCount = outBox.Items.Count

* Version of Python : 3.9 and pywin32 : 300

**Comment by mhammond** [comment]
Sorry, I've no idea why outlook is hanging for you, but there's nothing pywin32 can do about it - it just calls the COM interface exposed by outlook.
