### ISSUE TITLE
想使用linux调用

### ISSUE THREAD

**Issue by solitary-sen** [mhammond/pywin32#1708]
您好！我们团队想用linux版本调用此框架，目前在https://pypi.org/project/pywin32/223/#files这个里面找到的没有支持python3.8的版本，请问应该怎么做才能调用到框架。谢谢了。

**Comment by solitary-sen** [comment]
目前安装都不起效果
![image](https://user-images.githubusercontent.com/25165062/120301143-28175980-c2ff-11eb-9bb1-9da413d025b8.png)

**Comment by mhammond** [comment]
Google translates as:
> Hello! Our team wants to use the Linux version to call this framework. Currently, there is no version that supports python3.8 found in https://pypi.org/project/pywin32/223/#files. What should I do to call the framework? Thank you. 

This framework does not support Linux. Build 223 was released on 26 Feb 2018 - more recent versions support 3.8.

**Comment by solitary-sen** [comment]
Architecture:        aarch64
Byte Order:          Little Endian
CPU(s):              6
On-line CPU(s) list: 0-5
Thread(s) per core:  1
Core(s) per socket:  3
Socket(s):           2
Vendor ID:           ARM
Model:               4
Model name:          Cortex-A53
Stepping:            r0p4
CPU max MHz:         1800.0000
CPU min MHz:         408.0000
BogoMIPS:            48.00
Flags:               fp asimd evtstrm aes pmull sha1 sha2 crc32



# python3.8
Python 3.8.2rc2 (default, Jan 25 2021, 15:31:33)
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.

**Comment by mhammond** [comment]
You should be able to use pywin32-301.

**Comment by solitary-sen** [comment]
![image](https://user-images.githubusercontent.com/25165062/120410254-3445fa00-c385-11eb-8c65-ddb54ecdd987.png)
糟糕了

**Comment by mhammond** [comment]
This package does not work on Linux, only on Windows!
