### ISSUE TITLE
Detect Installation of pywin32

### ISSUE THREAD

**Issue by cpede** [mhammond/pywin32#1718]
Is it possible to detect if pywin32 is already installed on Windows.
E.g. I want to find out from my program (c++) if e.g. "Python 3.9. pywin32-900" is installed or if I need to install it.
A look in the Windows Registry, or a special call?

**Comment by vernondcole** [comment]
I'm assuming that your c++ program can execute a shell command.

To see if some version of pywin32 is installed, try importing a pywin32 module.
Run a DOS shell command like:
`py -c "import win32api"`
If Python returns with an error code (echo %ERRORLEVEL%") of 0 then it is installed. If 1 then it is not.

Finding the exact version number is more difficult. Try:
`py -m pip show pywin32 --verbose`
and parse the output for a line starting "Version: ".

**Comment by mhammond** [comment]
In the general case, the answer here is "look in python's site-packages" - eg, when installed via pip there will be nothing in the registry.
