### ISSUE TITLE
SMBv2  OpenEventLogW - Access is denied

### ISSUE THREAD

**Issue by madzombie** [mhammond/pywin32#1719]
I'm guessing pywin32 does not work with SMBv2
if SMBv1 is disabled on the server for security reasons, it does not work.

affected function ; 
`win32evtlog.OpenEventLog(server, "Security")`

it give an access denied error via SMBv2.

` (5, 'OpenEventLogW', 'Access is denied.')`

I have tested it with the following versions ;

- pywin32 301
-  python36

**Comment by mhammond** [comment]
> I'm guessing pywin32 does not work with SMBv2
...
> `win32evtlog.OpenEventLog(server, "Security")`

pywin32 is just a wrapper around the underlying Windows `OpenEventLog` function, so there's no real concept of "compatible with SMBv2" in this context. I suspect just calling the Windows function directly would fail with the same error, so I don't think there's anything actionable here.
