### ISSUE TITLE
Does it support excel .xlsm with password protected VBA project ?

### ISSUE THREAD

**Issue by cuongngoz** [mhammond/pywin32#1720]
* Expected behavior and actual behavior.
Should be able to read excel .xlsm with password protected VBA project
![image](https://user-images.githubusercontent.com/63572184/123048572-baa3a800-d428-11eb-98ea-d66fb00ede27.png)

* Steps to reproduce the problem.
Tried with following
```
FILE_PASS = os.getenv('FILE_PASS')
print(FILE_PASS)
Xl_wb = Xl_app.Workbooks.Open(Filename=file_path, UpdateLinks=False, ReadOnly=False, Format=None, Password=FILE_PASS,  WriteResPassword = FILE_PASS)
```
or 
```
Xl_wb = Xl_app.Workbooks.Open(Filename=file_path, Editable=True, Password=FILE_PASS,  WriteResPassword = FILE_PASS)
```
or 
```
Xl_wb = Xl_app.Workbooks.Open(Filename=file_path, Editable=True, Password=FILE_PASS)
```

Still get error
```
(-2147352567, 'Exception occurred.', (0, 'MyDataSheet', "Can't perform operation since the project is protected.", 'C:\\Program Files\\Common Files\\Microsoft Shared\\VBA\\VBA7.1\\1033\\VbLR6.chm', 50289, -2146777999), None)
```

If I remove password protected as screenshot above then it works fine.

* Version of Python and pywin32
  - Python 3.8.7
  - pip        20.2.3
  - pypiwin32  223
  - pywin32    301
  - setuptools 49.2.1

**Comment by fzumstein** [comment]
Workbooks.Open parameter are position only, they don't support keyword args as you tried. You can see how I implemented it with xlwings here:
https://github.com/xlwings/xlwings/blob/master/xlwings/_xlwindows.py#L492-L495
