### ISSUE TITLE
Service start failed

### ISSUE THREAD

**Issue by Anniywell** [mhammond/pywin32#1722]
I want to use localservice to create a Windows service, but the service failed to start.
This is my command:
```shell
python service.py --username "NT AUTHORITY\LocalService" install
```
This is windows service error message:
```
无法找到来自源 Python Service 的事件 ID 4 的描述。本地计算机上未安装引发此事件的组件，或者安装已损坏。可以安装或修复本地计算机上的组件。

如果该事件产生于另一台计算机，则必须在该事件中保存显示信息。

以下是包含在事件中的信息: 

ModuleNotFoundError: No module named 'service'
```

Software version is:
> Python: 3.8.10
> Pywin32: 301

**Comment by mhammond** [comment]
You will need to work out why the `service` module, part of pywin32, isn't on your sys.path. That will depend on your specific environment, including how you installed python and pywin32. Does the service work in debug mode?

**Comment by Anniywell** [comment]
> You will need to work out why the `service` module, part of pywin32, isn't on your sys.path. That will depend on your specific environment, including how you installed python and pywin32. Does the service work in debug mode?

I have added the directory where service.py is located to sys.path, but I still report this error when starting with Windows service.
Debug mode works fine.

**Comment by mhammond** [comment]
> I have added the directory where service.py is located to sys.path,

Hrm - I actually mis-spoke before and that shouldn't be necessary - the service should be registered with the full path to the .py file, and the startup code will add the directory to sys.path. Are you sure that LocalService user has access to that directory?

**Comment by Anniywell** [comment]
> > I have added the directory where service.py is located to sys.path,
> 
> Hrm - I actually mis-spoke before and that shouldn't be necessary - the service should be registered with the full path to the .py file, and the startup code will add the directory to sys.path. Are you sure that LocalService user has access to that directory?

Sorry, it's a permission issue.
