### ISSUE TITLE
Where is the document?

### ISSUE THREAD

**Issue by licaitong** [mhammond/pywin32#1723]
Note that issues in this repository are only for bugs or feature requests in the pywin32.

**If you need support or help using this package, please follow [these instructions](https://github.com/mhammond/pywin32/blob/master/README.md#support)** - support or help requests will be closed without comment.

For all bugs, please provide the following information.

* Expected behavior and actual behavior.

* Steps to reproduce the problem.

* Version of Python and pywin32

**Comment by arihant2math** [comment]
What do you mean by document?

**Comment by licaitong** [comment]
i mean the documentation

**Comment by arihant2math** [comment]
It was at [http://timgolden.me.uk/pywin32-docs/](http://timgolden.me.uk/pywin32-docs/) but it doesn't seem to be maintained anymore so you need to build the docs your self, to do so, just follow the readme here: 

[https://github.com/mhammond/pywin32/tree/master/AutoDuck#readme](https://github.com/mhammond/pywin32/tree/master/AutoDuck#readme)

**Comment by licaitong** [comment]
thanks bro

**Comment by arihant2math** [comment]
If this resolves your issue please close it.
