### ISSUE TITLE
ImportError: DLL load failed while importing win32gui: The specified procedure could not be found

### ISSUE THREAD

**Issue by mosaleh52** [mhammond/pywin32#1730]
when trying to import win32gui or win32api this is the output error
'''
C:\Users\m\Desktop\auto timer>main.py
Traceback (most recent call last):
  File "C:\Users\m\Desktop\auto timer\main.py", line 3, in <module>
    import win32gui
ImportError: DLL load failed while importing win32gui: The specified procedure could not be found.
'''
after install pywin32 for the first time it was working but now it doesn't 
what i have tried to solve this proplem:
----- reinstall pywin32 (it dosnot work )
-----create a conda env it doesn't work ( i have python installed seperatly , mini conda for ven only )
her is my system info
OS Name:                   Microsoft Windows 10 Home Single Language
OS Version:                10.0.19042 N/A Build 19042
Python 3.9.5
Name: pywin32
Version: 301
conda 4.10.3

**Comment by primal100** [comment]
I'm getting a similiar issue with pyin32 v301.

```python
DLL load failed while importing win32security: The specified procedure could not be found.
```

Works fine in pywin32 v300.


Windows 10 build 18363, python 3.8.6

**Comment by mmaylat** [comment]
I'm getting identical issues for python 3.6 versions with pywin32-301.

Don't see any problem with higher python versions.

**Comment by mosaleh52** [comment]
@mmaylat @primal100 after uninstall with pip then creating conda env with reboot it worked (pywin32 is defult installed in conda env)

**Comment by grgeorgeivanov** [comment]
We are also seeing this on Python 3.6.6, during `import requests_negotiate_sspi`

**Comment by elbakramer** [comment]
Getting similar issue when installed via pip.

```
$ pip install pywin32==301
```

System background:
* windows 10
* conda 4.10.1
* python 3.8.8 (64bit)
* pywin32-301

One of the workarounds that actually worked was just to downgrade to version 300:

```
$ pip install pywin32==300
```

Another workaround was to install using graphical installer that can be downloaded from [release page](https://github.com/mhammond/pywin32/releases/tag/b301).

But it seems that the installer can only detect `base` conda env but no others, and could not find any workaround for that.
So I think currently the first downgrading method is a pretty viable option.

**Comment by mhammond** [comment]
I suspect this will work better in build 303, but please reopen if it doesn't (but see also https://github.com/mhammond/pywin32#the-specified-procedure-could-not-be-found--entry-point-not-found-errors)

**Comment by marxangels** [comment]
> import pywintypes # Not used, but need it for win32gui to import correctly
> import win32gui

[stackoverflow](https://stackoverflow.com/questions/3956178/cant-load-pywin32-library-win32gui)

**Comment by PetteriAimonen** [comment]
Note for people hitting this after upgrading to pywin32 version 305:

The way `pywintypesXX.dll` is searched was changed by commit 50c31132e406510d1cb6525bde40c348f76d0258.
This causes the file to be moved under `pywin32_system32` subdirectory when packaged by e.g. pyinstaller.
This may need changes in installation scripts to make sure the old incompatible files do not stay lingering after upgrade.

**Comment by tomate1** [comment]
> Getting similar issue when installed via pip.
> 
> ```
> $ pip install pywin32==301
> ```
> 
> System background:
> 
> * windows 10
> * conda 4.10.1
> * python 3.8.8 (64bit)
> * pywin32-301
> 
> One of the workarounds that actually worked was just to downgrade to version 300:
> 
> ```
> $ pip install pywin32==300
> ```
> 
> or revert to initial conda distribution (version 228):
> 
> ```
> $ conda install pywin32
> ```
> 
> Another was to remove any existing dlls and copy valid ones in `sys.prefix` folder:
> 
> ```python
> import os
> import sys
> import glob
> import shutil
> import distutils.sysconfig
> 
> lib_dir = distutils.sysconfig.get_python_lib(plat_specific=1)
> 
> files = glob.glob(os.path.join(lib_dir, "pywin32_system32\\*.*"))
> bases = [os.path.basename(file) for file in files]
> 
> bad_dest_dirs = [
>     os.path.join(sys.prefix, "Library\\bin"),
>     os.path.join(sys.prefix, "Lib\\site-packages\\win32"),
> ]
> 
> for base in bases:
>     for bad_dest_dir in bad_dest_dirs:
>         bad_fname = os.path.join(bad_dest_dir, base)
>         if os.path.exists(bad_fname):
>             os.unlink(bad_fname)
> 
> for file in files:
>     shutil.copy(file, sys.prefix)
> ```

this was helpful to me
306 release broke my code
python cant find pywintypesXX anymore

I embed python in another application using Py_RunSimple string.

on version 305 everything works and the dlls are found there in ..Lib\site-packages\pywin32_system32

But on release 306 the dlls are simply not found anymore

I downgraded because it was easier in my case, I believe the copying to sys.prefix should work aswell
But this is really annoying
