### ISSUE TITLE
Can't find the Windows SDK

### ISSUE THREAD

**Issue by DR11110000** [mhammond/pywin32#1735]
Trying to install the _**setup.py**_ by using the cmd. 
1. cmd used: **_python setup.py install_** 
2. raise an exception:
   ```
 Building pywin32 3.8.301.1
    Can't find a windows 10 sdk
    
    It looks like you are trying to build pywin32 in an environment without
    the necessary tools installed. It's much easier to grab binaries!
    
    Please read the docstring at the top of this file, or read README.md
    for more information.
    
    Traceback (most recent call last):
      File "setup.py", line 252, in <module>
        raise RuntimeError("Can't find the Windows SDK")
    RuntimeError: Can't find the Windows SDK
```
3. How can we solved this issue.

**Purpose**
i. Installing the win32api for the venv, which was  created by me.
ii. Every other setup.py was working i.e. regex, eql, etc.
iii. While trying to install the WIN32API setup its throwing the above exception.

Please guide me, so i can achieve, what i was trying to do.
Thanks in advance.

**Comment by icanhasmath** [comment]
Ensure that Visual Studio has the correct components installed: [build_env.md](https://github.com/mhammond/pywin32/blob/14e84c0c5bc73dd1cd34e01581c2a871edba0c96/build_env.md)

**Comment by mhammond** [comment]
Why are you trying to build from sources? You should use pip or the .exe installers

**Comment by DR11110000** [comment]
Thanks for the reply, I will check and update.....

>>> Why are you trying to build from sources? You should use pip or the .exe installers
---- Because, I'm creating a Virtual enviroment, which have all the installed modules and wanted to installed the same modules to the Remote machines as well, without Installing it into remote systems. So, when i run the script, its showing the dll is missing. 

My concern:
1. How can i make installed the modules when the remote systems are not connected with internet.
2. I am using the force-reinstall command to install the module in remote systems and its working.
3. But, I wanted to install the module to the remote machines without commanding the remote systems to install the modules.
4. So, for that reasons i have comeup with the setup.py to install the required files.

Sorry, may be i'm not able to explain my concern clearly, because i'm not good at English, as I am from India.

Thanks for reponse...

**Comment by mhammond** [comment]
It sounds like you should use pip to install a local wheel/.whl file to solve the "no internet" problem. I don't understand (3), but you need the microsoft compilers and sdks for setup.py to work, which will be much more difficult than working with pip.

**Comment by DR11110000** [comment]
May we have a meet, so I can show you the demo, actually what I am trying
to do.

And then you can suggest the best way to resolve the issue.

Thanks
