### ISSUE TITLE
Error coming after uninstalling pywin32 mistakenly

### ISSUE THREAD

**Issue by adarshm93** [mhammond/pywin32#1737]
I uninstalled pywin32 mistakenly and installed again, and pythoncom38.dll also copied to system32, but still i am getting this error when i am opening anaconda or command prompt. So kindly help me in getting solve this error
![pywin32_error](https://user-images.githubusercontent.com/47291478/126064360-3e88f314-90fd-485e-8ef8-bb3dd85833fe.png)

**Comment by arihant2math** [comment]
You shouldn't edit SYSTEM32, try uninstalling and then reinstalling python.
