### ISSUE TITLE
No matching distribution found for pywin32==301 (from -r /tmp/build_901af13b/requirements.txt (line 43))

### ISSUE THREAD

**Issue by uhavaiya** [mhammond/pywin32#1739]
Note that issues in this repository are only for bugs or feature requests in the pywin32.

**If you need support or help using this package, please follow [these instructions](https://github.com/mhammond/pywin32/blob/master/README.md#support)** - support or help requests will be closed without comment.

For all bugs, please provide the following information.

* Expected behavior and actual behavior.

* Steps to reproduce the problem.

* Version of Python and pywin32

**Comment by mhammond** [comment]
What version of Python are you trying to use? It looks like maybe 2.7, in which case pywin32 build 228 is the latest available.

**Comment by younesh11** [comment]
@mhammond   i got the same error and i am using python version 3.6

**Comment by Mohamed-Salah-1** [comment]
Same error and am using Python 3.9.6. Am facing this error trying to deploy my builds to heroku

**Comment by fatihkabakk** [comment]
> Same error and am using Python 3.9.6. Am facing this error trying to deploy my builds to heroku

I don't know much about Heroku, but their systems might be using Linux, which does not contain windows features and API. Therefore, you should either use another library or do things manually.

**Comment by jithin03** [comment]
Facing the same issues on Python Venv(3.9.6). 
`ERROR: Could not find a version that satisfies the requirement pywin32==225 (from versions: none)
ERROR: No matching distribution found for pywin32==225`

**Comment by mhammond** [comment]
> Facing the same issues on Python Venv(3.9.6).
> `ERROR: Could not find a version that satisfies the requirement pywin32==225 (from versions: none`

version 225 did not support Python 3.9 - you need to specify a later pywin32 version, like 301

**Comment by jithin03** [comment]
@mhammond I downgraded Python to 3.7.11. Still getting the same issue 
![image](https://user-images.githubusercontent.com/68288007/128667735-210df0d2-2652-4e0c-9397-63ed2c335bda.png)

**Comment by mhammond** [comment]
huh - turns out I was wrong - build 225 *did* support 3.9! Are you on Windows? If so, then I'm afraid I've no idea why pip is giving that error, but [pypi](https://pypi.org/project/pywin32/225/#files) clearly shows that exists.

**Comment by jithin03** [comment]
Yeah, I could see that on PyPI. No, I am working on mac and this is a project I cloned. Is that the possible reason?. I commented out that dependency but I found that a package `cytoolz` that requires "pywin32>=223"

**Comment by mhammond** [comment]
Yes, that is most certainly the reason.

**Comment by mhammond** [comment]
Closing as there's not much I can do here

**Comment by Vishnu9412** [comment]
ghbdhdbfhbdfgbdfgbdfgbxfgbxfgbdfgbfg

**Comment by Vishnu9412** [comment]
I m also getting same issue

**Comment by bashirsadat** [comment]
I am having the same issue any solution

**Comment by mhammond** [comment]
This package only exists for Windows - trying to specify it as a dependency on any other OS is going to strike this. The bug is with the package specifying this as a dependency.

**Comment by MegaJoctan** [comment]
if you are

> Same error and am using Python 3.9.6. Am facing this error trying to deploy my builds to heroku

Since Heroku is run on Linux machines, no way pywin32==223 or pywin32==301 could be installed and used. go to your requirements.txt file and remove them

**Comment by marcotuliosant** [comment]
I'm using linux. I can't do this download, because appear this error:

ERROR: Could not find a version that satisfies the requirement pywin32 (from versions: none)
ERROR: No matching distribution found for pywin32

**Comment by fatihkabakk** [comment]
## *PLEASE READ BEFORE WRITING ANY OTHER COMMENTS*

### PyWin32 module is **ONLY** available on **WINDOWS!**

#### Steps to troubleshoot missing package(s);
* Make sure that you aren't trying to install `pywin32` on operating systems other than **Windows**.
* If your operating system is windows;
    - Check if your python version is compatible with the selected `pywin32` version.

*If it does not seem fixable, then please search for other packages instead of asking for help on this thread.*

**Comment by munisai2** [comment]
i have the issue with pywin32 while deploying django project in heroku
![Screenshot 2022-04-29 163249](https://user-images.githubusercontent.com/82820353/165932807-ee1f23ca-e192-4a9c-a5b4-2ef9d1dda107.png)

my requirements.txt file is 
![Screenshot 2022-04-29 163529](https://user-images.githubusercontent.com/82820353/165932959-dd81f8f9-59e7-488b-8b5c-1f03f2f2afb3.png)

**Comment by RichardVargasPilarte** [comment]
I am also having that same error but I am using Django 3.2.13 and I do not know how to fix it, if I remove pywin32 from the requirements it does not work either

**Comment by mhammond** [comment]
pywin32 only works on windows, so there's nothing I can do here. I notice "pypiwin32" is listed, which is very old and release by someone else, but is probably your remaining problem.

**Comment by munisai2** [comment]
> pywin32 only works on windows, so there's nothing I can do here. I notice "pypiwin32" is listed, which is very old and release by someone else, but is probably your remaining problem.

i am using windows only but it won't work 
what should I do with pypiwin32

**Comment by MegaJoctan** [comment]
> I'm using linux. I can't do this download, because appear this error:
> 
> ERROR: Could not find a version that satisfies the requirement pywin32 (from versions: none) ERROR: No matching distribution found for pywin32
Of course, there is no pywin32 for Linux so why do you want to install it then, if you found the pywin32 dependency mentioned on requirements.txt just remove it and you will be fine

**Comment by kirillportfolio** [comment]
ok guys, do you have a solution ?

**Comment by diegozegar** [comment]
If you are using a Python 3.5+ then you could add pypiwin32==223 to your requirements.txt file instead of pywin32

**Comment by brianpaden289** [comment]
For anyone who also hits this, I fixed it by setting os env filters in my requirements.txt: https://peps.python.org/pep-0508/

`pywin32==303; platform_system=="Windows"`

**Comment by pedroteles1** [comment]
Ty so much!! It worked for me.

**Comment by danielAlex92** [comment]
Thank you, it worked for me too
> For anyone who also hits this, I fixed it by setting os env filters in my requirements.txt: https://peps.python.org/pep-0508/
> 
> `pywin32==303; platform_system=="Windows"`

**Comment by hemangjoshi37a** [comment]
cant install in ubuntu. Please help me.

**Comment by mhammond** [comment]
> cant install in ubuntu. Please help me.

This only works on Windows

**Comment by hemangjoshi37a** [comment]
Ok thanks for the helpful response.

**Comment by sajeshmorje** [comment]
https://github.com/mhammond/pywin32/issues/2131
please help here
