### ISSUE TITLE
Try re-install pywin32

### ISSUE THREAD

**Issue by greenhandzdl** [mhammond/pywin32#1740]
Note that issues in this repository are only for bugs or feature requests in the pywin32.

**If you need support or help using this package, please follow [these instructions](https://github.com/mhammond/pywin32/blob/master/README.md#support)** - support or help requests will be closed without comment.

For all bugs, please provide the following information.

* Expected behavior and actual behavior.
Expectation: win32gui, win32ui and other libraries can be introduced
Actual:
` ` ` 
import win32gui
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: DLL load failed while importing win32gui: 找不到指定的程序。
` ` ` 
* Steps to reproduce the problem.

Problem1:
Prompt me when I use CONDA to reinstall (it has been uninstalled with PIP)
` ` ` 
# All requested packages already installed.
` ` ` 
However, when I perform the operation "uninstall", I am prompted
` ` ` 
Preparing transaction: done
Verifying transaction: failed
RemoveError: This operation will remove conda without replacing it with
another version of conda
` ` ` 
Problem2:
I still haven't solved the problem by installing the binary package in GitHub

* Version of Python and pywin32
` ` ` 
PS C:\Windows\system32> python --version
Python 3.9.5
` ` ` 
pywin32 version:301

**Comment by mhammond** [comment]
You will probably find there's an existing pywintypes39.dll installed somewhere on your system, and this is being found and used for the new version.

**Comment by greenhandzdl** [comment]
> You will probably find there's an existing pywintypes39.dll installed somewhere on your system, and this is being found and used for the new version.

But how to uninstall and reinstall? I don’t know the location at all, and I can’t remove pip and conda.

**Comment by elbakramer** [comment]
> > You will probably find there's an existing pywintypes39.dll installed somewhere on your system, and this is being found and used for the new version.
> 
> But how to uninstall and reinstall? I don’t know the location at all, and I can’t remove pip and conda.

Try this: https://github.com/mhammond/pywin32/issues/1730#issuecomment-884849762

**Comment by greenhandzdl** [comment]
Thanks.
