### ISSUE TITLE
ModuleNotFound: win32com

### ISSUE THREAD

**Issue by sourabh-hegde** [mhammond/pywin32#1742]
I am trying to run a script which will trigger a python file. The python file is using win32com.client. From PyCharm everything is running fine. But when I run script it says no module called win32com. 
I am running via venv. The activate.bat file called inside script. Earlier script was executing fine. No changes in script has been made. Its something to do with win32com. In lib of venv both pypiwin32 and win32 are present and also pywin32.pth is available.
I have installed pypiwin32 and pywin32 already. I have tried out below solutions:

1. Upgraded pip to new version (21.2.3)
2. Tried with pip install of pypiwin32
3. Downloaded file from https://github.com/mhammond/pywin32/releases and I have 64bit(AMD64) on win32
4. Also tried https://github.com/mhammond/pywin32 and installing via python Scripts/pywin32_postinstall.py -install
5. Added import os;os.environ["PATH"]+=(';'+os.path.join(sitedir,"pywin32_system32")) in pywin32.pth under the folder--\PythonVersion\Lib\site-packages\
6. Added enviroment variables by creating a PYTHONPATH environment variables, and append the win32 and win32/lib path
7. Tried with import sys sys.path.append('\\PythonVersion\\lib\\site-packages\\win32') sys.path.append('\\PythonVersion\\lib\\site-packages\\win32\\lib') 

I am on Windows 64bit machine.
But still the issue is same and somehow I am not able to resolve. Can anyone please help with this?

**Comment by mhammond** [comment]
Please see https://github.com/mhammond/pywin32/blob/master/README.md#support
