### ISSUE TITLE
Pywin32 - Could not find a version that satisfies the requirement pywin32==301

### ISSUE THREAD

**Issue by annemaryjose** [mhammond/pywin32#1745]
Note that issues in this repository are only for bugs or feature requests in the pywin32.

**If you need support or help using this package, please follow [these instructions](https://github.com/mhammond/pywin32/blob/master/README.md#support)** - support or help requests will be closed without comment.

For all bugs, please provide the following information.

trying to build a docker image and it says Could not find a version that satisfies the requirement pywin32==301

docker build image

*python 3.7.11 and pywin32 301

If i try pip install it says pywin32 301 is already installed!

**Comment by mhammond** [comment]
This package only works on Windows.

**Comment by annemaryjose** [comment]
I am on windows , however I found a fix . Thank you.

**Comment by AkimHR** [comment]
Hi, Annemaryjose what kind of fix did you find? i have the same error...
