### ISSUE TITLE
Rename 'master' branch to 'main'

### ISSUE THREAD

**Issue by mhammond** [mhammond/pywin32#1746]
I support why this is becoming the new default, and almost every other github repo I deal with has already made this jump, so we should too.

I'd welcome help here!

**Comment by LincolnPuzey** [comment]
I haven't done this before but Github has some docs on it.

https://github.com/github/renaming
https://docs.github.com/en/github/administering-a-repository/managing-branches-in-your-repository/renaming-a-branch

**Comment by alanoe** [comment]
What's the benefit of using "main" over "master" ? As long as it's clear for all developers, does it even matter? This seems to have very low priority to me.

**Comment by mhammond** [comment]
> What's the benefit of using "main" over "master" ?

Why do you even care? You appear to have never contributed, so it will have zero impact on you.

> IMHO this has very low priority.

I don't really care what priority you give to it, but you have absolutely no say in what priority others give it.

**Comment by mhammond** [comment]
> I haven't done this before but Github has some docs on it.

Wow - github sure made that easy - done.
