### ISSUE TITLE
upload  file   failed    from  selenium : not  support  Chinese 

### ISSUE THREAD

**Issue by chazhongbao** [mhammond/pywin32#1748]
useing selenium upload file：
![image](https://user-images.githubusercontent.com/43258262/130330343-55f26a40-83cb-48e3-a4c1-9ff803927d14.png)

after  upload:
![image](https://user-images.githubusercontent.com/43258262/130330165-dbf53ebe-b36a-436f-a7ef-79babff72c46.png)

python version：3.8
win32com version :  301

**Comment by mhammond** [comment]
Please see https://github.com/mhammond/pywin32/blob/master/README.md#support

**Comment by c384795430** [comment]
Sorry, I did not find useful information.
