### ISSUE TITLE
DLL load failed: The specified module could not be found. python 3.7.8

### ISSUE THREAD

**Issue by Turk3ysandwich** [mhammond/pywin32#1750]
i believe the problem is that the pywin32 version is 301-py3.9 when my python version is currently 3.7.8. i am using 3.7.8 for something specific so i cant just upgrade my python version. how can i change the version of pywin32?

For all bugs, please provide the following information.

* Expected behavior and actual behavior.
expected: use win32api to move mouse. actual: got dll load failed error

* Version of Python and pywin32
* 3.7.8, 301-py3.9

**Comment by mhammond** [comment]
I assume you mean pywin32 301-py3.8? I suggest you uninstall pywin32, look for any pywin32 related files that may remain on your system (eg, pywintypesXX.dll, maybe in your system32 directory etc), then install again.

**Comment by Turk3ysandwich** [comment]
The problem was fixed, but I can confirm it was 301-py**3.9**
