### ISSUE TITLE
Pywin32 and carriage return character in iPython REPL

### ISSUE THREAD

**Issue by marchinidavide** [mhammond/pywin32#1758]
Hi,

I noticed a strange behavior in my ipython repl before and after installing pywin32.
Before, I can paste multiple python lines in my reply and the character '^M' carriage return never appears.
After I install pywin32, if I paste multiple lines they all end with '^M'.

What am I doing wrong?

python version: 3.8.10
pywin32 version: 301
ipython version: 7.27.0

**Comment by mhammond** [comment]
I've no idea - you should probably open an ipython issue.
