### ISSUE TITLE
Applicaiton.Run does not work for Access.Application

### ISSUE THREAD

**Issue by dornech** [mhammond/pywin32#1759]
Hi there,
I need to call Office / VBA applications form a running Python script. While calling VBA from Python using Application.Run works with EXCEL, it does not work with ACCESS. What I do:
I link to the Office application via the win32com.client mechanism as usual and I can see the application object in the Python debugger. 
If I do an excelapp.Run('<EXCEL VBA UDF>") everything is fine.
If I do an accessapp.Run('<ACCESS VBA UDF>") it throws an error -2147352562 which FormatMessage states is an issue with the number of parameters. But that cannot be the case as the UDF has no parameter and I do not pass any (additional) parameter.
BTW I simulated this accessapp.Run call from EXCEL in VBA and there it works.

I could not find any informaiton ont hat issue and I wonder if this is an issue related to pywin32?

**Comment by mhammond** [comment]
This is a [support request](https://github.com/mhammond/pywin32/blob/master/README.md#support)

**Comment by brochuJP** [comment]
> 

I use to be able to run an Access.application but it recently stop working.
