### ISSUE TITLE
ModuleNotFoundError: No module named 'pywintypes'

### ISSUE THREAD

**Issue by ccpoon** [mhammond/pywin32#1764]
For all bugs, please provide the following information.

Download the latest version : pywin32-301-cp39-cp39-win_amd64.whl
And installation via pip success.

* Expected behavior and actual behavior.

import win32com.client

and then run the above line encountered the caption error.

* Steps to reproduce the problem.
import win32com.client

and then run the above line encountered the caption error.

Use IDE : Spyder 5.1.5

* Version of Python and pywin32
Python : 3.9.7
pywin32 : 301

**Comment by raedrizqie** [comment]
import pythoncom
import win32com.client

**Comment by mhammond** [comment]
I can't repro this, and I suspect the problem is that pywin32_postinstall.py wasn't run. Please feel free to reopen if you have more info.

**Comment by lipitb** [comment]
I resolved this with
Edit file: 
C:\Program Files\Python313\Lib\site-packages\pythoncom.py (Or other path for pythoncom.py)

Add:
import sys
sys.path.insert(1, r'C:\Program Files\Python313\Lib\site-packages\win32\lib')
sys.path.insert(1, r'C:\Program Files\Python313\Lib\site-packages\win32')

After:
import pywintypes
pywintypes.__import_pywin32_system_module__("pythoncom", globals())
