### ISSUE TITLE
pywin32==228 is giving error while deploying in heroku

### ISSUE THREAD

**Issue by Sara-cos** [mhammond/pywin32#1767]
Note that issues in this repository are only for bugs or feature requests in the pywin32.

**If you need support or help using this package, please follow [these instructions](https://github.com/mhammond/pywin32/blob/master/README.md#support)** - support or help requests will be closed without comment.

For all bugs, please provide the following information.

* Expected behavior and actual behavior.

* Steps to reproduce the problem.

* Version of Python and pywin32

**Comment by Avasam** [comment]
https://www.heroku.com/dynos
> The [Heroku Platform](https://www.heroku.com/platform) uses the container model to run and scale all Heroku apps. The containers used at Heroku are called “dynos.” Dynos are isolated, virtualized Linux containers that are designed to execute code based on a user-specified command.

**Comment by vernondcole** [comment]
As has been said a million times: pywin32 is a Windows only package. It
does not, can not, will never install on Linux. You must alter your
requirements file to conditionally install the package.
