### ISSUE TITLE
pip install pypiwin32

### ISSUE THREAD

**Issue by irfan-cpu** [mhammond/pywin32#1768]
Note that issues in this repository are only for bugs or feature requests in the pywin32.
#iam using pypiwin32 because if i use pip install pywin32 shows could not find a version that sattisfies the requirements
**If you need support or help using this package, please follow [these instructions](https://github.com/mhammond/pywin32/blob/master/README.md#support)** - support or help requests will be closed without comment.

For all bugs, please provide the following information.

* Expected behavior and actual behavior.
expected ='''pip install pypiwin32 
                   successfully installed '''

actual = '"pip install pypipwin32
                syntax error'''

* Steps to reproduce the problem.
* pip install pypiwin32
* #-------------------------error--------------------------
* Requirement already satisfied: pypiwin32 in c:\python\lib\site-packages (223)
Collecting pypiwin32
  Using cached pypiwin32-219.zip (4.8 MB)
    ERROR: Command errored out with exit status 1:
     command: 'C:\Python\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\ASUS\\AppData\\Local\\Temp\\pip-install-9vla8e7t\\pypiwin32_312f6502a2544f3589e546a5c9bc67b1\\setup.py'"'"'; __file__='"'"'C:\\Users\\ASUS\\AppData\\Local\\Temp\\pip-install-9vla8e7t\\pypiwin32_312f6502a2544f3589e546a5c9bc67b1\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\ASUS\AppData\Local\Temp\pip-pip-egg-info-shr18dve'
         cwd: C:\Users\ASUS\AppData\Local\Temp\pip-install-9vla8e7t\pypiwin32_312f6502a2544f3589e546a5c9bc67b1\
    Complete output (6 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\ASUS\AppData\Local\Temp\pip-install-9vla8e7t\pypiwin32_312f6502a2544f3589e546a5c9bc67b1\setup.py", line 121
        print "Building pywin32", pywin32_version
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/2b/ca/5c086c18de8f70222787b3e824e755b68d99272531522e77bb381d4f60c8/pypiwin32-219.zip#sha256=06d478295c89dbdd4187e1ac099bb8eab93c29e298bded4e2fbc77009287fa44 (from https://pypi.org/simple/pypiwin32/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement pywin32>=223 (from pypiwin32) (from versions: none)
ERROR: No matching distribution found for pywin32>=223

* Version of Python and pywin32
* python 3.10
* pywin32 - not installed

**Comment by fabiansald** [comment]
Hi! I got the same issue, using Windows 2019 and Python 3.10

**Comment by mhammond** [comment]
`pypiwin32` is the wrong package - you want `pywin32`
