### ISSUE TITLE
Missing constants: ShellExecuteEx SEE_MASK_*

### ISSUE THREAD

**Issue by NotWearingPants** [mhammond/pywin32#1769]
`ShellExecuteExA` accepts an `SHELLEXECUTEINFOA` structure with an `fMask` field, which is a combination of `SEE_MASK_*` flag constants. These constants are missing from `win32con.py`. [MSDN](https://docs.microsoft.com/en-us/windows/win32/api/shellapi/ns-shellapi-shellexecuteinfoa)

* Version of Python and pywin32

Python 3.9.6, pywin32==301

**Comment by mhammond** [comment]
They are in `win32com.shell.shellcon`
