### ISSUE TITLE
Python Windows Service does not start with pywin32-302 (windows server 2019)

### ISSUE THREAD

**Issue by zerokelvin-27315** [mhammond/pywin32#1771]
# Summary
After updating to pywin32 version 302,  a python 3.6 (also tested with python 3.8) windows services started failing with an error when started.
"Error 1053: The service did not respond to the start or control request in a timely fashion"

Rolling back to pywin32 version 301 does not have the issue.

# Steps to reproduce:
Using Windows_Server-2019 (I was using an EC2 instance) - I could not reproduce this issue on Windows 10.

1. Install pywin32 version 302
```
pip install pywin32==302
python C:\Python3\Scripts\pywin32_postinstall.py -install
```

2. Use the following code for testservice.py
```python
import win32serviceutil 
import win32service 
import win32event

class SmallestPythonService(win32serviceutil.ServiceFramework):
    _svc_name_ = "test service"
    _svc_display_name_ = "test service"

    def __init__(self, args):
        win32serviceutil.ServiceFramework.__init__(self, args)
        self.hWaitStop = win32event.CreateEvent(None, 0, 0, None)

    def SvcStop(self):
        self.ReportServiceStatus(win32service.SERVICE_STOP_PENDING)
        win32event.SetEvent(self.hWaitStop)

    def SvcDoRun(self):
        win32event.WaitForSingleObject(self.hWaitStop, win32event.INFINITE)

if __name__=='__main__':
    win32serviceutil.HandleCommandLine(SmallestPythonService)
```
3. Install the service
```powershell
python testservice.py install
```

4. Open service manager (services.msc) and start the "test service" service.
Note error: "Error 1053: The service did not respond to the start or control request in a timely fashion"

Expected behavior is that the service stars successfully.

**Comment by zerokelvin-27315** [comment]
Python3 is definitely in the path. As I said - rolling back and using the previous version (pip install pywin32==301 and run postinstall) worked without any other changes.

**Comment by zerokelvin-27315** [comment]
Trying to repro from scratch has revealed an important detail. It would seem this wheel is not supported on python 3.6. I'm not sure why I was able to install it previously, but on a fresh instance with Python 3.6, I get the following error when installing via pip: "pywin32 is in an unsupported or invalid wheel"

```powershell
PS C:\temp> python --version
Python 3.6.5

PS C:\temp> pip install pywin32==302
Collecting pywin32==302
  Using cached https://files.pythonhosted.org/packages/3c/a5/0acb70bd455a03da901d418e5f4fe4be99bbd762519193bbd3705bec0305/pywin32-302-cp36-cp36m-win_amd64.whl
Installing collected packages: pywin32
  Found existing installation: pywin32 301
    Uninstalling pywin32-301:
      Successfully uninstalled pywin32-301
  Rolling back uninstall of pywin32
pywin32 is in an unsupported or invalid wheel
```

Updating to Python 3.8 and installing seemed to work:
```
choco install python --version=3.8
```
```
PS C:\Users\Administrator> python --version
Python 3.8.0
PS C:\Users\Administrator> pip install pywin32==302
Collecting pywin32==302
  Downloading https://files.pythonhosted.org/packages/b1/e6/ddf43219ac2b2145b73bb7dc2163abbf0ea83a6d01ff7284b053eaf531e7/pywin32-302-cp38-cp38-win_amd64.whl (9.3MB)
     |████████████████████████████████| 9.3MB 3.3MB/s
Installing collected packages: pywin32
Successfully installed pywin32-302
```

**Comment by kxrob** [comment]
>  It would seem this wheel is not supported on python 3.6.
> ...
>   Using cached https://files.pythonhosted.org/packages/3c/a5/0acb70bd455a03da901d418e5f4fe4be99bbd762519193bbd3705bec0305/pywin32-302-cp36-cp36m-win_amd64.whl
> ```

This PyPI uploaded py3.6 wheel (.whl is just a zip file) indeed seems to be messy unlike the 3.8 one. It carries py3.10 DLLs in addition and e.g.  its `pythonservice.exe` wants to import `python310.dll` ...

You can use / try the wheel from the github CI artifacts (current commit https://github.com/mhammond/pywin32/actions/runs/1343774075 , which seems ok ) until the PyPI upload may be fixed. Those CI wheels just lack the PyWin32.chm help file, which you can copy form a PyPI wheel before running the postinstall, when needed.

**Comment by mhammond** [comment]
I've added some notes re services to https://github.com/mhammond/pywin32/blob/main/README.md#running-as-a-windows-service

**Comment by gdoermann** [comment]
I had this same issue and have been working on it for over 4 hours... I updated all the dlls and looked at the compiled directories and it was nothing like that! It comes down to making sure that if nothing is passed in, you start the application.  Update your service __main__ to be like the following and it worked for me!:
```
if __name__ == '__main__':
    if len(sys.argv) == 1:
        servicemanager.Initialize()
        servicemanager.PrepareToHostSingle(TestService)
        servicemanager.StartServiceCtrlDispatcher()
    else:
        win32serviceutil.HandleCommandLine(TestService)
```

**Comment by leolcao** [comment]
just share one unexpected reason to make this error. https://github.com/mhammond/pywin32/issues/2056#issuecomment-1821914810

**Comment by popy2k14** [comment]
> I had this same issue and have been working on it for over 4 hours... I updated all the dlls and looked at the compiled directories and it was nothing like that! It comes down to making sure that if nothing is passed in, you start the application. Update your service **main** to be like the following and it worked for me!:
> 
> ```
> if __name__ == '__main__':
>     if len(sys.argv) == 1:
>         servicemanager.Initialize()
>         servicemanager.PrepareToHostSingle(TestService)
>         servicemanager.StartServiceCtrlDispatcher()
>     else:
>         win32serviceutil.HandleCommandLine(TestService)
> ```

thx, that also worked for me!!!!!

**Comment by leolcao** [comment]
Just share the tool winsw(https://github.com/winsw/winsw) which can be used to wrap binary or script as windows service.
After practice, in overall, I find use an standalone toolj like winsw is better way than programming by using pywin32 like framekwork for such requirement.
