### ISSUE TITLE
Resolving conflicts between multiple installations of pywin32 w/ Python 3.8

### ISSUE THREAD

**Issue by davidkhess** [mhammond/pywin32#1787]
I'm using Python 3.8 embedded into a C++ application. I use pywin32 (version 301) within it to access some WMI information. I have pywin32 in a private venv which I "activate" using site.addsitedir(). That all works well.

When (for example) Anaconda is also installed on the same target Windows system as my C++ application and the user has put the Anaconda directory in their PATH, if the version of the pywin32_system32 DLLs in the Anaconda directory are incompatible with the other pywin32 .pyds in my private venv, things of course don't dynamically link correctly and I get an error dialog indicating that.

In Python 3.8 some changes were made to help manage these sorts of problems - in particular, on Windows, the PATH environment variable is no longer looked at when doing an import and searching for dependent DLLs. os.add_dll_directory() is used to add additional places to look for DLLs that are depended on by .pyds. Many projects (including pywin32) have adopted this function and use it on Windows to add folders with DLLs that are needed.

So, I was surprised when this was happening because I thought PATH should not be playing a factor here. I see in pywin32.pth how it ends up calling os.add_dll_directory() (via pywin32_bootstrap) which made me think it should be working.

I believe the issue is _win32sysloader. There appears to be (legacy?) code in pywin32 that uses this module which ends up calling LoadLibrary() directly and bypassing what Python is doing for imports in 3.8.  I think this use of LoadLibrary() results in the older PATH based lookup mechanism while Python 3.8 is using LoadLibraryExW with flags LOAD_LIBRARY_SEARCH_DEFAULT_DIRS | LOAD_LIBRARY_SEARCH_DLL_LOAD_DIR which ignores PATH.

I know there are bound to be a whole lot of reasons why this situation is the way it is, but I think this wouldn't have bit me if pywin32 started to rely on Python 3.8's load behavior (which is much safer now) or adopted the use of LoadLibraryExW() with the same flags.

Since the os.add_dll_directory from pywin32.pth wasn't helping me, I ended up copying the two pywin32_system32 DLLs next to my C++ .exe. LoadLibrary() looks next to the .exe before starting to search PATH so the Anaconda stuff no longer presents a problem. I guess an alternative would be to manually add my pywin32_system32 dir to the beginning of PATH. This might mean that rather than calling os.add_dll_directory on >= 3.8 or modifying the PATH on < 3.8, both os.add_dll_directory AND PATH modification should occur on Python >= 3.8 until this private use of LoadLibrary() is removed.

So, I don't have any solid recommendations as to what to do, but I thought this would be a good data point to report.

**Comment by mhammond** [comment]
> I believe the issue is _win32sysloader. There appears to be (legacy?) code in pywin32 that uses this module

Ironically, _win32sysloader isn't at all legacy and is actually trying to help this exact situation - it's used to ensure the "correct" `pywintypesXX.dll` and `pythoncomXX` are loaded. I believe that would be fine with LoadLibraryEx and those flags as it still handles the cases pywin32 cares about - mainly that system32 is still searched.
