### ISSUE TITLE
Programmatically debug excel vba module

### ISSUE THREAD

**Issue by awa5114** [mhammond/pywin32#1788]
Is there a way to set a breakpoint and *programmatically* debug an excel vba module using `pywin32`? So far, I've been able to connect to an open instance of excel, add a workbook, add a vba module and then inject from a text file into this module.

```
import win32com.client as win32
excel = win32.Dispatch("Excel.Application") # generates a com instance
excel.Visible = True
workbook = excel.Workbooks.Add()
xlmodule = workbook.VBProject.VBComponents.Add(1)

with open('test.bas') as fo:
    xlmodule.CodeModule.AddFromString(fo.read())

print('don')
```

I'm not sure how to then go about adding a breakpoint and then debug the module line by line. I know that `XL.Application.Run` can run the module for me, but I actually want to debug it through python. Any ideas?

**Comment by mhammond** [comment]
Please see https://github.com/mhammond/pywin32#support for support.
