### ISSUE TITLE
ImportError: DLL load failed while importing win32api: The specified procedure could not be found. [25960] Failed to execute script pyi_rth_win32comgenpy

### ISSUE THREAD

**Issue by lilianaarramalho** [mhammond/pywin32#1791]
When creating an exe with pyinstaller, the exe comes with this issue:

ImportError: DLL load failed while importing win32api: The specified procedure could not be found.
[25960] Failed to execute script pyi_rth_win32comgenpy

Python version:3.7
Pywin32 version:302

**Comment by mhammond** [comment]
See https://github.com/mhammond/pywin32/blob/main/README.md#the-specified-procedure-could-not-be-found--entry-point-not-found-errors
