### ISSUE TITLE
pyinstaller bundled app subproces.Popen venv python, venv python load pythoncom38.dll in _MEIxxxx dir

### ISSUE THREAD

**Issue by tshemeng** [mhammond/pywin32#1792]
I use pyinstaller to bundle an app, the app `subprocess.Popen` call the python.exe from the venv, however venv python does not load pythoncom38.dll at the `C:/Windows/System32`, but load the pythoncom38.dll at `%TEMP%/_MEIxxxxx/pythoncom38.dll`

When pythoncom38.dll version packaged by pyinstaller does not match the pywin32 version of venv, venv python will throw error Entry Point not Found
![Snipaste_2021-11-09_10-55-26](https://user-images.githubusercontent.com/8343797/140853480-56ef6680-1a9a-44dc-92af-22e63b2e7f87.png)

OS: Windows 10 x64
Python: Python 3.8.9 x64
Pywin32:
        - venv(pywin32==300)
        - pyinstaller venv(pywin32==302)

**Comment by tshemeng** [comment]
I found the code
![Snipaste_2021-11-09_10-59-11](https://user-images.githubusercontent.com/8343797/140853940-03d3a501-7a8f-400b-b120-ab74f644a234.png)

**Comment by tshemeng** [comment]
@mhammond yep, same problem, from one environment python call another python, the second python will inherit `pythoncom38.dll` path from the first.

**Comment by mhammond** [comment]
I suspect this will work better in build 303, but please reopen if it doesn't.
