### ISSUE TITLE
`win32clipboard.GetClipboardOwner()` produces `pywintypes.error` when the return value is `NULL` (valid)

### ISSUE THREAD

**Issue by lazy5f** [mhammond/pywin32#1796]
## Expected behavior and actual behavior

According to `GetClipboardOwner()`'s [Win32 API Doc](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getclipboardowner#return-value), the clipboard owner can be `NULL` and `win32clipboard.GetClipboardOwner()` would return `None` in that case.

But it produces `pywintypes.error` as follows:

```
Traceback (most recent call last):
  File "D:\...\agent.py", line 104, in <module>
    owner = win32clipboard.GetClipboardOwner()
pywintypes.error: (0, 'GetClipboardOwner', 'No error message is available')
```

## Reproduction

```py
win32clipboard.OpenClipboard()  # or `OpenClipboard(None)`
win32clipboard.EmptyClipboard()
win32clipboard.SetClipboardText('abc')
win32clipboard.CloseClipboard()

print(win32clipboard.GetClipboardOwner())
```

## [Relevant code](https://github.com/mhammond/pywin32/blob/main/win32/src/win32clipboardmodule.cpp#L524)

- AS-IS
  ```c
  HWND rc;
  Py_BEGIN_ALLOW_THREADS;
  rc = GetClipboardOwner();
  Py_END_ALLOW_THREADS;

  if (!rc)
      return ReturnAPIError("GetClipboardOwner");
  return PyWinLong_FromHANDLE(rc);
  ```
- TO-BE??
  ```c
  HWND rc;
  Py_BEGIN_ALLOW_THREADS;
  rc = GetClipboardOwner();
  Py_END_ALLOW_THREADS;

  return PyWinLong_FromHANDLE(rc);
  ```

**Comment by mhammond** [comment]
I think I should probably just update the documentation here - changing this will break existing code for no good reason. WDYT?

**Comment by lazy5f** [comment]
Yes. You're absolutely right. I could not think to such extent.

Then my solution would be to use `ctype.windll` like the following, which is not much deal:

```py
owner = windll.user32.GetClipboardOwner()
```

By the way, #759 seems similar to this issue. I think it is good to use `ctype.windll` in that case too.

**Comment by mhammond** [comment]
You could still do something like:
```
try:
  owner = win32clipboard.GetClipboardOwner()
except win32api.error as e:
  if e.winerror != 0:
    raise
  owner = None
```

**Comment by lazy5f** [comment]
Yes, I see. I missed `GetLastError()` point at this time. I should do like that. Thank you very much!

Best regards,

Byung-Hyun Ha

**Comment by mhammond** [comment]
Thanks, I updated the docs in ae69defad37100ff20aa97b7a2df6e85d9253e7d
