### ISSUE TITLE
Stub file not found for "win32con"

### ISSUE THREAD

**Issue by Avasam** [mhammond/pywin32#1800]
Note that issues in this repository are only for bugs or feature requests in the pywin32.

**If you need support or help using this package, please follow [these instructions](https://github.com/mhammond/pywin32/blob/master/README.md#support)** - support or help requests will be closed without comment.

For all bugs, please provide the following information.

* Expected behavior and actual behavior.
Type stubs to be available for win32con
* Steps to reproduce the problem.
Use PyLance/PyRight
`import win32con`
* Version of Python and pywin32
Pyhton 3.9, pywin32-301

**Comment by mhammond** [comment]
I don't know what this bug report means.

**Comment by Avasam** [comment]
It means that Pyright / Pylance can't find a type stub for `win32con`. Here's one autogenerated:
[`typings/win32con/__init__.pyi`](https://github.com/mhammond/pywin32/files/7560566/__init__.pyi.txt)

**Comment by mhammond** [comment]
win32con is just a .py file - it sounds like you need a bug against Pyright / Pylance rather than here.

**Comment by Avasam** [comment]
pyi are type stubs

> win32con is just a .py file - it sounds like you need a bug against Pyright / Pylance rather than here.

Actually from kaluluosi/pywin32-stubs , their PyPi page linked to here instead of their own project, making me think it was a monorepo.
