### ISSUE TITLE
pywintypes.py: DeprecationWarning: getargs: The 'u' format is deprecated. Use 'U' instead.

### ISSUE THREAD

**Issue by jiasli** [mhammond/pywin32#1802]
* Expected behavior and actual behavior.

No `DeprecationWarning` should be shown.

* Steps to reproduce the problem.

```py
> cat test_pywin32.py
def test_pywin32():
    import pywintypes

> pytest .\test_pywin32.py
===================================================== test session starts =====================================================
platform win32 -- Python 3.10.0, pytest-6.2.5, py-1.11.0, pluggy-1.0.0
rootdir: D:\cli\testproj
plugins: forked-1.3.0, xdist-2.4.0
collected 1 item

test_pywin32.py .                                                                                                        [100%]

====================================================== warnings summary =======================================================
test_pywin32.py::test_pywin32
  D:\cli\py310\lib\site-packages\win32\lib\pywintypes.py:54: DeprecationWarning: getargs: The 'u' format is deprecated. Use 'U' instead.
    found = _win32sysloader.GetModuleFilename(filename)

test_pywin32.py::test_pywin32
  D:\cli\py310\lib\site-packages\win32\lib\pywintypes.py:68: DeprecationWarning: getargs: The 'u' format is deprecated. Use 'U' instead.
    found = _win32sysloader.LoadModule(filename)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
================================================ 1 passed, 2 warnings in 0.13s ================================================
```

* Version of Python and pywin32

```
> python -V
Python 3.10.0

> pip list | Select-String pywin32

pywin32                                 302
```

**Comment by juliangilbey** [comment]
I'm seeing the same issue, but I don't have pywin32 installed and I'm not running on a Windows machine. There's some other underlying cause of this DeprecationWarning, but I don't know where it is.

**Comment by Tolker-KU** [comment]
I've done a bit of digging. This warnings seems to come from passing `"u"` as a format string to `PyArg_ParseTuple` here:
https://github.com/mhammond/pywin32/blob/7adb18f164ae7882d7ee95b4a38a726573a84f77/win32/src/_win32sysloader.cpp#L20-L31
and/or here:
https://github.com/mhammond/pywin32/blob/7adb18f164ae7882d7ee95b4a38a726573a84f77/win32/src/_win32sysloader.cpp#L49-L58
Which is [deprecated](https://docs.python.org/3/c-api/arg.html#strings-and-buffers). 

Actually solving it and making a PR is the next step

**Comment by liudonghua123** [comment]
I have the same warning, I use python 3.10. And the version of pywin32 installed is 303 which is the latest currently. I hope the new release which fixed this warning could release soon.
