### ISSUE TITLE
installer fails in 3.10-32

### ISSUE THREAD

**Issue by mhammond** [mhammond/pywin32#1805]
via email:

> The 32-bit Python 3.10 installed by python-3.10.0.exe creates registry key HKLM\SOFTWARE\Python\PythonCore\3.10-32.  Your 32-bit pywin32-302.win32-py3.10.exe installer looks for HKLM\SOFTWARE\Python\PythonCore\3.10, doesn't find it, and decides Python 3.10 is not installed.
> The 64-bit versions work correctly. 

Possibly complicated by the fact 3.10 no longer supports creating .exe installers, so we use 3.9 to build them 😭

**Comment by bvancil** [comment]
I can confirm the bug. As a workaround, I exported the HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Python\PythonCore\3.10-32 entries to a "python310-32.reg" file and find/replaced all "HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Python\PythonCore\3.10-32" to "HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Python\PythonCore\3.10". This will of course cause problems should I install 64-bit 3.10, but the installer worked fine after that.

**Comment by mhammond** [comment]
Thanks - I doubt I can reasonably fix this though, so I'm going to just stop distributing 32bit exe installers for 3.10 and up. At some point we will lose the installers for all new versions :(

**Comment by mhammond** [comment]
Which I did in b6391c880bef00c7cff93f917d76aebdbd4ed2d9.
