### ISSUE TITLE
Python call QPST to restore QCN failed: pywintypes.com_error: (-2147352567, 'Exception occurred.', (0, None, None, None, 0, -2147467259), None)

### ISSUE THREAD

**Issue by Carrie0647** [mhammond/pywin32#1806]
test code:
self.qpst = win32com.client.Dispatch("QPSTAtmnServer.Application")
self.software_download._FlagAsMethod("RestoreNV")
self.software_download._FlagAsMethod("GetErrorMessage")
...(check port status and QCN file)
self.software_download.RestoreNV(restore_path, spc, allow_esn_mismatch)  # restore the file
error_message = self.software_download.GetErrorMessage()

* Expected behavior and actual behavior.
Expected: error_message=0
actual behavior: in restore_nv
    self.software_download.RestoreNV(restore_path, spc, allow_esn_mismatch)  # restore the file
  File "<COMObject <unknown>>", line 2, in RestoreNV
pywintypes.com_error: (-2147352567, 'Exception occurred.', (0, None, None, None, 0, -2147467259), None)

* Steps to reproduce the problem.
pls see above test code

* Version of Python and pywin32
python version: 3.9.6
pywin32 version: 301
![QPST_restore_QCN_failure](https://user-images.githubusercontent.com/84497416/144394131-a431066d-74cf-4122-9876-ffb32a17b014.JPG)
Looking forward your reply, thank you!

**Comment by mhammond** [comment]
This is a problem in the COM object you are using, not pywin32. Please see https://github.com/mhammond/pywin32/blob/master/README.md#support
