### ISSUE TITLE
Python 3.10 - pywin32 v.303 -  ModuleNotFoundError: No module named win32ui

### ISSUE THREAD

**Issue by Example341** [mhammond/pywin32#1817]
I just updated python to 3.10.1 and now there is an import error with:
`import win32ui`

**Comment by mhammond** [comment]
How did you install pywin32? What is the exact error?

**Comment by DonLarry** [comment]
Maybe you should just run `python /path/to/your/venv/Scripts/pywin32_postinstall.py -install` (https://github.com/mhammond/pywin32#installing-via-pip)

**Comment by mhammond** [comment]
Let us know if you need more help!
