### ISSUE TITLE
Incorrect encoding in COM exception messages (UTF-8 not decoded)

### ISSUE THREAD

**Issue by panda-34** [mhammond/pywin32#1823]
if in python COM server I throw an exception with a non-ASCII message, e.g. `raise RuntimeError('ошибка')` the client receives `...  RuntimeError: РѕС�РёР±РєР°  ...` which is raw UTF-8 bytes reinterpreted in system codepage.
The error messages should be decoded from UTF-8 to wide chars
python 3.7 pywin32 303

**Comment by mhammond** [comment]
Any chance you could make a repro for this using one of the tests in win32com/test?

**Comment by panda-34** [comment]
You can insert this `raise` into any method of a com server and execute it. For example you can run a VB Script:

```
set o = CreateObject("Python.Interpreter")
o.Exec("raise RuntimeError('\u043E\u0448\u0438\u0431\u043A\u0430')")
```
you'll see the wrong encoding in error description

I have no means to debug but by looking at the source I believe the problem is around here:
https://github.com/mhammond/pywin32/blob/44afd86ba8485194df93234639243252deeb40d5/com/win32com/src/ErrorUtils.cpp#L83
description is converted by `PyWin_String_AsBstr` which converts from codepage, UTF-8 is never decoded

**Comment by mhammond** [comment]
great, thanks! I'll have a poke at this over the next week or 2.
