### ISSUE TITLE
An error is reported when the computer is unlocked

### ISSUE THREAD

**Issue by 1997shp** [mhammond/pywin32#1824]
For all bugs, please provide the following information.

* Expected behavior and actual behavior.
I used win32api.SetCursorPos(point) in the code After running for eight hours, it suddenly reported an error
    win32api.SetCursorPos(point)
pywintypes.error: (0, 'SetCursorPos', 'No error message is available')
I'm sure I didn't turn on the computer lock screen
I would like to know what else could lead to this problem
I hope to get your help

* Steps to reproduce the problem.
def demo(wait_ts, interval_time=1):
    """
    DEMO
    """
    import win32api,win32con
    import random

    x = win32api.GetSystemMetrics(win32con.SM_CXSCREEN)
    y = win32api.GetSystemMetrics(win32con.SM_CYSCREEN)

    for _ in range(wait_ts):
        move_x = random.randint(1, x)
        move_y = random.randint(1, y)
        point = (move_x, move_y)

        win32api.SetCursorPos(point)

        time.sleep(interval_time)

demo(wait_ts=28,800)

* Version of Python and pywin32
pywin32                   300
pywin32-ctypes            0.2.0
Python 3.7.9
win 10

**Comment by mhammond** [comment]
See https://github.com/mhammond/pywin32/blob/master/README.md#support
