### ISSUE TITLE
Negative value for ace.mask

### ISSUE THREAD

**Issue by silent-nekto** [mhammond/pywin32#1828]
Hello
I've got directory `c:\test\folder`, and try to read the DACL:
```
path = r'c:\test\folder'
info = win32security.GetNamedSecurityInfo(
    path,
    win32security.SE_FILE_OBJECT,
    win32security.DACL_SECURITY_INFORMATION
)
dacl = info.GetSecurityDescriptorDacl()
sddl = win32security.ConvertSecurityDescriptorToStringSecurityDescriptor(
    info,
    win32security.SDDL_REVISION_1,
    win32security.DACL_SECURITY_INFORMATION
)

count = dacl.GetAceCount()
for i in range(count):
    ace_info = dacl.GetAce(i)
    print(ace_info)
```
in output i see incorrect value:
```
...
((0, 27), -536805376, <PySID object at 0x00000000000C56F0>)
...
```

-536805376 = FFFFFFFFE0010000
but i am waiting
3758161920 = E0010000

windows 7x64
Python 3.8
pywin32 303

**Comment by mhammond** [comment]
pywin32 tends to create most numeric constants as signed ints to avoid having to "promote" the value to a long. Just add `(1 << 32)` to the value if you really want it as unsigned. Please see https://github.com/mhammond/pywin32#support if you have followup support questions.
