### ISSUE TITLE
Why is the version 303 of pywin32 call 'Build 303'

### ISSUE THREAD

**Issue by killerwhite** [mhammond/pywin32#1831]
The previous version call “Release XXX”.

Is that mean this version is not an official version？Does anyone knows what is the different between Build 303 and previous？

**Comment by mhammond** [comment]
Where did that terminology change? But 303 is an official build/release/whatever :)

**Comment by mhammond** [comment]
Oh, I see in "Releases", 302 and 303 changed to "Build" - I'll try and stick to "Release" in the future!
