### ISSUE TITLE
pywintypes.com_error when use the Range.Characters 

### ISSUE THREAD

**Issue by ep081106** [mhammond/pywin32#1832]
hi！
i want to change the color of some characters in a string in excel，such as change 'CDE' to the red font in “abCDEf”，i used the "Characters" in VBA and it works find, 
![46027734-A845-45f0-83DD-DF021F284DB9](https://user-images.githubusercontent.com/50546434/154256544-6b56f0d7-c8d9-47a0-89b5-960c64fe0cb3.png)
then i try to use the “Range("AK4").Characters（3，3）” but get the error ：“pywintypes.com_error: (-2147352573, '找不到成员。', None, None)”, 
![B320FED9-3D62-4e71-838D-F68FBC4A1A42](https://user-images.githubusercontent.com/50546434/154256565-fd89f8a3-54c7-4904-9b29-80d1938a935b.png)
or could you give me a better way to change the characters‘s color in a string？

**Comment by mhammond** [comment]
Please see https://github.com/mhammond/pywin32/blob/main/README.md#support
