### ISSUE TITLE
The file pywintypes37.DLL is put in Disk "C:\Windows\system32", but there is still an alarm, resulting in service startup failure

### ISSUE THREAD

**Issue by birdhan** [mhammond/pywin32#1835]
**** WARNING ****
The executable at "C:\Users\xxxxxxx\AppData\Local\Programs\Python\Python37\lib\
site-packages\win32\PythonService.exe" is being used as a service.

This executable doesn't have pythonXX.dll and/or pywintypesXX.dll in the same
directory. This is likely to fail when used in the context of a service.

The exact environment needed will depend on which user runs the service and
where Python is installed. If the service fails to run, this will be why.

NOTE: You should consider copying this executable to the directory where these
DLLs live - "C:\Windows\system32" might be a good place.
****

**Comment by mhammond** [comment]
Is python37.dll there too? The warning comes from https://github.com/mhammond/pywin32/blob/main/win32/Lib/win32serviceutil.py#L49-L57, so please try and work out why that's wrong on your machine?

**Comment by bachi76** [comment]
The problem exists and it doesn't work.
Same messages as above mentioned. I have no pythonXX.dll, but a pythoncomXX.dll (pythoncom39.dll). If I rename it to pythonXX.dll then the warning messages go away. However, the service still can't be started @mhammond

**Comment by mhammond** [comment]
You must have a pythonXX.dll - it's part of Python.
