### ISSUE TITLE
win32service: pythonX.dll or pythoncomXX.dll missing warning issued even if those DLLs are on the system path.

### ISSUE THREAD

**Issue by Wissperwind** [mhammond/pywin32#1840]
Hi,

Tody I updated my pywin32. After installing a service it printed a new warning that there are no pythonX.dll or pythoncomXX.dll files near the executable and that this could cause problems. It recommends to copy those files in the main python folder. But the files were already there in my case.
Could you please add a check weather your recommendation is already fullfilled? In that case there is no need to display a warning.

**Comment by Wissperwind** [comment]
```
Installing service Prostep-BP-Server-3

**** WARNING ****
The executable at "C:\Users\user\Downloads\testInstallation\psbp\python-windows\Lib\site-packages\win32\PythonService.exe" is being used as a service.

This executable doesn't have pythonXX.dll and/or pywintypesXX.dll in the same
directory. This is likely to fail when used in the context of a service.

The exact environment needed will depend on which user runs the service and
where Python is installed. If the service fails to run, this will be why.

NOTE: You should consider copying this executable to the directory where these
DLLs live - "C:\Users\user\Downloads\testInstallation\psbp\python-windows" might be a good place.
****

Service installed
```

**Comment by Wissperwind** [comment]
The dlls are already in the main python folder. So the warning is not needed.

**Comment by mhammond** [comment]
The check is made at https://github.com/mhammond/pywin32/blob/21f1e1f3ea225af7fb14f98939126677b9ed92ca/win32/Lib/win32serviceutil.py#L49-L57 - can you please try and see what is going wrong for you in that block?

**Comment by MedvedevSA** [comment]
Also faced the problem

**Comment by Wissperwind** [comment]
I missunderstood the reccomendation. You should not copy the dlls to the executable - bad things happen, I tried, - you should copy the executable to the dlls. After that the warning dissappears.
But to me this feels like monkey patching. I would prefere the version 301 where this was not necessary, there was no warning and it simply worked.

**Comment by mhammond** [comment]
I think it only worked on 301 if you used the .exe installer and installed it as an administrator? Actually, I think it will print the warning in that case even though it still works - I really should update that check to see if those DLLs are in SYSTEM32. IOW, I didn't actually change anything about how things were installed, just added the warnings due to it not working if it was installed that way.

**Comment by Wissperwind** [comment]
I installed it as administrator. I think this is standard with windows services. I also added my portable python to the windows path. To install it I used the python command. My script.py install.
My problem is, that I don't wan't to explain all my users, that they can safely ignore this message.
But as I understand what I have to copy to avoid this message, I can use the new version in the future.

**Comment by mhammond** [comment]
Can you please confirm the DLLs in question are in SYSTEM32? It seems like it should be relatively easy for the code generating the warning to also handle that case.

**Comment by mhammond** [comment]
(well, more precisely, in the directory returned by `win32api.GetSystemDirectory()`)

**Comment by Wissperwind** [comment]
No, there aren't in my case. I explain what we do:
We use a embedded / portable python and ship this to our customers.
The dlls are in the main folder of that portable python.
I tould every installation administrator to put the folder of the portable python at the bottom of the windows path. So there can be another python installation on the server for other applications. But ours is also in the path, just at the bottom.

I think the dlls were found in our installations, because they are in a folder that is in the windows path.

**Comment by mhammond** [comment]
> I think the dlls were found in our installations, because they are in a folder that is in the windows path.

Thanks! I'm not sure just checking the PATH will work for this use-case though, because the current PATH might not be the actual PATH for the service. I guess I could try and see what's on the "system" path but I was hoping to avoid that. I think I'll re-open this to handle that case though, but will probably not implement it myself.

**Comment by mhammond** [comment]
Added the system check in cdac5649051f2134c2da050a8a6df9b32a5342e8

**Comment by Wissperwind** [comment]
Sorry, I struggle afain to remove this warning. I use version at the moment.

- The portable python folder which includes the python310.dll in in windows path. The warning is still there.
-  The warning talks about an executable named "PythonService.exe". But in my win32 folder is only a pythonservice.exe
- I tried to copy the pythonservice.exe in the folder \Lib\site-packages\pywin32_system32 like recommended in the warning but the warning is still there.
- I tried to copy the pythonservice.exe in the main python folder near python.exe and python310.dll but the warning is still there.

What can I do to get rid if this warning when installing a service?

**Comment by mhammond** [comment]
It sounds like what you did should work - I can only suggest that you add some `print` statements to `win32serviceutil.py` to help diagnose.

**Comment by Wissperwind** [comment]
Ok, you are checking if files a and b or c and d exist:
```
a C:\...\python-windows\Lib\site-packages\win32\python310.dll
b C:\...\python-windows\Lib\site-packages\win32\pywintypes310.dll
c C:\WINDOWS\system32\python310.dll
d C:\WINDOWS\system32\pywintypes310.dll
```

They don't on my machine. the folder python-windows\Lib\site-packages\pywin32_system32 is not used in the check. So it doesn't change anything if I copy a file there.
found is C:\...\Lib\site-packages\win32\PythonService.exe

**Comment by Wissperwind** [comment]
```
**** WARNING ****
The executable at "C:\...\python-windows\Lib\site-packages\win32\PythonService.exe" is being used as a service.

This executable doesn't have pythonXX.dll and/or pywintypesXX.dll in the same
directory, and they can't be found in the System directory. This is likely to
fail when used in the context of a service.

The exact environment needed will depend on which user runs the service and
where Python is installed. If the service fails to run, this will be why.

NOTE: You should consider copying this executable to the directory where these
DLLs live - "C:\...\python-windows\Lib\site-packages\pywin32_system32" might be a good place.
****
```

**Comment by Wissperwind** [comment]
good is `C:\Users\...\python-windows\Lib\site-packages\pywin32_system32`

**Comment by mhammond** [comment]
Oh, sorry, this was changed recently via #1871, which I thought was in 304, but it looks like it was not. Do you mind seeing if replacing your copy of win32serviceutil with https://raw.githubusercontent.com/mhammond/pywin32/main/win32/Lib/win32serviceutil.py works better for you?

**Comment by Wissperwind** [comment]
Ok. Now the warning has changed:

```
**** WARNING ****
The executable at "C:\Users\...\python-windows\Lib\site-packages\win32\PythonService.exe" is being used as a service.

The service will need to find "python310.dll" and "pywintypes310.dll" in it's environment,
but we were unable to find these in locations we can safely predict.
We searched in:
 C:\WINDOWS\system32
 C:\Users\...\python-windows
 C:\Users\...\python-windows\Lib\site-packages\win32
and found:
 C:\Users\...\python-windows\python310.dll
 C:\Users\...\python-windows\Lib\site-packages\win32\python310.dll
Note that this warning will appear despite any files found in "C:\Users\...\python-windows"
as this may not be in the PATH that the service will see.
If the service does fail to run, not finding these files will be the reason.

You should consider copying this executable to the directory where these
DLLs live - "C:\Users\...\python-windows\Lib\site-packages\pywin32_system32" might be a good place.
****
```

You found python310.dll. Good. But I think you can also safely predict `C:\Users\...\python-windows\Lib\site-packages\pywin32_system32` because it's part of the warning text. And If you can safely predict this folder, why did you not found the pywintypes310.dll there?

**Comment by mhammond** [comment]
The problem is that when being run as a service, that directory will not be on the path. `C:\Users\...\python-windows\Lib\site-packages\win32` isn't on the path, but is the same directory as the executable - which is why we suggest copying the executable to `C:\Users\...\python-windows\Lib\site-packages\pywin32_system32` - that DLL will then be found next to the exe and it will be happy.

**Comment by mhammond** [comment]
IOW, the text "in locations we can safely predict." should probably say something like "in locations we can safely predict that the DLL will be found at runtime when being run as a service".

**Comment by mhammond** [comment]
I don't think so - did the path to the executable in the message (`The executable at "C:\Users\...\python-windows\Lib\site-packages\win32\PythonService.exe" is being used as a service.` in your example) change to the new path, or still pointing at the original? I suspect it still points at the original. If so, we probably need a new issue opened and in the meantime you could delete that original and see if that helps?

**Comment by Wissperwind** [comment]
Deleting the original makes the whole thing crash.

**Comment by mhammond** [comment]
Did you re-register after deleting it?

**Comment by Wissperwind** [comment]
Here is your OK check. Ife a and b exist or file c and d exist. This could never be true because pywintypes is shipped in the directory pywin32_system32.
```
a C:\...\python-windows\Lib\site-packages\win32\python310.dll
b C:\WINDOWS\system32\python310.dll
or
c C:\...\python-windows\Lib\site-packages\win32\pywintypes310.dll
d C:\WINDOWS\system32\pywintypes310.dll
```

I don't think that the copied executable is noticed by the software.

**Comment by Wissperwind** [comment]
What is re registering?

**Comment by mhammond** [comment]
re-register the service - the path to the exe is written to the registry as you install the service. IOW, delete the original, then re-run your script to install the service. Hopefully you see no warning and the service will start.

**Comment by Wissperwind** [comment]
I always do remove service and than install service and see if the warning appears. If I "move" the exe. So it is not in win32 anymore this happens:
```
Traceback (most recent call last):
  File "C:\Users\akilian\Downloads\testInstallation\psbp\python-windows\Lib\site-packages\win32\lib\win32serviceutil.py", line 114, in _LocatePythonServiceExe
    exeName = win32api.RegQueryValue(
pywintypes.error: (2, 'RegQueryValue', 'Das System kann die angegebene Datei nicht finden.')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\akilian\Downloads\testInstallation\psbp\python-windows\Lib\site-packages\win32\lib\win32serviceutil.py", line 132, in _LocatePythonServiceExe
    return win32api.SearchPath(None, exeName)[0]
pywintypes.error: (2, 'SearchPath', 'Das System kann die angegebene Datei nicht finden.')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\akilian\Downloads\testInstallation\psbp\resource\server\bpServer3\bpService3.py", line 40, in <module>
    win32serviceutil.HandleCommandLine(MyService)
  File "C:\Users\akilian\Downloads\testInstallation\psbp\python-windows\Lib\site-packages\win32\lib\win32serviceutil.py", line 915, in HandleCommandLine
    InstallService(
  File "C:\Users\akilian\Downloads\testInstallation\psbp\python-windows\Lib\site-packages\win32\lib\win32serviceutil.py", line 291, in InstallService
    exeName = '"%s"' % LocatePythonServiceExe(
  File "C:\Users\akilian\Downloads\testInstallation\psbp\python-windows\Lib\site-packages\win32\lib\win32serviceutil.py", line 45, in LocatePythonServiceExe
    found = _LocatePythonServiceExe(exeName)
  File "C:\Users\akilian\Downloads\testInstallation\psbp\python-windows\Lib\site-packages\win32\lib\win32serviceutil.py", line 138, in _LocatePythonServiceExe
    raise error(msg)
RuntimeError: PythonService.exe is not correctly registered
Please locate and run PythonService.exe, and it will self-register
Then run this service registration process again.
```

**Comment by Wissperwind** [comment]
This was an install command

**Comment by mhammond** [comment]
It looks like you will need to run the executable with no args after the copy and then re-install the service :(

**Comment by Wissperwind** [comment]
Ok, in this case it is easier to explain the admins which install my software, that they can ignore the warning that explain them that they first have to execute an executable.

**Comment by Wissperwind** [comment]
Or I use 302 or I just comment the warning code in my shippment.

**Comment by mhammond** [comment]
Sadly, that's not enough - if that warning shows up, the service will probably not work. You will need an environment where the service registers without that warning.

**Comment by mhammond** [comment]
I meant to say: I think the actual process here is:
* copy the exe
* run that exe with no args
* execute your service install script.
