### ISSUE TITLE
Makeypy doesn't start. Message: TypeError: 'float' object cannot be interpreted as an integer

### ISSUE THREAD

**Issue by Heribert17** [mhammond/pywin32#1842]
The problem occurs on my home and on my office PC.
Version: 
  Python 3.10.2
  pywin32                   303

I fixed it for me in file pythonwin\pywin\dialogs\list.py
I changed line 101 to create an int in the division

itemDetails = (commctrl.LVCFMT_LEFT, int(width / numCols), col, 0)

**Comment by mhammond** [comment]
I can't repro this - works fine locally (with 3.10) and on a test VM with a pip-installed 303 of 3.9.

**Comment by mhammond** [comment]
oh bugger - sorry, I commented in the wrong issue :)

**Comment by mhammond** [comment]
Thanks - fixed!
