### ISSUE TITLE
BUG: Access Violation on type checking

### ISSUE THREAD

**Issue by lydiym** [mhammond/pywin32#1845]
**Steps to reproduce**
```python
import win32evtlog

hand = win32evtlog.OpenEventLog(None, 'Application')
flags = win32evtlog.EVENTLOG_BACKWARDS_READ | win32evtlog.EVENTLOG_SEQUENTIAL_READ
logs = win32evtlog.ReadEventLog(hand, flags, 0)

log = logs[0]
print(type(log))
```

**expected result**
-> `<class 'PyEventLogRecord'>`

**actual result**
-> python critical error: `0xC0000005 Access Violation`

**affected python-pywin32 pairs**
- python version: `3.8.5`, pywin32 version: `228`
- python version: `3.10.3`,  pywin32 version: `303`

**something else**
- The behavior affects pycharm debugger and other tools, that automatically check types of objects.
- Strange workaround:
```python
log = logs[0]
print(log.Data) # secret sauce
print(type(log)) # it works
```

**Comment by mhammond** [comment]
fixed by #1846
