### ISSUE TITLE
.click function doesnt take coordinate

### ISSUE THREAD

**Issue by yagizzha** [mhammond/pywin32#1847]
wincap=WindowCapture(LAname)
hwnd=win32gui.FindWindow(None,wincap.windowname)
timer=time()

app = Application()  
app.connect(handle=hwnd)  # Access app's window object 
app_dialog = app.top_window() 
#app_dialog.minimize() 

while True:
    if time()-timer>1:
        print("Clicking?")
        app_dialog.click(button="Left", coords=(960, 540), double=True, absolute=False)
        timer=time()

when running this , instead of clicking the "(960, 540)" mentioned , it just clicks where my mouse is instead

**Comment by mhammond** [comment]
It sounds like you are struggling with some external app used via COM - see https://github.com/mhammond/pywin32/blob/main/README.md#support
