### ISSUE TITLE
app_dialog.send_keystrokes("{w down}") doesnt work

### ISSUE THREAD

**Issue by yagizzha** [mhammond/pywin32#1848]
from what i understand this is supposed to hold the key "down" until "{w up}" comes , but in this example it just presses and lifts key back up instantly

**Comment by mhammond** [comment]
I have no idea what this means - neither `app_dialog` nor `send_keystrokes` exist in this project. You might want https://github.com/mhammond/pywin32/blob/main/README.md#support?
