### ISSUE TITLE
file name contains brackets got converted to %5B and %5D

### ISSUE THREAD

**Issue by 300Zombies** [mhammond/pywin32#1851]
Hi, 

My docx file name contains brackets (`[` and `]`) and those brackets were changed to %5B and %5D after I convert the docx to pdf.

Is there any way to keep the brackets in file name after the convertion?

I've searched [Document.ExportAsFixedFormat method (Word)](https://docs.microsoft.com/en-us/office/vba/api/word.document.exportasfixedformat) and didn't find any solution.

* Version of Python and pywin32
Python v3.8.10, pywin32 v300

**Comment by mhammond** [comment]
https://github.com/mhammond/pywin32/blob/master/README.md#support
