### ISSUE TITLE
Source distributions on PyPI to help windows/arm64 installations

### ISSUE THREAD

**Issue by nsait-linaro** [mhammond/pywin32#1857]
Pywin32 doesn't provide any source distributions or binary wheel for windows/arm64 platforms so that means it cannot be installed using pip command.

It will be helpful if we can either publish the binary wheel for windows/arm64 platform or at least source distributions that can be compiled by pip and setuptools during installation.

https://pypi.org/project/pywin32/

**Comment by mhammond** [comment]
I'd rather not do source via pypi but do intend publishing arm versions there.

**Comment by nsait-linaro** [comment]
Thanks @mhammond
