### ISSUE TITLE
NTEventLogHandler - ServiceFramework - pywintypes.error: (5, 'RegCreateKey', 'Access is denied.')

### ISSUE THREAD

**Issue by skewty** [mhammond/pywin32#1867]
NTEventLogHandler always raises "Access is denied" error when using "Network Service" account in pywin32 ServiceFramework.

I had to implement this fix which surprisingly works.

# Work Around Code
```python
from contextlib import contextmanager

@contextmanager
def patched_add_source_to_registry():
    def try_add_source_to_registry(*args, **kwargs):
        try:
            original_add_source_to_registry(*args, **kwargs)
        except Exception:  # noqa
            servicemanager.LogErrorMsg(traceback.format_exc())

    import win32evtlogutil
    original_add_source_to_registry = win32evtlogutil.AddSourceToRegistry
    setattr(win32evtlogutil, "AddSourceToRegistry", try_add_source_to_registry)
    yield
    setattr(win32evtlogutil, "AddSourceToRegistry", original_add_source_to_registry)

class FooService(win32serviceutil.ServiceFramework):
    @classmethod
    def setup_logging(cls) -> logging.Logger:
        logger = logging.root  # alternatively: logging.getLogger(cls._svc_name_)
        logger.setLevel(logging.INFO)
        with patched_add_source_to_registry():
            logger.addHandler(logging.handlers.NTEventLogHandler(cls._svc_name_))
        return logger
```

# Error Stack Trace (Without Patch)
```
Traceback (most recent call last):
  File "C:\proj\fabric\doc\Example\samplewebservice.py", line 36, in try_add_source_to_registry
    original_add_source_to_registry(*args, **kwargs)
  File "C:\Python310\lib\site-packages\win32\lib\win32evtlogutil.py", line 37, in AddSourceToRegistry
    hkey = win32api.RegCreateKey(
pywintypes.error: (5, 'RegCreateKey', 'Access is denied.')
```
and the service never starts / is unable to start.

## Version Numbers
- pywin 303
- python 3.10.4

**Comment by mhammond** [comment]
It looks like you are just handling the fact that `win32evtlogutil.AddSourceToRegistry()` might fail - better options include (a) not calling in the first place - who is making that call? and (b) registering it from an account with the ability to modify the registry, such as an elevated command prompt.

**Comment by skewty** [comment]
`logging.handlers.NTEventLogHandler(cls._svc_name_)` makes that call.

**Comment by skewty** [comment]
So the suggestion / expectation is to not use `logging.handlers.NTEventLogHandler` in a Windows Service?

**Comment by skewty** [comment]
The service was installed (aka registered) using an elevated command prompt as suggested so (b) isn't a work around as thought.

**Comment by mhammond** [comment]
I'm not familiar with that. In general, calling `AddSourceToRegistry()` should only be called at service install time, where elevated permissions are already required. If that ends up being called as the service starts, then yeah, it's not going to work and your work-around might make sense. I don't know enough about that logging handler to know how it is designed to be used.

**Comment by skewty** [comment]
Here is the source code from CPython 3.10

```python
class NTEventLogHandler(logging.Handler):
    def __init__(self, appname, dllname=None, logtype="Application"):
        logging.Handler.__init__(self)
        try:
            import win32evtlogutil, win32evtlog
            self.appname = appname
            self._welu = win32evtlogutil
            if not dllname:
                dllname = os.path.split(self._welu.__file__)
                dllname = os.path.split(dllname[0])
                dllname = os.path.join(dllname[0], r'win32service.pyd')
            self.dllname = dllname
            self.logtype = logtype
            self._welu.AddSourceToRegistry(appname, dllname, logtype)
            self.deftype = win32evtlog.EVENTLOG_ERROR_TYPE
            self.typemap = {
                logging.DEBUG   : win32evtlog.EVENTLOG_INFORMATION_TYPE,
                logging.INFO    : win32evtlog.EVENTLOG_INFORMATION_TYPE,
                logging.WARNING : win32evtlog.EVENTLOG_WARNING_TYPE,
                logging.ERROR   : win32evtlog.EVENTLOG_ERROR_TYPE,
                logging.CRITICAL: win32evtlog.EVENTLOG_ERROR_TYPE,
         }
        except ImportError:
            print("The Python Win32 extensions for NT (service, event "\
                        "logging) appear not to be available.")
            self._welu = None
```

it is called in this line: `self._welu.AddSourceToRegistry(appname, dllname, logtype)`

**Comment by mhammond** [comment]
Well yes, I'd say that is broken. It should not assume that everyone who wants to log to the event log has the rights to register a new event log source, so registration should be split out from initialization.

**Comment by skewty** [comment]
I agree with you 100%. 

Can I / we perhaps include something in the docs to help others who might run into this?  The work around solution I created may prove valuable in the situation I present above and I can't think of a better way to solve it short of an upstream change in CPython.

**Comment by mhammond** [comment]
The upstream change is what makes the most sense. It's not clear where I could document that where you would have noticed it. None of the service or event log samples in pywin32 use that function. I'd suggest you report a cpython bug.
