### ISSUE TITLE
what version of Python?

### ISSUE THREAD

**Issue by dw-hydro** [mhammond/pywin32#1876]
Note that issues in this repository are only for bugs or feature requests in the pywin32.

**If you need support or help using this package, please follow [these instructions](https://github.com/mhammond/pywin32/blob/master/README.md#support)** - support or help requests will be closed without comment.

For all bugs, please provide the following information.

* Expected behavior and actual behavior.

* Steps to reproduce the problem.

* Version of Python and pywin32

**Comment by dw-hydro** [comment]
Trying to identify the correct install file. I've tried a few in release 304
When I run Python command line I get " 2.7.8.14 32 bit " but when I look at an application (ArcGIS Pro) that uses Python it says "3.7.11". It is this application that I need to employ pywin32. 

I went to the registry editor and it says 2.7 . So maybe I cannot use release 304.

Any suggestions of which install to use would be most helpful. Thank you.

**Comment by mhammond** [comment]
It sounds like you have a stand-alone Python 2 installed, which does not work with pywin32 300 and up (you would need version 228 for that). However, if ArcGIS uses Python 3.7 then this would work, but I've no idea how you would install it in their environment - you should either contact their support forums or follow the **bold instructions** in the very first comment in this issue.
