### ISSUE TITLE
could create COM objects from ctype.c_void_p in pythoncom?

### ISSUE THREAD

**Issue by thqby** [mhammond/pywin32#1882]
Some DLL export functions return `IDispatch*`. How to create COM objects through this.

**Comment by mhammond** [comment]
`pythoncom.ObjectFromAddress()` lets you do this.

**Comment by thqby** [comment]
@mhammond 
Is there a function to get the `IDispatch*` from the PyIDispatch object, currently I can only get it from the string returned by `obj.__str__()`.

**Comment by mhammond** [comment]
it looks like there is not.
