### ISSUE TITLE
issue with func [GetTickCount\GetLastInputInfo] wrong value

### ISSUE THREAD

**Issue by idanless** [mhammond/pywin32#1883]
Hi all

anyone know why suddenly all my servers  fail got those func  currently

i try play with ntp \ anti virus i didnt find the source why i got this result

**####windows 10\11 release######### - all ok**
win32api.GetTickCount() 409830718
win32api.GetLastInputInfo() 409830281
win32api.GetTickCount() 409831750
win32api.GetLastInputInfo() 409830281

**#####windows server 2019 VM EXSIX####**
win32api.GetLastInputInfo() 2613722203
win32api.GetTickCount() -1681243125
win32api.GetLastInputInfo() 2613722203
win32api.GetTickCount() -1681242109
win32api.GetLastInputInfo() 2613722203
win32api.GetTickCount() -1681241109
win32api.GetLastInputInfo() 2613722203
win32api.GetTickCount() -1681240093
win32api.GetLastInputInfo() 2613722203
win32api.GetTickCount() -1681239093
win32api.GetLastInputInfo() 2613728140

**Comment by mhammond** [comment]
https://github.com/mhammond/pywin32/blob/main/README.md#support
