### ISSUE TITLE
Missing endpoint to create PyCComboBox object

### ISSUE THREAD

**Issue by Itzsten** [mhammond/pywin32#1884]
pywin32 304 using Python 3.9

How am I supposed to create a PyCComboBox object? There does not seem to be a CreateComboBox function anywhere.
I have tried using ``CreateControl("COMBOBOX", ...)``, however it states that the CLSID is invalid.

While using CreateWindow may work, it does not provide the functionality and high levelness compared to the PyCComboBox object,
Regards.

**Comment by mhammond** [comment]
https://github.com/mhammond/pywin32/blob/main/README.md#support
