### ISSUE TITLE
Cannot install pywin32 with pip

### ISSUE THREAD

**Issue by phiradd** [mhammond/pywin32#1885]
I have tried installing pywin32 (304) with pip:
`pip install pywin32`

I get the following error message:
`ERROR: Could not find a version that satisfies the requirement pywin32 (from versions: none)
ERROR: No matching distribution found for pywin32`

I am using a clean winpython environment. python -V gives me:
`Python 3.8.12 (0089b4a7ab2306925a251b35912885d52ead1aba, Mar 16 2022, 13:51:04)
[PyPy 7.3.9 with MSC v.1929 64 bit (AMD64)]`

Please help as I really need to get this to work. Thank you!

**Comment by phiradd** [comment]
Strangely it worked with winpython version 3.10.0. So it seems to be some version incompatibilty.

**Comment by vernondcole** [comment]
Not only a version, but an implementation incompatibility.  You were
running "PyPy 7.3.9" which is a different implementation of the Python
language using a just-in-time compiler.
Pywin32 is intended for use with the CPython implementation, such as that
from python.org <https://www.python.org/downloads/>.
Operation under PyPy is not supported.
