### ISSUE TITLE
generated an exception: (-2147319779, '库没有注册。', None, None) library is not registred

### ISSUE THREAD

**Issue by brightAI2021** [mhammond/pywin32#1888]
Note that issues in this repository are only for bugs or feature requests in the pywin32.

**If you need support or help using this package, please follow [these instructions](https://github.com/mhammond/pywin32/blob/master/README.md#support)** - support or help requests will be closed without comment.

For all bugs, please provide the following information.

* Expected behavior and actual behavior.
using pywin32 convert docx, ppt, wps etc.. to pdf format
* Steps to reproduce the problem.
# Retrieve a single page and report the URL and contents
def convert_2_pdf(filename,output,convert_dict):

    try:

        sha1 = hashlib.sha1()
        sha1.update(filename.encode("utf-8"))
        sha1code = sha1.hexdigest()
        is_converted = file_operation.doc_is_converted(sha1code)
        if is_converted:
            #print('文档 %r 已经转为pdf' % (filename))

            return sha1code

        postfix = filename.split('.')[-1].lower()
        funcCall = getattr(Office2Pdf(output), postfix)
        funcCall(filename)
        convert_dict[sha1code] = 1
        #file_operation.gen_pdf_info(sha1code,1)
        return sha1code
    except Exception as exc:
        print('%r generated an exception: %s' % (filename, exc))
        convert_dict[sha1code] = 0
        #file_operation.gen_pdf_info(sha1code, 0)
        return sha1code

 with concurrent.futures.ThreadPoolExecutor(max_workers=5) as executor:
        # Start the load operations and mark each future with its URL
        future_to_file = {executor.submit(convert_2_pdf, filename, output,convert_dict): filename for filename in files}
        for future in concurrent.futures.as_completed(future_to_file):
            file = future_to_file[future]
            try:
                data = future.result()
            except Exception as exc:
                print('%r generated an exception: %s' % (file, exc))
                file_operation.gen_pdf_info(data, 0)

* Version of Python and pywin32
* python3.8 pywin32 303

**Comment by mhammond** [comment]
You even left the text "If you need support or help using this package, please follow [these instructions](https://github.com/mhammond/pywin32/blob/master/README.md#support) - support or help requests will be closed without comment." in-place. Please read it.
