### ISSUE TITLE
_fixup_sdk_dirs in setup.py will become redundant

### ISSUE THREAD

**Issue by zooba** [mhammond/pywin32#1897]
Just as an FYI, I submitted the patch for distutils/setuptools that will make this hack in your setup.py redundant:

https://github.com/mhammond/pywin32/blob/e1c0237a6897dbc4adbfda6470711fade43228b7/setup.py#L530

The PR is at https://github.com/pypa/distutils/pull/153 (and should go into `setuptools` after that) for reference.

I haven't tried, but I _believe_ the code in your setup.py will still work, and none of the asserts will trigger. So you may not notice anything at all (unless you happen to see that there are twice as many include/lib directories in the compiler commands). There's no good way to detect that it's running with a fixed setuptools, so I guess just be aware that if the asserts _do_ start triggering, it may be intentional and they can be relaxed a bit.

**Comment by mhammond** [comment]
Thanks for the heads-up Steve!

**Comment by mhammond** [comment]
pywin32's build will now fail unless setuptools is fairly recent, so once that lands, I'll just force a requirement on that new version. I'm sure you can imagine how much I want to kill some of the crazy stuff setup.py does :)

**Comment by kxrob** [comment]
#1936 includes removal of the _fixup_sdk_dirs() mechanism.

**Comment by Avasam** [comment]
@mhammond Should this have been closed by https://github.com/mhammond/pywin32/pull/1936 ?
