### ISSUE TITLE
win32api module does not exist

### ISSUE THREAD

**Issue by AkitotheExiled** [mhammond/pywin32#1906]
**Expected Behavior:**

1. Install pywin32 by using pip in a venv
2. Import win32api 
3. Able to use getCursorPos()

**Actual Behavior:**

1. Install pywin32 by using pip in a venv
2. Import win32api
3. Get module 'win32api' does not have getCursorPos() and module 'win32api' does not exist

**Steps to reproduce the problem**

1. Pip install pywin32 into venv
2. Run post_install and drag dlls into the venv\...\win32 and system32\...\win32
3. Attempt to run script that contains the lines to import win32api and using the win32api method getCursorPos()

`AttributeError: module 'win32api' has no attribute 'getCursorPos'
`

**Version of Python and pywin32**

Python Version: 3.10.5 64 bit
OS V: Windows 10 64 Bit
Pywin32 Version: 304(latest)

Python 3.10.5 is also added to system path and user variable path as well.  I recently was talking to @mhammond in a closed issue.  However, since that issue was from 2019 and was closed a long time ago.  I opened up a new issue since it is still happening in 2022.  Please feel free to advise, I'm sure its something that I'm not doing correctly.  Thanks for your time!

**Comment by mhammond** [comment]
> 3\. Get module 'win32api' does not have getCursorPos() and module 'win32api' does not exist

Both of those things can't be true! But you want `win32api.GetCursorPos()`
