### ISSUE TITLE
pywintypes.py:2: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses   import imp, sys, os

### ISSUE THREAD

**Issue by jaried** [mhammond/pywin32#1910]
Note that issues in this repository are only for bugs or feature requests in the pywin32.

**If you need support or help using this package, please follow [these instructions](https://github.com/mhammond/pywin32/blob/master/README.md#support)** - support or help requests will be closed without comment.

For all bugs, please provide the following information.

* Expected behavior and actual behavior.

No warnings

* Steps to reproduce the problem.
```
import imp,sys,os
```
* Version of Python and pywin32
python==3.8.8
pywin32==227

I read the following issue, the problem has been solved, why is it still appearing now?

https://github.com/mhammond/pywin32/issues/1256

**Comment by vernondcole** [comment]
That would be: because you, yourself, typed "import imp".

It has nothing to do with pywin32, which,  by the way, you are using an
obsolete version of.

**Comment by jaried** [comment]
import imp is not what I typed, but the second line of my native .\Lib\site-packages\win32\lib\pywintypes.py:
```python
# Magic utility that "redirects" to pywintypesxx.dll
import imp, sys, os
```
However, in your source code,
https://github.com/mhammond/pywin32/blob/main/win32/Lib/pywintypes.py#L2
```python
import importlib.util, importlib.machinery, sys, os
```
My `pywin32` is also upgraded to the latest version 227 that can be upgraded with `pip install pywin32 -U`, so how can I solve it?
