### ISSUE TITLE
I have multiple versions of Python installed. 3.1, 2.7 x64, and 2.7 x32. Can I install pywin32 on all of them by running each installer?

### ISSUE THREAD

**Issue by visusys** [mhammond/pywin32#1917]
My question is the title of this post.

My install locations:

`C:\Python\Python27`
`C:\Python\Python27x86`
`C:\Python\Python310`

My Python version strings:

`Python 2.7.18 (v2.7.18:8d21aa21f2, Apr 20 2020, 13:25:05) [MSC v.1500 64 bit (AMD64)] on win32`
`Python 2.7.18 (v2.7.18:8d21aa21f2, Apr 20 2020, 13:19:08) [MSC v.1500 32 bit (Intel)] on win32`
`Python 3.10.5 (tags/v3.10.5:f377153, Jun  6 2022, 16:14:13) [MSC v.1929 64 bit (AMD64)] on win32`

I want to side-by-side install pywin32.

Can I just run the following binaries below and be done with it?

`pywin32-228.win-amd64-py2.7.exe`
`pywin32-228.win32-py2.7.exe`
`pywin32-304.win-amd64-py3.10.exe`

If this is an inappropriate place to ask for help with this issue, feel free to close or delete. I just signed up for the mailing list so hopefully I can get my question answered there if nobody here provides an answer.

Thanks so much,
Jay

**Comment by xflatkds1** [comment]
On my system running multiple versions of python causes issues if it is in
path on windows. On Linux I personally don't have a clue.  System in
windows if in path on 3 versions seems to conflict from my experience with
it. Your primary python maybe in path and I took other versions out  and
run them only in the install directory's when installing using pip I cd to
that directory and use pip specific install
. Python 2.7 will have issues conflicts with 32 and 64bit vers I believe
not sure especially if in path. My be Hammond can better explain it to you,
my logic says I'm python and I'm confused.

**Comment by mhammond** [comment]
That should work fine and there should not be any 32/64 bit issues. The first on your PATH will obviously "win" in some cases, but you don't need python on your PATH in the first place. Python comes with the "py" installer, so something like `py -3.6-32 -m pip install pywin32` should magically do the right thing.

**Comment by mhammond** [comment]
> I just signed up for the mailing list

FWIW, I don't see any messages to the python-win32 mailing list about this, so if you think you sent one, something went wrong.

**Comment by xflatkds1** [comment]
32/64 bit if running 64 bit and 32 tries to run it I've had issues and
something written in 64 doesn't read right on 32 mixing at least in my case
doesn't seem compatible.  As I say it could be a issue I have .

**Comment by mhammond** [comment]
There shouldn't be any such issues - if you have something concrete then maybe we can help, but you haven't given me much to go on.
