### ISSUE TITLE
How can I use class like CFolderPickerDialog in my project?

### ISSUE THREAD

**Issue by BuffFly** [mhammond/pywin32#1919]
I need to use win32API create a dialog to select folder,in Microsoft docs,there is a class CFolderPickerDialog.but I can not find any class in win32ui like this,only CreateFileDialog.

How can I select folder with CreateFileDialog?or there is any class/func can do it?

I'm hopefully if anyone here provides some answer.

Thanks so much!

**Comment by kxrob** [comment]
There is 
`win32com.shell.shell.SHBrowseForFolder()`
win32ui / CFolderPickerDialog as far as it would do something else would require a PR (unlikely).
Normal support questions: https://github.com/mhammond/pywin32#support
