### ISSUE TITLE
pywin32 available for colab?

### ISSUE THREAD

**Issue by seq2193** [mhammond/pywin32#1921]
Note that issues in this repository are only for bugs or feature requests in the pywin32.

**If you need support or help using this package, please follow [these instructions](https://github.com/mhammond/pywin32/blob/master/README.md#support)** - support or help requests will be closed without comment.

For all bugs, please provide the following information.

* Expected behavior and actual behavior.

* Steps to reproduce the problem.

* Version of Python and pywin32

https://colab.research.google.com/drive/1HCTZYDE2qGmZaQNO86e3h79V008McTxV?usp=sharing
![44](https://user-images.githubusercontent.com/109962092/181577623-065dcf53-a7e6-44c6-b2e0-2ce4eccd5f6b.PNG)

In colab , it is not possible to install using the following command
!pip install pywin32
!pip install pypiwin32

Is there any solution please, thank you!

**Comment by vernondcole** [comment]
I have never heard of "colab", so I did a quick Google search, and found
the following:
"Colab is a Python development environment that runs in the browser using
Google Cloud."
As such, it is highly unlikely to be running on a Windows operating system,
so will never be able to run pywin32, which is Windows specific.

Also, "pypiwin32" (notice the "pi" in there) is an obsolete, unsupported
fork of pywin32.

In the unlikely event that you are actually running colab under Windows on
your local computer, you will most likely be using a packaged version of
Python, such as Anaconda.  They do not do a good job of keeping their
version of pywin32 up to date, and you will need to look in their package
library for a compatible version. The generally useful wheels in the PyPi
will not work with their custom builds of Python.

**Comment by mhammond** [comment]
Thanks Vernon!

**Comment by Mani2511** [comment]
How can we able to install it in collab is their any way?

**Comment by vernondcole** [comment]
No. As explained before, there is no way.

If you need pywin32 features in your program, you will need to install
Python on your own Windows computer. There is no way that a program running
on a cloud server somewhere can make Windows system calls on another
computer. (Unless some app is installed on the Windows machine to do that
remotely.)
