### ISSUE TITLE
Pywin32 on anaconda repo

### ISSUE THREAD

**Issue by albertino87** [mhammond/pywin32#1963]
Hi, what I'm asking here is not a feature request but just the update of pywin32 in the conda repo to the latest version for the 32bit version:
https://anaconda.org/anaconda/pywin32
I don't know if this the right place to ask for it but I couldn't fin any other place.
Many thanks
Regards

**Comment by mhammond** [comment]
Sorry, I've no idea how that package gets populated - I assume they just grab them from pypi, but you probably need to ask them.
