### ISSUE TITLE
Xlwings issue due to pywin32 and windows 

### ISSUE THREAD

**Issue by createrep** [mhammond/pywin32#1966]
Note that issues in this repository are only for bugs or feature requests in the pywin32.

**If you need support or help using this package, please follow [these instructions](https://github.com/mhammond/pywin32/blob/master/README.md#support)** - support or help requests will be closed without comment.

For all bugs, please provide the following information.

* Expected behavior and actual behavior.

We did automation using xlwings which performs XL calculation which used to work ing IBM-TM1( COGNOs -planning & analytics application) server.  but it is not working now. I can ran the same prog from command prompt but through TM1 or Pycharm. 

* Steps to reproduce the problem.* 
getting pywin32 errors, and excel file is not opening and not doing any operations 

* Version of Python and pywin32
python version - 3.9 
Pywin32 = 304 due to issue i also implemented - pywinpty =2.0.9
XLwings = 0.28.5 
Microsoft office version = MSO(16.0.5361.1000)

**Comment by createrep** [comment]
I saw latest release couple of hours before, can this issue resolve above problem - [Release 305](https://github.com/mhammond/pywin32/releases/tag/b305)

**Comment by mhammond** [comment]
If you need support or help using this package, please follow [these instructions](https://github.com/mhammond/pywin32/blob/master/README.md#support) - support or help requests will be closed without comment.

**Comment by createrep** [comment]
thanks for the quick revert but is above issue resolves my issue. kindly confirm
