### ISSUE TITLE
online documentation gone : https://mhammond.github.io/pywin32

### ISSUE THREAD

**Issue by dreamflow** [mhammond/pywin32#1968]
the online documentation is gone .

it was available at
https://mhammond.github.io/pywin32
and is linked on the pages
https://github.com/mhammond/pywin32
https://pypi.org/project/pywin32
behind the text "there's now an online version" .

could please this online documentation
be made available again .

**Comment by brian3johnson** [comment]
I encountered this issue a few minutes ago as well.

**Comment by Amourspirit** [comment]
Me too

**Comment by mhammond** [comment]
Worked it out, fixed now.
