### ISSUE TITLE
build fails using Visual Studio v17.4 Community Edition and Python 3.11

### ISSUE THREAD

**Issue by vernondcole** [mhammond/pywin32#1972]
As requested, this is a report from attempting to build pywin32 for Python3.11 using only free tools.

### Environment:

Edition	Windows 10 Pro
Version	22H2
Installed on	‎11/‎18/‎2022
OS build	19045.2251
Experience	Windows Feature Experience Pack 120.2212.4180.0

### Steps taken:

Install Python 3.11 from python .org for all users.
Install current version of Visual Studio Community Edition
Install Python development workload for above.
clone a fork of current master of pywin32 from github
reboot workstation
start VS command line

### console dump

`**********************************************************************
** Visual Studio 2022 Developer Command Prompt v17.4.1
** Copyright (c) 2022 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x64'

C:\Program Files\Microsoft Visual Studio\2022\Community>cd \Users\vcole\PycharmProjects\pywin32

C:\Users\vcole\PycharmProjects\pywin32>py setup.py install --user
Building pywin32 3.11.305.1
running install
running build
running build_py
running build_ext
-- distutils hack to expose all include & lib dirs
-- orig compiler.include_dirs: ['C:\\Program Files\\Python311\\include', 'C:\\Program Files\\Python311\\Include']
-- orig compiler.library_dirs: ['C:\\Program Files\\Python311\\libs', 'C:\\Program Files\\Python311', 'C:\\Program Files\\Python311\\PCbuild\\amd64', 'build\\temp.win-amd64-cpython-311\\Release']
copying build\temp.win-amd64-cpython-311\Release\win32/src\pywintypes311.lib -> build\temp.win-amd64-cpython-311\Release\pywintypes.lib
building 'perfmondata' extension
creating build\temp.win-amd64-cpython-311\Release\win32\src\PerfMon
"C:\Program Files (x86)\Windows Kits\10\bin\10.0.22000.0\x86\mc.exe" -h win32/src/PerfMon -r build\temp.win-amd64-cpython-311\Release\win32/src/PerfMon win32/src/PerfMon/PyPerfMsgs.mc
MC: Compiling win32/src/PerfMon/PyPerfMsgs.mc
"C:\Program Files (x86)\Windows Kits\10\bin\10.0.22000.0\x86\rc.exe" /fobuild\temp.win-amd64-cpython-311\Release\win32/src/PerfMon/PyPerfMsgs.res build\temp.win-amd64-cpython-311\Release\win32/src/PerfMon\PyPerfMsgs.rc
Microsoft (R) Windows (R) Resource Compiler Version 10.0.10011.16384` 

**<< long build output clipped here >>**

`LINK : warning LNK4075: ignoring '/MANIFESTUAC' due to '/MANIFEST:NO' specification
   Creating library build\temp.win-amd64-cpython-311\Release\win32/src/PerfMon\perfmondata.lib and object build\temp.win-amd64-cpython-311\Release\win32/src/PerfMon\perfmondata.exp
Generating code
Finished generating code
py.exe -mwin32verstamp --version=3.11.305.1 --comments=https://github.com/mhammond/pywin32 --original-filename=perfmondata.dll --product=PyWin32 --quiet build\lib.win-amd64-cpython-311\win32\perfmondata.dll
C:\Program Files\Python311\python.exe: No module named win32verstamp
** Failed to versionstamp the binaries.
** If you want to skip this step, pass '--skip-verstamp' on the command-line
error: command 'C:\\Windows\\py.exe' failed with exit code 1
`
### Comment

Did I miss installing a prerequisite, or is this a real failure?

NOTE: normal "pip install pywin32 --user" works correctly.

**Comment by vernondcole** [comment]
### Update:
after running:
`pip install pywin32 --user`
and
`sudo py -3.10 setup.py install --user`
**then**
`sudo py setup.py install`
ran without error.

So this will need further testing.

**Comment by kxrob** [comment]
This is a known chicken and egg  problem, thats why it says in the error msg:

> ** Failed to versionstamp the binaries. ** If you want to skip this step, pass '--skip-verstamp' on the command-line

As the CI build does:
https://github.com/mhammond/pywin32/blob/dcfd66ccbc27aeed26678cbd1213048f5381253e/.github/workflows/main.yml#L36

For putting the build version into each created extension DLLs some already working pywin32 is required ( `win32verstamp`, `win32api`).
`py.exe` is currently used and simply uses the highest installed Python ver - 3.11 here - hoping for the best but in your case that had no pywin32 so far. After your pip binary install, it had ...
Or first run install with skip, then again (after possibly cleaning the build dir) without skip to get verstamped DLLs.

The error message could perhaps say more on that.

I'm using a preliminary script which allows to run pywin32 directly from the sources & extensions build dir (kind of pseudo venv), even partial builds overlaying an existing install. Its mainly for easier debugging and testing small changes without a complete install dance. That or a similar simplified thing just for that limited purpose could be used in future to verstamp directly in one go on CI or a pristine machine.

**Comment by vernondcole** [comment]
Thank you. 
Good explanation.
If the error message had said "on the setup.py command line" there would have been no question. Unfortunately "the command line" is not sufficiently definitive. 
I will look at quick changes in documentation to keep others from falling into this rabbit hole.

**Comment by vernondcole** [comment]
I opened Pull Request #1976 to help the next person who tries this.

**Comment by mhammond** [comment]
Thanks! I'm closing this under the assumption that there's nothing else to do here, but please reopen if you think there is.
