### ISSUE TITLE
pywintypes.Time does not handle repeated hours during DST transition

### ISSUE THREAD

**Issue by plocharz-9livesdata** [mhammond/pywin32#1973]
When `pywintypes.Time` object is created on system with timezone that has `DST`, for example `EST` and `EDT` some information about actual time can be lost.

When `pywintypes.Time` is created during `DST` transition information about repeated hour is lost. As a result two different timestamps give the same result. In Python this is handled by `fold` argument in `datetime.datetime` object:
https://docs.python.org/3.10/library/datetime.html#datetime.datetime.fold

**Actual behavior**
Example run on system with timezone set to `New York` (`EDT` or `EST`):
```
In [1]: import pywintypes
In [2]: pywintypes.Time(1_667_717_461) == pywintypes.Time(1_667_713_861)
Out[2]: True      
```

**Expected behavior**
```
In [1]: import pywintypes
In [2]: pywintypes.Time(1_667_717_461) == pywintypes.Time(1_667_713_861)
Out[2]: False      
```

**Versions:**

`Python 3.10.7 (tags/v3.10.7:6cc6b13, Sep  5 2022, 14:08:36) [MSC v.1933 64 bit (AMD64)] on win32`
`pywin32==305`

**Comment by mhammond** [comment]
A pywin32 Time object is a `datetime.datetime` object, so in your specific example I'd suggest just using datetime. More generally though, when passing time values in to pywin32, it should be possible to construct that object with the fold attribute set. However, when pywin32 is returning values (so internally creates the object) I don't really see how it would be possible to conditionally set this attribute - and I doubt it makes sense to unconditionally set it, or datetime itself would unconditionally set it.

What do you suggest we do?

**Comment by plocharz-9livesdata** [comment]
The problem is that `win32file.SetFileTime` accepts `pywintypes.Time` instance, but when given `pywintypes.Time(1_667_713_861)` it sets file datetime to wrong value: `1_667_717_461`. Cannot use `datetime.datetime` in this case.

> I don't really see how it would be possible to conditionally set this attribute

I'm not sure if I understand you. I think the condition is: When dealing with repeated hour, set `fold` to `1`. Otherwise set to `0`.

**Comment by mhammond** [comment]
I guess my question is: why doesn't datetime itself set this attribute when it's dealing with a repeated hour? IOW, why doesn't datetime have something like `fold="auto"`, or just have `fold=1` when it detects this case? IOW, having this attribute be the responsibility of the caller implies to me that there will be times when it should not be set in this case.

But getting back to the point here, can you suggest a patch?

**Comment by mhammond** [comment]
hrm, I thought `win32file.SetFileTime` would take a datetime object?

**Comment by mhammond** [comment]
pywin32 should *accept* any `datetime` object, so `fold` can be specified. It will only return time objects without that attribute and I don't think there's anything we can do about that.
