### ISSUE TITLE
LocatePythonServiceExe function overwrites the path of pythonservice.exe with the incorrect one

### ISSUE THREAD

**Issue by yamakox** [mhammond/pywin32#1985]
Please delete the following line. The bad path of pythonservice.exe is stored into the Windows service registry value.

https://github.com/mhammond/pywin32/blob/e6e941c7cbebf45354fa94d2254d9b82e500d05a/win32/Lib/win32serviceutil.py#L46

**Comment by mhammond** [comment]
Ouch, yes, I see what you mean. I'll fix this soon, thanks.

**Comment by mhammond** [comment]
Fixed by d73b0200eba81fa551b90d15cf5da097f4197f8f

**Comment by yamakox** [comment]
Thank you very much for fixing this problem so quickly.
