### ISSUE TITLE
ModuleNotFoundError: No module named 'pythoncom'

### ISSUE THREAD

**Issue by Amembrino** [mhammond/pywin32#1998]
Note that issues in this repository are only for bugs or feature requests in the pywin32.

**If you need support or help using this package, please follow [these instructions](https://github.com/mhammond/pywin32/blob/master/README.md#support)** - support or help requests will be closed without comment.

For all bugs, please provide the following information.

* Expected behavior and actual behavior.

I'have install the pywin32 dependency via pip and via exe (i took the link from gitbub).
when i run my application the prompt gives me always  "ModuleNotFoundError: No module named 'pythoncom'". why?
on every page of stackoverflow they specify that installing pywin32  the issue  will disappear. 
I'm useing python on 32 bit 
* Version of Python and pywin32 305 32bit

**Comment by mhammond** [comment]
you probably need to run `pywin32_postinstall.py` as noted in the README.
