### ISSUE TITLE
How do I pass parameter to a property?

### ISSUE THREAD

**Issue by weiw11** [mhammond/pywin32#2000]
Using `Range.AddressLocal` as an example, I'm unable to pass `ReferenceStyle` using `Range.AddressLocal(ReferenceStyle=xlR1C1)` as `AddressLocal` is a property and not a method.

Trying to do so will raise the following TypeError:

> TypeError: 'str' object is not callable

**Comment by mhammond** [comment]
Is this a problem using Excel? See https://github.com/mhammond/pywin32#support

**Comment by weiw11** [comment]
I'm trying to figure out how we can pass multiple values to a property in python using the win32com package.

See VBA [Range.AddressLocal](https://learn.microsoft.com/en-us/office/vba/api/Excel.Range.AddressLocal) documentation.
