### ISSUE TITLE
UnregisterHotKey not implemented

### ISSUE THREAD

**Issue by Athanasius** [mhammond/pywin32#2004]
[UnregisterHotKey](https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-unregisterhotkey), the counterpart to [RegisterHotKey](https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-registerhotkey) (which is implemented in win32gui), doesn't appear to be implemented in pywin32 at all.

At least I can't find the string `UnregisterHotKey` anywhere in a git clone or in the shipped DLLs.

**Comment by Athanasius** [comment]
NB: As I work through the ctypes code I'm migrating to pywin32 (to more easily fix the few issues we have on 64-bit Windows) I might find some other missing implementations as well.  Do you want an issue for each ?

**Comment by mhammond** [comment]
> Do you want an issue for each ?

I don't think one issue for every Windows function that's not in pywin32 makes much sense - there would be a massive number. There's also not much of a chance someone will implement them just because an issue is open - so really, a PR which implements them is what would be the most effective strategy.

**Comment by Athanasius** [comment]
That assumes that someone trying to use pywin32 has the skills and knowledge to correctly program an implementation *in the paradigm of pywin32*.

In this specific  case it seems strange to implement RegisterHotKey but not UnregisterHotKey.

**Comment by mhammond** [comment]
I agree, but it still takes a PR to get resolved.

**Comment by mhammond** [comment]
Fixed by #2185
