### ISSUE TITLE
linter is giving me an error on ImpersonateLoggedOnUser

### ISSUE THREAD

**Issue by hl1** [mhammond/pywin32#2006]
**Error:**
occurs when calling ImpersonateLoggedOnUser:
Argument of type "PyHANDLE" cannot be assigned to parameter "handle" of type "int" in function "ImpersonateLoggedOnUser"
  "PyHANDLE" is incompatible with "int"

**Steps to reproduce the problem**
check the code below using flake8 or any linter.
```python
import win32security
import win32con
import win32api

class Impersonate:
    def __init__(self, login, password, domain):
        self.domain = domain
        self.login = login
        self.password = password
        self.logon()

    def logon(self):
        self.handle = win32security.LogonUser(
            self.login,
            self.domain,
            self.password,
            win32con.LOGON32_LOGON_INTERACTIVE,
            win32con.LOGON32_PROVIDER_DEFAULT,
        )
        win32security.ImpersonateLoggedOnUser(self.handle)
```
pywin32==305
pywin32-ctypes==0.2.0
pywinpty==2.0.10
Python 3.8.1

**Comment by Avasam** [comment]
@mhammond I think you can close as this isn't a pywin32 issue
