### ISSUE TITLE
Issue while sending an email using win32

### ISSUE THREAD

**Issue by Pravin770** [mhammond/pywin32#2016]
Tried to send an outlook email using win32 for automation purposes. But the actual code seems not working.

I have 2 accounts logged in my outlook application. But need to send the emails from my primary account.

Here is the code I tried, The issue pops up while creating item

`import win32com.client`
`outlook=win32com.client.Dispatch("outlook.application")`
`outlook.CreateItem(0)`

Deleted the files under temp/gen_py but still the issue continues.

![image](https://user-images.githubusercontent.com/56891610/218734621-0a5b00c9-6a88-47af-a41e-700e59961ebf.png)

The expected output should be able to send the emails

**Comment by mhammond** [comment]
https://github.com/mhammond/pywin32#support
