### ISSUE TITLE
possible data corruption when deleting iTunes playlist items

### ISSUE THREAD

**Issue by ShortyCM** [mhammond/pywin32#2023]
Python 3.11.2 installed via MS Store
pywin32 305 via pip install

I've got a small script to create/maintain a randomized rolling 25-song playlist in iTunes which emulates some of the behaviour of an iTunes feature called Party Shuffle or iTunes DJ, which was removed from the iTunes app year ago. I've got its playback behaviour figured out and working except I seem to have come across a bug that seems to be causing data corruption somehow.  The script was erroring out occasionally with error messages like this:

`Traceback (most recent call last):
  File "C:\iTunesDJ-project\iTunesDJ-current working version-debugging4.py", line 138, in <module>
    playlist.AddTrack(song)
  File "<COMObject <unknown>>", line 2, in AddTrack
pywintypes.com_error: (-2147352567, 'Exception occurred.', (0, None, 'The track has been deleted.', None, 0, -1610350078), None)
Error printing song.Name:
`

I tried troubleshooting and added some print statements, and when it tried printing song.Name it gave a similar error:

`Traceback (most recent call last):
  File "C:\iTunesDJ-project\iTunesDJ-current working version-debugging.py", line 138, in <module>
    print("song.Name:", song.Name)
                        ^^^^^^^^^
  File "C:\Users\Clay\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\win32com\client\dynamic.py", line 628, in __getattr__
    ret = self._oleobj_.Invoke(retEntry.dispid, 0, invoke_type, 1)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pywintypes.com_error: (-2147352567, 'Exception occurred.', (0, None, 'The track has been deleted.', None, 0, -1610350078), None)`

I pared the script down so that the only things it was doing was connecting to iTunes to get the song library list and then doing a loop where it printed song.Name for random entries 1,000 times using "try" so it would continue if there was an error. This worked perfectly, so I was confused. I started adding commands back in one at a time until it finally started producing errors after a playlist.Tracks[0].Delete() command was executed.  I can now reproduce the problem very easily.  Only 1/20 trials ran without error once I reintroduced the delete command. 19/20 trials produced hundreds of errors in the 1,000 attempts in the loop.

Here's the script in question, with the errors happening during the while < 25 loop(s) when it attempts to execute a playlist.AddTrack(song) command:

edit: Hmm, listing the code doesn't seem to work very well. It can be downloaded from here. https://drive.google.com/file/d/1HMuZV7W1xDvYkkrbQ0O2wgJ782VLYqPa/view?usp=sharing

`
import os
import pywintypes
import time
import random
import win32com.client # Make sure to install the pywin32 library

os.system('cls')
print("Loading iTunes if not already loaded...")

# Set up the iTunes COM interface
itunes = win32com.client.Dispatch("iTunes.Application")

print("Loading music library...")

# Define the playlist name
playlist_name = "iTunes DJ"

# Check if the playlist already exists, and create it if not
playlist = None
for pl in itunes.LibrarySource.Playlists:
    if pl.Name == playlist_name:
        playlist = pl
        break
if not playlist:
    playlist = itunes.CreatePlaylist(playlist_name)

# Load all songs from the library and group them by rating
all_songs = itunes.LibraryPlaylist.Tracks
grouped_songs = {}
for song in all_songs:
    if song.Rating > 0 and not song.ExcludeFromShuffle:
        if song.Rating not in grouped_songs:
            grouped_songs[song.Rating] = []
        grouped_songs[song.Rating].append(song)

# Define the rating group weighting
rating_weighting = [20, 40, 40, 60, 60, 60, 80, 80, 80, 80, 100, 100, 100, 100, 100]

print("Checking for iTunes DJ playlist and creating if not found...")
# Fill the playlist with songs
print("Ensuring playlist contains at least 25 songs...")
while len(playlist.Tracks) < 25:
    time.sleep(1)
    # Select a random rating group
    rating = random.choice(rating_weighting)
    # Select a random song from that rating group
    song = random.choice(grouped_songs[rating])
    # Add the song to the playlist if it's not already there
    if song not in playlist.Tracks:
        try:
            playlist.AddTrack(song)
        except pywintypes.com_error as e:
            # I no longer care to see the errors because I can't do anything about them anyway.
            pass
            
# Set shuffle and repeat off for the current playlist
playlist.Shuffle = 0
playlist.SongRepeat = 0

# Start playback if necessary
print("Ctrl-C any time to halt this process, after which you can stop or exit iTunes.")
print("You can add or delete any songs you like in the iTunes DJ playlist and it'll get topped up as necessary.")
state = itunes.PlayerState
if itunes.PlayerState == 1 and itunes.CurrentPlaylist.Name == playlist_name:
    print("iTunes DJ is already playing...")
else:
    print("Beginning playback...")
    # Start playback
    playlist.PlayFirstTrack()

# Delete tracks above current song if necessary
current_track = itunes.CurrentTrack
current_index = 0
for i in range(0, playlist.Tracks.Count):
    #print(f"playlist.Tracks[{i}].Name: {playlist.Tracks[i].Name}")
    if playlist.Tracks[i].Name == current_track.Name:
        current_index = i
        break
#print("current_index:", current_index)
#input()
while current_index > 5:
    playlist.Tracks[0].Delete()
    current_index -= 1

print("First five track check completed...")

# Top up the playlist if anything was deleted
while len(playlist.Tracks) < 25:
    time.sleep(1)
    # Select a random rating group
    rating = random.choice(rating_weighting)
    # Select a random song from that rating group
    song = random.choice(grouped_songs[rating])
    #print("song: ", song.Name)
    #input()
    # Add the song to the playlist if it's not already there
    if song not in playlist.Tracks:
        try:
            playlist.AddTrack(song)
        except pywintypes.com_error as e:
            # I no longer care to see the errors because I can't do anything about them anyway.
            pass
            
# Watch for track changes and update the playlist accordingly
while True:
    # Having this set to 6 means it keeps 5 previously played songs above the currently playing track.
    current_track = itunes.CurrentTrack
    current_index = 0
    for i in range(0, playlist.Tracks.Count):
        #print(f"playlist.Tracks[{i}].Name: {playlist.Tracks[i].Name}")
        if playlist.Tracks[i].Name == current_track.Name:
            current_index = i
            break
    while current_index > 5:
        # Delete the top track if there are more than 25 tracks
        playlist.Tracks[0].Delete()
        current_index -= 1
        # Add a new song to the bottom of the playlist if there are less than 25 tracks
        while len(playlist.Tracks) < 25:
            time.sleep(1)
            # Select a random rating group
            rating = random.choice(rating_weighting)
            # Select a random song from that rating group
            song = random.choice(grouped_songs[rating])
            # Add the song to the playlist if it's not already there
            print("Topping up...", rating)
            if song not in playlist.Tracks:
                try:
                    playlist.AddTrack(song)
                except pywintypes.com_error as e:
                    # I no longer care to see the errors because I can't do anything about them anyway.
                    pass
            else:
                # I haven't seen this printed yet so it probably isn't a file-already-in-playlist failure.
                print("Song already in playlist. Skipping...")
            
    # Wait for a short time before checking again
    time.sleep(1)
`

**Comment by mhammond** [comment]
If you need support or help using this package, please follow [these instructions](https://github.com/mhammond/pywin32/blob/master/README.md#support)
