### ISSUE TITLE
How can i show a window without title bar？

### ISSUE THREAD

**Issue by Monday-Leo** [mhammond/pywin32#2024]
I just want to show a picture without tile bar. Any exmaples?
![YKK4GHIM~O6E5JE1QA8`$EH](https://user-images.githubusercontent.com/53975909/223028203-950e91f0-17ac-4b0e-a392-c9fea4784188.png)

**Comment by kcvinker** [comment]
@Monday-Leo 
You need to make sure you are not using these window styles 
WS_CAPTION, WS_SYSMENU, WS_MAXIMIZEBOX and WS_MINIMIZEBOX. These are the styles which causes a window to display the title bar.
