### ISSUE TITLE
Isapi does not work in python 3.11

### ISSUE THREAD

**Issue by sys2065** [mhammond/pywin32#2025]
Everything is working with python310, but with python311 w3wp.exe / application pool crashes in IIS. Crash happens in ucrtbase.dll

I was able to trace crash to PythonEng.cpp line 194: CEnterLeavePython celp; (Which calls PyGILState_Ensure())

Looking at line 93: PyGILState_Release(old_state);

Notice there is no call to PyGILState_Ensure() before that? I'm guessing Py_Initialize(); does that. No idea how this should work.

Anyway that "release" is not working in Python311.

I managed to fix it by replacing that "PyGILState_Release(old_state);" with "PyEval_SaveThread();"

Please check and make this change, atleast for python311, so we can start using it, thanks

**Comment by sys2065** [comment]
Is PythonEng.cpp line 61: "if (Py_IsInitialized())" ever true here?

Current code does this:

Py_Initialize();
old_state = PyGILState_UNLOCKED;
PyGILState_Release(old_state);

Tried google, but could not find clear answer if that is supported or not?

If no better suggestions, see attached patch
[patch.txt](https://github.com/mhammond/pywin32/files/10934813/patch.txt)

**Comment by SourCandy80** [comment]
Cant import in python 3.11 at all, failed to resolve from source, downgraded my project to 3.10 for stability just now 😭

**Comment by psimons2** [comment]
Wouldn't it be simpler to just always call PyGILState_Ensure():
```
diff --git a/isapi/src/PythonEng.cpp b/isapi/src/PythonEng.cpp
index 5d4d31fa..1cb99424 100644
--- a/isapi/src/PythonEng.cpp
+++ b/isapi/src/PythonEng.cpp
@@ -57,13 +57,8 @@ bool CPythonEngine::InitMainInterp(void)
     // ensure only 1 engine/thread initialises this only
     CSLock l(m_initLock);
     if (!m_haveInit) {
-        PyGILState_STATE old_state;
-        if (Py_IsInitialized())
-            old_state = PyGILState_Ensure();
-        else {
-            Py_Initialize();
-            old_state = PyGILState_UNLOCKED;
-        }
+        Py_Initialize();
+        PyGILState_STATE old_state = PyGILState_Ensure();
 #if PY_VERSION_HEX < 0x03070000
         PyEval_InitThreads();
 #endif
```

**Comment by sys2065** [comment]
```
Py_Initialize();
PyGILState_STATE old_state = PyGILState_Ensure();
```

Seems to hang, atleast for me. Py_Initialize() has lock and I think it must to be released before PyGILState_Ensure() is called.

PyEval_SaveThread() works because it (according to documentation) "Releases the global interpreter lock" and allows other threads to run.

It's also possible there is bug cpython and should be reported there.

**Comment by sys2065** [comment]
Attached minimal example to reproduce.

Compile&run with python310 -> OK

Compile&run with python311 -> Fatal Python error: init_threadstate: thread state already initialized

[test.txt](https://github.com/mhammond/pywin32/files/10951728/test.txt)

**Comment by psimons2** [comment]
You are correct that Py_Initialize() takes the GIL and so does PyGILState_Ensure(), so my version doesn't work.
There is quite a lot of changes in pylifecycle.c and pystate.c when comparing python 3.10 and 3.11.

**Comment by sys2065** [comment]
Response to this in cpython:
**"It needs to be fixed in pywin32, it should use PyEval_SaveThread instead of GIL state apis."**
->
To fix this simply apply patch attached to comment2, thank you

**Comment by mhammond** [comment]
> To fix this simply apply patch attached to comment2, thank you

But people above are reporting that doesn't work. Sadly I don't have IIS installed here, so I'm going to struggle to test this.

**Comment by mhammond** [comment]
Oops, I misunderstood which patch you referred to. I tried and failed to get IIS working to test this, but I applied this in 8b4eb226
