### ISSUE TITLE
Unable to install for Python 3.12

### ISSUE THREAD

**Issue by avylove** [mhammond/pywin32#2030]
* Expected behavior and actual behavior.

Pip returns `ERROR: No matching distribution found for pywin32` when trying to install for Python 3.12a4 on Windows

* Steps to reproduce the problem.

```console
> pip install pywin32
ERROR: Could not find a version that satisfies the requirement pywin32 (from versions: none)
ERROR: No matching distribution found for pywin32
```

* Version of Python and pywin32
Python 3.12.0a6

I realize 3.12 is still in alpha so the package may not be fully functional, but I would like to be able to install it in order to be able to identify potential issues with 3.12 early. For me this dependency is a couple levels down from what I'm trying to test.
I do see [3.12 support was added ](https://github.com/mhammond/pywin32/pull/1941), but I don't think there has been a release since then.

**Comment by MauBorre** [comment]
Hi, after a few days of researching I found that pip can't match the compatibility for Python 3.12 becouse there isn't yet an updated package in PyPI with the correspondent **wheel tags**.

Indeed the Python 3.12 support was added, but tags need to match the current environment for pip to install the module.

For example:

**Python 3.10 wheel tag**: pywin32-305-cp310-cp310-win_arm64.whl
**Python 3.12 wheel tag**: pywin32-305-cp312-cp312-win_arm64.whl

Until the package administrators upload Pywin32 with 3.12 compatibility tags you can simply change the tags in the file's name and pip will build the module.

Hope this helps!

**Comment by avylove** [comment]
It looks like pywin32 306 was released on March 25th and installs as expected.
