### ISSUE TITLE
SOLUTION FOR WIN 10 ImportError: DLL load failed

### ISSUE THREAD

**Issue by spacewalkingninja** [mhammond/pywin32#2039]
Hey guys,
I noticed this is quite common on win 10 so here's something of a hunch, a lot of **y'all** and myself too got pythons installed in the C:\Program Files\WindowsApps folder.
THe solution is IOBit unlocker so that u can copy the dreaded files from

C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\pywin32_system32

to

C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0

or whatever ur python is, which can be done by:

python3 -c "import os, sys; print(os.path.dirname(sys.executable))"

where python3 can be [python, py, could be whatever the python command in **ur** PATH] 

Then, once **u** got **d**is done now proceed **2**:

The only way I know of that works natively within Windows, is to use IObit Unlocker.

After it's installed, just right click on the file you wish to move and select the IObit Unlocker shell extension.

At the next screen, press the drop arrow next to 'Unlock' and select 'Unlock & Move' (or copy), browse to and select destination, and you're done.

https://answers.microsoft.com/en-us/windows/forum/all/windowsapps-folder-permissions/c1d41339-8cdf-4e38-98f2-63bd1c72c619

LETS END THIS MICROSOFT BAD DOMINATION OF THE CONTROL OF OUR PCS!
ALSO MAKE SURE U ASK GITHUB TO LKET US NOT USE 2FA! I HATE 2FA!

**Comment by Avasam** [comment]
This is not a pywin32 issue, nor a Microsoft or GitHub forum.

Although yes Microsoft is annoying with their default override of the python3 command. So here's a bit of help I can give you, and future readers: https://github.com/python/typeshed/pull/8798#discussion_r985281846
> Sure. Btw just FYI, you don't have to install it from the store (which I've had very bad experience with as well). You can disable that store alias by going under settings > App execution aliases, and disabling it. Then symlink python3 --> python, create a new alias, or copy+rename the python executable. But yeah, annoying just to get a consistent experience across OSes. ![image](https://user-images.githubusercontent.com/1350584/193471514-04050533-ca29-4da2-b1a8-ee3134b315ac.png).
