### ISSUE TITLE
win32file.GetBinaryType should support ARM64 binaries

### ISSUE THREAD

**Issue by randomascii** [mhammond/pywin32#2047]
While experimenting with ARM64 Chromium builds for Windows I tried using win32file.GetBinaryType() on an ARM64 Windows executable and it failed like this:

>>> import win32file
>>> win32file.GetBinaryType(r'out\arm64_release\base_unittests.exe')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
pywintypes.error: (193, 'GetBinaryType', '%1 is not a valid Win32 application.')

This can most easily be tested by downloading the ARM64 version of the sysinternals suite and running GetBinaryType on one of the binaries:

https://learn.microsoft.com/en-us/sysinternals/downloads/sysinternals-suite

This can be reproduced on x64 Windows - no ARM64 device is needed.

This is related to but separate from issue #1462

**Comment by sschukat** [comment]
The function is just a wrapper of the win32 API function [getbinarytype](https://learn.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-getbinarytypew) which does not support ARM executables. Hence there is nothing PyWin32 could do. 
Try pefile:
```python
import pefile
# https://learn.microsoft.com/en-us/windows/win32/debug/pe-format#machine-types
machinetypes = {0: 'IMAGE_FILE_MACHINE_UNKNOWN', 388: 'IMAGE_FILE_MACHINE_ALPHA', 644: 'IMAGE_FILE_MACHINE_AXP64', 467: 'IMAGE_FILE_MACHINE_AM33', 34404: 'IMAGE_FILE_MACHINE_AMD64', 448: 'IMAGE_FILE_MACHINE_ARM', 43620: 'IMAGE_FILE_MACHINE_ARM64', 452: 'IMAGE_FILE_MACHINE_ARMNT', 3772: 'IMAGE_FILE_MACHINE_EBC', 332: 'IMAGE_FILE_MACHINE_I386', 512: 'IMAGE_FILE_MACHINE_IA64', 25138: 'IMAGE_FILE_MACHINE_LOONGARCH32', 25188: 'IMAGE_FILE_MACHINE_LOONGARCH64', 36929: 'IMAGE_FILE_MACHINE_M32R', 614: 'IMAGE_FILE_MACHINE_MIPS16', 870: 'IMAGE_FILE_MACHINE_MIPSFPU', 1126: 'IMAGE_FILE_MACHINE_MIPSFPU16', 496: 'IMAGE_FILE_MACHINE_POWERPC', 497: 'IMAGE_FILE_MACHINE_POWERPCFP', 358: 'IMAGE_FILE_MACHINE_R4000', 20530: 'IMAGE_FILE_MACHINE_RISCV32', 20580: 'IMAGE_FILE_MACHINE_RISCV64', 20776: 'IMAGE_FILE_MACHINE_RISCV128', 418: 'IMAGE_FILE_MACHINE_SH3', 419: 'IMAGE_FILE_MACHINE_SH3DSP', 422: 'IMAGE_FILE_MACHINE_SH4', 424: 'IMAGE_FILE_MACHINE_SH5', 450: 'IMAGE_FILE_MACHINE_THUMB', 361: 'IMAGE_FILE_MACHINE_WCEMIPSV2'}
pe = pefile.PE(r"c:\Python39\python.exe")
print(machinetypes[pe.FILE_HEADER.Machine])
```

**Comment by randomascii** [comment]
Excellent suggestion. Thank you.

**Comment by Avasam** [comment]
Explanation and solution provided. Thanks @sschukat 

If you somehow absolutely need to use `win32file.GetBinaryType()`, then:
```py
import win32file
import pywintypes

try:
    win32file.GetBinaryType(r'out\arm64_release\base_unittests.exe')
except pywintypes.error:
    # Assume Arm64
```
