### ISSUE TITLE
issue when installing. (you would think that a major library developer would know the most simple method in python)

### ISSUE THREAD

**Issue by WestinFrancis** [mhammond/pywin32#2055]
TERMINAL OUTPUT:

pip install pypiwin32

Defaulting to user installation because normal site-packages is not writeable
Collecting pypiwin32
  Using cached pypiwin32-223-py3-none-any.whl (1.7 kB)
  Using cached pypiwin32-219.zip (4.8 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-wwk6b0o4/pypiwin32_27c2631a409a4a629dca67b60c308f22/setup.py", line 121
          print "Building pywin32", pywin32_version
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by mhammond** [comment]
`pypiwin32` is the wrong package - you just want `pywin32`
