### ISSUE TITLE
Problem not found pywin32 == 306

### ISSUE THREAD

**Issue by Fernando473** [mhammond/pywin32#2058]
I got this error when I trying to deploy on production. I am using django channels.
![image](https://github.com/mhammond/pywin32/assets/74788563/54ffaeed-ebb7-4f1b-a90b-4fe4266c1581)

I hope you can help me!.

**Comment by mhammond** [comment]
this only works on windows.

**Comment by mhammond** [comment]
You simply can't use this package anywhere other than windows - the reason it exists is to expose windows-only APIs. So you simply can't depend on it anywhere other than Windows.
