### ISSUE TITLE
pywintypes.com_error: (-2147467238, 'The server process could not be started because the configured identity is incorrect. Check the username and password.', None, None)

### ISSUE THREAD

**Issue by mallikarjun2912** [mhammond/pywin32#2059]
* When Am trying to dispatch vector Canoe application through the jenkins pipeline. Am getting this error
pywintypes.com_error: **(-2147467238, 'The server process could not be started because the configured identity is incorrect. Check the username and password.', None, None)**. FYI: The user name and password is correct. When I take the rdp its working and dispatching. When I close/release the rdp It doesn't working.

* Python version--> 3.11
* pywin32 version --> 306

**Comment by mhammond** [comment]
It sounds like you need to file a Canoe bug.
