### ISSUE TITLE
win32clipboard.OpenClipboard "Access is denied" when used with Ditto

### ISSUE THREAD

**Issue by VladimirAlexiev** [mhammond/pywin32#2060]
I use the [Ditto clipboard manager](https://ditto-cp.sourceforge.io/) (github: https://github.com/sabrogden/Ditto) all the time.
As reported at https://github.com/jkitchin/scimax/issues/282, when I try `win32clipboard.OpenClipboard()`,  I get error "Access is denied".
If I Disconnect Ditto from the clipboard, I don't get this error.

Steps to reproduce the problem:
* Install Ditto
* Save `html-clip-w32.py` as shown in https://stackoverflow.com/questions/76175244/how-to-put-formatted-text-on-clipboard-with-python-and-avoid-conflict-with-ditto
* `echo test | python html-clip-w32.py`

Versions:
Windows10 64bit with Cygwin
```
# uname
CYGWIN_NT-10.0
# which python
/c/Python310/python
# python -V
Python 3.10.4
# pip show pywin32
Name: pywin32
Version: 306
Summary: Python for Window Extensions
Home-page: https://github.com/mhammond/pywin32
Author: Mark Hammond (et al)
Author-email: mhammond@skippinet.com.au
License: PSF
Location: c:\python310\lib\site-packages
```

**Comment by mhammond** [comment]
See https://github.com/mhammond/pywin32#support (although in this case you probably want to search wider - this is a Windows question not a Python question)
