### ISSUE TITLE
PutHtml() doesn't work with Unicode chars

### ISSUE THREAD

**Issue by VladimirAlexiev** [mhammond/pywin32#2061]
(This is a repost of https://github.com/jkitchin/ox-clip/issues/2)

Expected behavior and actual behavior:
- I should be able to put HTML with Unicode chars on the clipboard
- If there are some Unicode chars, nothing is put on the clipboard (whereas it works with Unicode entities)

Steps to reproduce the problem:
- Save `html-clip-w32.py` as shown in https://stackoverflow.com/questions/76175244/how-to-put-formatted-text-on-clipboard-with-python-and-avoid-conflict-with-ditto. It's adapted from http://code.activestate.com/recipes/474121-getting-html-from-the-windows-clipboard, and shows author = "Phillip Piper", date= "2006-02-21"
- Save `test.html`:
```html
<p>
¡ ¢ £ ¤ ¥ ¦ § ¨ © ª « ¬ ­ ® ¯ ° ± ² ³ ´ µ ¶ · ¸ ¹ º » ¼ ½ ¾ ¿ À Á Â Ã Ä Å Æ Ç È É Ê Ë Ì Í Î Ï Ð Ñ Ò Ó Ô Õ Ö × Ø Ù Ú Û Ü Ý Þ ß à á â ã ä å æ ç è é ê ë ì í î ï ð ñ ò ó ô õ ö ÷ ø ù ú û ü ý þ ÿ
</p>

<p>
let's try "quotes" and long&#x2014;dash.
</p>
```
- run `python html-clip-w32.py < test.html`
- Nothing is put on the clipboard
- Remove the first paragraph and repeat the test
- This is put on the clipboard in HTML format: `let's try "quotes" and long—dash. `

Versions:
Windows10 64bit with Cygwin
```
# uname
CYGWIN_NT-10.0
# which python
/c/Python310/python
# python -V
Python 3.10.4
# pip show pywin32
Name: pywin32
Version: 306
```

**Comment by mhammond** [comment]
https://github.com/mhammond/pywin32#support

**Comment by VladimirAlexiev** [comment]
In another case, this source
```md
|  4 | Musée Royal d’Afrique centrale (MRAC)                       | Belgium |
```

comes out like this:
<html>
<body>
<b style="font-weight:normal;" id="docs-internal-guid-02459686-7fff-b285-c6c3-bf0335dfefa1"><div dir="ltr" style="margin-left:0pt;" align="left">

4 | MusÃ©e Royal dâ€™Afrique centrale (MRAC) | Belgium
-- | -- | --


</div></b>
</body>
</html>

**Comment by VladimirAlexiev** [comment]
Posted on mailing list, awaiting a response: https://mail.python.org/pipermail/python-win32/2023-May/014799.html
