### ISSUE TITLE
New Outlook version isn't working

### ISSUE THREAD

**Issue by PahlawanJoey** [mhammond/pywin32#2063]
```
olApp = win32.Dispatch("Outlook.Application")
olNS = olApp.GetNameSpace("MAPI")
```

This code is giving me `pywintypes.com_error: ('Operation unavailable'`

I noticed it only happens when I switch in outlook to the new version, when I switch back to the "old" version of outlook it works again.

![image](https://github.com/mhammond/pywin32/assets/98671646/20ec2127-f4e9-418c-9e2b-618658f9b6f0)

**Comment by kowabounga173** [comment]
Answer is there : https://stackoverflow.com/questions/77387302/send-email-with-python-in-windows-11-with-outlook-new

**Comment by Avasam** [comment]
So, probably not a pywin32 issue because there's no Component Object Model (COM) to use?
