### ISSUE TITLE
`CredGetSessionTypes` is not implemented in `win32credmodule.cpp`

### ISSUE THREAD

**Issue by gosselind1** [mhammond/pywin32#2067]
Hi, I was looking to write up a function to sanity check that credentials could be saved before attempting to write credentials. To accomplish this, I wanted to call  [`CredGetSessionTypes`](https://learn.microsoft.com/en-us/windows/win32/api/wincred/nf-wincred-credgetsessiontypes) to ensure the following:

1. `CRED_PERSIST_NONE` was not returned for the particular credential type.
2. `ERROR_NO_SUCH_LOGON_SESSION` was not produced as an error.

Both the error and constant are implemented in the current pywin32 source.

Looking at the API details for the function, it appears to not be a low-level "clean-up" function like [`CredFree`](https://learn.microsoft.com/en-us/windows/desktop/api/WinCred/nf-wincred-credfree), and therefore `CredGetSessionTypes` not being a part of the currently implemented source is either a bug or feature omission depending on perspective.

**Comment by Avasam** [comment]
Closed by #2232
