### ISSUE TITLE
Unexpected value of 'sys.executable' in windows service

### ISSUE THREAD

**Issue by ThisIsAlsoMyPassword** [mhammond/pywin32#2068]
I'm not sure if this is in fact related to the pywin32 package but I fail to find another reason for the behavior I am observing:

I have a windows service that is packaged into a single-file frozen binary using Pyinstaller. In this service I locate the folder of the executable using

``` Python
 Path(sys.executable).parent
```
There was never an issue with this and this would always return the folder in which the frozen binary resides.

Now I have the issue that on some systems after a fresh installation of the service, this statement returns the directory that is created by Pyinstaller's bootloader (/Windows/Temp/_MEIPASSxxx). The registered executable of the service is still the correct location of the frozen binary.

I'm not sure if this behavior was introduced with the overhaul of the service installation logic or if I just didn't see it before by chance. My only idea here is that the implementation of the windows process in pywin32 overrides `sys.executable´ at some point.

I'm sorry I can't provide steps to reproduce the problem because I fail to reproduce it myself on my machine.

Python: 3.11.2
pywin32: 305
pywin32-ctypes: 0.2.0
pyinstaller: 5.9.0
Windows: 11

Sorry for the limited information. I'm happy about any pointers.

**Comment by mhammond** [comment]
I'm fairly sure python never sets `sys.executable`, so I've no idea what could be going wrong.

**Comment by ThisIsAlsoMyPassword** [comment]
Sorry for letting this sit for so long. I expected to get more information that never came. Now I'm almost sure that on the system in question, the windows temp folder was changed to a different location than the default using environment variables. This broke my "freeze-detection". Totally unrelated to pywin32.
Sorry for bothering and thanks for the quick reply!
