### ISSUE TITLE
Python Wiki still points to old repos

### ISSUE THREAD

**Issue by csrabak** [mhammond/pywin32#2079]
In [https://wiki.python.org/moin/PythonWin](url) the suggested sites are [http://starship.python.net/crew/mhammond/win32/Downloads.html](url) and [https://sourceforge.net/projects/pywin32](url), the latter again informs the project has been migrated to here!

The last edit in the Wiki has been, it seems, in 2014, so I wonder if an update would be worthwhile and who can do it?

HTH

**Comment by Avasam** [comment]
That wiki has info about the procedure to edit content: https://wiki.python.org/moin/FrontPage#use and has mailing lists. You could try those.
