### ISSUE TITLE
VSS integration produces error when checking out a file

### ISSUE THREAD

**Issue by ghost** [mhammond/pywin32#209]
Python version 2.4.1.
Pythonwin version 203.

Below is the traceback seen in PythonWin.

The error can be worked around by going to the 
mentioned line and changing the code to fit the list in 
one line \(like xxx = \[IVSSVersion,\]\)

With Python 2.3.3. and PythonWin 203 for 2.3 it worked 
fine.

Traceback \(most recent call last\):
File "C:\Python24\Lib\site-
packages\pythonwin\pywin\framework\editor\vss.py", 
line 65, in CheckoutFile
mod = win32com.client.gencache.EnsureModule
\('\{783CD4E0-9D54-11CF-B8EE-00608CC9A71F\}', 0, 5, 0\)
File "C:\Python24\Lib\site-
packages\win32com\client\gencache.py", line 407, in 
EnsureModule
module = GetModuleForTypelib\(typelibCLSID, tlbAttr
\[1\], tlbAttr\[3\], tlbAttr\[4\]\)
File "C:\Python24\Lib\site-
packages\win32com\client\gencache.py", line 258, in 
GetModuleForTypelib
mod = \_GetModule\(modName\)
File "C:\Python24\Lib\site-
packages\win32com\client\gencache.py", line 629, in 
\_GetModule
mod = \_\_import\_\_\(mod\_name\)
File "C:\Python24\lib\site-
packages\win32com\gen\_py\783CD4E0-9D54-11CF-
B8EE-00608CC9A71Fx0x5x1.py", line 679
IVSSVersion,
\]
^
SyntaxError: invalid syntax

Reported by: astraujums

Original Ticket: "pywin32/bugs/209":https://sourceforge.net/p/pywin32/bugs/209

**Comment by Avasam** [comment]
@mhammond Trailing commas are no longer a SyntaxError in Python. This can be closed
