### ISSUE TITLE
Input using the numeric keypad does not work in build 221

### ISSUE THREAD

**Issue by Arkads-PL** [mhammond/pywin32#2090]
Input using the numeric keypad does not work in PyWin32 build 221 for Python 2.7 (ArcMap).

**Comment by mhammond** [comment]
Sorry, Python 2.7 is no longer supported (and even if it was, it would be a bug in arcmap, not pywin32)

**Comment by Arkads-PL** [comment]
This is no matter. build 221 has a reported bug. Please fix it.
