### ISSUE TITLE
win32clipboard increasing size of data when `SetClipboardData` used with `CF_DIB`

### ISSUE THREAD

**Issue by cmdvmd** [mhammond/pywin32#2096]
* Expected behavior and actual behavior.

  When copying an image to the clipboard using `CF_DIB`, the size of the data should be the same both before AND after copying the image. However, the size of the copied image is 1 byte larger.

* Steps to reproduce the problem.

  Download the [image.png](https://github.com/mhammond/pywin32/assets/55916643/5ad08bda-8469-44db-ad89-7dc74773b15f) file (or just any image file named `image.png`) and run the following Python script in the same 
  directory:
  ```python
  import win32clipboard

  with open('image.png', 'rb') as image:
      image_bytes = image.read()


  win32clipboard.OpenClipboard()

  win32clipboard.EmptyClipboard()
  win32clipboard.SetClipboardData(win32clipboard.CF_DIB, image_bytes)

  copied_bytes = win32clipboard.GetClipboardData(win32clipboard.CF_DIB)

  win32clipboard.CloseClipboard()

  print('Original image size:', len(image_bytes))  # 37257 bytes using attached file
  print('Copied data size:', len(copied_bytes))  # 37258 bytes using attached file
  ```

* Version of Python and pywin32
Python: 3.11.4
pywin32: 306

**Comment by Avasam** [comment]
Closed by #2184
