### ISSUE TITLE
Python 3.12: imp module removed

### ISSUE THREAD

**Issue by jemiele1** [mhammond/pywin32#2104]
The problem of the imp module being depreciated was supposedly corrected by #1503 

However, after reading this issue, I noticed the following comment from mhammond:

**I backed this out as it broke Python 2. I'm in the process of "formally" killing support for python 2, so I'll reapply it after that.**

It does not appear that the merge was ever reapplied. The use of the imp module is still present in version 306. Can someone please check into this soon? Python 3.12 is scheduled for release in a few months.

**Comment by johns1c** [comment]
### is this the same bug?

Using Python 3.12rc1 under windows 11 and it crashes when I run the either
```
from win32ctypes.pywin32 import pywintypes
```
or
```
from win32ctypes.pywin32 import win32cred
```
the exception seems to occur when the `__init__.py` issues the import for win32cred but the Python import functionality is so convoluted I cannot see where it occurs but it seems to be after it has pulled the bytecode from the cache

**Comment by Avasam** [comment]
@johns1c (without trying it out myself) I don't think so? The `imp` module is only used for axscript and isapi. See: https://github.com/mhammond/pywin32/pull/2113/files

**Comment by mhammond** [comment]
> Using Python 3.12rc1 under windows 11 and it crashes when I run the either
> 
> ```
> from win32ctypes.pywin32 import pywintypes
> ```
> 
> or
> 
> ```
> from win32ctypes.pywin32 import win32cred
> ```

This is a bug in whatever provides the `win32ctypes` module - which isn't pywin32. Whatever package that is probably is re-packaging an old version of pywin32.
