### ISSUE TITLE
A problem when piping the package

### ISSUE THREAD

**Issue by RedLeZ** [mhammond/pywin32#2115]
well idk how but the package seems to have a problem with a command and.... its print
Take a look ur self:
`Using cached pypiwin32-219.zip (4.8 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-hnt8slui/pypiwin32_9969884a4f824d8090b383b8c6bfba6e/setup.py", line 121
          **print "Building pywin32", pywin32_version
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?**
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.`

**Comment by mhammond** [comment]
`pypiwin32` is a fork of this package - you should be using plain-old `pywin32`

**Comment by RedLeZ** [comment]
THANK YOU ITS WORKS NOW
