### ISSUE TITLE
Add dpi_aware Parameter to win32gui.GetWindowRect for Actual Window Size

### ISSUE THREAD

**Issue by songyuc** [mhammond/pywin32#2117]
Hi, guys!
I'm suggesting the addition of a `dpi_aware` parameter to `win32gui.GetWindowRect` to accurately reflect the window size on high-DPI displays.

### Problem Description
When using `win32gui.GetWindowRect(hwnd)` to get the window size, the dimensions returned are not always accurate on high-DPI displays. This leads to some layout and rendering issues.

### Usage Scenario
This feature would be particularly useful for developers working on applications that need to adapt to different display settings, especially on high-DPI screens.

### Example Code
```python
# Current usage
rect = win32gui.GetWindowRect(hwnd)

# Suggested usage
rect = win32gui.GetWindowRect(hwnd, dpi_aware=True)

**Comment by mhammond** [comment]
`GetWindowRect()` just wraps the [Windows `GetWindowRect()` function](https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getwindowrect) - it has no such param, so it doesn't make sense to add it here.
