### ISSUE TITLE
pywintypes.com_error:  'Microsoft Excel', 'Document not saved. The document may be open, or an error may have been encountered when saving.', 'xlmain11.chm'

### ISSUE THREAD

**Issue by mominurr** [mhammond/pywin32#2125]
Traceback (most recent call last):
  File "D:\Web Scraping Project\excel_to_pdf\excel_to_pdf.py", line 99, in convert_sheet_to_pdf
    sheet.ExportAsFixedFormat(0, sheet_pdf_path)
  File "<COMObject <unknown>>", line 4, in ExportAsFixedFormat
pywintypes.com_error: (-2147352567, 'Exception occurred.', (0, 'Microsoft Excel', 'Document not saved. The document may be open, or an error may have been encountered when saving.', 'xlmain11.chm', 0, -2146827284), None)

**Comment by mhammond** [comment]
Please see https://github.com/mhammond/pywin32#support
