### ISSUE TITLE
No matching distribution found for pywin32==306 python v 3.11.4

### ISSUE THREAD

**Issue by sajeshmorje** [mhammond/pywin32#2131]
Note that issues in this repository are only for bugs or feature requests in the pywin32.

**If you need support or help using this package, please follow [these instructions](https://github.com/mhammond/pywin32/blob/master/README.md#support)** - support or help requests will be closed without comment.

For all bugs, please provide the following information.

ERROR: Could not find a version that satisfies the requirement pywin32==306 (from versions: none)
ERROR: No matching distribution found for pywin32==306

I am getting above error when i try to deploy webapi to azure web app. I have observed when i have installed azure-identity (pip install azure-identity), pywin32 gets added into requirements.txt (after freeze cmd). i have also tried to upgrade pywin32 as per documentation but no success. I have also tried to install pip install pypiwin32, but still its failing

can you please help or guide?

* Expected behavior and actual behavior.

* Steps to reproduce the problem.

* Version of Python and pywin32

**Comment by vernondcole** [comment]
You have not included information about which operating system you are using. 
Usually, this error message occurs when installing on a Linux or other non-Windows system.
You should edit your requirements.txt file to look like 
`pywin32;sys_platform == 'win32' `
so that pip does not attempt to install pywin32 unless you are running on Windows.

**Comment by sajeshmorje** [comment]
@vernondcole 
thank you for reply, we are deploying FastApi in Azure Web App. I guess internally it uses docker
I am able to resole this issue simply by ust removing entry from requirements.txt of pywin32 == 306
