### ISSUE TITLE
Detected Virus Trojan:Win64/Malgent!MSR

### ISSUE THREAD

**Issue by FGiacobe** [mhammond/pywin32#2135]
Today 2023-10-04 I installed the pywin32 v306 package to generate an executable using the pyinstaller 6.0.0 package and during the process I received a warning that the win32 package contained a virus and then Microsoft Antivirus accused the virus " Trojan:Win64/ Malgent!MSR".

**Comment by mhammond** [comment]
That's a false positive - unfortunately it probably means someone *did* create a virus using pyinstaller/pywin32 and they added an overly broad signature to their database.
