### ISSUE TITLE
ImportError: DLL load failed while importing win32crypt

### ISSUE THREAD

**Issue by JustLmr** [mhammond/pywin32#2140]
**the error here is giving an error when importing the win32crypt module I have done almost everything I can do to help please** 

his error:
```
Microsoft Windows [Version 10.0.22621.2428]
(c) Microsoft Corporation. Tüm hakları saklıdır.

C:\Users\Emire\Desktop\malware\build\exe.win-amd64-3.11>scx.exe
Traceback (most recent call last):
  File "C:\Users\Emire\AppData\Local\Programs\Python\Python311\Lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 124, in run
    module_init.run(name + "__main__")
  File "C:\Users\Emire\AppData\Local\Programs\Python\Python311\Lib\site-packages\cx_Freeze\initscripts\console.py", line 16, in run
    exec(code, module_main.__dict__)
  File "scx.py", line 17, in <module>
ImportError: DLL load failed while importing win32crypt: Belirtilen modül bulunamadı.

```

Setup.py:
```
from cx_Freeze import setup, Executable

build_exe_options = {
    "includes": ["pywin32"],
}

setup(
    name="myscript",
    version="1.0",
    description="My Script",
    options={"build_exe": build_exe_options},
    executables=[Executable("myscript.py")]
)
```

**Comment by mhammond** [comment]
If it works for you with a plain Python + pywin32 install I suspect something will be wrong in your freeze environment - ie, that you might not be trying to load the win32crypt.pyd you think you are.

**Comment by Avasam** [comment]
That being said, I do have questions about your project being called "malware" and trying to freeze it into an executable file.

**Comment by Avasam** [comment]
Punting this off as a `cx_Freeze` issue. There's [many other related issues](https://github.com/mhammond/pywin32/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+cx_Freeze+) anyway.
