### ISSUE TITLE
Could not run library with newest version of outlook (December 2023)

### ISSUE THREAD

**Issue by agosmou** [mhammond/pywin32#2156]
* Expected behavior and actual behavior.
    - I couldnt run this library with the newest version of outlook

* Steps to reproduce the problem.
    1. Update Outlook to "Outlook(new)"
    2. run:
    ```python
    >> import win32com.client as client
    >> outlook = client.Dispatch("Outlook.Application")
    ```
    3. Program will hang after line 2.
    4. Revert Outlook(new) to Outlook
    5. Run the above commands successfully

* Version of Python and pywin32
    - `windows 10`
    - `pywin32 version 306`
    - `python version 3.11.0`

**Comment by EdiWil** [comment]
Same problem on my system resolved using:

[link stackoverflow.com](https://stackoverflow.com/questions/77387302/send-email-with-python-in-windows-11-with-outlook-new)
