### ISSUE TITLE
pywin32 installation issue 

### ISSUE THREAD

**Issue by justincletus** [mhammond/pywin32#2157]
Note that issues in this repository are only for bugs or feature requests in the pywin32.

**If you need support or help using this package, please follow [these instructions](https://github.com/mhammond/pywin32/blob/master/README.md#support)** - support or help requests will be closed without comment.

For all bugs, please provide the following information.

* Traceback (most recent call last):
  File "service.py", line 10, in <module>
    import win32serviceutil
  File "C:\Users\vboxuser\pythonProg\venv\lib\site-packages\win32\lib\win32serviceutil.py", line 9, in <module>
    import win32service, win32api, win32con, winerror
ImportError: DLL load failed while importing win32service: The specified module could not be found.

* Steps to reproduce the problem.
pywin32 is installed in global level
* Version of Python and pywin32
* python 3.8

**Comment by mhammond** [comment]
> File "C:\Users\vboxuser\pythonProg\venv\lib\site-packages\win32\lib\win32serviceutil.py", line 9, in
...
> pywin32 is installed in global level

Services and virtual envs are not compatible - your service exists in a directory under your user. It's not clear exactly when you are getting this traceback (ie, when starting the service or installing it) nor what version of pywin32 you have, so this specific problem might not be directly related, but you will still have problems in a virtualenv.

Please follow the "these instructions" link you included in your report for support.
