### ISSUE TITLE
DispatchEx("PowerPoint.Application")  error

### ISSUE THREAD

**Issue by LvYyLong** [mhammond/pywin32#2159]
DispatchEx("PowerPoint.Application")

It can be executed with ordinary permission

If you run it with administrator rights

PowerPoint:(-2146959355, 'Server failed to run ', None, None)

**Comment by LvYyLong** [comment]
Is it not possible to run as administrator

**Comment by mhammond** [comment]
This is an issue with powerpoint, not with pywin32.
