### ISSUE TITLE
Regarding pywin32=306 compatibility with python 

### ISSUE THREAD

**Issue by GT-OP** [mhammond/pywin32#2172]
I am not able to deploy my website on vercel it shows this error

%%
Error: Command failed: pip3.9 install --disable-pip-version-check --target . --upgrade -r /vercel/path0/requirements.txt
--
06:09:03.085 | ERROR: Ignored the following versions that require a different python version: 8.19.0 Requires-Python >=3.10; 8.20.0 Requires-Python >=3.10
06:09:03.085 | ERROR: Could not find a version that satisfies the requirement pywin32==306 (from versions: none)
06:09:03.085 | ERROR: No matching distribution found for pywin32==306
%%

I want to know whether python 3.11.4 is compatible with pywin32=306 or not if not then which version is compatible

**Comment by mhammond** [comment]
pywin32 only works on Windows.
