### ISSUE TITLE
Cannot install pywin32! 

### ISSUE THREAD

**Issue by ideepthinv** [mhammond/pywin32#2191]
Note that issues in this repository are only for bugs or feature requests in the pywin32.

**If you need support or help using this package, please follow [these instructions](https://github.com/mhammond/pywin32/blob/master/README.md#support)** - support or help requests will be closed without comment.

For all bugs, please provide the following information.

* Expected behavior and actual behavior.

* Steps to reproduce the problem.

* Version of Python and pywin32

**Comment by ideepthinv** [comment]
RuntimeError

  Unable to find installation candidates for pywin32 (306)

  at /usr/local/lib/python3.10/site-packages/poetry/installation/chooser.py:73 in choose_for
       69│ 
       70│             links.append(link)
       71│ 
       72│         if not links:
    →  73│             raise RuntimeError(f"Unable to find installation candidates for {package}")
       74│ 
       75│         # Get the best link
       76│         chosen = max(links, key=lambda link: self._sort_key(package, link))
       77│ 

Cannot install pywin32.

**Comment by mhammond** [comment]
pywin32 only works on Windows.

**Comment by ideepthinv** [comment]
What is an alternate lib I can use?

**Comment by vernondcole** [comment]
There is no alternate, as such. Any package which attempts to import pywin32 on a non-Windows system is in error.
