### ISSUE TITLE
Feature Request: Add Python API for PrintWindow Function

### ISSUE THREAD

**Issue by songyuc** [mhammond/pywin32#2195]
Hello `pywin32` maintainers,

I am reaching out to discuss the potential inclusion of a Python API for the `PrintWindow` function within the `pywin32` library.

### Background
I am currently working on a Windows automation testing project, which requires capturing screenshots of application windows. This functionality is crucial for validating the state of different UI elements and ensuring our applications are functioning as expected, especially when windows are minimized or not in the foreground.

### The Request
While `pywin32` provides a wide range of useful APIs for Windows interaction, it appears that `PrintWindow` is not currently one of them. The `PrintWindow` function is particularly useful because it can capture screenshots of a window without bringing it to the foreground, and this feature would greatly enhance our testing capabilities.

Therefore, I am kindly requesting the consideration of adding a Python API for the `PrintWindow` function to the `pywin32` library. This addition would be beneficial not only for my current project but I believe it would also be a valuable asset to many others in the community who face similar challenges.

### Alternative Solutions
I understand that we can currently use `ctypes` to call `PrintWindow` indirectly, but having a direct API through `pywin32` would simplify the process and reduce the boilerplate code required to achieve this functionality.

### Contribution
I am more than willing to contribute to the development of this feature if that would be helpful. I can provide use cases, sample code, or even assist with the implementation if given some guidance on how you would like it structured within the library.

I appreciate your time and consideration of this feature request, and I am looking forward to the possibility of contributing to this excellent project.

Best regards,
Yucheng Song

**Comment by mhammond** [comment]
Thanks for your interest. I think this would be a simple change, an addition to (probably) win32gui.i, plus ideally a trivial test.
