### ISSUE TITLE
Unable to install/load from wheel at run time

### ISSUE THREAD

**Issue by mubinskt** [mhammond/pywin32#2246]
For all bugs, please provide the following information:

## Expected behavior and actual behavior

The script at run time should be able to load/install Pywin32 package.

I am creating a virtual env at run time and then trying to install pywin32, it gets installed but i am not able to import/load the pywintypes out of it.

I see that the virtual env is created and it also has the pywin32 files in it still the script could not load the same.

Also I have tried to add the Virtual env path to the Environment paths still no luck, the attached file has the script. 

## Steps to reproduce the problem

1. Attached the stand alone script to load Pywin32 from a whl
2. the whl is local and already downloaded to a folder
3. if we run the script it should successfully import the pywin32 but it doesn't

```python

```

## System information

Python version and distribution: 3.10.5, 64 bit

pywin32 version: pywin32-306-cp310-cp310-win_amd64.whl

Installed from PyPI or exe installer: Wheel

Windows Version: 10.0.19045 build 19045

DLL locations:

[TeatPyWin32LoadCopy.zip](https://github.com/mhammond/pywin32/files/14978379/TeatPyWin32LoadCopy.zip)

**Comment by mhammond** [comment]
Our wheels do work fine - I can't guess what problem you are having though as there's only a .zip file here, not the 2 lines it should take to demonstrate the problem. How to use wheels in this way is outside the scope of this repo.
