### ISSUE TITLE
IDispatch = pythoncom.connect(IDispatch) pywintypes.com_error: (-2147221021, 'Operation unavailable', None, None)

### ISSUE THREAD

**Issue by gopinath0712** [mhammond/pywin32#2252]
Hi Team,
I am also facing this issue as listed below but above solutions not working
Someone pls help?

Issue: (Refer Screenshot)
File "C:\Users\SuperUser\AppData\Local\Programs\Python\Python312\Lib\site-packages\win32com\client\dynamic.py", line 84, in _GetGoodDispatch
IDispatch = pythoncom.connect(IDispatch)
pywintypes.com_error: (-2147221021, 'Operation unavailable', None, None)

Details:
Trying to run OPC Server simulation script using Python language

OS: Windows Server 2019
Python: Python 3.12.3 (64 bit)
<img width="1145" alt="Python Error1" src="https://github.com/mhammond/pywin32/assets/168803513/7c137cb4-02bb-4d7f-ae31-d10a3b74560e">

**Comment by mhammond** [comment]
This is your COM object throwing an error that it doesn't support the interface being requested. You need to talk to whoever supplies the OPC server.
