### ISSUE TITLE
where the fuck is win32crypt

### ISSUE THREAD

**Issue by FutureScrpts** [mhammond/pywin32#2296]
Exception has occurred: ModuleNotFoundError
No module named 'win32crypt'
  File "C:\Users\Adim\Downloads\Test\main.py", line 2, in <module>
    from win32crypt import CryptUnprotectData
ModuleNotFoundError: No module named 'win32crypt'

**Comment by CristiFati** [comment]
What about importing other modules: *win32api*, *win32file*, *win32gui,*, *win32ts*?

**Comment by FutureScrpts** [comment]
every one of the win32... ones it says `ModuleNotfoundError`

**Comment by CristiFati** [comment]
Could it be that *PyWin32* installation is corrupted (or maybe it's not even installed) for the *Python* instance you're using?
[\[SO\]: How to update pywin32 automatically? (@CristiFati's answer)](https://stackoverflow.com/a/49499867/4788546)
[\[SO\]: PyCharm doesn't recognize installed module (@CristiFati's answer)](https://stackoverflow.com/a/73363599/4788546)

**Comment by FutureScrpts** [comment]
i have reinstalled python more than 3 times to fix it and reinstalled this module manually even, no luck.

**Comment by CristiFati** [comment]
Maybe you're not launching the *Python* version that you think you are.
