### ISSUE TITLE
Does not install on Python 3.13

### ISSUE THREAD

**Issue by andy-maier** [mhammond/pywin32#2367]
Trying to install pywin32 on Python 3.13.0rc1 with pip results in the following error:

```
> pip install pywin32
ERROR: Could not find a version that satisfies the requirement pywin32 (from versions: none)
ERROR: No matching distribution found for pywin32
```
Full log, see https://github.com/zhmcclient/python-zhmcclient/actions/runs/10756922763/job/29830348232

I saw issue #2306, but that installs pywin32 from the repo and the symptom is different, so I created this new issue.

The issue could probably be solved by providing download archives on PyPI for Python 3.13, even without solving the other issues (setuptools based install deprecated, install dependency on verstamp).

## Expected behavior and actual behavior

pywin32 should install on Python 3.13.0

## Steps to reproduce the problem

1. Run "pip install pywin32", on Python 3.13.0-rc1 on Windows

## System information

Python version and distribution: CPython 3.13.0rc1 (Github Actions)
pip version: 24.2
pywin32 version: 306 (latest released version at the time of the issue)
Installed from PyPI or exe installer: PyPI
Windows Version: Microsoft Windows Server 2022 10.0.20348
DLL locations: ? (pywin32 cannot be installed to find out)

**Comment by Avasam** [comment]
Ref https://github.com/mhammond/pywin32/issues/2294#issuecomment-2271658861

A new release would bring Python 3.13 support for most scenarios. Missing #2311 & #2312 for complete support.

**Comment by bobzomer** [comment]
Would also love to see Python 3.13 supported!

**Comment by hugovk** [comment]
The full release of 3.13.0 final is in a couple of weeks, it would be great to have wheels uploaded before then:

https://peps.python.org/pep-0719/

The Release Manager has issued a [call to action](https://discuss.python.org/t/python-3-13-0rc2-3-12-6-3-11-10-3-10-15-3-9-20-and-3-8-20-are-now-available/63161?u=hugovk]):

> We strongly encourage maintainers of third-party Python projects to prepare their projects for 3.13 compatibilities during this phase, and where necessary publish Python 3.13 wheels on PyPI to be ready for the final release of 3.13.0. Any binary wheels built against Python 3.13.0rc2 will work with future versions of Python 3.13. As always, report any issues to [the Python bug tracker](https://github.com/python/cpython/issues).

**Comment by glyph** [comment]
Is there anything that interested downstream dependents can do to move this along?

**Comment by yan12125** [comment]
> Is there anything that interested downstream dependents can do to move this along?

FWIW, buildbot uses [an unmerged PR](https://github.com/mhammond/pywin32/pull/2349) to [test](https://github.com/buildbot/buildbot/pull/7620/files#diff-881c8173c25e0340286efa57853f9d953b9e3573ecb7ec2c07a90ecfd39ea0d2R20) if pywin32 can work on Python 3.13. I guess some more testing will be helpful.

**Comment by henryiii** [comment]
Was trying to update Plumbum for 3.13 support (release next week!), and this is blocking.

**Comment by Avasam** [comment]
https://github.com/mhammond/pywin32/issues/2294#issuecomment-2394493117
> I just released 307 taking the PRs @Avasam mentioned above. I'll let it bake for a week or so to see if the new release process actually works, before getting back to the other PRs - after that I intend making more timely releases - sorry for the huge delay here!

**Comment by njss** [comment]
not working on windows 11 with python 3.13 (globally, without environment). It installs but it doesn't work when import...

**Comment by Avasam** [comment]
@njss This issue is about adding Python 3.13 support and build wheels in the first place. Please open a new issue and closely follow the template: https://github.com/mhammond/pywin32/issues/new?template=issue_template.md
