### ISSUE TITLE
Product version info is missing in 307

### ISSUE THREAD

**Issue by sys2065** [mhammond/pywin32#2386]
PyISAPI_loader.dll product version was fine in previous pywin32 versions, but in 307 it's empty.

See image bellow.

![kuva](https://github.com/user-attachments/assets/89e89e62-c68d-4497-9c12-d630546e25fa)

**Comment by Avasam** [comment]
I think this would be solved by https://github.com/mhammond/pywin32/pull/2349

**Comment by Avasam** [comment]
![image](https://github.com/user-attachments/assets/9536bdc4-236f-4a74-9f41-f36560ac8594)
