### ISSUE TITLE
Regression: Python 3.12.7 interpreter crashes when accessing a COM Record field

### ISSUE THREAD

**Issue by geppi** [mhammond/pywin32#2415]
## Bug description

Accessing a COM Record field crashes the Python 3.12.7 interpreter.

## Steps to reproduce the problem

Compile and register the _PyCOMTest.PyCOMTest_ server DLL and run the following Python code:

```python
import pythoncom
from win32com.client import gencache

try:
    gencache.EnsureModule("{6BCDCB60-5605-11D0-AE5F-CADD4C000000}", 0, 1, 1)
except pythoncom.com_error:
    print("The PyCOMTest module can not be located or generated.")
    raise RuntimeError

o = gencache.EnsureDispatch("PyCOMTest.PyCOMTest")
r = o.GetStruct()
```
Any attempt to access a field of the COM record like `a = r.int_value`  does crash the Python interpreter.

## System information

Python version and distribution: **3.12.7**

pywin32 version: **308**

Installed from PyPI or exe installer: **PyPI**

Windows Version: **Windows 10 Pro 22H2 Build 19045.5011**

## Further investigation

I've tried to debug this issue with the following result.

It is caused by an access violation ( 0xC0000005) in the _python312.dll_.
Going down the callstack, it happens in _PyRecord.cpp:getattro()_ on line 481 with the call
`PyWinObject_FreeWCHAR(wname);`.
This leads down into _cpython/Objects/obmalloc.c:get_state()_ where on line 866 the call
`PyInterpreterState *interp = _PyInterpreterState_GET();`
is causing the access violation.

However, maybe this is a red herring and the problem is caused by some other part of the code, looming, just to hit at that point?

I just recognized that moving from 3.11 to 3.12 seems to have introduced major code changes to prepare for getting rid of the GIL.
Although the code that triggers the access violation is not doing anything fancy with regard to threading, I'm wondering what this `PY_INTERFACE_PRECALL;` before and `PY_INTERFACE_POSTCALL;` afer the call to `PyWinObject_FreeWCHAR(wname);` are good for?

I'm not experienced enough to put all this into the proper context. :-(

**Comment by geppi** [comment]
Just confirming that this issue doesn't exist with Python 3.10 and 3.11 but it persists with Python 3.13.0

**Comment by mhammond** [comment]
sorry I missed this before:

> I do also have a question regarding the use of these macros:
> When are they required or recommended around a COM call?

They typically are required if the COM call might end up calling back into Python - most COM entry-points try and acquire that lock, which means if there's Python code up the stack, it must have release it.

It's recommended whenever the call might be expensive, so Python in other threads is able to run.

> In _PyRecord.cpp_ for example they are used around calls to `GetFieldNoCopy()` and `PutField()` but not around `RecordCreateCopy()`.

That's more like an oversight - typically I tended to err on the side of just releasing it, because it's not always obvious when a call is expensive or when it might reenter in edge-cases.

**Comment by geppi** [comment]
Thanks for the explanation.

I would expect that `RecordCreateCopy()` is more expensive than `GetFieldNoCopy()` or `PutField()`.  
So should I issue another PR to sandwich the `RecordCreateCopy()` call?

**Comment by mhammond** [comment]
I don't see why not - it seems like we should be consistent!
