### ISSUE TITLE
Install of build 210 fails with Python 2.5 on Win XP Pro

### ISSUE THREAD

**Issue by ghost** [mhammond/pywin32#314]
In postinstall pywin32 seems to rely on the python24.dll so it gives this error:
Traceback \(most recent call last\):
File "&lt;string&gt;", line 365, in &lt;module&gt;
File "&lt;string&gt;", line 157, in install
ImportError: DLL load failed: Das angegebene Modul wurde nicht gefunden.
\*\*\* run\_installscript: internal error 0xFFFFFFFF \*\*\*

See also the attached screenshot.
I had installed python24 on that same machine but have uninstalled it meanwhile.
NB: While there was accidentally a python24.dll in the same path I started the pywin32 installer, this one seemed to be executed but the another error appeared:
Traceback \(most recent call last\):
File "&lt;string&gt;", line 365, in &lt;module&gt;
File "&lt;string&gt;", line 157, in install
ImportError: Module use of python24.dll conflicts with this version of Python.
\*\*\* run\_installscript: internal error 0xFFFFFFFF \*\*\*

Reported by: mkallas

Original Ticket: "pywin32/bugs/314":https://sourceforge.net/p/pywin32/bugs/314

**Comment by Avasam** [comment]
> ImportError: Module use of python24.dll conflicts with this version of Python.

Nowadays, just updating Python and pywin32 will resolve this issue.
