### ISSUE TITLE
easy_install silently fails

### ISSUE THREAD

**Issue by ghost** [mhammond/pywin32#334]
If I install pywin32 by executing pywin32-210.win32-py2.5.exe , it works.

If I run "easy\_install pywin32" then it claims that it is downloading and installing pywin32-210.win32-py2.5.exe , and after a while it claims that it has successfully installed it, but an attempt to use pywin32 yields errors like this:

$ python -c 'import win32process'
Traceback \(most recent call last\):
File "&lt;string&gt;", line 1, in &lt;module&gt;
ImportError: DLL load failed: The specified module could not be found.

I'm not sure whether this should be considered a bug in pywin32 or in easy\_install, or both.

Regards,

Zooko

Reported by: zooko

Original Ticket: "pywin32/bugs/334":https://sourceforge.net/p/pywin32/bugs/334

**Comment by Avasam** [comment]
Easy Install (and eggs) have been deprecated in favor of wheels and package managers like pip https://setuptools.pypa.io/en/latest/deprecated/easy_install.html

**Comment by Avasam** [comment]
xref: https://github.com/twisted/twisted/issues/3004
