### ISSUE TITLE
Installer for Python 2.5 / v211 does not work

### ISSUE THREAD

**Issue by ghost** [mhammond/pywin32#374]
After Downloading the Win-Installer for Python 2.5 / v211  and starting it for installation using the current user \(not admin\), the message "Setup program invalid or damaged" appears and the installer exits.

Tried different mirrors to download \(Berlin, Kent\) - same results.

Regards, HB

Reported by: hb08

Original Ticket: "pywin32/bugs/374":https://sourceforge.net/p/pywin32/bugs/374

**Comment by Avasam** [comment]
@mhammond This issue seems to be about Python 2.5 support, which is no longer relevant. Should maybe close?
