### ISSUE TITLE
PyTime's .msec method always returns 0

### ISSUE THREAD

**Issue by ghost** [mhammond/pywin32#387]
PyTime stores times internally as DATE objects, which support fractional second resolution \(since they are just a double number of days\).

However the method to retrieve attributes including msec uses the Win32 VariantTimeToSystemTime function to convert the m\_time to a SYSTEMTIME.

This function is known not to convert the fractional part of seconds \(see http://support.microsoft.com/kb/297463, and http://www.codeproject.com/KB/datetime/SysTimeToVarTimeWMillisec.aspx for some example workaround code\).

So although the fractional part is actually stored in the PyTime object, it cannot be retrieved.

Reported by: davidfraser

Original Ticket: "pywin32/bugs/387":https://sourceforge.net/p/pywin32/bugs/387

**Comment by brunomsantiago** [comment]
Hi,

Any plan to work on that?

I am [playing with some OPC DA stuff](https://github.com/brunomsantiago/py_opcda_datalogger) using [OpenOPC](https://sourceforge.net/projects/openopc/), which uses pywin32. This VariantTimeToSystemTime issue is limiting my applications.

I would like to help but don't know how to start.
The only hint I found on pywin32 repo was on MakeDefaultArgRepr() method of DispatchItem() class of win32com.client module [build.py](https://github.com/mhammond/pywin32/blob/master/com/win32com/client/build.py).
I have also found this [article on code project](https://www.codeproject.com/Articles/17576/SystemTime-to-VariantTime-with-Milliseconds) explaining the VariantTimeToSystemTime issue, but it didn't help much regarding pywin32.


Minimum working code to demonstrate the issue with OPC DA (adapted from  [here](http://idahogray.github.io/blog/writing-a-opc-client.html)) (require both [Matrikon OPC Simulaton Server](https://www.matrikonopc.com/products/opc-drivers/opc-simulation-server.aspx) and registered [Graybox dll](http://gray-box.net/daawrapper.php) to run):

```python
import win32com.client

c = 'Graybox.OPC.DAWrapper'
opc = win32com.client.gencache.EnsureDispatch(c, 0)

opc_server='Matrikon.OPC.Simulation.1'
opc_host='localhost'
opc.Connect(opc_server, opc_host)

group = opc.OPCGroups.Add('Test Group')


sensor_tag = 'Saw-toothed Waves.Int4'
item = group.OPCItems.AddItem(sensor_tag, 1)

value, quality, timestamp = item.Read(win32com.client.constants.OPCDevice)
print(timestamp)
print(timestamp.__repr__())
print(timestamp.microsecond)
```
Output:
```
>> 2018-10-20 04:21:57+00:00
>> pywintypes.datetime(2018, 10, 20, 4, 21, 57, tzinfo=TimeZoneInfo('GMT Standard Time', True))
>> 0
```
