### ISSUE TITLE
Can't install on non-std Python installation

### ISSUE THREAD

**Issue by ghost** [mhammond/pywin32#39]
\( I also submitted this in the Support section\)
Esteemed Python People and Lurkers:

I would really like to install the Win extensions to
Python ... I just started using Python and I LOVE it\!
I've never seen Python before in my life, and with the
PeachPit Press Python Visual Quick Start book, I got a
simple HTML Automatic Table generator up and running in
a total of about 4 hours\!

The problem is I can NOT install the Win extensions\!
My Python is installed in:
&amp;quot;F:\Applications\Python&amp;quot;
and the Win extension installer \(win32all-153.exe\) just
can't find it. I click the &amp;quot;Continue anyway&amp;quot; button on
the popup, but it just jumps back to the same popup and
will NOT continue no matter what I do.

How can I get the extensions installed on my
Non-Standard Python installation?

Thank you for your gracious and patient assistance with
this issue.

Art Du Rea Carlisle, PA USA
NoSpam e-mail: imadeptNOGI@NOGOpa-net
Remove the caps letters
\(NO Garbage In : NO Garbage Out\)

Reported by: durea

Original Ticket: "pywin32/bugs/39":https://sourceforge.net/p/pywin32/bugs/39

**Comment by Avasam** [comment]
[.exe installers are now deprecated](https://github.com/mhammond/pywin32#binaries)
