### ISSUE TITLE
Unicode exception when using ie.Navigate after dispatch

### ISSUE THREAD

**Issue by ghost** [mhammond/pywin32#399]
The situation: When using a IE browser after dispatch and navigating to a particular URL, the exception at the end of this note is observed
Important information: this is from the user of a commercial python program \(provided as an executable\) called CiteSmart. The error is observed very likely because th user is using a Corean version of Windows XP. This bug couldn't be reproduced on an english plate-form.

&gt; Traceback \(most recent call last\):
&gt; File &amp;quot;win32com\server\policy.pyo&amp;quot;, line 285, in \_Invoke\_
&gt; File &amp;quot;win32com\server\policy.pyo&amp;quot;, line 290, in \_invoke\_
&gt; File &amp;quot;win32com\server\policy.pyo&amp;quot;, line 658, in \_invokeex\_
&gt; File &amp;quot;win32com\server\policy.pyo&amp;quot;, line 653, in
&gt; \_transform\_args\_
&gt; : 'ascii' codec can't encode
&gt; characters in position 0-1: ordinal not in

Reported by: merrami

Original Ticket: "pywin32/bugs/399":https://sourceforge.net/p/pywin32/bugs/399

**Comment by Avasam** [comment]
@mhammond None of the code referenced here exists anymore. I get the feeling you can probably close this unicode-related issue.
