### ISSUE TITLE
pywin32 installation error

### ISSUE THREAD

**Issue by ghost** [mhammond/pywin32#402]
I have installed python 2.5.1 and I am receiving an installation error while trying to install pywin32-212.win32-py2.5.  

The error reported is.

Setup pywin32-212:pywin32-212.win32-py2.5.exe - entry point not found
The procedure entry point ?PyWinObject\_AsHANDLE@@YAHPAU\_object@@PAPAXH@Z could not be located in the dynamic link library pywintypes 25.dll

As suggested I searched for duplicates of pythonxx.dll, pywintypesxx.dll, or pythoncomxx.dll and removed any dups not within the system32 directory. I am running WindowsXP.

Thanks in advance for any suggestions\!
Kevin

Reported by: chalawu

Original Ticket: "pywin32/bugs/402":https://sourceforge.net/p/pywin32/bugs/402

**Comment by Avasam** [comment]
@mhammond Considering this this issue is specifically about python 2, and windows XP (for which the latest official Python version is 3.4). Can it be closed?
