### ISSUE TITLE
Install problem XP

### ISSUE THREAD

**Issue by ghost** [mhammond/pywin32#437]
When I try to install 
pywin32-214.win32-py3.1.exe
on a system with Windows XP SP3 the installation finish with this message:

Copied pythoncom31.dll to C:\WINDOWS\system32\pythoncom31.dll
Copied pywintypes31.dll to C:\WINDOWS\system32\pywintypes31.dll
Registered: Python.Interpreter 
Registered: Python.Dictionary 
Registered: Python 
-&gt; Software\Python\PythonCore\3.1\Help\[None\]=None
-&gt; Software\Python\PythonCore\3.1\Help\Pythonwin Reference\[None\]='C:\\\Python31\\\Lib\\\site-packages\\\PyWin32.chm'
Failed to register pythonwin as editor
'utf8' codec can't decode bytes in position 39-43: unsupported Unicode code range
The pywin32 extensions were successfully installed.
Traceback \(most recent call last\):
File "&lt;string&gt;", line 398, in install
File "&lt;string&gt;", line 208, in RegisterPythonwin
WindowsError: \[Error 5\] Acceso denegado

The user has admin rights.
Thanks in advance.

Reported by: trancos7

Original Ticket: [pywin32/bugs/437](https://sourceforge.net/p/pywin32/bugs/437)

**Comment by Avasam** [comment]
A lot of utf-8 / unicode issues have been fixed, or are no longer relevant. Due to the difficulties of contacting old SourceForge accounts, I'll close this. Feel free to open a new issue if you think you're having the same.
