### ISSUE TITLE
win32ui crash in embedded app (212 -> 213 & 214 regression)

### ISSUE THREAD

**Issue by ghost** [mhammond/pywin32#443]
I have an application that embeds python and uses the win32ui module. Everything worked fine until I upgraded from 212 to 214. After the upgrade my application crashes on exit. The Visual Studio debugger is showing that the crash is occurring after my application calls CoUninitialize. Here is a rough outline of what my app does:

CoInitialize\(NULL\)
InitPython\(\)
RunPythonCode\(\) //This code will import win32ui
ClosePython\(\)
CoUninitialize\(\)

Simply importing the win32ui module causes the crash. I don't even need to call any of the modules functions. If I don't import win32ui then my application exits cleanly. I tried downgrading to version 213 but the crash still occurs. Version 212 seems to be the last version that was stable with my application.

Reported by: farshizzo

Original Ticket: [pywin32/bugs/443](https://sourceforge.net/p/pywin32/bugs/443)

**Comment by mhammond** [comment]
Probably fixed by #1841
