### ISSUE TITLE
win32com can be used only one time in embedded python

### ISSUE THREAD

**Issue by ghost** [mhammond/pywin32#445]
Hello all

I embed python interpreters in a C++ program. For each script to execute I create a new interpreter. In this environment I can use the win32 extensions only one time. Here is a little piece of code to illustrate the problem:

int main\(int argc, char \*\*argv\) \{ Py\_Initialize\(\); Py\_SetProgramName\(argv\[0\]\);

PyThreadState \*save\_tstate=PyThreadState\_Swap\(NULL\); PyThreadState \*state=Py\_NewInterpreter\(\);

int rc=PyRun\_SimpleString\("import sys\nimport win32com.client\nw=win32com.client.Dispatch\("Word.Application"\)\nw.Visible = 1\n"\); //this works well printf\("%d\n",rc\);

Py\_EndInterpreter\(state\);

PyThreadState\_Swap\(save\_tstate\);

state=Py\_NewInterpreter\(\);

rc=PyRun\_SimpleString\("import sys\nimport win32com.client\nw=win32com.client.Dispatch\("Word.Application"\)\nw.Visible = 1\n"\); //this and all further atemps will fail printf\("%d\n",rc\);

Py\_EndInterpreter\(state\); PyThreadState\_Swap\(save\_tstate\);

; \}

Here is the output of this little program:

Traceback \(most recent call last\):
File "&lt;string&gt;", line 8 \(13\), in &lt;module&gt;
File "C:\cre\2009.2\techlog\PythonScripts\External261\_x86\win32com\\\_\_init\_\_.py", line 6, in &lt;module&gt;
import pythoncom
File "C:\cre\2009.2\techlog\PythonScripts\External261\_x86\Lib\pythoncom.py", line 3, in &lt;module&gt;
File "C:\cre\2009.2\techlog\PythonScripts\External261\_x86\Lib\pywintypes.py", line 20, in \_\_import\_pywin32\_system\_module\_\_
TypeError: 'NoneType' object is not callable

I use

Python 2.6 compiled with MSC v.8 32 bit \(Intel\)\] on win32

with

Pywin32- 214

Is there any way to overcome this problem?

Reported by: cyr34

Original Ticket: [pywin32/bugs/445](https://sourceforge.net/p/pywin32/bugs/445)

**Comment by dzzie** [comment]
Hi, I am running into this same issue.

I am embedding python within a vb6 host process. Would like the ability to run scripts clean in a new interpreter instance each time with Py_Initialize / Py_FinalizeEx. Python itself doesnt mind this.

import win32com.client works the first time in the process and fails subsequent. 

GetObject is a very convenient way for me to communicate between my vb6 host and the python code. I am considering extracting it and bringing it into my C shim dll. 

I would be willing to dig and try to come up with a solution to this problem. Seems like it can be fixed. We are still always single threaded, seems like something has a lock to only init once per process. 

Any hints on insights to get me started?

**Comment by mhammond** [comment]
I suggest you do all the work in a child python process and start a new one each time.

**Comment by dzzie** [comment]
Looks like I have been able to recover the ability to call Initilize/Finalize repeatably in an embedded context by stripping out just the desired COM access code and putting it in a helper dll. Direct sharing of host COM objects without using the ROT also worked out well. Great code. thank you for sharing.
