### ISSUE TITLE
assert sys.modules[modname] is old_mod error in pywintypes

### ISSUE THREAD

**Issue by ghost** [mhammond/pywin32#452]
When running Apache+Mod Python \(Python 2.4\), I was getting this error - 

\[Mon Nov 30 15:13:50 2009\] \[error\] \[client 127.0.0.1\] Traceback \(most recent call last\):
\[Mon Nov 30 15:13:50 2009\] \[error\] \[client 127.0.0.1\]   File "C:\\\Python24\\\Lib\\\site-packages\\\mod\_python\\\importer.py", line 1537, in HandlerDispatch\n    default=default\_handler, arg=req, silent=hlist.silent\)
\[Mon Nov 30 15:13:50 2009\] \[error\] \[client 127.0.0.1\]   File "C:\\\Python24\\\Lib\\\site-packages\\\mod\_python\\\importer.py", line 1229, in \_process\_target\n    result = \_execute\_target\(config, req, object, arg\)
\[Mon Nov 30 15:13:50 2009\] \[error\] \[client 127.0.0.1\]   File "C:\\\Python24\\\Lib\\\site-packages\\\mod\_python\\\importer.py", line 1128, in \_execute\_target\n    result = object\(arg\)
\[Mon Nov 30 15:13:50 2009\] \[error\] \[client 127.0.0.1\]   File "c:\\\python24\\\Lib\\\site-packages\\\django\\\core\\\handlers\\\modpython.py", line 228, in handler\n    return ModPythonHandler\(\)\(req\)
\[Mon Nov 30 15:13:50 2009\] \[error\] \[client 127.0.0.1\]   File "c:\\\python24\\\Lib\\\site-packages\\\django\\\core\\\handlers\\\modpython.py", line 201, in \_\_call\_\_\n    response = self.get\_response\(request\)
\[Mon Nov 30 15:13:50 2009\] \[error\] \[client 127.0.0.1\]   File "c:\\\python24\\\Lib\\\site-packages\\\django\\\core\\\handlers\\\base.py", line 73, in get\_response\n    response = middleware\_method\(request\)
\[Mon Nov 30 15:13:50 2009\] \[error\] \[client 127.0.0.1\]   File "c:\\\python24\\\Lib\\\site-packages\\\django\\\contrib\\\sessions\\\middleware.py", line 10, in process\_request\n    engine = import\_module\(settings.SESSION\_ENGINE\)
\[Mon Nov 30 15:13:50 2009\] \[error\] \[client 127.0.0.1\]   File "c:\\\python24\\\Lib\\\site-packages\\\django\\\utils\\\importlib.py", line 35, in import\_module\n    \_\_import\_\_\(name\)
\[Mon Nov 30 15:13:50 2009\] \[error\] \[client 127.0.0.1\]   File "c:\\\python24\\\Lib\\\site-packages\\\django\\\contrib\\\sessions\\\backends\\\db.py", line 2, in ?\n    from django.contrib.sessions.models import Session
\[Mon Nov 30 15:13:50 2009\] \[error\] \[client 127.0.0.1\]   File "c:\\\python24\\\Lib\\\site-packages\\\django\\\contrib\\\sessions\\\models.py", line 4, in ?\n    from django.db import models
\[Mon Nov 30 15:13:50 2009\] \[error\] \[client 127.0.0.1\]   File "c:\\\python24\\\Lib\\\site-packages\\\django\\\db\\\models\\\\\_\_init\_\_.py", line 12, in ?\n    from django.db.models.fields.files import FileField, ImageField
\[Mon Nov 30 15:13:50 2009\] \[error\] \[client 127.0.0.1\]   File "c:\\\python24\\\Lib\\\site-packages\\\django\\\db\\\models\\\fields\\\files.py", line 8, in ?\n    from django.core.files.storage import default\_storage
\[Mon Nov 30 15:13:50 2009\] \[error\] \[client 127.0.0.1\]   File "c:\\\python24\\\Lib\\\site-packages\\\django\\\core\\\files\\\storage.py", line 7, in ?\n    from django.core.files import locks, File
\[Mon Nov 30 15:13:50 2009\] \[error\] \[client 127.0.0.1\]   File "c:\\\python24\\\Lib\\\site-packages\\\django\\\core\\\files\\\locks.py", line 25, in ?\n    import pywintypes
\[Mon Nov 30 15:13:50 2009\] \[error\] \[client 127.0.0.1\]   File "C:\\\Python24\\\Lib\\\site-packages\\\win32\\\lib\\\pywintypes.py", line 124, in ?\n    \_\_import\_pywin32\_system\_module\_\_\("pywintypes", globals\(\)\)
\[Mon Nov 30 15:13:50 2009\] \[error\] \[client 127.0.0.1\]   File "C:\\\Python24\\\Lib\\\site-packages\\\win32\\\lib\\\pywintypes.py", line 114, in \_\_import\_pywin32\_system\_module\_\_\n    assert sys.modules\[modname\] is old\_mod
\[Mon Nov 30 15:13:50 2009\] \[error\] \[client 127.0.0.1\] AssertionError

With PythonDebug = On, assert took effect. I removed it and it worked without any issues.
I found that another user - &lt;a href="http://markmail.org/message/hqnf6obaillzspxj\#query:assert%20sys.modules\[modname\]%20is%20old\_mod+page:1+mid:nahkqunchycwqtd4+state:results"&gt;here&lt;/a&gt; also has the same issue.
He solved it by going back a version.

Reported by: *anonymous

Original Ticket: [pywin32/bugs/452](https://sourceforge.net/p/pywin32/bugs/452)

**Comment by Wissperwind** [comment]
No plan to fix that bug more than 10 years after opening the issue?

**Comment by kxrob** [comment]
> No plan to fix that bug more than 10 years after opening the issue?

The error line `assert sys.modules[modname] is old_mod` is not used anymore with Python 3 only support. 
Do you have a current traceback? Or a problem description or indication that the pywintypesXX.dll is somehow loaded twice?

**Comment by Avasam** [comment]
Closed by #1821
