### ISSUE TITLE
Installer Crashes in Windows 7

### ISSUE THREAD

**Issue by ghost** [mhammond/pywin32#457]
The installer crashes with a Visual C++ runtime error near the end of the installation process in Windows 7.

Reported by: beef623

Original Ticket: [pywin32/bugs/457](https://sourceforge.net/p/pywin32/bugs/457)

**Comment by Avasam** [comment]
[.exe installers are now deprecated](https://github.com/mhammond/pywin32#binaries) and pywin32 should be installed using wheels available on PyPI
