### ISSUE TITLE
python 3.1 and pywin 214 gives some errors when installing

### ISSUE THREAD

**Issue by ghost** [mhammond/pywin32#468]
python 3.1 and pywin 214 gives some errors when installing:

Traceback \(most recent call last\):
File "&lt;string&gt;", line 601, in &lt;module&gt;
File "&lt;string&gt;", line 329, in install
File "&lt;string&gt;", line 15, in write
AttributeError: 'NoneType' object has no attribute 'write'

Reported by: emakital

Original Ticket: [pywin32/bugs/468](https://sourceforge.net/p/pywin32/bugs/468)

**Comment by Avasam** [comment]
@mhammond With the lack of information in this issue, I doubt it's still relevant. pywin32 installation has also changed a lot since then.
