### ISSUE TITLE
Error at the end of install on Win 7

### ISSUE THREAD

**Issue by ghost** [mhammond/pywin32#498]
A colleague and I both got this error on Win 64-bit in the last dialog of the installer:

close failed in file object destructor:
Error in sys.excepthook:

Original exception was:

I was able find this thread which describe the same problem:
http://python-forum.com/pythonforum/viewtopic.php?f=15&t=17163&start=0&sid=84e05d8a7c989bb8a3f36ea0a868c28a

When I run pywin32\_postinstall.py manually, this is what I get:

C:\Python27\Scripts&gt;pywin32\_postinstall.py -install
Copied pythoncom27.dll to C:\Windows\system32\pythoncom27.dll
Copied pywintypes27.dll to C:\Windows\system32\pywintypes27.dll
Registered: Python.Interpreter
Registered: Python.Dictionary
Registered: Python
-&gt; Software\Python\PythonCore\2.7\Help\[None\]=None
-&gt; Software\Python\PythonCore\2.7\Help\Pythonwin Reference\[None\]='C:\\\Python27\\\
Lib\\\site-packages\\\PyWin32.chm'
Pythonwin has been registered in context menu
Can't install shortcuts - u'C:\\\Users\\\SND\\\AppData\\\Roaming\\\Microsoft\\\Windows
\\\Start Menu\\\Programs\\\Python 2.7' is not a folder
The pywin32 extensions were successfully installed.

PyWin32 appears to be installed and operational despite the error.  The Python 2.7 program group icons are also registered despite the warning in the output above.

Reported by: tnili

Original Ticket: [pywin32/bugs/498](https://sourceforge.net/p/pywin32/bugs/498)

**Comment by Avasam** [comment]
Given the sheer amount of installation issues duplication and old history, I'd like to consolidate the current state of these issues. So I'll close and reference back any issue that only has comments showing the issue:
- from before November 10th, 2019 (pywin32<226)
- using `.exe` installers
- using Python < 3.8

Please also try https://github.com/mhammond/pywin32#troubleshooting before opening a new issue, or let us, and others, know here if it did fix your issue.

If you're having this issue with Jupyter Notebooks, refer to https://github.com/mhammond/pywin32/issues/1409 instead.
If you're having this issue using the Microsoft Store distribution of Python, refer to https://github.com/mhammond/pywin32/issues/1383 instead.
If you're having this issue with the Anaconda distribution of Python, refer to https://github.com/mhammond/pywin32/issues/1865 instead.
