### ISSUE TITLE
"This object does not support enumeration"

### ISSUE THREAD

**Issue by ghost** [mhammond/pywin32#506]
I have  script which works fine with python 2.5, but in 2.6 raises error below. The script can be nabbed from http://code.google.com/p/maphew/source/browse/trunk/gis/list-fc-aliases.py.  Unfortunately the script requires ArcGIS 9.3 installed on the host machine, along with arcgisscripting.py from here \(http://www.yukongis.ca/How\_To/Upgrading\_ArcGIS\_Python\) plunked into C:\Python2.6\Lib\site-packages, so duplicating it is not easy.

I'm hoping that someone just eyeballing the code can tell me what's wrong?
Thanks

\{\{\{
Traceback \(most recent call last\):
File "list-fc-aliases.py", line 40, in &lt;module&gt;
getDataSets\(\)
File "list-fc-aliases.py", line 17, in getDataSets
for fd in fds:
File "C:\Python26\lib\site-packages\win32com\client\dynamic.py", line 242, in
\_\_getitem\_\_
raise TypeError\("This object does not support enumeration"\)
TypeError: This object does not support enumeration
\}\}\}

Reported by: maphew

Original Ticket: [pywin32/bugs/506](https://sourceforge.net/p/pywin32/bugs/506)

**Comment by Avasam** [comment]
@mhammond This issue seems to be about Python 2.6 support, which is no longer relevant. Should maybe close?
