### ISSUE TITLE
problem with ADO.CommandeExecute() options

### ISSUE THREAD

**Issue by ghost** [mhammond/pywin32#55]
I posted this originally on comp.python.  I'm reposting it 
here since it seems a more appropriate place.

I'm hoping this is a coding error on my part, but I've 
encountered a problem with parameters that I cannot 
understand.  Perhaps someone out there might be willing 
to assist me with some suggestions.

First, here is some VB code that correctly does what I 
want to do:

\--------------------------- begin cmdtest.vbs
Dim cn
Dim rs
Dim cmd

Set cn = CreateObject\( &amp;quot;ADODB.Connection&amp;quot; \)
cn.Open\( &amp;quot;Provider=SQLOLEDB;Data Source=
\(local\);Initial Catalog=Environmental 
Monitoring;Integrated Security=SSPI&amp;quot; \)

Set rs = CreateObject\( &amp;quot;ADODB.Stream&amp;quot; \)
rs.Open\(\)

Set cmd = CreateObject\( &amp;quot;ADODB.Command&amp;quot; \)

cmd.ActiveConnection = cn          
cmd.Properties\(&amp;quot;Output Stream&amp;quot;\).Value = rs
cmd.CommandText = &amp;quot;SELECT \* FROM \[Sources\] for 
XML AUTO&amp;quot;

cmd.Execute , , 1024 'adExecuteStream

rs.Position = 0
WScript.Echo rs.ReadText\(\)
\--------------------------- end cmdtest.vbs

Here is partial output I get:
C:\&amp;gt;cscript cmdtest.vbs
Microsoft \(R\) Windows Script Host Version 5.6
Copyright \(C\) Microsoft Corporation 1996-2001. All 
rights reserved.

&amp;lt;Sources ID=&amp;quot;1&amp;quot; Name=&amp;quot;South Asia&amp;quot; 
Type=&amp;quot;7&amp;quot;/&amp;gt;&amp;lt;Sources ID=&amp;quot;2&amp;quot; Name=&amp;quot;Japan&amp;quot; Type=&amp;quot;2&amp;quot;/&amp;gt;...

Now, if I attempt to do the same thing in python, it 
returns no output.
\------------------------- begin cmdtest.py
import ADO, sys

cn = ADO.Connection\(\)
cn.Open\( &amp;quot;Provider=SQLOLEDB;Data Source=
\(local\);Initial Catalog=Environmental 
Monitoring;Integrated Security=SSPI&amp;quot; \)

rs = ADO.Stream\(\)
rs.Open\(\)

cmd = ADO.Command\(\)

cmd.ActiveConnection = cn          
cmd.Properties\(&amp;quot;Output Stream&amp;quot;\).Value = rs
cmd.CommandText = &amp;quot;SELECT \* FROM \[Sources\] for 
XML AUTO&amp;quot;

cmd.Execute\( Options = 
ADO.constants.adExecuteStream \)

rs.Position = 0
sys.stdout.write\( rs.ReadText\(\) \) \# prints nothing
\------------------------- end cmdtest.py

If I pass no parameters to cmd.Execute in the VBScript 
verison, I get no output.  Other tests have further led 
me to conclude that the constant value 1024 is not 
being properly passed to ADO.Command.Execute in the 
Python version only.

Here are some other points of information:
\- Using the literal 1024 in the Python code instead of 
the constant reference make no difference. 
\- The VBScript code does not recognize 
adExecuteStream by name. 
\- Using win32com.client.Dispatch\( 'ADODB.\*' \) to 
create the objects \(instead of ADO.py created from 
make PY\) yields the same results. 
\- Using a different PROVIDER in the connection \(such 
as SQLXMLOLEDB\) will yield different results, but still 
indicates that the 'adExecuteStream' is not being set 
properly. 
\- I'm using &amp;quot;Microsoft ActiveX Data Objects 2.8 Library&amp;quot; 
for the ADO.  I've tried using v2.5 and 2.7, but get 
identical results. 
\- The first parameter to ADO.Command.Execute 
appears to be an \[out\] parameter, but the 
documentation is confusing and I haven't seen the first 
parameter used anywhere.

Any insight into this problem would be most appreciated.

Regards,
Jason R. Coombs
Sandia National Laboratories

Reported by: jaraco

Original Ticket: "pywin32/bugs/55":https://sourceforge.net/p/pywin32/bugs/55

**Comment by Avasam** [comment]
Tagging @jaraco as the original SourceForge issue creator.

**Comment by jaraco** [comment]
I know I offered to look at this again, but I never did and I've lost almost all of the context necessary to investigate further. I guess this should be closed again.
