### ISSUE TITLE
Need VC 10 version of Python for Windows extensions

### ISSUE THREAD

**Issue by ghost** [mhammond/pywin32#551]
Background: have app that has Python embedded and we using the extensions in many scripts that we supply. Needed features in new MFC with VC10. Want to use Python 2.7. Python won't initialize unless same C run-time, so rebuilt python27.dll \(and some others, but that seems all that is critical\). We've done this before \(at Python 2.8 with VC 9\) but this time cannot import win32api. So thought we needed to rebuild that, too.
Using Python 2.7. Downloaded source for v 216.2. Try to build it using setup.py that came with it with installed Py 2.7. Fails trying to build perfmondata; appears to be looking for \*.man files that do not exist. Decided to try again using rebuilt Python \(VC10\). Setup correctly identifies compiler and linker \(cool\!\) but now failure occurs trying to load winapi. Tried rebuilding that using VS project file. Seems to build. Tried to run product on bare hope that that was all that was needed - failure importing \_win32sysloader. Don't see how that gets rebuilt. Still can't get past perfmondata in setup.
Are we going about this the right way?

Reported by: martymike

Original Ticket: [pywin32/bugs/551](https://sourceforge.net/p/pywin32/bugs/551)

**Comment by Avasam** [comment]
Closing as correct build steps are provided.
Also documented: https://github.com/mhammond/pywin32#building-from-source

As a sidenote: [python setup.py and the use of setup.py as a command line tool are deprecated](https://packaging.python.org/en/latest/discussions/setup-py-deprecated/#is-setup-py-deprecated). pywin32 itself needs to move away from it. https://github.com/mhammond/pywin32/issues/2208
