### ISSUE TITLE
dde module initialization failing

### ISSUE THREAD

**Issue by ghost** [mhammond/pywin32#555]
If I import the dde module after importing the win32ui module, the error generated tells me to import the win32ui module.

I get the same behaviour for builds 215 and 216

Below is a copy of a real session

C:\&gt;c:\Python31\python.exe
Python 3.1.3 \(r313:86834, Nov 27 2010, 17:20:37\) \[MSC v.1500 64 bit \(AMD64\)\] on win32
Type "help", "copyright", "credits" or "license" for more information.
&gt;&gt;&gt; import win32ui
&gt;&gt;&gt; import dde
Traceback \(most recent call last\):
File "&lt;stdin&gt;", line 1, in &lt;module&gt;
ImportError: This must be an MFC application - try loading win32ui first
&gt;&gt;&gt; win32ui.GetApp\(\)
object 'PyCWinApp' - assoc is 000000000247D150, vi=&lt;None&gt;, notify=0,ch/u=0/0
&gt;&gt;&gt; 

Looking at the source code, the import error from the dde module appears to be generated because there is no CWinApp being created
by the win32ui import, but the call to win32ui.GetApp\(\) seems to show that there is one created.

Reported by: ajssf

Original Ticket: [pywin32/bugs/555](https://sourceforge.net/p/pywin32/bugs/555)

**Comment by Avasam** [comment]
@kxrob Is this issue still relevant?

**Comment by Avasam** [comment]
Looks like this must've been fixed at some point:
```
>>> import win32ui
>>> import dde
>>> dde.APPCLASS_MONITOR
1
```
