### ISSUE TITLE
Import Error: DLL load Failed Win XP Pro

### ISSUE THREAD

**Issue by ghost** [mhammond/pywin32#558]
Installed python 2.7, installed pywin32-216 without problems
Uninstalled python 2.7, pywin32
Installed python 2.6
When installing pywin32-216 \(or -215, same result\), setup dialog shows:
Traceback \(most recent call last\):
File "&lt;string&gt;", line 604, in &lt;module&gt;
File "&lt;string&gt;", line 314, in install
File "&lt;string&gt;", line 152, in LoadSystemModule
ImportError: DLL load failed: The specified module could not be found.

Reported by: rzn8tr

Original Ticket: [pywin32/bugs/558](https://sourceforge.net/p/pywin32/bugs/558)

**Comment by Avasam** [comment]
@mhammond Given that the latest official Python version to support Windows XP is 3.4, should this be closed?
OS-specificity aside, `ImportError: DLL load failed: The specified module could not be found.` is also duplicated by a lot of other issues with more details.
