### ISSUE TITLE
pywintypes must be explicitly imported before win32api

### ISSUE THREAD

**Issue by ghost** [mhammond/pywin32#562]
Hi,

I just want to raise awareness of this bug that affects Twisted on Windows using a 'portable' Python installation.
http://twistedmatrix.com/trac/ticket/3868

it looks like the following import will fail

from win32api import OpenProcess
import pywintypes

while changing the import order fixed the problem.

from win32api import OpenProcess
import pywintypes

\----

This only happend if I call python.exe from another working folder as the one hosting the python.exe file.
All DLLs are in the same folder as python.exe

I am thinking that win32api is only trying to load the dlls from the current working folder, not the one hosting the python.exe.

Reported by: *anonymous

Original Ticket: [pywin32/bugs/562](https://sourceforge.net/p/pywin32/bugs/562)

**Comment by Avasam** [comment]
xref: https://github.com/twisted/twisted/issues/3868

**Comment by Avasam** [comment]
Closed downstream and I could not replicate with OP's directions on a modern install
