### ISSUE TITLE
error 6034 installing from pywin32-216.win32-py2.6.exe (solv

### ISSUE THREAD

**Issue by ghost** [mhammond/pywin32#569]
Installing from pywin32-216.win32-py2.6.exe the installation progressed but mid-installation a MsgBox poped-up showing
"ERROR 6034 An application has made an attempt to load the C runtime library incorrectly"

Installation continues after clicking ok in the warning, damage is unknown. 

I tracked the problem to having a msvcr90.dll in a directory added to the PATH environment variable, even if it only holds said dll.

In my case, the problem was caused by Bazaar \(the revision control system\). I filled with them a more detailed bug report, see 
https://bugs.launchpad.net/bzr/+bug/881203

To locate such an offending dll, other than a search over the dirs in the PATH you can do the following

1\. install Process Explorer from SysInternals \( http://technet.microsoft.com/en-us/sysinternals/bb896653 \)
2\. launch it
3\. run pywin32-216.win32-py2.6.exe
4\. When the error message shows, without dismissing it, Alt-tab to process explorer
5\. In Process Explorer window select the process   pywin32-216.win32-py2.6.exe ,  then menu select View | Lower Pane View | DLLs  \(or use CTRL+D\)
6\. Look for duplicates of msvcr90.dll in the dlls attached to the process, right cliking on them will give the location. One is the correct dll, the other should not be there. In my case removing the dir holding the dll from the PATH fixed the issue.

Reported by: claxo

Original Ticket: [pywin32/bugs/569](https://sourceforge.net/p/pywin32/bugs/569)

**Comment by Avasam** [comment]
@mhammond Other than this being an issue raised for a Python 2 version of pywin32. It also sounds like the problem doesn't come from pywin32: some other app placed DLLs in an area it shouldn't have, causing it to be picked up and mess with other programs.
