### ISSUE TITLE
AssertionError: assert sys.modules[modname] is old_mod

### ISSUE THREAD

**Issue by ghost** [mhammond/pywin32#582]
This problem is opened at ID \#2905909.

I want to attach file, which tells what is in old\_mod and mod variables.

This problem has been described by me at: http://stackoverflow.com/questions/9479239/running-two-django-apps-on-apache-with-mod-auth-sspi-and-mod-wsgi

Reported by: honyczek

Original Ticket: [pywin32/bugs/582](https://sourceforge.net/p/pywin32/bugs/582)

**Comment by Avasam** [comment]
Closed by #1821
