### ISSUE TITLE
UnicodeDecodeError when trying help(win32gui)

### ISSUE THREAD

**Issue by ghost** [mhammond/pywin32#586]
Hello,

I just tried pywin32 build 217 with python 3.2 on Windows 7 64 bits.
With ipython, I dit this :
import win32gui
help\(win32gui\)

Then I get a UnicodeDecodeError. You'll find the traceback in attachement.

Regards,
Nicolas

Reported by: sylock01

Original Ticket: [pywin32/bugs/586](https://sourceforge.net/p/pywin32/bugs/586)

**Comment by Avasam** [comment]
> This doesn't happen with normal python.exe, idle, or pythonwin. Most likely it's a bug in ipython itself.

I reach the same conclusion. Closing as "can't fix" and original poster cannot be reached anymore.
