### ISSUE TITLE
InvokeTypes error using win32com v2.17

### ISSUE THREAD

**Issue by ghost** [mhammond/pywin32#594]
I think we have found a bug in win32com 2.17.  We are using it with Python 2.7.2.  We are calling a proprietary DLL named PATE, which provides APIs to a database named Enovia from the Dassault corporation.  The Enovia client is linked to a CAD program named CATIA so we must conjure objects of both CATIA and Enovia as shown in the code snippet below.  The strApplicationID is a password administered by my company and has nothing to do with the PATE DLL itself.  Rather, PATE should pass the strApplicationID to the Enovia server, which should authenticate the session.
====================================================================
import win32com.client, win32com.client.gencache, win32com.client.selecttlb
strPATECLSID = '\{9BB3CB79-7098-47D0-83A2-F8F56D236DC8\}'
strPATEclassCLSID = '\{9A1F3C8E-46B7-4CFA-A820-E4256ECD53B5\}'

self.objCATIA = win32com.client.GetActiveObject\('CATIA.Application'\)
win32com.client.gencache.EnsureModule\(strPATECLSID, 0, 0, 0\)
self.objBase= win32com.client.gencache.GetClassForCLSID\(strPATEclassCLSID\)
self.\_\_objPATECOM = self.objBase\(self.objCATIA\)
strApplicationID = &lt;secret&gt; 
try:
self.\_\_objPATECOM.SetApplicationID\(strApplicationID\)
except \(pywintypes.com\_error\), \_e:
print "Connection error: %s" %\(\_e\)
return False
====================================================================
When we use win32com 2.16 the code above works fine but when we use win32com 2.17 it throws the error message shown below.

File testKBE\_PATECAKE.py, line 367 in ConnectToENOVIA
self.\_\_objPATECOM.SetApplicationID\(strApplicationID\)
File "C:\Python27\lib\site-packages\win32com\gen\_py\9BB3CB79 -7098-47D0-83A2-F8
F56D236DC8x0x0x0.py", line 457 in SetApplicationID
return self.\_oleobj\_.InvokeTypes\(1610940417, LCID, 1, \(24, 0\), \(\(16396, 1\),\)
, iAID
File "C:\Python27\lib\site-packages\win32com\client\dynamic.py", line 516 in 
\_\_getattr\_\_
raise AttributeError\("%s.%s" % \(self.\_username\_, attr\)\)
AttributeEror: CATIA.Application.InvokeTypes

Reported by: mike_fox

Original Ticket: [pywin32/bugs/594](https://sourceforge.net/p/pywin32/bugs/594)

**Comment by nickvans** [comment]
@mhammond I'm baffled by why InvokeTypes is available in v216 but not in v217 as well. I'm sure you've had plenty of more interesting things to work on since Jun 2012, but as python 2 is reaching it's end of life I'm afraid we'll soon be screwed if there's no solution to this. 

In the absence of a ready path forward, Is there any chance one could recompile pywin32 v 216 for python 3.6?

**Comment by mhammond** [comment]
Sorry, I'm almost certainly unable to build 216 for Python 3.6 - lots of the work done since then is to support later python 3 versions.

**Comment by nickvans** [comment]
Fair enough. Thanks for taking the time to respond. I really appreciate the
work you do and have done for the community!

Nick

**Comment by Avasam** [comment]
@mhammond With Python 2 in EOL, I don't see pywin32 ever doing a backport patch / Py2 support. Should this be closed?

**Comment by nickvans** [comment]
I had completely forgotten about this issue. By all means close it. Thank
you for getting back to me!
