### ISSUE TITLE
Errors when installing with UAC disabled

### ISSUE THREAD

**Issue by ghost** [mhammond/pywin32#598]
If your installation of pywin32 on Windows 7 always end with 

close failed in file object destructor:
sys.excepthook is missing
lost sys.stderr

This is maybe because you are running Windows under the "Administrator" account and anything you normally run is equal to a "run as Administrator"

And paradoxically running the installation of pywin32 on Windows 7 as Administrator causes this error.

So a workaround is to create another admin account

net user Admin /add
net user Admin &lt;type your password&gt;
net localgroup Administrators Admin /add

and then run the pywin32 installation with

runas /user:Admin pywin32-217.win32-py2.7.exe

Reported by: class1o1

Original Ticket: [pywin32/bugs/598](https://sourceforge.net/p/pywin32/bugs/598)

**Comment by mhammond** [comment]
I don't think this is related to UAC - I occasionally see the same error when testing. I'm not sure what causes this, but I'll track it in #498.
