### ISSUE TITLE
errors towards the end of installation.

### ISSUE THREAD

**Issue by ghost** [mhammond/pywin32#599]
While trying to install pywin32-217.win-amd64-py2.6.exe, I get following errors towards the end of installation.

Traceback \(most recent call last\):

File "&lt;string&gt;", line 612, in &lt;module&gt;

File "&lt;string&gt;", line 322, in install

File "&lt;string&gt;", line 160, in LoadSystemModule

ImportError: DLL load failed: The specified module could not be found.

Reported by: *anonymous

Original Ticket: [pywin32/bugs/599](https://sourceforge.net/p/pywin32/bugs/599)

**Comment by Avasam** [comment]
[.exe/binary installers are now deprecated](https://github.com/mhammond/pywin32#binaries) and a lot of DLL location issues have been resolved since then, especially by using wheels available on PyPI
