### ISSUE TITLE
Unhelpful traceback if sdk_dir is None

### ISSUE THREAD

**Issue by ghost** [mhammond/pywin32#600]
In setup.py, the global variable sdk\_dir is set on line 310 by find\_platform\_sdk\_dir\(\).

If find\_platform\_sdk\_dir\(\) can't find a Platform SDK it returns None, since os.environ.get\("MSSdk"\) on line 162 returns None.

Later, sdk\_dir is used as the first argument to os.path.join on line 604, but this fails with a slightly unhelpful traceback:

Traceback \(most recent call last\):
File "setup.py", line 1945, in &lt;module&gt;
""" % dirs\).split\(\),
File "setup.py", line 604, in \_\_init\_\_
if os.path.isfile\(os.path.join\(sdk\_dir, "include", "activdbg.h"\)\):
File "H:\external\local\_windows\_32\_vc8\python27\lib\ntpath.py", line 96, in join
assert len\(path\) &gt; 0
TypeError: object of type 'NoneType' has no len\(\)

A check for "if sdk\_dir is None" after line 310 with a relevant error messge would be nice :-\)

I'm hitting this problem because I'm building with Visual Studio 2005, whose Platform SDK is at C:\Program Files \(x86\)\Microsoft Visual Studio 8\VC\PlatformSDK \(on a 64bit system, but building the 32bit binaries\).

Thanks for all the hard work on this package\!

Reported by: stevenwinfield

Original Ticket: [pywin32/bugs/600](https://sourceforge.net/p/pywin32/bugs/600)

**Comment by Avasam** [comment]
@mhammond I believe this should be closed by https://github.com/mhammond/pywin32/pull/1936
