### ISSUE TITLE
ISAPI dll loading failed with pywin32 x64 version

### ISSUE THREAD

**Issue by ghost** [mhammond/pywin32#614]
I installed ActivePython 2.7 on the WinServer 2008r2. Activepython 2.7 comes with pywin32. The use of ISAPI package fails with error 500.0. THe IIS failure page is at http://snag.gy/33FuZ.jpg 

I have verified with dumpbin that the PyISAPI.dll that comes with the package is indeed x64 version.

I worked around this problem by installing x86 activepython + pywin32 on the same machine. And let IIS to load 32bit applications.

Reported by: *anonymous

Original Ticket: [pywin32/bugs/614](https://sourceforge.net/p/pywin32/bugs/614)

**Comment by Avasam** [comment]
OP can't be contacted anymore and their failure image is a broken link.
The linked pywinstaller issue was also just a typo.

Given the OP's workaround/resolution, I can only assume that this had to do with the version of pywin32 being shipped with ActivePython at the time (see similar issues with Conda  https://github.com/mhammond/pywin32/issues/1865), the install location (see: https://github.com/mhammond/pywin32#troubleshooting) or a bitness inconsistency (32-bit vs 64-bit)
