### ISSUE TITLE
Header files missing in pywin32-218.zip

### ISSUE THREAD

**Issue by ghost** [mhammond/pywin32#619]
Building pywin32-218 from the source distribution, pywin32-218.zip, fails because several header files are missing from win32\src\PerfMon and other source directories. Building from Mercurial repository works.

Reported by: cjgohlke

Original Ticket: [pywin32/bugs/619](https://sourceforge.net/p/pywin32/bugs/619)

**Comment by Avasam** [comment]
Source distribution is no longer provided.
Documentation to build from source can be found here: https://github.com/mhammond/pywin32#building-from-source
