### ISSUE TITLE
Dynamic dispatch and passing arguments by reference

### ISSUE THREAD

**Issue by ghost** [mhammond/pywin32#622]
I have the following problem when calling methods that accept arguments passed by reference.

Consider the following code:

import win32com.client
import pythoncom
sldworks = win32com.client.gencache.EnsureModule\('\{83A33D31-27C5-11CE-BFD4-00400513BB57\}', 0, 21, 0\)
swconst = win32com.client.gencache.EnsureModule\('\{4687F359-55D0-4CD3-B6CF-2EB42C11F989\}', 0, 21, 0\)
sw = sldworks.SldWorks\(\)
model\_path = 'C:\Demo\model.SLDPRT'
model, errors, warnings = sw.OpenDoc6\(model\_path, swconst.constants.swDocPART, swconst.constants.swOpenDocOptions\_Silent, '', pythoncom.Missing, pythoncom.Missing\)
ext = model.Extension

In case of static dispatch it works correctly:

&gt;&gt;&gt; ext
&gt;&gt;&gt;  &lt;win32com.gen\_py.SldWorks 2013 Type Library.IModelDocExtension instance at 0x206388400&gt;
&gt;&gt;&gt; ext.GetAdvancedSpotLightProperties\('Ambient'\)
&gt;&gt;&gt; \(0.0, 1.0, 0.0, 0.0\)

In case of dynamic dispatch it sets wrong value for the last argument:

dext = win32com.client.dynamic.DumbDispatch\(ext\)
arg1 = win32com.client.VARIANT\(pythoncom.VT\_BYREF | pythoncom.VT\_R8, 0.0\)
arg2 = win32com.client.VARIANT\(pythoncom.VT\_BYREF | pythoncom.VT\_R8, 0.0\)
arg3 = win32com.client.VARIANT\(pythoncom.VT\_BYREF | pythoncom.VT\_R8, 0.0\)
arg4 = win32com.client.VARIANT\(pythoncom.VT\_BYREF | pythoncom.VT\_R8, 0.0\)

&gt;&gt;&gt; dext
&gt;&gt;&gt; &lt;COMObject &lt;unknown&gt;&gt;
&gt;&gt;&gt; dext.GetAdvancedSpotLightProperties\('Ambient', arg1, arg2, arg3, arg4\)
&gt;&gt;&gt; arg1.value, arg2.value, arg3.value, arg4.value
&gt;&gt;&gt; \(0.0, 1.0, 0.0, u'Ambient'\)

I've checked more methods in SolidWorks API: in case of dynamic dispatch, when arguments are passed by reference, value of the last argument equals to the value of the first argument after call.

Since pywin32 fails to provide static dispatch object in some cases,
\(for example, if I call model.SelectionManager, it returns &lt;COMObject SelectionManager&gt;\),
I can't use some methods in SolidWorks API.

Reported by: n-perestoronin

Original Ticket: [pywin32/bugs/622](https://sourceforge.net/p/pywin32/bugs/622)

**Comment by hauptmech** [comment]
I'm facing this issue too. Here's an example signature from solidworks for the call that's failing.
```
[id(0x00000005), helpstring("Gets data from matrix"), helpcontext(0x06900005)] 
		HRESULT GetData(
			[in, out] IDispatch** XAxisObjOut,
			[in, out] IDispatch** YAxisObjOut,
			[in, out] IDispatch** ZAxisObjOut,
			[in, out] IDispatch** TransformObjOut,
			[in, out] double* ScaleOut
		);
```
byref arguments are returned in reverse order.

relevant snippets from makepy, using GetData2 which has the exact same signature :
```
class IMathTransform(DispatchBaseClass):
	'Interface for MathTransform'
	CLSID = IID('{F7D97F82-162E-11D4-AEAB-00C04FA0AC51}')
	coclass_clsid = IID('{F7D97F83-162E-11D4-AEAB-00C04FA0AC51}')

	def GetData2(self, XAxisObjOut=defaultNamedNotOptArg, YAxisObjOut=defaultNamedNotOptArg, ZAxisObjOut=defaultNamedNotOptArg, TransformObjOut=defaultNamedNotOptArg
			, ScaleOut=defaultNamedNotOptArg):
		'Gets data from matrix'
		return self._ApplyTypes_(11, 1, (24, 0), ((16393, 3), (16393, 3), (16393, 3), (16393, 3), (16389, 3)), 'GetData2', None,XAxisObjOut

<snip>
IMathTransform_vtables_ = [
	(( 'GetData2' , 'XAxisObjOut' , 'YAxisObjOut' , 'ZAxisObjOut' , 'TransformObjOut' , 
			 'ScaleOut' , ), 11, (11, (), [ (16393, 3, None, None) , (16393, 3, None, None) , (16393, 3, None, None) , 
			 (16393, 3, None, None) , (16389, 3, None, None) , ], 1 , 1 , 4 , 0 , 152 , (3, 0, None, None) , 0 , )),
```

I'm currently calling it with a helper function as follows:

```
def GetData2(T):
    A1 = client.VARIANT(pythoncom.VT_BYREF | pythoncom.VT_DISPATCH, None)
    A2 = client.VARIANT(pythoncom.VT_BYREF | pythoncom.VT_DISPATCH, None)
    A3 = client.VARIANT(pythoncom.VT_BYREF | pythoncom.VT_DISPATCH, None)
    A4 = client.VARIANT(pythoncom.VT_BYREF | pythoncom.VT_DISPATCH, None)
    A5 = client.VARIANT(pythoncom.VT_BYREF | pythoncom.VT_R8, 0.0)
    res1 = T.GetData2(A1,A2,A3,A4,A5)
    
    return (A5.value.ArrayData,A4.value.ArrayData,A3.value.ArrayData,A2.value.ArrayData,A1.value)
```
where T is of type `<COMObject <unknown>>`

**Comment by hauptmech** [comment]
I dug deeper into this. I get a type mismatch com_error if I reverse the order passed in so the order they are going in is correct. I waded through PyIDispatch.cpp and can see that the order they are going in should match the order coming out. 

For now I'm assuming that there is something wrong on the solidworks side

**Comment by mhammond** [comment]
Thanks - and yeah, I'd expect that if we were consistently passing args in the wrong order it would have been noticed well before now.

**Comment by qfdragon** [comment]
Another open bug reported here: 
> https://github.com/mhammond/pywin32/issues/1303
