### ISSUE TITLE
Installer error message on pywin32-218.win32-py2.7 

### ISSUE THREAD

**Issue by ghost** [mhammond/pywin32#625]
Installer completed with error message:

close failed in file object destructor:
sys.excepthook is missing
lost sys.stderr

Reported by: cpu2

Original Ticket: [pywin32/bugs/625](https://sourceforge.net/p/pywin32/bugs/625)

**Comment by segevfiner** [comment]
I'm seeing this with pywin32-222.win32-py2.7.exe on Python 2.7.14 on Windows 10.0.16299.192 with UAC enabled at the default level.
