### ISSUE TITLE
installation won't run

### ISSUE THREAD

**Issue by ghost** [mhammond/pywin32#641]
Trying to install win32 2.7.4 on Windows 7 64-bit \(all patches up-to-date\) and keep receiving a message that the system can't execute a necessary .dll required for installation.  I'm not a programmer; I made sure all the security permissions were complete, and tried turning off anti-virus, etc.  Nothing works.  I'd installed Python at a previous time, and uninstalled that to install this update.

This seems to be the only place with a hope of getting support.  In browsing prior posts I did find one with the the subject, "\[pywin32-bugs\] \[ pywin32-Bugs-3607350 \] pywin32 218 amd64 vista py3.3.0 installation Issue," that seems to be related.

Any help or suggestions would be much appreciated.  Thanks.  \(Python 2.7.4 is a prerequisite for an application I'd like to install\).

Reported by: mbmaser

Original Ticket: [pywin32/bugs/641](https://sourceforge.net/p/pywin32/bugs/641)

**Comment by Avasam** [comment]
@mhammond Given this issue was about installing on Python 2.7.4 specifically, and contains no additional information. Should it be closed?
