### ISSUE TITLE
Control-V not mapped to Watch pane

### ISSUE THREAD

**Issue by ghost** [mhammond/pywin32#644]
In the Watch window if you double click on a variable, you can type a new name for it.
bug: But if you hit Control-V to paste text in, it gets pasted into the code window instead.

expected behavior: Control-V \(and Control-C, Control-X, etc.\) should map to the highlighted watch variable.

Reported by: nicksjacobson

Original Ticket: [pywin32/bugs/644](https://sourceforge.net/p/pywin32/bugs/644)

**Comment by Avasam** [comment]
Confirmed this issue is still valid
![copy paste](https://github.com/mhammond/pywin32/assets/1350584/6ee7159e-5fb7-4767-85c9-430a6ca74b92)
