### ISSUE TITLE
Installation Bug

### ISSUE THREAD

**Issue by ghost** [mhammond/pywin32#646]
When I tried to install pywin32 from source, I got the following error:
  File "<string>", line 2283, in <module>
  File "<string>", line 2074, in convert_data_files
  RuntimeError: No files match 'pythonwin\pywin\*.cfg'

I checked the "pythonwin/pywin" folder and there was two files with the ".cfg" file extension, the "IDLE.cfg" and the "default.cfg".

Any Ideas?

Reported by: tyyppi77

Original Ticket: [pywin32/bugs/646](https://sourceforge.net/p/pywin32/bugs/646)

**Comment by Avasam** [comment]
Given the sheer amount of installation issues duplication and old history, I'd like to consolidate the current state of these issues. So I'll close and reference back any issue that only has comments showing the issue:
- from before November 10th, 2019 (pywin32<226)
- using `.exe` installers
- using Python < 3.8

Please also try https://github.com/mhammond/pywin32#troubleshooting before opening a new issue, or let us, and others, know here if it did fix your issue.
