### ISSUE TITLE
version 218 compilation error

### ISSUE THREAD

**Issue by ghost** [mhammond/pywin32#647]
I am trying to use the bdist_msi distribution build option from the latest sources because I need to do a silent install of the win32 extensions for python 2.7.  However, when I try to compile, I get the following error:

c:\Program Files\Microsoft Visual Studio 9.0\VC\BIN\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -DDISTUTILS_BUILD -D_CRT_SECURE_NO_WARNINGS -Icom/win32com/src/include -Iwin32/src -Ic:\Python27\include -Ic:\Python27\PC "-IC:\Program Files\Microsoft SDKs\Windows\v6.0A\include" /Tpwin32\src\perfmon\perfmondata.cpp /Fobuild\temp.win32-2.7\Release\win32\src\perfmon\perfmondata.obj /Zi /Fdbuild\temp.win32-2.7\Release\perfmondata_vc.pdb /EHsc /DMFC_OCC_IMPL_H=\"..\src\occimpl.h\" /DUNICODE /D_UNICODE /DWINNT
perfmondata.cpp
win32\src\perfmon\perfmondata.cpp(11) : fatal error C1083: Cannot open include file: 'perfutil.h': No such file or directory
error: command '"c:\Program Files\Microsoft Visual Studio 9.0\VC\BIN\cl.exe"' failed with exit status 2

As far as I can tell, I am up to date on VS2008 patches, so what is going on here, and how do I fix it?
(full build log attached.)

Thanks in advance,
/Will Sadkin
Parlance Corporation

Reported by: wsadkin

Original Ticket: [pywin32/bugs/647](https://sourceforge.net/p/pywin32/bugs/647)

**Comment by Avasam** [comment]
Issue specific to pywin32==218 . Which isn't currently available anymore on PyPI and build instructions are different than from back then.
