### ISSUE TITLE
pywin32-218.win-amd64-py2.7 stops working

### ISSUE THREAD

**Issue by ghost** [mhammond/pywin32#655]
I recently had to replace my hard drive due to a catastrophic failure. I am running Windows 7. I have installed Python 2.7.5 (64-bit). When attempting to run the pywin installer, after clicking "Next" through the first three screens, I get a message that "pywin32-218.win-amd64-py2.7 has stopped working". Windows never finds a "solution" to the problem, and I cannot get the installer to run. Based on a Google search for similar problems, I have tried running the installer as an administrator, and I have tried manually setting the Python directory to be not-read-only. Nothing is working. (I can see inside the archive with 7-Zip; is it possible to manually install?)

Reported by: drgaellon

Original Ticket: [pywin32/bugs/655](https://sourceforge.net/p/pywin32/bugs/655)

**Comment by Avasam** [comment]
@mhammond This issue happened with .exe installer (now obsolete) and seems to have been caused by specificity of the user environment. Moreso this was with a Python 2 version of a pywin32 installer.
