### ISSUE TITLE
pip database is not updated

### ISSUE THREAD

**Issue by ghost** [mhammond/pywin32#658]
Hi,

I installed the package using the installer from this page. When I run `pip search pywin32` I get the following response. I suppose the database is not up-to-date. Could you please fix that?

    pywin32                   - Python extensions for Windows
      INSTALLED: 218
      LATEST:    214

Reported by: volongoto

Original Ticket: [pywin32/bugs/658](https://sourceforge.net/p/pywin32/bugs/658)

**Comment by Avasam** [comment]
```
ERROR: XMLRPC request failed [code: -32500]
RuntimeError: PyPI no longer supports 'pip search' (or XML-RPC search). Please use https://pypi.org/search (via a browser) instead. See https://warehouse.pypa.io/api-reference/xml-rpc.html#deprecated-methods for more information.
```
