### ISSUE TITLE
Pywin32 script install doesn't work on Windows 8.1

### ISSUE THREAD

**Issue by ghost** [mhammond/pywin32#660]
Hello,

My IT group has built a python script that runs as a service on our windows boxes and makes use of the pywin32 module. However, we are attempting to upgrade to Windows 8.1 and need an automated way to install the pywin32 module to python. However, the setup.py fails with the following error: 

Traceback (most recent call last):
File "\\path\to\setup.py", line 1957, in <module>
""" % dirs).split()
File "\\path\to\setup.py", line 605,
in __init__
if os.path.isfile(os.path.join(sdk_dir, "include", "activng.h")):
File "\\other\path\to\ntpath.py, line 96, in join
assert len(path) > 0
TypeError: object of type 'NoneType' has no len()

The GUI installer has given me no problems, but that is not an option, as this should be an unattended install.

Thanks!

Reported by: jbray1982

Original Ticket: [pywin32/bugs/660](https://sourceforge.net/p/pywin32/bugs/660)

**Comment by Avasam** [comment]
> if os.path.isfile(os.path.join(sdk_dir, "include", "activng.h")):

@mhammond I believe this should be closed by https://github.com/mhammond/pywin32/pull/1936
