### ISSUE TITLE
DeprecationWarning in pywintypes.py

### ISSUE THREAD

**Issue by ghost** [mhammond/pywin32#663]
Received this warning while working with [django](https://docs.djangoproject.com/en/1.6/intro/tutorial01/):

C:\Python33\lib\site-packages\win32\lib\pywintypes.py:39: DeprecationWarning: imp.get_suffixes() is deprecated; use the constants defined on importlib.machinery instead
&nbsp;&nbsp;for suffix_item in imp.get_suffixes():

pywin32 build 218
Python 3.3.3 (v3.3.3:c3896275c0f6, Nov 18 2013, 21:18:40) [MSC v.1600 32 bit (Intel)] on win32

I've seen other reports of this problem, but no resolution.

http://stackoverflow.com/questions/20839558/imp-get-suffixes-is-deprecated-how-to-repair-it

https://groups.google.com/d/msg/django-users/P4UX6tzceLk/H1kIZjOd08MJ

Reported by: bigjimtx

Original Ticket: [pywin32/bugs/663](https://sourceforge.net/p/pywin32/bugs/663)

**Comment by Avasam** [comment]
Fixed by https://github.com/mhammond/pywin32/commit/201db642fc8dc1b2871da626f0865ee37110e262
