### ISSUE TITLE
win32api GetNativeSystemInf() crashes Python interpreter - fix provided

### ISSUE THREAD

**Issue by ghost** [mhammond/pywin32#665]
This issue is caused by a one like copy/paste error in win32apimodule.cpp on line 2192.

CHECK_PFN(SetSystemPowerState); should be CHECK_PFN(GetNativeSystemInfo);

When called on Windows 2000 (where GetNativeSystemInfo does not exist), CHECK_PFN returns successfully since SetSystemPowerState exists.  The function goes on to call GetNativeSystemInfo which is NULL and the access violation in unmanaged code crashes the whole process.

Reported by: marqo09

Original Ticket: [pywin32/bugs/665](https://sourceforge.net/p/pywin32/bugs/665)

**Comment by Avasam** [comment]
Fixed by https://github.com/mhammond/pywin32/commit/ae392dadc60779890649f8d8ca2149069260e430
