### ISSUE TITLE
'pip install pywin32' doesn't work

### ISSUE THREAD

**Issue by ghost** [mhammond/pywin32#669]
It would be great if pywin32 could be distributed as a binary wheel.  This is the last remaining dependency of Twisted on Windows which requires manual intervention and installation.

Reported by: glyf

Original Ticket: [pywin32/bugs/669](https://sourceforge.net/p/pywin32/bugs/669)

**Comment by Avasam** [comment]
> For what it's worth, `python setup.py bdist_wheel` _almost_ works.

Note that [`python setup.py` and the use of setup.py as a command line tool are deprecated](https://packaging.python.org/en/latest/discussions/setup-py-deprecated/#is-setup-py-deprecated). pywin32 itself needs to move away from it. #2208

**Comment by Avasam** [comment]
@glyph Is this issue still relevant? Are the current wheels good for Twisted or do you still need anything?

**Comment by glyph** [comment]
@Avasam I think that this was fixed quite some time ago, not sure why the issue is still open.  `pip install pywin32` works pretty much everywhere I try it, so, I think I'm good!

**Comment by Avasam** [comment]
> not sure why the issue is still open

That's what I'm working through rn ^^" Lots of old issues migrated from sourceforge.

Thanks for taking the time to answer!
