### ISSUE TITLE
Intermittent access violation using win32cred.CredRead

### ISSUE THREAD

**Issue by ghost** [mhammond/pywin32#670]
Issue is intermittent and may be difficult to reproduce.

Call win32cred.CredRead with a TargetName that does not exist. This will randomly cause Python to crash with an access violation.

I believe the root cause is that the variable "cred" in PyCredRead is not being initialized. If the call to CredRead fails it will not set cred to any value. Since cred is uninitialized there's a random chance the PyCredRead will call CredFree on an invalid address.

Initializing cred to NULL stopped the crash from occurring during my testing.

Reported by: dsoeder

Original Ticket: [pywin32/bugs/670](https://sourceforge.net/p/pywin32/bugs/670)

**Comment by Avasam** [comment]
Fixed by f6f6c382f900195b2e73bb32daa6b73ed3bc3dad
