### ISSUE TITLE
several files missing from adodbapi

### ISSUE THREAD

**Issue by ghost** [mhammond/pywin32#671]
Reported by:Sibylle Koczian <nulla.epistola@web.de>
to:	 PyWin-Liste <python-win32@python.org>
date:	 Wed, May 28, 2014 at 4:12 PM
-- -- -- -- -- --
I just installed Python 3.4.1 and pywin32, using pywin32-219.win-amd64-py3.4.exe. No problems, no error messages during installation.

When I try to use adodbapi, I get an ImportError:

Python 3.4.1 (v3.4.1:c0e311e010fc, May 18 2014, 10:45:13) [MSC v.1600 64 bit (AMD64)] on win32
Type "copyright", "credits" or "license()" for more information.
>>> import adodbapi
Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    import adodbapi
  File "C:\Python34\lib\site-packages\adodbapi\__init__.py", line 16, in <module>
    from .apibase import apilevel, threadsafety, paramstyle
ImportError: No module named 'adodbapi.apibase'
>>>

In fact there is no file called "apibase" in my Python34 directory.
-- -- -- -- - - 

Reply from: Vernon Cole

Several files are missing.

You can work around this problem my installing adodbapi from pypi or sourceforge:

(in Python 3.4)
py -3 -m pip install adodbapi

(if you have pip installed)
pip install adodbapi --upgrade

(otherwise)
http://sourceforge.net/projects/adodbapi/files/latest/download?source=dlp

Note that there is no difference between adodbapi 2.6.0.6 and 2.6.0.7, except that the latter will download directly from pypi and not try using the (broken) url link.

Reported by: kf7xm

Original Ticket: [pywin32/bugs/671](https://sourceforge.net/p/pywin32/bugs/671)

**Comment by Avasam** [comment]
This should be resolved by now and adodbapi is available from the PyPI distributions
```py
>>> import adodbapi
>>> import adodbapi.apibase
# No error
```
