### ISSUE TITLE
distribute binaries somewhere that is at least marginally secure (stop using sourceforge)

### ISSUE THREAD

**Issue by ghost** [mhammond/pywin32#673]
Sourceforge appears uninterested in securing their file distribution infrastrucutre even a little bit, so it would be helpful to distribute downloads via Google Code or Bitbucket or Gitlab or PyPI, anywhere that has HTTPS download links: https://sourceforge.net/p/forge/feature-requests/270/

Reported by: glyf

Original Ticket: [pywin32/bugs/673](https://sourceforge.net/p/pywin32/bugs/673)

**Comment by Avasam** [comment]
pywin32 is now distributed on PyPI
