### ISSUE TITLE
pywin32 219 for Python 2.6 Broken Installer

### ISSUE THREAD

**Issue by ghost** [mhammond/pywin32#674]
After extracting the executables for both versions 218 and 219 of pywin32 for python2.6, you can see the directory pywin32_system32 is missing. This forces the installation to fail on 219 during the postinstall script.

Reported by: jb2780

Original Ticket: [pywin32/bugs/674](https://sourceforge.net/p/pywin32/bugs/674)

**Comment by Avasam** [comment]
@mhammond This issue seems to be about Python 2.6 support, which is no longer relevant. Should maybe close?
