### ISSUE TITLE
error 234 on PyRegEnumValue and RegEnumKey

### ISSUE THREAD

**Issue by ghost** [mhammond/pywin32#677]
Hi,
I 'm facing to an issue regarding RegEnumKey and RegEnumValue.
On japanese windows 2008r2, for some registry key, I have the following error:
(234, 'PyRegEnumValue', 'Plus de donnees sont disponibles .')
CopyValue agent
(234, 'RegEnumKey', 'Plus de donnees sont disponibles .')

In order to reproduce this bug, you need to switch Windows to Japanese locale(Localized.png)
This issue don't exist with US locale.
After, you only need to import reg file and start test_pywin32_reg.py

This bug is already mentionned as Bug 356.
I made the same test with the last pywin32 release. I have the same error.

Best regards

Reported by: ddoe99

Original Ticket: [pywin32/bugs/677](https://sourceforge.net/p/pywin32/bugs/677)

**Comment by mhammond** [comment]
> This issue does not exist anymore in python3.

Great, thanks!
