### ISSUE TITLE
Upload latest version to pypi

### ISSUE THREAD

**Issue by ghost** [mhammond/pywin32#680]
The latest version of pywin32 in pypi is out of date and contains no distributions:
https://pypi.python.org/pypi/pywin32
The latest version should be uploaded so that pywin32 can be installed using easy_install / pip

Reported by: wiggin15

Original Ticket: [pywin32/bugs/680](https://sourceforge.net/p/pywin32/bugs/680)

**Comment by Avasam** [comment]
PyPI is now the main distribution location (exe installers are being deprecated, and you could always build from source)
