### ISSUE TITLE
CreateWindowFromHandle causes app crash in embedded Win32 app

### ISSUE THREAD

**Issue by ghost** [mhammond/pywin32#681]
Python is embedded in our main app.
I use 'Very High Level Embedding' and just call PyRun_SimpleString. The string is created on the fly with the current window handle embedded.
The called script looks something like that:

shellHandle = 0x0...0  #Handle is filled on the fly
import win32api
wnd = win32ui.CreateWindowFromHandle(shellHandle)
wnd.SetWindowText("new window text")

The text of the window has changed but when the script has finished the app crashes.
What happens at the end of the script?
Is Destroy called on wnd? (which should not)

System: Window 8.1 64bit
Python: 3.4.1 
Pythonwin: build 219

Reported by: egalo

Original Ticket: [pywin32/bugs/681](https://sourceforge.net/p/pywin32/bugs/681)

**Comment by mhammond** [comment]
This is very old and may even be fixed by #1841
