### ISSUE TITLE
[adodbapi]Failed to update the data in more than 510 characters by args

### ISSUE THREAD

**Issue by xoviat** [mhammond/pywin32#683]
- Python 2.7.8
- pywin32 218
- Windows XP SP3

Update a string (`text`) which have 903 characters to the MS Access *.mdb:
`All work and no play makes Jack a dull boy.All work and no play makes Jack a dull boy.All work and no play makes Jack a dull boy.All work and no play makes Jack a dull boy.All work and no play makes Jack a dull boy.All work and no play makes Jack a dull boy.All work and no play makes Jack a dull boy.All work and no play makes Jack a dull boy.All work and no play makes Jack a dull boy.All work and no play makes Jack a dull boy.All work and no play makes Jack a dull boy.All work and no play makes Jack a dull boy.All work and no play makes Jack a dull boy.All work and no play makes Jack a dull boy.All work and no play makes Jack a dull boy.All work and no play makes Jack a dull boy.All work and no play makes Jack a dull boy.All work and no play makes Jack a dull boy.All work and no play makes Jack a dull boy.All work and no play makes Jack a dull boy.All work and no play makes Jack a dull boy.`

By using the following code:
    sql = "update Paragraphs set Data = ?  where Id = ?"
    args = [text, id]
    cur.execute(sql, args)
    conn.commit() 
    cur.close()
    conn.close()

Then open the *.mdb by MS Access to browse the data, now there are 510 characters only:
`All work and no play makes Jack a dull boy.All work and no play makes Jack a dull boy.All work and no play makes Jack a dull boy.All work and no play makes Jack a dull boy.All work and no play makes Jack a dull boy.All work and no play makes Jack a dull boy.All work and no play makes Jack a dull boy.All work and no play makes Jack a dull boy.All work and no play makes Jack a dull boy.All work and no play makes Jack a dull boy.All work and no play makes Jack a dull boy.All work and no play makes Jack a dul`

But if I don't use args at all:
    sql = "update Paragraphs set Data = '%s'  where Id = %d" % (text, id)
    cur.execute(sql)
    conn.commit() 
    cur.close()
    conn.close()

All of the characters will be updated successfully.

Reported by: darkranger-red

Original Ticket: [pywin32/bugs/683](https://sourceforge.net/p/pywin32/bugs/683)

**Comment by vernondcole** [comment]
already fixed
