### ISSUE TITLE
unsupported character in PyTime format string causes python 2.7.8 crash

### ISSUE THREAD

**Issue by ghost** [mhammond/pywin32#692]
To clarify:  Python itself crashes.

Environment:
Python 2.7.8 (32-bit) on Windows 7
Running from console window with .py extension set in PATH_EXT environment variable.

    :::python
    import win32file
    
    ftest = 'c:\\temp\\temp.txt'
    print '\n' + ftest
    handle_ftest = win32file.CreateFile(ftest,win32file.GENERIC_READ,0,None,win32file.OPEN_EXISTING,0,None)
    py_ctime, py_atime, py_mtime = win32file.GetFileTime(handle_ftest)
    #print py_ctime.Format('%Y-%m-%d %H:%M:%S.%f') #<< unsupported millisecond format parameter causes python 2.7 to crash
    
    print py_ctime.Format('%Y-%m-%d %H:%M:%S') #<< otherwise works fine
    
    handle_ftest.close

workaround:
ignore ms or use built-in datetime instead.

Cheers,
--bm

Reported by: vorpalswordsman

Original Ticket: [pywin32/bugs/692](https://sourceforge.net/p/pywin32/bugs/692)

**Comment by Avasam** [comment]
Python 3.9, pywin32 306, Windows 10:
```python
import win32file

ftest = "c:\\temp\\temp.txt"
print("\n" + ftest)
handle_ftest = win32file.CreateFile(ftest, win32file.GENERIC_READ, 0, None, win32file.OPEN_EXISTING, 0, None)
py_ctime, py_atime, py_mtime = win32file.GetFileTime(handle_ftest)

print(py_ctime.Format("%Y-%m-%d %H:%M:%S.%f"))
print(py_ctime.Format("%Y-%m-%d %H:%M:%S"))

handle_ftest.close
```
```
c:\temp\temp.txt
2024-03-17 01:35:02.069000
2024-03-17 01:35:02
```
