### ISSUE TITLE
TypeError: 'str' does not support the buffer interface in ResourceUpdate

### ISSUE THREAD

**Issue by ghost** [mhammond/pywin32#694]
This occurs in PyInstaller when trying to update a Manifest. The version is pywin32-219.win-amd64-py3.4. The call is

`win32api.UpdateResource(hdst, type_, name, data, language)`

where hdst=63307784, type_=24, name=1, language=0 and data=

    <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
    <assembly manifestVersion="1.0" xmlns="urn:schemas-microsoft-com:asm.v1">
    <assemblyIdentity name="PPQT2" processorArchitecture="amd64" type="win32"
    version="1.0.0.0"/></assembly>'

The "str does not support the buffer interface" error is a very common Python3 problem, indicating passing a str to a file opened as raw bytes.

Reported by: dcortesi

Original Ticket: [pywin32/bugs/694](https://sourceforge.net/p/pywin32/bugs/694)

**Comment by Avasam** [comment]
It now does:
```python
>>> import win32api
>>>
>>> hdst=63307784
>>> type_=24
>>> name=1
>>> language=0
>>> data="""
...     <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
...     <assembly manifestVersion="1.0" xmlns="urn:schemas-microsoft-com:asm.v1">
...       <assemblyIdentity name="PPQT2" processorArchitecture="amd64" type="win32" version="1.0.0.0"/>
...     </assembly>
... """
>>>
>>> win32api.UpdateResource(hdst, type_, name, data, language)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: a bytes-like object is required, not 'str'
```
