### ISSUE TITLE
219 3.5 32-bit Installer does not find Python registry key

### ISSUE THREAD

**Issue by ghost** [mhammond/pywin32#702]
Hi there,

I've just installed Python 3.5.0 on my Windows 7 box, followed by Python for Windows Extensions 219 for Python 3.5. All worked well.

However, I then successfully installed Python 3.5.0 32-bit and attempted to install Python for Windows Extensions 219 for Python 3.5 32-bit. The installer produced the error message "Python 3.5 required, which was not found in the registry". The following window would not allow me to enter any characters into "Python Directory" or "Installation Directory".

This was not a problem with version 3.4. The keys installed by Python 3.5 have changed and it appears that the 32-bit Python for Windows Extension 219 for Python 3.5 installer does not recognise any of these keys or at least the key it is supposed to.

Reported by: nobody

Original Ticket: [pywin32/bugs/702](https://sourceforge.net/p/pywin32/bugs/702)

**Comment by Avasam** [comment]
[.exe installers are now deprecated](https://github.com/mhammond/pywin32#binaries) and wheels for all bitness are available on PyPI
