### ISSUE TITLE
pywin32-32 fails to install on Win 7-64/Py 3.5-32

### ISSUE THREAD

**Issue by ghost** [mhammond/pywin32#707]
I installed Python 3.5-32 on Win7-64. But when I tried to install pywin32 the installer popped up a "Cannot install" dialog saying "Python version 3.5 required, which was not found in the registry".

Of course, it is possible that the Python 3.5 32-bit installer is at fault (i.e., maybe it hasn't updated the registry--although I used admin privileges and did an install for all), but I don't know how to discover that.

The packages I used:
python-3.5.0.exe
pywin32-219.win32-py3.5.exe

Reported by: m_n_summerfield

Original Ticket: [pywin32/bugs/707](https://sourceforge.net/p/pywin32/bugs/707)

**Comment by Avasam** [comment]
[.exe installers are now deprecated](https://github.com/mhammond/pywin32#binaries) and wheels for all bitness are available on PyPI
