### ISSUE TITLE
pyWin32-py3.5 uses a different vc runtime than python 3.5

### ISSUE THREAD

**Issue by ghost** [mhammond/pywin32#708]
Hi I just found an issue with pyWin32 failing to install on a system that doesn't have the vc2010 runtime loaded.
The pyd dll files still depend of the vc2010 runtime but python 35 now uses the vc2015 runtime (non xp).
(only tested the 64 bit build but I also see that the 32 bit pyd files still depend on MSVCR100.dll)

*I think this could cause issues (like heap corruption) if the runtimes are different.

Note though that the vc2015 runtime that python 35 uses is isolated in the python root folder - and may be a different version than the official MS install -- which is actually the case now as vc2015 update 1 has been relaeased.

This is the issue behind bug #706
https://sourceforge.net/p/pywin32/bugs/706/

Reported by: bmiller_qw

Original Ticket: [pywin32/bugs/708](https://sourceforge.net/p/pywin32/bugs/708)

**Comment by Avasam** [comment]
[.exe/binary installers are now deprecated](https://github.com/mhammond/pywin32#binaries) and wheels for all bitness are available on PyPI
This issue should also be fixed in pywin32>=220
