### ISSUE TITLE
win32file._get_osfhandle crashes python3.5

### ISSUE THREAD

**Issue by ghost** [mhammond/pywin32#711]
calls to win32file._get_osfhandle cause python 3.5 to crash on windows 10.

this has been logged as a bug on a number of packages but probably should be here.
https://github.com/google/google-api-python-client/issues/139
https://github.com/google/oauth2client/issues/361
https://github.com/web2py/pydal/issues/3100

Reported by: simoneva

Original Ticket: [pywin32/bugs/711](https://sourceforge.net/p/pywin32/bugs/711)

**Comment by Avasam** [comment]
Python 3.5 specific compilation issue, Python 3.5 is no longer supported (and issue should've already been fixed back then)
