### ISSUE TITLE
no links on https://pypi.python.org/simple/pywin32/

### ISSUE THREAD

**Issue by ghost** [mhammond/pywin32#713]
I think that your pywin32 is great (thanks very much!) but when I tried to install it with pip this time it did not work apparently because https://pypi.python.org/simple/pywin32/ includes no links
(Subsequently I could not download it directly from sourceforge because my job here thinkgs it is a virus hazard but that has nothing to do with your superb software.)
Best regards,
Rob

Reported by: dutchrob

Original Ticket: [pywin32/bugs/713](https://sourceforge.net/p/pywin32/bugs/713)

**Comment by Avasam** [comment]
It now does!
