### ISSUE TITLE
GetTickCount should be unsigned

### ISSUE THREAD

**Issue by ghost** [mhammond/pywin32#718]
The call to win32api.GetTickCount() is returning a signed integer. It should be unsigned.

In particular, this causes problems when comparing it to, say, win32api.GetLastInputInfo() which returns an unsigned integer.

For more information, see this StackOverflow question: http://stackoverflow.com/questions/36312480/getlastinputinfo-and-gettickcount-are-not-consistent-with-each-other/

Reported by: oddthinking

Original Ticket: [pywin32/bugs/718](https://sourceforge.net/p/pywin32/bugs/718)

**Comment by fabiopedrosa** [comment]
This has been here for a while.

A quick solution:

```python
tick_count = win32api.GetTickCount()
if tick_count < 0:
    tick_count+= 2**32

```

**Comment by kxrob** [comment]
Should return unsigned 64bit via #1946

**Comment by dreamflow** [comment]
this issue can be closed , because win32api.GetTickCount()
returns an unsigned 64bit integer , since the already released
version 305 of pywin32 .
