### ISSUE TITLE
PyWin mismatch error

### ISSUE THREAD

**Issue by ghost** [mhammond/pywin32#731]
I downloaded/installed the latest Python for 64 bit system
(python-3.6.0b1-amd64) for use on a Win10 system.

figuring that this is now the latest/greatest Python, I then download PyWin
(pywin32-220.win-amd64-py3.6)

I get the following error - what combination should I be using?

Reported by: swsolutionsnv

Original Ticket: [pywin32/bugs/731](https://sourceforge.net/p/pywin32/bugs/731)

**Comment by Avasam** [comment]
[.exe installers are now deprecated](https://github.com/mhammond/pywin32#binaries) and wheels for all bitness are available on PyPI
