### ISSUE TITLE
Lack of Python 3.6 builds leads to SyntaxError

### ISSUE THREAD

**Issue by ghost** [mhammond/pywin32#734]
In https://github.com/cherrypy/cherrypy/issues/1537, installation of Python 3.6 in Windows fails due to a dependency on pypiwin32 because the binary builds aren't available. Now that Python 3.6 is final, can you upload binaries for Python 3.6?

Reported by: jaraco

Original Ticket: [pywin32/bugs/734](https://sourceforge.net/p/pywin32/bugs/734)

**Comment by ERaunig** [comment]
This is still an issue as of 11/9/2017. Any way that someone could just fix the syntax error in that file?

**Comment by xoviat** [comment]
Does `pip install pypiwin32` not work?

**Comment by xoviat** [comment]
Also, the syntax error is just the first error. It's hiding thousands of Python and c++ errors that will show up after that's fixed.

**Comment by ERaunig** [comment]
I'm having issues.

In my own development work -I have to fix all bugs before I release
something into the wild. I'm not asking you to do it, but if I had my hands
on the code, I could at least fix that python syntax error in a script
without having to know what it's doing. Better than nothing.

**Comment by ERaunig** [comment]
C:\Users\e.raunig>pip install --no-cache-dir cherrypy
Collecting cherrypy
  Downloading CherryPy-11.1.0-py2.py3-none-any.whl (439kB)
    100% |████████████████████████████████| 440kB 6.0MB/s
Collecting jaraco.classes (from cherrypy)
  Downloading jaraco.classes-1.4.1-py2.py3-none-any.whl
Collecting portend>=2.1.1 (from cherrypy)
  Downloading portend-2.2-py2.py3-none-any.whl
Collecting six>=1.11.0 (from cherrypy)
  Downloading six-1.11.0-py2.py3-none-any.whl
Collecting cheroot>=5.8.3 (from cherrypy)
  Downloading cheroot-5.8.3-py2.py3-none-any.whl (65kB)
    100% |████████████████████████████████| 71kB 7.2MB/s
Collecting pypiwin32; sys_platform == "win32" (from cherrypy)
  Downloading pypiwin32-219.zip (4.8MB)
    100% |████████████████████████████████| 4.8MB 6.0MB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File
"C:\Users\EA4F9~1.RAU\AppData\Local\Temp\pip-build-cfcqknzx\pypiwin32\setup.py",
line 121
        print "Building pywin32", pywin32_version
                               ^
    SyntaxError: Missing parentheses in call to 'print'. Did you mean
print("Building pywin32", pywin32_version)?

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in
C:\Users\EA4F9~1.RAU\AppData\Local\Temp\pip-build-cfcqknzx\pypiwin32\

**Comment by webknjaz** [comment]
Compare https://pypi.python.org/pypi/pypiwin32/219 and https://pypi.python.org/pypi/pypiwin32/220. You'll notice that the last version is missing sdist and lots of wheel binaries, and win installer. Mystery solved.

**Comment by webknjaz** [comment]
@mhammond plz publish complete wheels matrix to PYPI

**Comment by xoviat** [comment]
> I'm not asking you to do it, but if I had my hands
on the code, I could at least fix that python syntax error in a script
without having to know what it's doing. Better than nothing.

Ah yes. Anyone can do that. But can you fix all of the c++ failures that will come after that?

**Comment by xoviat** [comment]
Also, I can resolve these problems. But I promised @mhammond that I would not make changes without his approval.

**Comment by ERaunig** [comment]
>Ah yes. Anyone can do that. But can you fix all of the c++ failures that
will come after that?

Depends on the failures. If it's a simple syntax problem or not sourcing
the right library then sure. If it's something more complex like a logical
error, or having to know how it is supposed to work then probably not.

I noticed that you have a version 220.

https://pypi.python.org/pypi/pypiwin32

is this working?

`C:\Users\e.raunig>pip install --no-cache-dir --ignore-installed
pypiwin32==219
Collecting pypiwin32==219
  Downloading pypiwin32-219.zip (4.8MB)
    100% |████████████████████████████████| 4.8MB 6.6MB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File
"C:\Users\EA4F9~1.RAU\AppData\Local\Temp\pip-build-y91trp4b\pypiwin32\setup.py",
line 121
        print "Building pywin32", pywin32_version
                               ^
    SyntaxError: Missing parentheses in call to 'print'. Did you mean
print("Building pywin32", pywin32_version)?

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in
C:\Users\EA4F9~1.RAU\AppData\Local\Temp\pip-build-y91trp4b\pypiwin32\

C:\Users\e.raunig>pip install --no-cache-dir --ignore-installed
pypiwin32==220
Collecting pypiwin32==220
  Could not find a version that satisfies the requirement pypiwin32==220
(from versions: 219)
No matching distribution found for pypiwin32==220
`

**Comment by xoviat** [comment]
Yes 220 works. Why did your pip not prefer it?

**Comment by ERaunig** [comment]
Got me..I recently downloaded Python.

`
C:\Users\e.raunig>python --version
Python 3.7.0a2

C:\Users\e.raunig>pip --version
pip 9.0.1 from
c:\users\e.raunig\appdata\local\programs\python\python37\lib\site-packages
(python 3.7)
`

**Comment by xoviat** [comment]
Why are you running an unreleased Python? Zero libraries will support it.

**Comment by ERaunig** [comment]
IT installed it.

**Comment by ERaunig** [comment]
I'll open up a new ticket.

**Comment by hnazkani** [comment]
With latest anaconda installation (python 3.7), I am still getting this issue. Is this solved ??

**Comment by mhammond** [comment]
Please ensure you are using pywin32, not pypiwin32
