### ISSUE TITLE
PEP 514 compatibility?

### ISSUE THREAD

**Issue by ghost** [mhammond/pywin32#738]
So I installed Python 3.6.0 (64 bit), then tried to install pywin32-220.win-amb64-py3.6.exe and it reported

---------------------------
Cannot install
---------------------------
Python version 3.6-32 required, which was not found in the registry.
---------------------------
OK   
---------------------------

Not sure what it is looking for in the registry, but PEP 514 maybe changed some of that?

Reported by: guruglenn

Original Ticket: [pywin32/bugs/738](https://sourceforge.net/p/pywin32/bugs/738)

**Comment by Avasam** [comment]
[.exe installers are now deprecated](https://github.com/mhammond/pywin32#binaries) and wheels for all bitness are available on PyPI
