### ISSUE TITLE
Cannot install on Python 3.6 (32 bit)

### ISSUE THREAD

**Issue by ghost** [mhammond/pywin32#739]
Not sure if this is python's or pywin32's fault, but either way, trying to install pywin32 in python 3.6 (32 bit) leads to the following...

C:\Users\Samuel\Downloads\pywin32-220\pywin32-220>C:\Users\Samuel\AppData\Local\Programs\Python\Python36-32\python.exe setup3.py install
Converting...
Executing...
Building pywin32 3.6.220.0
Traceback (most recent call last):
  File "setup3.py", line 16, in <module>
    exec(str(got))
  File "<string>", line 1944, in <module>
  File "<string>", line 594, in __init__
  File "C:\Users\Samuel\AppData\Local\Programs\Python\Python36-32\lib\ntpath.py", line 75, in join
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType

Reported by: timothygrove

Original Ticket: [pywin32/bugs/739](https://sourceforge.net/p/pywin32/bugs/739)

**Comment by AlreadyAsleep** [comment]
Did you ever get the install on Python 3.6? I am having the same issue as you were I believe

**Comment by xoviat** [comment]
What's the issue?

**Comment by xoviat** [comment]
BTW, you cannot compile pywin32 on a default Python/MSVC installation. Would highly recommend:

```
pip install pypiwin32
```

**Comment by AlreadyAsleep** [comment]
Oh my goodness you are a lifesaver. That did it.
Why is this not in the README?

**Comment by xoviat** [comment]
No idea. I'm not the decision-maker here.

**Comment by AlreadyAsleep** [comment]
Well thank you anyway, I'm still a noob so it really goes a long way

**Comment by Avasam** [comment]
@mhammond Given this issue was specifically about installing on Python 3.6, which pywin32 no longer supports, should it be closed?
