### ISSUE TITLE
DCOM Disabled and Install Error

### ISSUE THREAD

**Issue by ghost** [mhammond/pywin32#74]
Everything installs OK until the very last portion of
the process when items are &amp;quot;registering&amp;quot; a Windows
Error box appears and asks if you want to submit an
error report created by the win32all program to MS.
We've disabled DCOM \(for obvious security reasons\) on
these XP machines... would that cause a problem for the
win32all installer?

Outside the registration error, everything seems to
work OK the IDE, the modules, of course, we don't use
the COM components.

Reported by: *anonymous

Original Ticket: "pywin32/bugs/74":https://sourceforge.net/p/pywin32/bugs/74

**Comment by Avasam** [comment]
I have disabled dcom (https://support.microsoft.com/en-us/topic/how-to-disable-dcom-support-in-windows-2bb8c280-9698-7f9c-bf67-2625a5873c7b) on Windows 10 and restarted my computer.

Tried the `pywin32-306.win-amd64-py3.9.exe` installer. I had no error and could not replicate this issue.

w/o a way to contact the original poster (Anonymous and disabled email) for further information, and no way to replicate, there's nothing that can be done here other than to assume this was fixed or a Windows XP problem.
