### ISSUE TITLE
pywin32-220.win-amd**64**-py3.6.exe is looking for the 32 (not 64)

### ISSUE THREAD

**Issue by ghost** [mhammond/pywin32#742]
I was looking for windows 7, 64. 
pywin32-220.win-amd**64**-py3.6.exe : is looking for the 32 version. So I could not install it: "Python version 3.6-32 required, which was not found in the registry." but pywin32-220.zip worked for 64

Is there a mistake with the filename?

Reported by: guillaumecombot

Original Ticket: [pywin32/bugs/742](https://sourceforge.net/p/pywin32/bugs/742)

**Comment by Avasam** [comment]
[.exe installers are now deprecated](https://github.com/mhammond/pywin32#binaries) and wheels for all bitness are available on PyPI
Also issue was solved by user
