### ISSUE TITLE
gencache.py: StringIO needs to be BytesIO

### ISSUE THREAD

**Issue by ghost** [mhammond/pywin32#750]
When deploying a win32com-based executable (using py2exe), in python3, gencache.py line 107 throws an error, since StringIO expects a string and not bytes (which is the correct data type of the "data" parameter). After changing StringIO to BytesIO, the problem seems to be resolved. It would be great if that change can be applied in the source tree. Thanks.

Reported by: f_wenzel

Original Ticket: [pywin32/bugs/750](https://sourceforge.net/p/pywin32/bugs/750)

**Comment by Avasam** [comment]
Fixed by 0f26e938b3f57b0b90ae77093bc3198fe1374a64
