### ISSUE TITLE
ERROR_BAD_LENGTH in winfile.GetFileInformationByHandleEx on x86 - a struct alignment issue.

### ISSUE THREAD

**Issue by xoviat** [mhammond/pywin32#752]
In latests x86 builds(211), both 2.7 and 3.6, when called with [`FileBasicInfo`](https://msdn.microsoft.com/en-us/library/windows/desktop/aa364228.aspx), [`GetFileInformationByHandleEx`](https://msdn.microsoft.com/en-us/library/windows/desktop/aa364953.aspx) throws an exeption with winerror code `ERROR_BAD_LENGTH`:

Python 2.7.13 x86 with latest Pythonwin on windows 7sp1-64:
~~~
>>> from win32file import *; from win32con import *
>>> hfile = CreateFile(r'C:\Windows\notepad.exe', GENERIC_READ, FILE_SHARE_READ, None, OPEN_EXISTING, 0, None)
>>> GetFileInformationByHandleEx(hfile, FileBasicInfo)
Traceback (most recent call last):
  File "<interactive input>", line 1, in <module>
error: (24, 'GetFileInformationByHandleEx', 'The program issued a command but the command length is incorrect.')
~~~

The cause of the error is a bug in `<winsock2.h>` included from `win32file.i`. 
Here's some cl.exe output with `/showIncludes` switch:
~~~
Note: including file: \WinSDK\Include\winsock2.h
Note: including file:  \WinSDK\Include\pshpack4.h << pragma pack(push, 4) here
Note: including file:  \WinSDK\Include\windows.h  << all Windows stuff gets compiled with non default alignment
Note: including file:   \WinSDK\Include\sdkddkver.h
...cut
Note: including file:  \WinSDK\Include\poppack.h
~~~
This bug can tracked to [2003](https://groups.google.com/forum/#!topic/microsoft.public.vc.ide_general/C_IW_byLdQU), it's present in 7.0a SDK and is fixed already in 8.1.

Struct [`FILE_BASIC_INFO`](https://msdn.microsoft.com/en-us/library/windows/desktop/aa364217.aspx) contains four int64 fields and one int32 so its `sizeof` by default would be 40 bytes with padding, the odd packing directive decreases its size by omitting padding and `GetFileInformationByHandleEx` refuses to fill the struct.

The obvious fix would be to just include `windows.h` before `winsock2` but it's not [that easy](https://stackoverflow.com/questions/1372480) due to conflict between `winsock2` and `winsock`. The second option is to define `WIN32` macro before inclusion of `winsock2.h` but I don't know will it work with all supported SDKs.

I'll attach a patch later today.

Reported by: robyschek

Original Ticket: [pywin32/bugs/752](https://sourceforge.net/p/pywin32/bugs/752)

**Comment by mhammond** [comment]
Sorry for the delay - fixed in #3623bff39973b2e07fb9b05da0083e9901f0a9f2
