### ISSUE TITLE
python3 doesn't have "execfile" in "pywin\framework\interact.py"

### ISSUE THREAD

**Issue by ghost** [mhammond/pywin32#758]
file: pywin\framework\interact.py uses "execfile()" which is canceled in python3.

Apparently i'm the only python programmer who uses python startup file with pythonwin.exe.

This solution works for me (interact.py, instead of line 299) :

            if (sys.version_info > (3, 0)):
                exec(open(rcfile).read(), __main__.__dict__, __main__.__dict__)
            else:
                execfile(rcfile, __main__.__dict__, __main__.__dict__)

Reported by: asafgr

Original Ticket: [pywin32/bugs/758](https://sourceforge.net/p/pywin32/bugs/758)

**Comment by Avasam** [comment]
execfile is no longer referenced anywhere in the code
