### ISSUE TITLE
Manual Uninstallation Procedure

### ISSUE THREAD

**Issue by ghost** [mhammond/pywin32#760]
Due to the fact that the installation failed in the case 
where the target directory contained a space, I now 
have a half-installed copy of the Win32 extensions and 
no installation log available for uninstallation.

Please provide me with the correct procedure for manual 
uninstallation of this broken version of the utility such 
that I may avoid future registry corruption.

Reported by: nobody

Original Ticket: "pywin32/feature-requests/1":https://sourceforge.net/p/pywin32/feature-requests/1

**Comment by Avasam** [comment]
https://github.com/mhammond/pywin32#troubleshooting
^ This should help with reinstallation, and problems that can arise.

As for old "space in path" issues, they should all already be fixed.
