### ISSUE TITLE
support for cygwin

### ISSUE THREAD

**Issue by ghost** [mhammond/pywin32#764]
Not sure that it will be easy, but there are w32api
package...

Reported by: dubnerm

Original Ticket: "pywin32/feature-requests/5":https://sourceforge.net/p/pywin32/feature-requests/5

**Comment by Avasam** [comment]
Related to https://github.com/mhammond/pywin32/issues/764
Closing in favor of https://github.com/mhammond/pywin32/issues/1378 which has more modern discussions

**Comment by Avasam** [comment]
Tagging @pyhedgehog as original SourceForge issue Creator.
