### ISSUE TITLE
GetProcAddress has no use right now

### ISSUE THREAD

**Issue by ghost** [mhammond/pywin32#765]
win32api.GetProcAddress\(\) should be either removed or
has some counterpart that will allow to call arbitrary
functions with specified parameter types.

Reported by: dubnerm

Original Ticket: "pywin32/feature-requests/6":https://sourceforge.net/p/pywin32/feature-requests/6

**Comment by Avasam** [comment]
Tagging @pyhedgehog as original SourceForge issue Creator.
