### ISSUE TITLE
win32comext makes many problems (py2exe, zip-packages, etc)

### ISSUE THREAD

**Issue by ghost** [mhammond/pywin32#785]
Each time I install a new release of pywin, I first
copy the win32comext folder  contents to win32com.
Otherwise I have a lot of trouble with that module-fake
code in win32com/\_\_init\_\_.py

Is there a true reason for win32comext?
If anybody makes an own extenstion \(as I used some\)
they don't need to live in win32comext.? If modules
come with pywin they can anyway stay in win32com and
load clean, I think.

Reported by: kxroberto

Original Ticket: "pywin32/feature-requests/26":https://sourceforge.net/p/pywin32/feature-requests/26

**Comment by Avasam** [comment]
@kxrob Is this issue still relevant?

**Comment by Avasam** [comment]
Closing as duplicate of #678, which also has more details.
