### ISSUE TITLE
Integration with pychecker

### ISSUE THREAD

**Issue by ghost** [mhammond/pywin32#788]
Hi --

It would be nice to include integration with PyChecker 
\(http://sourceforge.net/projects/pychecker\) in the same 
way there is TabNanny integration. A Google search 
comes up with the cfg below to do it yourself by adding 
a new pywin editor configuration \(slightly modified below 
to handle pathnames with spaces and to add messaging 
to the status bar\). It would be nice to ship this out-of-
the-box to encourage adoption. Barring that, maybe add 
a pointer / reference to these instructions in the FAQ?

Thanks\!

Ramon

\[General\]
\# place this in &lt;pythondir&gt;\Lib\site-
packages\Pythonwin\pywin\
Based On = Default

\[Keys:Editor\]
Shift+Ctrl+v      = checksource

\[Extensions\]
def checksource\(editor\_window, event\):
import pywin.framework.scriptutils
import os
import re
import win32ui

filename = 
pywin.framework.scriptutils.GetActiveFileName\(\)
win32ui.SetStatusText\("PyChecker is checking your 
source..." , True\)
messages = os.popen\(r'&lt;pythondir&gt;\pychecker.bat "%
s"' % filename\)
for message in messages.xreadlines\(\):
print re.sub\(r"\(.\*\):\(\d+\):\(.\*\)", r'File "\1", line \2, 
\3', message.strip\(\)\)
messages.close\(\)
win32ui.SetStatusText\("PyChecker is done checking 
your source." , True\)

Reported by: felciano

Original Ticket: "pywin32/feature-requests/29":https://sourceforge.net/p/pywin32/feature-requests/29

**Comment by Avasam** [comment]
Looks like this was added in 79f41c5dd54692f5a85027750fa6a424628cce2a by @kxrob
