### ISSUE TITLE
would like to have ReadProcessMemory

### ISSUE THREAD

**Issue by ghost** [mhammond/pywin32#804]
would like to see ReadProcessMemory added to the api.

Reported by: jpcurrey

Original Ticket: "pywin32/feature-requests/45":https://sourceforge.net/p/pywin32/feature-requests/45

**Comment by divinity76** [comment]
this issue should be closed as resolved, ReadProcessMemory was added in build 227 :)

**Comment by mhammond** [comment]
Thanks for reminding me :)
