### ISSUE TITLE
Printer font and point size

### ISSUE THREAD

**Issue by ghost** [mhammond/pywin32#827]
The user should have control over what font and what font point size is used to print a listing. While I like a large point size for sitting back and looking at the screen, this same size fits poorly on the printed page.

\--hsm

Reported by: nobody

Original Ticket: "pywin32/feature-requests/68":https://sourceforge.net/p/pywin32/feature-requests/68

**Comment by Avasam** [comment]
@mhammond any idea what this is referring to exactly? (specific win32print functionality? Pythonwin page printing?) Otherwise w/o a user to ask (anonymous post on sourceforge), there's not much else we can gleam from this feature request.

**Comment by mhammond** [comment]
I assume win32print, but agree it's not actionable, so let's kill it.
