### ISSUE TITLE
Cannot build pywin32 on Vista using VC++ Express Edition

### ISSUE THREAD

**Issue by ghost** [mhammond/pywin32#833]
I always try to use only free stuff -- especially if I have to buy things from Micro$oft -- so, just as an experiment, I attempted to build pywin32 \(current CVS as of 2009-06-05\) using the current free compiler on my Vista laptop. It worked much better than I expected, but setup.py finally crashed with:
v v v v v
Microsoft Windows \[Version 6.0.6002\]
...
C:\pywin32&gt;c:\python26\python.exe setup.py build
Building pywin32 2.6.213.1
running build
running build\_py
running build\_ext
Found version 0x600 in C:\Program Files\Microsoft SDKs\Windows\v6.0A\include\SDK
DDKVER.H
building 'perfmondata' extension
mc.exe -h win32\src\perfmon -r build\temp.win32-2.6\Release\win32\src\perfmon wi
n32\src\perfmon\PyPerfMsgs.mc
error: command 'mc.exe' failed: No such file or directory

C:\pywin32&gt;
^ ^ ^ ^ ^
Environment:
Vista Home Basic with SP2
CPython 2.6.2
Microsoft Visual C++ 2008 Express Edition with SP1 - ENU
Microsoft Visual C++ 2008 Redistributable - x86 9.0.30729
Microsoft  Windows SDK for Visual Studio 2008 Headers and Libraries
Microsoft  Windows SDK for Visual Studio 2008 SP1 Express Tools for .NET Framework - enu
Microsoft  Windows SDK for Visual Studio 2008 SP1 Express Tools for Win32
\--
Vernon Cole

Reported by: kf7xm

Original Ticket: [pywin32/feature-requests/74](https://sourceforge.net/p/pywin32/feature-requests/74)

**Comment by Avasam** [comment]
> C:\pywin32>c:\python26\python.exe setup.py build

Note that [`python setup.py` and the use of setup.py as a command line tool are deprecated](https://packaging.python.org/en/latest/discussions/setup-py-deprecated/#is-setup-py-deprecated). pywin32 itself needs to move away from it. #2208

**Comment by Avasam** [comment]
Support for Vista has been removed in #1874
