### ISSUE TITLE
pywin32 for PyPy

### ISSUE THREAD

**Issue by ghost** [mhammond/pywin32#842]
I've just managed to make pywin32 compile and work on top of PyPy.
I open this ticket to keep track of the various changes that I made to the pywin32 source code.
I'm currently preparing patches; for the moment, changes are of two kinds:

\- In some .cpp files you can find "if PyString\_Check\(xxx\)" without surrounding parentheses. This works on CPython because PyString\_Check is actually a macro which adds parentheses to its expression; with PyPy PyString\_Check is a function.

\- With PyPy it's not allowed to change ob\_type after object creation. This is used a lot by all PyIBase subclasses. The solution I found is to pass the TypeObject to the base constructor, and ensure that ob\_type is set just before calling \_Py\_NewReference\(\). Of course these two lines can be replaced by "PyObject\_Init\(this, type\);"

Reported by: amauryf

Original Ticket: [pywin32/feature-requests/83](https://sourceforge.net/p/pywin32/feature-requests/83)

**Comment by Avasam** [comment]
Duplicated by #1289 (that other issue is more modern with up to date discussion, so may as well close this one)
