### ISSUE TITLE
QueryServiceConfig() not exist

### ISSUE THREAD

**Issue by ghost** [mhammond/pywin32#851]
Please implement method QueryServiceConfig\(\) method to win32serviceutil library.
I have example:
&gt;&gt;&gt; scm = win32service.OpenSCManager\(None, None, win32service.SC\_QUERY\_CONFIG\)
&gt;&gt;&gt; svc = win32service.OpenService\(scm, "TestQueueMgrSvc", win32service.SC\_QUERY\_CONFIG\)
&gt;&gt;&gt; svccfg = win32service.QueryServiceConfig\(svc\)
&gt;&gt;&gt; svccfg
Thanks,

Reported by: *anonymous

Original Ticket: [pywin32/feature-requests/92](https://sourceforge.net/p/pywin32/feature-requests/92)

**Comment by Avasam** [comment]
This is a strange request, as `QueryServiceConfig` exists in `win32service`, and `SC_QUERY_CONFIG` doesn't exist anywhere, but `win32service.SERVICE_QUERY_CONFIG` does.

Anyway, w/o a user to contact (anonymous post), we shall never know what they were really asking for.
