### ISSUE TITLE
Provide msi as-is for downloading

### ISSUE THREAD

**Issue by xoviat** [mhammond/pywin32#855]
By reading the tracker I learned that the msi created with bdist\_msi doesn't work, and that easy\_install doesn't work either. 
For both, it is because they are unable to run the post-install script.

As far as I know, there is no way to silently install this module \(I need that in order to install it on thousands of computers...\)

I know I could setup the sdk and try to create an installer with inno setup or something like that, but I don't want to reinvent the wheel and I would much prefer that a solution could be found for everyone, not just me.

Would it be possible for you to publish the not-fully-working msis, together with the post-install script ?
If I understand correctly, it should work to install the msi then run the post-install script separately ?

Reported by: jarod38

Original Ticket: [pywin32/feature-requests/96](https://sourceforge.net/p/pywin32/feature-requests/96)

**Comment by mhammond** [comment]
MSI installers are no longer on the radar - I'm working on painless pypi/wheel support which should make life even easier than using an MSI.
