### ISSUE TITLE
GCC-compiled pywin32

### ISSUE THREAD

**Issue by ghost** [mhammond/pywin32#861]
Could we have a GCC-compiled pywin32? It would be awesome for Cygwin users.

Reported by: khalak

Original Ticket: [pywin32/feature-requests/102](https://sourceforge.net/p/pywin32/feature-requests/102)

**Comment by Avasam** [comment]
https://setuptools.pypa.io/en/latest/deprecated/distutils/apiref.html#module-distutils.cygwinccompiler
note that distutils is removed from Python 3.12 and usage with setuptools is deprecated  #2119
