### ISSUE TITLE
Distribute as a binary wheel

### ISSUE THREAD

**Issue by ghost** [mhammond/pywin32#869]
"It would be great if pywin32 could be distributed as a binary wheel."
See https://sourceforge.net/p/pywin32/bugs/669/

That would really be great!

This would remove the manual intervention for the installation of pywin32.

wheel: http://wheel.readthedocs.org/

Reported by: robi-wan

Original Ticket: [pywin32/feature-requests/110](https://sourceforge.net/p/pywin32/feature-requests/110)

**Comment by mhammond** [comment]
We now support wheels.

**Comment by Avasam** [comment]
xref: https://github.com/mhammond/pywin32/issues/869
