### ISSUE TITLE
pip install pywin32

### ISSUE THREAD

**Issue by ghost** [mhammond/pywin32#872]
This python extension is really useful for me and I assume it is for a lot of other people. Please add it to pip, so that others and I can install it by just typing pip install pywin32.

Regards
Sebastian Nilsson

Reported by: sebnil

Original Ticket: [pywin32/feature-requests/113](https://sourceforge.net/p/pywin32/feature-requests/113)

**Comment by Avasam** [comment]
https://pypi.org/project/pywin32/
