### ISSUE TITLE
LocalService support

### ISSUE THREAD

**Issue by ghost** [mhammond/pywin32#940]
With this module you can create out-of-process COM
server in NT Service.

Usage:

class MyCOMObject1:
\_reg\_clsid\_ = ...
\_reg\_...

class MyCOMService\(localservice.LocalCOMService\):  

\_svc\_com\_servers\_ = \[MyCOMObject1, ...\]          

if \_\_name\_\_=='\_\_main\_\_':
localservice.ProcessCommandLine\(MyCOMService\)    

Reported by: dubnerm

Original Ticket: "pywin32/patches/66":https://sourceforge.net/p/pywin32/patches/66

**Comment by Avasam** [comment]
Tagging @pyhedgehog as original SourceForge issue Creator.
