### ISSUE TITLE
installation failure for Win2K

### ISSUE THREAD

**Issue by ghost** [mhammond/pywin32#98]
Using all defaults for Install of build 201.

wxPython Demo works fine as do Idle and python from a 
DOS prompt - all are for Python 2.3.3.

I get this error:
Can't load Python for pre-install script

I don't have Admin permissions on this box, so maybe 
that confuses the installer ?

Reported by: akrassowski

Original Ticket: "pywin32/bugs/98":https://sourceforge.net/p/pywin32/bugs/98

**Comment by Avasam** [comment]
@mhammond Since the recommended installation method is now as a python package from PyPI, and that this issue was created for Windows 2000 (with he last comment referencing Windows XP). Should this be closed?
